import { CatalogItem } from "../interfaces";
export const GenericCatalog: CatalogItem[] = [
  {
    code: "SDNRG",
    name: "Service Numbers",
    fullname: "Service Dispatch Numbers (1000/bx)",
    colors: ["_0000", "1000", "2000", "3000", "4000", "5000", "6000", "7000", "8000", "9000"],
    type: "service",
    default_color: "1000",
    discount: [
      { quantity: 1, price: 84.99 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "1470",
    name: "Multi-Purpose Tags",
    fullname: "Multi-Purpose Tags (500/box)",
    colors: ["Blue", "Green", "White", "Yellow"],
    type: "parts",
    default_color: "Yellow",
    discount: [
      { quantity: 1, price: 25.99 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "117L",
    name: "Car Covers",
    fullname: "Car Cover - Large 25 ft. (30/roll)",
    colors: ["Plastic"],
    type: "bodyshop",
    default_color: "Plastic",
    discount: [
      { quantity: 1, price: 180.99 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "45450",
    name: "Sanitizing",
    fullname: "Safe Shield Sanitizing System (1 gallon)",
    colors: ["Black"],
    type: "detail",
    default_color: "Black",
    discount: [
      { quantity: 1, price: 44.99 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "J331",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® All-Conditions Jacket",
    colors: ["Black", "Direct Blue", "True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 58.29,
      Medium: 58.29,
      Large: 58.29,
      XLarge: 58.29,
      "2XLarge": 60.29,
      "3XLarge": 62.29,
      "4XLarge": 64.29,
    },
  },
  {
    code: "J333",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Torrent Waterproof Jacket",
    colors: ["Black", "Engine Red", "Magnet", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,
      "3XLarge": 53.99,
      "4XLarge": 55.99,
    },
  },
  {
    code: "NF0A7V4F",
    name: "The North Face® Jacket",
    fullname: "The North Face® Down Hybrid Jacket",
    colors: ["Black", "Medium Grey Hthr"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 189.00,
      Medium: 189.00,
      Large: 189.00,
      XLarge: 189.00,
      "2XLarge": 191.00,
      "3XLarge": 193.00,
    },
  },
  {
    code: "ST740",
    name: "Sport-Tek® UV Polo",
    fullname: "Sport-Tek® UV Micropique Polo",
    colors: ["Black", "Deep Red", "Graphite", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 19.99,
      Medium: 19.99,
      Large: 19.99,
      XLarge: 19.99,
      "2XLarge": 21.99,
      "3XLarge": 23.99,
      "4XLarge": 25.99,
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Anthracite", "Black", "Game Royal", "University Red"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 36.99,
      "3XLarge": 38.99,
      "4XLarge": 40.99,
      LT: 40.99,
      XLT: 42.99,
      "2XLT": 44.99,
      "3XLT": 46.99,
      "4XLT": 48.99,
    },
  },
  {
    code: "TM1MAA370",
    name: "TravisMathew Solid Polo",
    fullname: "TravisMathew Cabana Solid Polo",
    colors: ["Black", "Classic Blue", "Crimson", "Stormy Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 74.99,
      Medium: 74.99,
      Large: 74.99,
      XLarge: 74.99,
      "2XLarge": 76.99,
      "3XLarge": 78.99,
    },
  },
  {
    code: "OG1002",
    name: "OGIO® Woven Shirt",
    fullname: "OGIO® Commuter Woven Shirt",
    colors: ["Blacktop", "Gear Grey Hthr", "Metal Blue Hthr", "White"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 42.99,
      Medium: 42.99,
      Large: 42.99,
      XLarge: 42.99,
      "2XLarge": 44.99,
      "3XLarge": 46.99,
      "4XLarge": 48.99,
    },
  },
  {
    code: "K584",
    name: "Port Authority® 1/4-Zip",
    fullname: "Port Authority® Silk Touch™ 1/4-Zip",
    colors: ["Black", "Red", "Royal", "Steel Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 23.99,
      Medium: 23.99,
      Large: 23.99,
      XLarge: 23.99,
      "2XLarge": 25.99,
      "3XLarge": 27.99,
      "4XLarge": 29.99,
    },
  },
  {
    code: "NKBV6044",
    name: "Nike 1/2-Zip Cover-Up",
    fullname: "Nike Dry 1/2-Zip Cover-Up",
    colors: ["Black", "Black Heather", "Gym Blue"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 62.50,
      Medium: 62.50,
      Large: 62.50,
      XLarge: 62.50,
      "2XLarge": 64.50,
      "3XLarge": 66.50,
      "4XLarge": 68.50,
    },
  },
  {
    code: "TM1MY397",
    name: "TravisMathew 1/4-Zip",
    fullname: "TravisMathew Coto Performance 1/4-Zip",
    colors: [
      "Black",
      "Brilliant Blue Hthr",
      "Quiet Shade Grey Hthr",
      "Vintage Indigo",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 74.99,
      Medium: 74.99,
      Large: 74.99,
      XLarge: 74.99,
      "2XLarge": 76.99,
      "3XLarge": 78.99,
    },
  },
  {
    code: "5470",
    name: "A/P Voucher Jacket",
    fullname: "9 in. x 12 in. A/P Voucher Jacket (DSA-540)",
    colors: ["Blue", "Buff", "Green", "Lavender", "Pink", "White"],
    type: "office",
    default_color: "Buff",
    discount: [
      { quantity: 100, price: 0.0 },
      { quantity: 500, price: 0.0 },
    ],
    sizes: {
      100: 0.0,
      500: 0.0,
    },
  },
  {