import { CatalogItem } from "../interfaces";
export const HennessyCatalog: CatalogItem[] = [
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    discount: [
      { quantity: 500, price: 73.50 },      
    ],
    sizes: {
      default: 73.50,
    },
  }, 
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 500, price: 72.97 },      
    ],
    sizes: {
      default: 72.97,      
    },
  },
  {
    code: "BGVinyl",
    name: "Vinyl Sheet",
    fullname: "8.5 x 11 Blank Vinyl Sheet #9300 (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",
    discount: [
      { quantity: 1, price: 135.00 },      
    ],
    sizes: {
      default: 135.00,      
    },
  },
  {
    code: "BGE12-AL",
    name: "Buyers Guide",
    fullname: "Buyers Guide, Blank Front (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",
    discount: [
      { quantity: 1, price: 74.95 },      
    ],
    sizes: {
      default: 74.95,      
    },
  },
  {
    code: "3198WB",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers (Blue/White)  (12/pk)",
    colors: ["YR 07","YR 08","YR 09","YR 10","YR 11","YR 12","YR 13","YR 13","YR 14","YR 15","YR 16", "YR 17", "YR 18",
    "YR 19", "YR 20", "YR 21", "YR 22", "YR 23", "YR 24", "YR 25", "YR 26"],
    type: "sales",
    default_color: "YR 2025",
    discount: [
      { quantity: 1, price: 10.99 },      
    ],
    sizes: {
      default: 10.99,    
    },
  },
  {
    code: "GP955",
    name: "Grease Marker",
    fullname: "Grease Marker (1 each)",
    colors: ["Blue", "Green", "Pink", "Orange", "Purple", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Orange",
    discount: [
      { quantity: 1, price: 10.69 },      
    ],
    sizes: {
      default: 10.69,      
    },
  },
  {   
    code: "GP200",
    name: "Key Tags",
    fullname: "Key Tag Versa #200 (250/bx)",
    colors: ["Blue", "Gray", "Green", "Lilac", "Lime Green", "Orange", "Red", "Tan", "White", "Yellow"],
    type: "sales",
    default_color: "White",
    discount: [
      { quantity: 1, price: 36.95 },      
    ],
    sizes: {
      default: 36.95,      
    },
  },
  {   
    code: "GP790",
    name: "Sticker",
    fullname: "Sticker - Vehicle Not for Sale (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",
    discount: [
      { quantity: 1, price: 27.95 },      
    ],
    sizes: {
      default: 27.95,      
    },
  },
  {
    code: "BB18002",
    name: "Brooks Brothers® Shirt",
    fullname: "Brooks Brothers® Wrinkle-Free Nailhead Shirt",
    colors: ["Cobalt Blue", "White"],
    type: "mens",
    default_color: "White",
    sizes: {
      Small: 79.99,
      Medium: 79.99,
      Large: 79.99,
      XLarge: 79.99,
      "2XLarge": 80.99,
      "3XLarge": 81.99,
      "4XLarge": 82.99,
    },
  },
  {
    code: "BB18003",
    name: "Brooks Brothers® Shirt",
    fullname: "Brooks Brothers® Women's Wrinkle-Free Nailhead Shirt",
    colors: ["Cobalt Blue", "White"],
    type: "womens",
    default_color: "White",
    sizes: {
      Small: 79.99,
      Medium: 79.99,
      Large: 79.99,
      XLarge: 79.99,
      "2XLarge": 80.99,
      "3XLarge": 81.99,
      "4XLarge": 82.99,
    },
  },
  {
    code: "S608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt",
    colors: ["White"],
    type: "mens",
    default_color: "White",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 35.99,
      "3XLarge": 36.99,
      "4XLarge": 37.99,
      "5XLarge": 38.99,
      "6XLarge": 39.99,
    },
  },
  {    
    code: "L608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Women's Long Sleeve Shirt",
    colors: ["White"],
    type: "womens",
    default_color: "White",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 35.99,
      "3XLarge": 36.99,
      "4XLarge": 37.99,
      "5XLarge": 38.99,
      "6XLarge": 39.99,
    },
  },
  {    
    code: "OG101",
    name: "OGIO® - Caliber2.0 Polo",
    fullname: "OGIO® - Caliber2.0 Polo",
    colors: ["Blacktop"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 32.99,
      Medium: 32.99,
      Large: 32.99,
      XLarge: 32.99,
      "2XLarge": 33.99,
      "3XLarge": 34.99,
      "4XLarge": 35.99,
    },
  },
  {
    code: "LOG101",
    name: "OGIO® - Jewel Polo",
    fullname: "OGIO® - Jewel Polo",
    colors: ["Blacktop"],
    type: "womens",
    default_color: "Blacktop",
    sizes: {
      Small: 32.99,
      Medium: 32.99,
      Large: 32.99,
      XLarge: 32.99,
      "2XLarge": 33.99,
      "3XLarge": 34.99,
      "4XLarge": 35.99,
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 50.99,
      "3XLarge": 51.99,
      "4XLarge": 52.99,
      "5XLarge": 53.99,
      "6XLarge": 54.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Women's Core Soft Shell Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 50.99,
      "3XLarge": 51.99,
      "4XLarge": 52.99,      
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee",
    fullname: "Sport-Tek PosiCharge Competitor Tee",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 10.99,
      Medium: 10.99,
      Large: 10.99,
      XLarge: 10.99,
      "2XLarge": 11.99,
      "3XLarge": 12.99,
      "4XLarge": 13.99,      
    },
  },
  {
    code: "HENFAT-FOB-505249",
    name: "Laser Engraved Keychain",
    fullname: "Blue Banner Keychain w/Laser Engraved Imprint",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    discount: [
      { quantity: 500, price: 2.39 },
      { quantity: 1000, price: 2.19 },
      { quantity: 2500, price: 1.99 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "CG1640",
    name: "Laser Engraved Keychain",
    fullname: "Brushed Zinc/Leather Key Tag w/Laser Engraved Imprint",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    discount: [
      { quantity: 500, price: 3.99 },
      { quantity: 1000, price: 3.29 },
      { quantity: 2500, price: 2.99 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT31DD",
    name: "Die Cut Decal",
    fullname: "Decal Thermo Die Cut",
    colors: ["Black", "Silver", "White"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 1000, price: .75 },
      { quantity: 2500, price: .65 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT-34MRE-419207",
    name: "Alumninum Embossed Plate",
    fullname: "Aluminum Plate w/black imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 500, price: 3.59 },
      { quantity: 1000, price: 3.19 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT-34MRE-418853",
    name: "Aluminum Embossed Plate",
    fullname: "White Aluminum Plate w/blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 3.59 },
      { quantity: 2500, price: 3.19 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT-34MLF-445719",
    name: "Zinc Metal Frame",
    fullname: "Standard Zinc Metal Frame",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    discount: [
      { quantity: 1000, price: 3.69 },
      { quantity: 2500, price: 3.09 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT-280C-497703",
    name: "Hang Tag",
    fullname: "VIP OFFER Hang Tag",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 500, price: .89 },
      { quantity: 1000, price: .69 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT-280C-491902",
    name: "Hang Tag",
    fullname: "SOLD Hang Tag",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 500, price: .89 },
      { quantity: 1000, price: .69 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENFAT-33G24-443352",
    name: "Poly Coated Plate",
    fullname: "Poly Coated Cardboard w/black/blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: .89 },
      { quantity: 2500, price: .79 },
      { quantity: 5000, price: .69 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
    },
  },
  {
    code: "HENFAT-1830-478437",
    name: "Service Due Sticker",
    fullname: "Service Due Sticker w/QR code",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 5000, price: .21 },
      { quantity: 10000, price: .19},
     ],
    sizes: {
      5000: 0.0,
      10000: 0.0,     
    },
  },
  {
    code: "HENFAT-FOB-506092",
    name: "Laser Engraved Leather Keychain",
    fullname: "Chrome Keychain w/laser engraved imprint",
    colors: ["Metal"],
    type: "accessory",
    default_color: "Metal",
    discount: [
      { quantity: 500, price: 3.59 },     
     ],
    sizes: {
      500: 0.0,         
    },
  },
  {
    code: "HENFAT-MUG-505968",
    name: "15oz. Mug w/imprint",
    fullname: "Royal 15oz. Ember Mug w/silver imprint",
    colors: ["Royal"],
    type: "accessory",
    default_color: "Royal",
    discount: [
      { quantity: 360, price: 2.89 },     
     ],
    sizes: {
      360: 0.0,         
    },
  },
  {
    code: "HENFAT-TOTE-493101",
    name: "Vinyl Tote w/imprint",
    fullname: "Vinyl Tote w/full color imprint",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    discount: [
      { quantity: 1000, price: 1.69 },     
     ],
    sizes: {
      1000: 0.0,         
    },
  },
  {
    code: "HENFAT-MUG-492907",
    name: "15oz. Mug w/imprint",
    fullname: "Black 15oz. Mug w/laser engraved imprint",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    discount: [
      { quantity: 1000, price: 1.69 },     
     ],
    sizes: {
      1000: 0.0,         
    },
  },
  {
    code: "HENFAT-TOTE-492717",
    name: "Laminated Tote w/imprint",
    fullname: "Black Gloss Laminated Tote w/white imprint",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    discount: [
      { quantity: 100, price: 2.29 },     
     ],
    sizes: {
      100: 0.0,         
    },
  },
  ];
