import { CatalogItem } from "../interfaces";
export const LeithCatalog: CatalogItem[] = [
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather", "Deep Smoke", "Dress Blue Navy", "Forest Green", "Maroon", "Navy Heather", "Pearl Grey Heather", "Rich Red", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 40.49,
      Medium: 40.49,
      Large: 40.49,
      XLarge: 40.49,
      "2XLarge": 40.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,
      "5XLarge": 43.99,
      "6XLarge": 44.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather", "Deep Smoke", "Dress Blue Navy", "Navy Heather", "Pearl Grey Heather", "Rich Red", "True Royal", "Very Berry"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 40.49,
      Medium: 40.49,
      Large: 40.49,
      XLarge: 40.49,
      "2XLarge": 40.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,      
    },
  },
  {
    code: "TLJ317",
    name: "Port Authority® TALL Jacket",
    fullname: "Port Authority® TALL Core Soft Shell Jacket",
    colors: ["Battleship Grey", "Black", "Dress Blue Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      LT: 41.49,
      XLT: 41.49,
      "2XLT": 41.99,
      "3XLT": 42.99,
      "4XLT": 43.99,
    },
  },
  {
    code: "L540LS",
    name: "Port Authority® Long Sleeve Polo",
    fullname: "Port Authority® Long Sleeve Polo",
    colors: ["Black", "Bright Purple", "Carolina Blue", "Navy", "Red", "Royal", "Steel Grey"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 22.49,
      Medium: 22.49,
      Large: 22.49,
      XLarge: 22.49,
      "2XLarge": 23.99,
      "3XLarge": 24.99,
      "4XLarge": 25.99,      
    },
  },
  {
    code: "ST657",
    name: "Sport-Tek® Long Sleeve Polo Shirt",
    fullname: "Sport-Tek® Long Sleeve Sport-Wick Polo",
    colors: ["Black", "Deep Red", "Forest Green", "Iron Grey", "Maroon", "True Navy", "True Red", "True Royal", "White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 27.49,
      Medium: 27.49,
      Large: 27.49,
      XLarge: 27.49,
      "2XLarge": 28.49,
      "3XLarge": 29.49,
      "4XLarge": 30.49,      
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Sport-Wick Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Lime Shock",
      "Maroon",
      "Purple",
      "Texas Orange",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "Vegas Gold",
      "White"
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 23.49,
      Medium: 23.49,
      Large: 23.49,
      XLarge: 23.49,
      "2XLarge": 24.49,
      "3XLarge": 25.49,
      "4XLarge": 26.49,
      "5XLarge": 27.49,
      "6XLarge": 28.49,
    },
  },
  {
    code: "TST650",
    name: "Sport-Tek® Tall Polo Shirt",
    fullname: "Sport-Tek® Tall Sport-Wick Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Red",
      "Forest Green",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Maroon",
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White"
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      LT: 27.99,
      XLT: 28.99,
      "2XLT": 29.99,
      "3XLT": 31.99,
      "4XLT": 32.99,
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Sport-Wick Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Light Pink",
      "Lime Shock",
      "Maroon",
      "Pink Raspberry",
      "Purple",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "White"
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 23.49,
      Medium: 23.49,
      Large: 23.49,
      XLarge: 23.49,
      "2XLarge": 24.49,
      "3XLarge": 25.49,
      "4XLarge": 26.49,      
    },
  },
  // {
  //   code: 'CP80',
  //   name: 'Twill Cap',
  //   fullname: 'Port & Company® Six-Panel Twill Cap',
  //   colors: ['Black', 'True Red', 'Navy', 'Hunter', 'Royal', 'Charcoal', 'Woodland Brown'],
  //   type: 'hat',
  //   default_color: 'Black',
  //   sizes: {
  //     'One Size Fits All': 14.29
  //   }
  // },
  
  // {
  //   code: 'C112',
  //   name: 'Snapback',
  //   fullname: 'Port Authority® Snapback Trucker Cap',
  //   colors: ['Black', 'Navy', 'Black White', 'Patriot Royal', 'Red White', 'Royal White', 'Grey Steel', 'Pink White', 'Woodland Camo', 'Khaki White'],
  //   type: 'hat',
  //   halfColors: ['Black White', 'Red White', 'Royal White', 'Pink White', 'Khaki White'],
  //   default_color: 'Black',
  //   sizes: {
  //     'One Size Fits All': 14.29
  //   }
  // },
    {
    code: "K805",
    name: "Port Authority® 1/4-Zip Pullover",
    fullname: "Port Authority® 1/4-Zip Pullover",
    colors: ["Black", "Regatta Blue", "True Navy", "Iron Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 30.49,
      Medium: 30.49,
      Large: 30.49,
      XLarge: 30.49,
      "2XLarge": 31.49,
      "3XLarge": 32.49,
      "4XLarge": 33.49,
      "5XLarge": 34.99,
      "6XLarge": 35.99,
    },
  },
  {
    code: "L805",
    name: "Port Authority® 1/4-Zip Pullover",
    fullname: "Port Authority® 1/4-Zip Pullover",
    colors: ["Black", "Regatta Blue", "True Navy", "Iron Grey"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 30.49,
      Medium: 30.49,
      Large: 30.49,
      XLarge: 30.49,
      "2XLarge": 31.49,
      "3XLarge": 32.49,
      "4XLarge": 33.49,
    },
  },
];
