import { CatalogItem } from "../interfaces";
export const LeithCatalog: CatalogItem[] = [
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Micropique Polo",
    colors: ["Iron Grey", "True Red", "Black", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 22.99,
      Medium: 22.99,
      Large: 22.99,
      XLarge: 22.99,
      "2XLarge": 24.99,
      "3XLarge": 26.99,
      "4XLarge": 27.99,
      "5XLarge": 28.99,
      "6XLarge": 29.99,
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: ["Iron Grey", "True Red", "Black", "True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 22.99,
      Medium: 22.99,
      Large: 22.99,
      XLarge: 22.99,
      "2XLarge": 24.99,
      "3XLarge": 26.99,
      "4XLarge": 27.99,
    },
  },
  {
    code: "ST657",
    name: "Sport-Tek Long Sleeve Polo",
    fullname: "Sport-Tek® Long Sleeve Micropique Polo",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 58.98,
      Medium: 58.98,
      Large: 58.98,
      XLarge: 58.98,
      "2XLarge": 60.98,
      "3XLarge": 61.98,
      "4XLarge": 62.98,
    },
  },
  {
    code: "L540LS",
    name: "Port Authority® Polo",
    fullname: "Port Authority Womens Long Sleeve Polo",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 58.98,
      Medium: 58.98,
      Large: 58.98,
      XLarge: 58.98,
      "2XLarge": 60.98,
      "3XLarge": 61.98,
      "4XLarge": 62.98,
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 37.99,
      Medium: 37.99,
      Large: 37.99,
      XLarge: 37.99,
      "2XLarge": 38.99,
      "3XLarge": 39.99,
      "4XLarge": 40.99,
      "5XLarge": 41.99,
      "6XLarge": 42.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 37.99,
      Medium: 37.99,
      Large: 37.99,
      XLarge: 37.99,
      "2XLarge": 38.99,
      "3XLarge": 39.99,
      "4XLarge": 40.99,
    },
  },
  {
    code: "K805",
    name: "Port Authority® Pullover",
    fullname: "Port Authority® Vertical Texture 1/4-Zip Pullover",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 58.98,
      Medium: 58.98,
      Large: 58.98,
      XLarge: 58.98,
      "2XLarge": 60.98,
      "3XLarge": 61.98,
      "4XLarge": 62.98,
    },
  },
  {
    code: "L805",
    name: "Port Authority® Pullover",
    fullname: "Port Authority® Women's Vertical Texture Full-Zip Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 58.98,
      Medium: 58.98,
      Large: 58.98,
      XLarge: 58.98,
      "2XLarge": 60.98,
      "3XLarge": 61.98,
      "4XLarge": 62.98,
    },
  },  
];
