export const config = {
  title: "Cannon",
  company_logo: "cannon_logo.png",
  logo_placements: [],
  show_modification_thumbnail: false,
  minimum_apparel_order: false,
  render_logo_preview: false,
  embroideries: {
    hat: [],
    mens: [],
    womens: [],
    accessory: [],
    customs: [],
    office: [],
    service: [],
  },
  stores: {
    "Cannon Ford of Cleveland": "CANFCL",
    "Cannon Ford of Starkville": "CANLST",
    "Cannon Chevrolet Buick GMC": "CANBCL",
    "Cannon Chevrolet Greenwood": "CANCGR",
    "Cannon Chevrolet Buick GMC of West Point": "CANCWE",
    "Cannon Chevrolet Buick Cadillac of Oxford": "CANCOX",
    "Cannon Honda": "CANHPO",
    "Cannon CDJR of Cleveland": "CANCCL",
    "Cannon Ford of Pascagoula": "CANFPA",
    "Cannon CDJR Greenwood": "CANCGE",
    "Cannon Preowned Grenada": "CANPGR",
    "Cannon Toyota of Vicksburg": "CANTVI",
    "Cannon Toyota of Mosspoint": "CANTMO",
    "Cannon Nissan of Moss Point": "CANNMO",
    "Cannon CDJR of West Point": "CANDWE",
    "Cannon Preowned of Jackson": "CANPJA",
    "Cannon Preowned Calhoun City": "CANPCC",
    "Cannon Nissan of Greenwood": "CANNGR",
    "Cannon Nissan of Jackson": "CANNJA",
    "Cannon Nissan of Oxford": "CANNOX",
    "Grenada Nissan": "GREIGR",
    "Cannon Chevrolet Nissan of Laurel": "CANCLR",
    "Cannon GMC Vicksburg": "CANBVI",
    "Cannon CDJR Senatobia": "CANCSE",
  },
  bypass_codes: ["CANNJA"],
  server_hostname: "https://o1yn7lpenj.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Louis Budbill", phone: "678-287-1659" },
    { name: "Glenn Rodney", phone: "678-287-1608" },
  ],
};
