export const config = {
  title: "Friendship",
  company_logo: "friendship_cars.png",
  logo_placements: {
    mens: ["Left Chest"],
    womens: ["Left Chest"],
    hat: ["Front Center"],
    tshirts: ["Left Chest"],
  },
  show_image_preview: true,
  embroideries: {
    hat: ["Friendship Cars", "Friendship2"],
    mens: ["Friendship Cars", "Friendship2"],
    womens: ["Friendship Cars", "Friendship2"],
    tshirts: ["Friendship2"],
    accessory: [],
    customs: [],
    office: [],
    service: [],
    sales: [],
    detail: [],
    bodyshop: [],
    parts: [],
  },
  email_recipients: [
    "lbudbill@gpcorp.com",
    "bkays@gpcorp.com",
    "shanell@gpcorp.com",
    "webportalorders@gpcorp.com",
  ],
  stores: [
    {
      name: "Friendship Corp. Enterprises",
      address: "1954 West State Street, Bristol, TN 37620",
      code: "FRICBT",
    },
    {
      name: "Friendship Ford Bristol",
      address: "3192 W. State Street, Bristol, TN 37620",
      code: "FRIFBR",
    },
    {
      name: "Friendship CDJR Bristol",
      address: "3193 W. State Street, Bristol, TN 37620",
      code: "FRICBR",
    },
    {
      name: "Friendship Hyundai Bristol",
      address: "2638 West State Street, Bristol, TN 37620",
      code: "FRIHBR",
    },
    {
      name: "Friendship Volvo Bristol",
      address: "2638 West State Street, Bristol, TN 37620",
      code: "FRIVBR",
    },
    {
      name: "CDJR Johnson City",
      address: "3700 Bristol Hwy, Johnson City, TN 37601",
      code: "FRIOJC",
    },
    {
      name: "Friendship Hyundai Johnson City",
      address: "3408 North Roan Street, Johnson City, TN 37601",
      code: "FRIHJO",
    },
    {
      name: "Friendship Ford of Lenoir",
      address: "515 Wilkesboro Blvd, Lenoir, NC 28645",
      code: "FRIFLE",
    },
    {
      name: "Friendship CDJR of Forest City",
      address: "190 Oak Street Extension, Forest City, NC 28043",
      code: "FRICFO",
    },
    {
      name: "Friendship Nissan of Forest City",
      address: "156 Oak Street Extension, Forest City, NC 28043",
      code: "FRINFO",
    },
    {
      name: "Friendship Hyundai of Princeton",
      address: "720 Oakvale Rd, Princeton, WV 24740",
      code: "FRIHPR",
    },
    {
      name: "Friendship Hyundai of Beckley",
      address: "3921 Robert C Byrd Dr, Beckley, WV 25801",
      code: "FRIHBE",
    },
    {
      name: "Friendship Kia of Beckley",
      address: "111 Midtown Ave, Mount Hope, WV 25880",
      code: "FRIKBE",
    },
    {
      name: "Friendship Subaru of Beckley",
      address: "117 Midtown Ave, Mount Hope, WV 25880",
      code: "FRISMO",
    },
    {
      name: "Friendship Honda of Boone",
      address: "1440 Blowing Rock Rd, Boone, NC 28607",
      code: "FRIHBO",
    },
    {
      name: "Friendship Nissan of Boone",
      address: "135 Innovation Drive, Boone, NC 28607",
      code: "FRINBO",
    },
    {
      name: "Friendship Chevy of Forest City",
      address: "1740 College Ave, Forest City, NC 28043",
      code: "FRICFC",
    },
  ],
  bypass_codes: ["FRIEND"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Betsy Kays", phone: "678-287-1636" },
                 { name: "Bob Sugden", phone: "678-287-1620" },
                 { name: "Hunter Peck", phone: "678-287-1642" },
  ],
  route_prefix: "/friendship",
  paypal_not_supported: true,
  password: "FriendshiP",
};
