export const config = {
  title: "Giles",
  company_logo: "giles.png",
  logo_placements: {
    mens: ["Left Chest"],
    womens: ["Left Chest"],
    hat:[],
    tshirts: ["Left Chest"],
  },
  show_image_preview: true,
  minimum_apparel_order: false,
  enable_customs_store_picker: true,
  embroideries: {
    mens: ["Giles Automotive.EMB"],
    womens: ["Giles Automotive.EMB"],
    tshirts: ["Giles Automotive"],
    hat:  [],
    customs: [],
    office: [],
    service: [],
    sales: [],
    detail: [],
    bodyshop: [],
    parts: [],
    accessory: [],        
  },
  email_recipients: [
    "rgreenberg@gpcorp.com",          
    "shanell@gpcorp.com",
    "webportalorders@gpcorp.com",    
  ],
  stores: [
    {
      name: "Giles Nissan (Lafayette)",
      address: "6137 Johnston St, Lafayette, LA 70503",
      code: "GILNLA",
    },
    {
      name: "Giles Subaru (Lafayette)",
      address: "100 Town Center Pkwy, Lafayette, LA 70503",
      code: "GILSLA",
    },
    {
      name: "Giles Volvo (Lafayette)",
      address: "111 South City Pkwy, Lafayette, LA 70503",
      code: "GILVLA",
    },
    {
      name: "Giles Volvo Cars (El Paso)",
      address: "6585 S Desert Blvd, El Paso, TX 79932",
      code: "GILVEL",
    },
    {
      name: "Giles Hyundai (Alexandria)",
      address: "3220 S MacArthur Dr, Alexandria, LA 71301",
      code: "GILHAL",
    },
    {
      name: "Giles Nissan (Opelousas)",
      address: "5731 I-49 S Service Rd, Opelousas, LA 70570",
      code: "GILNOP",
    },
    {
      name: "Giles Kia of Las Cruces (Las Cruces)",
      address: "1840 N Main St, Las Cruces, NM 88001",
      code: "GILKCR",
    },
                      
    ],
  bypass_codes: ["GileS"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Richard Greenberg", phone: "678-287-1635" },],   
  route_prefix: "/giles",
  paypal_not_supported: true,
  password: "GileS",
};
