export const config = {
  title: "Hennessy",
  company_logo: "hennessy.png",
  logo_placements: ["Left Chest", "Right Sleeve","Front Center"],
  show_image_preview: true,
  embroideries: {
    hat: [
      "Cadillac",
      "Cadillac Cursive",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche",
      "JLR",
      "Porsche",
      "Porsche Atlanta NW",
      "Porsche North Atl",
      "Hennessy Vehicle Buying",
    ],
    mens: [
      "Cadillac",      
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche", 
      "JLR",     
      "Porsche Atlanta NW",
      "Porsche North Atl",
      "Hennessy Vehicle Buying",
    ],
    womens: [
      "Cadillac",    
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche", 
      "JLR",     
      "Porsche Atlanta NW",
      "Porsche North Atl",
      "Hennessy Vehicle Buying",
    ],
    accessory: [
      "Cadillac",
      "Cadillac Cursive",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche",
      "JLR",
      "Porsche",
      "Porsche Atlanta NW",
      "Porsche North Atl",
      "Hennessy Vehicle Buying",
    ],
    customs: [],
    office: [],
    sales: [],
    service: [],
    detail: [],
    bodyshop: [],
    parts: [],
  },
  email_recipients: ["lbudbill@gpcorp.com", "lbudbell@comcast.net", "zwarner@hennessyauto.com", "asarazua@gpcorp.com"],

  stores: {    
    "Hennessy Cadillac Duluth, 3377 Satellite Blvd, Duluth, GA 30096": "HENCDU",
    "Hennessy Ford Lincoln Atlanta, 5675 Peachtree Industrial Blvd, Atlanta, GA 30341":
      "HENFAT",
    "Hennessy Honda Woodstock, 8931 Highway 92, Woodstock, GA 30189": "HENHWO",    
    "Hennessy Land Rover, 1505 Mansell Rd, Alpharetta, GA 30004": "HENLAL",
    "Hennessy Land Rover Gwinnett, 3423 Old Norcross Rd, Duluth, GA 30096": "HENADU",
    "Hennessy Lexus Atlanta, 5955 Peachtree Industrial Blvd, Atlanta, GA 30341":
      "HENLAT",
    "Hennessy Lexus Duluth, 3383 Satellite Blvd, Duluth, GA 30096": "HENLDU",
    "Hennessy Mazda Buick GMC, 7261 Jonesboro Rd, Morrow, GA 30260": "HENMMO",
    "Hennessy Porsche Marietta, 2501 Windy Hill Rd SE, Marietta, GA 30067":
      "HENPMA",
    "Hennessy Porsche Roswell, 990 Mansell Rd, Roswell, GA 30076": "HENPRO",    
  },
  bypass_codes: ["HENNES"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Andrew Sarazua", phone: "678-287-1604" },
    { name: "John Boston", phone: "678-287-1601" },
  ],
  route_prefix: "/hennessy",
  paypal_not_supported: true,
  password: "HennessY",
};
