export const config = {
  title: "Hennessy",
  company_logo: "hennessy.png",
  logo_placements: ["Left Chest","Front Center"],
  show_modification_thumbnail: true,
  minimum_apparel_order: true,
  render_logo_preview: true,
  embroideries: {
    mens: [
      "Hennessy Automobile",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",    
      "Hennessy Vehicle Buying",
      "Hennessy Porsche",
      "Porsche",      
      "Porsche North Atl",
      "Porsche Atlanta NW",            
      ],
    womens: [
      "Hennessy Automobile",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",    
      "Hennessy Vehicle Buying",
      "Hennessy Porsche",
      "Porsche",      
      "Porsche North Atl",
      "Porsche Atlanta NW", 
    ],  
    customs: [
      "Hennessy Automobile",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Lexus",
      "Hennessy Mazda",
      "Hennessy Mazda GMC",    
      "Hennessy Vehicle Buying",
      "Hennessy Porsche",
      "Porsche",     
      "Porsche North Atl",
      "Porsche Atlanta NW", 
    ],
    accessory: [],
    sales: [],
    service: [],  
  },
  email_recipients: [
    "lbudbill@gpcorp.com", 
    "lbudbell@comcast.net",
    "asarazua@gpcorp.com",
    "jboston@gpcorp.com",
    "Zwarner@hennessyauto.com"],

  stores: [
     {
      name: "Hennessy Cadillac",
      address: "3377 Satellite Blvd, Duluth, GA 30096",
      code: "HENCDU ",
      password: "HennessY",
    },
    {
      name: "Hennessy Lexus Duluth",
      address: "3383 Satellite Blvd, Duluth, GA 30096",
      code: "HENLDU",
      password: "HennessY",
    },
    {
      name: "Hennessy Ford",
      address: "5675 Peachtree Ind Blvd, Atlanta, GA 30341",
      code: "HENMMO",
      password: "HennessY",
    },
    {
      name: "Hennessy Land Rover",
      address: "1505 Mansell Road, Alpharetta, GA 30004",
      code: "HENLAL",
      password: "HennessY",
    },
    {
      name: "Hennessy Land Rover Gwinnett",
      address: "3423 Old Norcross Rd, Duluth, GA 30096",
      code: "HENADU",
      password: "HennessY",
    },
    {
      name: "Hennessy Lexus Atlanta",
      address: "5955 Peachtree Ind Blvd, Atlanta, GA 30341",
      code: "HENLAT",
      password: "HennessY",
    },
    {
      name: "Hennessy Mazda GMC",
      address: "7261 Jonesboro Rd, Morrow, GA 30260",
      code: "HENMMO",
      password: "HennessY",
    },    
    {
      name: "Hennessy Honda Woodstock",
      address: "8931 Highway 92, Woodstock, GA 30189",
      code: "HENHWO",
      password: "HennessY",
    },
    {
      name: "Hennessy Porsche",
      address: "900 Mansell Rd, Roswell, GA 30076",
      code: "HENPRO",
      password: "HennessY",
    },
    {
      name: "Hennessy Porsche Marietta",
      address: "2501 Windy Hill Rd SE, Marietta, GA 30067",
      code: "HENPMA",
      password: "HennessY",
    },
  ],    
  bypass_codes: ["HENNES"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Andrew Sarazua", phone: "678-287-1604" },
    { name: "John Boston", phone: "678-287-1601" },
  ],
  route_prefix: "/hennessy",
  paypal_not_supported: true,
  password: "HennessY",
};
