export const config = {
  title: "Hoffman",
  company_logo: "hoffman.png",
  logo_placements: {
    mens: ["Left Chest", "Right Sleeve", "Left Sleeve", "Yoke"],
    womens: ["Left Chest", "Right Sleeve", "Left Sleeve", "Yoke"],
    hat: ["Front Center"],
    tshirts: ["Left Chest", "Right Sleeve", "Left Sleeve", "Yoke"],
  },
  show_image_preview: true,
  embroideries: {
    hat: [
      "Audi with Rings 3 Inch",
      "BMW 2 Inch Icon Open.EMB",
      "Honda Stacked 2 Inches.EMB",
      "Lexus Stacked 3 Inches.EMB",
      "Nissan New Icon 2,5 Inch.EMB",
      "Toyota Stacked 2,50 Wide.EMB",
      "Porsche 3,625 Logo.EMB",
      "Toyota Stacked 2,50 Wide.EMB",
      "Hoffman Auto Group.EMB",
      "Genesis Stacked 3,5 Inch.EMB",
      "Subaru Hyundai Stacked",   
      "Ford Lincoln 3,75 Inch.EMB",          
      "Hoffman Insurance Agency.EMB",
      "Hoffman Collision Center",       
      "Hoffman Motor Sports.EMB",
      "Hoffman H Logo.EMB",       
      
    ],
    mens: [
      "Audi with Rings 3 Inch",
      "BMW 2 Inch Icon Open.EMB",
      "Honda Stacked 2 Inches.EMB",
      "Lexus Stacked 3 Inches.EMB",
      "Nissan New Icon 2,5 Inch.EMB",
      "Toyota Stacked 2,50 Wide.EMB",
      "Porsche 3,625 Logo.EMB",
      "Toyota Stacked 2,50 Wide.EMB",
      "Hoffman Auto Group.EMB",
      "Genesis Stacked 3,5 Inch.EMB",
      "Subaru Hyundai Stacked",   
      "Ford Lincoln 3,75 Inch.EMB",          
      "Hoffman Insurance Agency.EMB",
      "Hoffman Collision Center",       
      "Hoffman Motor Sports.EMB",
      "Hoffman H Logo.EMB",   
    ],
    womens: [
      "Audi with Rings 3 Inch",
      "BMW 2 Inch Icon Open.EMB",
      "Honda Stacked 2 Inches.EMB",
      "Lexus Stacked 3 Inches.EMB",
      "Nissan New Icon 2,5 Inch.EMB",
      "Toyota Stacked 2,50 Wide.EMB",
      "Porsche 3,625 Logo.EMB",
      "Toyota Stacked 2,50 Wide.EMB",
      "Hoffman Auto Group.EMB",
      "Genesis Stacked 3,5 Inch.EMB",
      "Subaru Hyundai Stacked",   
      "Ford Lincoln 3,75 Inch.EMB",          
      "Hoffman Insurance Agency.EMB",
      "Hoffman Collision Center",       
      "Hoffman Motor Sports.EMB",
      "Hoffman H Logo.EMB",   
    ],
    accessory: [],
    customs: [],
    office: [],
    sales: [],
    service: [],
    detail: [],
    bodyshop: [],
    parts: [],
  },
  email_recipients: [
    "lbudbill@gpcorp.com",    
    "bsugden@gpcorp.com",
    "shanell@gpcorp.com",
    "webportalorders@gpcorp.com",
  ],

  stores: [
    {
      name: "Hoffman APA",
      address: "600 Connecticut Blvd, East Hartford, CT 06108",
      code: "HOFAPA",
    },
  ],
  bypass_codes: ["BRONX"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Bob Sugden", phone: "678-287-1620" }],
  route_prefix: "/hoffman",
  paypal_not_supported: true,
  password: "HoffmaN",
};
