export const config = {
  title: "Krause",
  company_logo: "krause.png",
  logo_placements: {
    mens: ["Left Chest"],
    womens: ["Left Chest"],
    hat:[],
    tshirts: ["Left Chest"],
  },
  show_image_preview: true,
  minimum_apparel_order: false,
  enable_customs_store_picker: true,
  embroideries: {
    mens: ["Angela Krause Ford Lincoln.EMB"],
    womens: ["Angela Krause Ford Lincoln.EMB"],
    tshirts: ["Angela Krause Ford Lincoln"],
    hat:  [],
    customs: [],
    office: [],
    service: [],
    sales: [],
    detail: [],
    bodyshop: [],
    parts: [],
    accessory: [],        
  },
  email_recipients: [
    "lbudbill@gpcorp.com",          
    "shanell@gpcorp.com",
    "webportalorders@gpcorp.com",    
  ],
  stores: [
    {
      name: "Motorcars of Atlanta",
      address: "7865 Roswell Rd, Atlanta, GA 30350",
      code: "ROLMAT",
    },              
    ],
  bypass_codes: ["TEST"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Louis Budbill", phone: "678-287-1649" },],   
  route_prefix: "/krause",
  paypal_not_supported: true,
  password: "KrausE",
};
