export const config = {
  title: "Leith",
  company_logo: "leith.png",
  logo_placements: ["Left Chest", "Yoke"],
  show_modification_thumbnail: true,
  minimum_apparel_order: true,
  render_logo_preview: true,
  embroideries: {
    mens: ["honda"],
    womens: ["honda"],
    hat: [],
    customs: [],
  },
  stores: {
    "Leith Acura, 2300 Capital Summit Court, Raleigh, NC 27616": "10118LEIARA",
    "Chris Leith Automotive, PO Box 1707, Wake Forest, NC 27588": "CHRIWA",
    "Leith Acura, 2300 Capital Summit Ct, Raleigh, NC 27616": "LEIARA",
    "Leith CDJR, 11220 N. US HWY 15 501 N, Aberdeen, NC 27603": "LEICAB",
    "Leith Chrysler Jeep, 400 Autopark Boulevard, Cary, NC 27511": "LEICCA",
    "Leith Corporate Headquarters, 8005 Capital Blvd, Raleigh, NC 27616":
      "LEICRA",
    "Leith Ford, PO Box 1809, Wendell, NC 27591": "LEIFWE",
    "Leith Honda, 3940 Capital Hills Drive, NC 27606": "LEIHRA",
    "Leith Lincoln, 2350 Capital Summit Ct, Raleigh, NC 27616": "LEILRA",
    "Leith Nissan, 2100 Auto Park Drive, Cary, NC 27511": "LEINCA",
    "Leith Nissan, 2000 Auto Park Drive, Cary, NC 27511": "LEITCA",
    "Leith BMW/Mercedes Benz, 5603 Capital Blvd, Raleigh, NC 27616": "LEITR2",
    "Leith Mercedes, 5601 Capital Boulevard, Raleigh, NC 27616": "LEITRA",
    "Leith Toyota, 8005 Capital Blvd, Raleigh, NC 27616": "LEITRL",
    "Leith Autopark Kia, 5330 Rolesville Rd, Wendell, NC 27591": "LEITWE",
    "Leith Volkswagen, 4005 Capital Hills Drive, Raleigh, NC 27616": "LEIVRA",
    "Leith Chrysler Jeep, 5500 Capital Blvd, Raleigh, NC 27619": "LETCRA",
  },
  bypass_codes: ["LEITH"],

  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Bob Sugden", phone: "678-287-1662" },
    { name: "Louis Budbill", phone: "678-287-1659" },
  ],
  route_prefix: "/leith",
  paypal_not_supported: true,
  password: "LeitH",
};
