export const config = {
  title: "Leith",
  company_logo: "leith.png",
  logo_placements: {
    mens: ["Left Chest", "Right Chest","Yoke","Left Sleeve","Right Sleeve"],
    womens: ["Left Chest", "Right Chest","Yoke","Left Sleeve","Right Sleeve"],
    hat: ["Front Center"],
    tshirts: ["Left Chest", "Right Chest","Yoke","Left Sleeve","Right Sleeve"],
  },
  show_image_preview: true,
  enable_customs_store_picker: true,
  embroideries: {
    mens: [  
       "Acura 3 Inches Wide.EMB",     
       "Audi Rings 3 Inch.EMB",
       "BMW Icon 2,5 Inches.EMB",
       "Chrysler Jeep Ram Dodge.EMB",
       "Ford Oval 3 Inches Wide.EMB",
       "GMC 3,5 Inch.EMB",
       "Holman 3,125 Inch.EMB",
       "Holman 3,5 Inch for Hats.EMB",
       "Holman H Only 2 Inch.EMB",
       "Holman Vinfast.EMB",
       "Honda Stacked 3 Inch x 2 Inch", 
       "Jaguar Only 3,5X.EMB",
       "Kia New Logo 3 Inches.EMB",
       "Land Rover.EMB",
       "Lexus Stacked 3 Inches.EMB",
       "Mercedes Icon Only 3 Inches.EMB",
       "Nissan Icon New 3 Inch.EMB",
       "Porsche 3 Inches.EMB",
       "Toyota Stacked 3 Inches Wide.EMB",
       "VW Icon New.EMB",      
    ],
    womens: [
       "Acura 3 Inches Wide.EMB",     
       "Audi Rings 3 Inch.EMB",
       "BMW Icon 2,5 Inches.EMB",
       "Chrysler Jeep Ram Dodge.EMB",
       "Ford Oval 3 Inches Wide.EMB",
       "GMC 3,5 Inch.EMB",
       "Holman 3,125 Inch.EMB",
       "Holman 3,5 Inch for Hats.EMB",
       "Holman H Only 2 Inch.EMB",
       "Holman Vinfast.EMB",
       "Honda Stacked 3 Inch x 2 Inch", 
       "Jaguar Only 3,5X.EMB",
       "Kia New Logo 3 Inches.EMB",
       "Land Rover.EMB",
       "Lexus Stacked 3 Inches.EMB",
       "Mercedes Icon Only 3 Inches.EMB",
       "Nissan Icon New 3 Inch.EMB",
       "Porsche 3 Inches.EMB",
       "Toyota Stacked 3 Inches Wide.EMB",
       "VW Icon New.EMB",       
    ],
    tshirts: ["Holman", "Holman Driving Whats Right"],
    hat: [],
    customs: [],
  },
  email_recipients: [
    "lbudbill@gpcorp.com",
    "shanell@gpcorp.com",
    "webportalorders@gpcorp.com",
    "bsugden@gpcorp.com",
  ],
  stores: [
    {
      name: "Leith CDJR (Aberdeen)",
      address: "11220 N. US HWY 15 501 N, Aberdeen, NC 27603",
      code: "LEICAB",
    },
    {
      name: "Leith Honda (Aberdeen)",
      address: "11045 US-15 #501, Aberdeen, NC 28315",
      code: "LEIHAB",
    },
    {
      name: "Leith Acura (Cary)",
      address: "900 Autopark Blvd, Cary, NC 27511",
      code: "LEIACA",
    },
    {
      name: "Leith Chrysler Jeep (Cary)",
      address: "400 Autopark Boulevard, Cary, NC 27511",
      code: "LEICCA",
    },
    {
      name: "Leith Nissan (Cary)",
      address: "2100 Auto Park Drive, Cary, NC 27511",
      code: "LEINCA",
    },
     {
      name: "Leith Vinfast (Cary)",
      address: "200 Auto Park Blvd, Cary, NC 27511",
      code: "LEIVNC",
    },  
    {
      name: "Leith Volkswagen (Cary)",
      address: "2300 Auto Park Blvd, Cary, NC 27511",
      code: "LEIVCA",
    },           
    {
      name: "Leith Acura (Raleigh)",
      address: "2300 Capital Summit Ct, Raleigh, NC 27616",
      code: "LEIARA",
    },    
    {
      name: "Leith BMW/Mercedes (Raleigh)",
      address: "5603 Capital Blvd, Raleigh, NC 27616",
      code: "LEITR2",
    },      
    {
      name: "Leith Chrysler Jeep (Raleigh)",
      address: "5500 Capital Blvd, Raleigh, NC 27616",
      code: "LEICRB",
    },  
    {
      name: "Leith Honda (Raleigh)",
      address: "3940 Capital Hills Drive, Raleigh, NC 27606",
      code: "LEIHRA",
    },
    {
      name: "Leith Lincoln (Raleigh)",
      address: "2350 Capital Summit Ct, Raleigh, NC 27616",
      code: "LEILRA",
    },
    {
      name: "Leith Mercedes (Releigh)",
      address: "5601 Capital Boulevard, Raleigh, NC 27616",
      code: "LEITRA",
    },       
    {
      name: "Leith Toyota (Raleigh)",
      address: "8005 Capital Blvd, Raleigh, NC 27616",
      code: "LEITRL",
    },
    {
      name: "Leith Volkswagen (Raleigh)",
      address: "4005 Capital Hills Drive, Raleigh, NC 27616",
      code: "LEIVRA",
    },
    {
      name: "Leith Autopark Kia (Wendell)",
      address: "5330 Rolesville Rd, Wendell, NC 27591",
      code: "LEITWE",
    },
    {
      name: "Leith CDJR (Wendell)",
      address: "5310 Rolesville Rd, Wendell, NC 27591",
      code: "LEICWE",
    },
    {
      name: "Leith Ford (Wendell)",
      address: "PO Box 1809, Wendell, NC 27591",
      code: "LEIFWE",
    },
    {
      name: "Leith GMC (Wendell)",
      address: "5320 Rolesville Rd, Wendell, NC 27591",
      code: "LEIGWE",
    },
    {
      name: "Chris Leith Automotive",
      address: "PO Box 1707, Wake Forest, NC 27588",
      code: "",
    },
    {
      name: "Leith Corporate Headquarters",
      address: "8005 Capital Blvd, Raleigh, NC 27616",
      code: "",
    },    
  ],
  bypass_codes: ["LEITH"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Bob Sugden", phone: "678-287-1662" },
    { name: "Louis Budbill", phone: "678-287-1649" },
  ],
  route_prefix: "/leith",
  paypal_not_supported: true,
  password: "LeitH",
};
