export const config = {
  title: "Mattbowers",
  company_logo: "matt_bowers.png",
  logo_placements: {
    mens: ["Left Chest"],
    womens: ["Left Chest"],
    hat: ["Front Center"],
    tshirts: ["Left Chest", "Front Center"],
  },
  show_image_preview: true,
  minimum_apparel_order: false,
  embroideries: {
    mens: [
      "Matt B Ford Metairie",
      "Matt B Chevy Slidell",
      "MB Auto Group", 
      "Matt B Hyundai Slidell", 
      "MB Ford Metairie",    
      "MB Chevy Slidell", 
      "MB Hyundai Slidell", 
      "MB",         
      "Matt B Ford Met Blue",      
      "MB Flag",
                 
    ],
    womens: [
      "Matt B Ford Metairie",
      "Matt B Chevy Slidell",
      "MB Auto Group", 
      "Matt B Hyundai Slidell", 
      "MB Ford Metairie",    
      "MB Chevy Slidell", 
      "MB Hyundai Slidell", 
      "MB",         
      "Matt B Ford Met Blue",      
      "MB Flag",
    ],
    tshirts: [
      "Matt B Ford Metairie",
      "Matt B Chevy Slidell",
      "MB Auto Group", 
      "Matt B Hyundai Slidell", 
      "MB Ford Metairie",    
      "MB Chevy Slidell", 
      "MB Hyundai Slidell", 
      "MB",         
      "Matt B Ford Met Blue",      
      "MB Flag",
    ],
    hat:  [
      "Matt B Ford Metairie",
      "Matt B Chevy Slidell",
      "MB Auto Group", 
      "Matt B Hyundai Slidell", 
      "MB Ford Metairie",    
      "MB Chevy Slidell", 
      "MB Hyundai Slidell", 
      "MB",         
      "Matt B Ford Met Blue",      
      "MB Flag", 
    ],
    customs: [],
    office: [],
    service: [],
    sales: [],
    detail: [],
    bodyshop: [],
    parts: [],

  },
  email_recipients: [
    "rgreenberg@gpcorp.com",
    "shanell@gpcorp.com",
    "support@gpcorp.com",
    
  ],
  stores: [
    {
      name: "Matt Bowers Ford",
      address: "3724 Veterans Memorial Blvd, Metairie, LA 70002",
      code: "MATFME",
    },
    {
      name: "Matt Bowers Chevrolet Cadillac",
      address: "316 E Howze Beach Rd, Slidell, LA 70461",
      code: "BOWCSL",
    },
    {
      name: "Matt Bowers Hyundai",
      address: "298 E Howze Beach Rd, Slidell, LA 70461",
      code: "BOWHSL",
    },
    ],
  bypass_codes: ["MATTB"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Richard Greenberg", phone: "678-287-1635" },],   
  route_prefix: "/mattbowers",
  paypal_not_supported: true,
  password: "MattbowerS",
};
