export const config = {
  title: "Mcdonald",
  company_logo: "mcdonald.png",
  logo_placements: ["Left Chest"],
  show_image_preview: true,
  embroideries: {
    hat: ["Mcdonald"],
    mens: [],
    womens: [],
    tshirts: [],
    accessory: [],
    customs: [],
    office: [],
    service: [],
    sales: [],
    detail: [],
    bodyshop: [],
    parts: [],    
  },
  email_recipients: ["lbudbill@gpcorp.com", "lbudbell@comcast.net"],
  stores: [
    {
      name: "Audi Parker",
      address: "18455 Ponderosa Drive, Parker, CO 80134",
      code: "AUDPCO",
    },
    {
      name: "Genesis of Littleton",
      address: "6500 S. Broadway, Littleton, CO 80121",
      code: "GENOLI",
    },
    {
      name: "McDonald Audi - Denver",
      address: "6060 S. Broadway, Denver, CO 80121",
      code: "MCDADE",
    },
    {
      name: "McDonald Automotive",
      address: "6060 S. Broadway, Denver, CO 80121",
      code: "MCDALI",
    },
    {
      name: "McDonald Hyundai",
      address: "1400 Plum Valley Lane, Highlands Ranch, CO 80129",
      code: "MCDHLI",
    },
    {
      name: "McDonald Mazda West",
      address: "10345 Colfaz Ave, Lakewood, CO 80214",
      code: "MCDMLA",
    },
    {
      name: "McDonald Mazda South",
      address: "6100 S. Broadway, Littleton, CO 80121 ",
      code: "MCDMLI",
    },
    {
      name: "McDonald Mazda North",
      address: "1461 Vista View Drive, Longmont, CO 80504",
      code: "MCDMLO",
    },
    {
      name: "McDonald Nissan Highlands Ranch",
      address: "1320 Plum Valley Lane, Highlands Ranch, CO 80129",
      code: "MCDNHI",
    },
    {
      name: "McDonald Toyota - Fort Morgan",
      address: "1209 Main Street, Fort Morgan, CO 80701",
      code: "MCDTCO",
    },
    {
      name: "McDonald Toyota - Greeley",
      address: "4732 West 26th Street, Greeley, CO 80634",
      code: "MCDTGR",
    },
    {
      name: "McDonald Volkswagen",
      address: "6000 S. Broadway, Littleton, CO 80121",
      code: "MCDVLI",
    },
    {
      name: "McDonald Volvo",
      address: "6040 S. Broadway, Denver, CO 80121",
      code: "MCDVLT",
    },
    {
      name: "Polestar Denver",
      address: "240 St. Paul Street, Denver, CO 80206",
      code: "POLDEN",
    },
  ],
  bypass_codes: ["MCDONA"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Louis Budbill", phone: "678-287-1659" }],
  route_prefix: "/mcdonald",
  paypal_not_supported: true,
  password: "McdonalD",
};
