export const config = {
  title: "Tasca",
  company_logo: "tascalanding.png",
  logo_placements: {
    mens: ["Left Chest"],
    womens: ["Left Chest"],
    hat: [],
    tshirts: [],
  },
  show_image_preview: true,
  minimum_apparel_order: false,
  enable_customs_store_picker: true,
  embroideries: {
    hat: [],
    mens: [
      "Tasca",
      "Yonkers Kia", 
      "Scarsdale Ford", 
      "Central Ave CDJR",       
      "Gary Crossley Ford",
      "Ford Pro Yonkers",      
      "Ford Pro Berlin",
      "Ford Pro Cranston",
      "Ford Pro Arlington Heights",
      "Arlington Heights Ford",
    ],
    womens: [
      "Tasca",
      "Yonkers Kia", 
      "Scarsdale Ford", 
      "Central Ave CDJR", 
      "Arlington Heights Ford",
      "Gary Crossley Ford",
      "Ford Pro Yonkers",      
      "Ford Pro Berlin",
      "Ford Pro Cranston",
      "Ford Pro Arlington Heights",
    ],
    accessory: [],
    customs: [],
    office: [],
  },
   email_recipients: [    
    "kmay@gpcorp.com",    
    "shanell@gpcorp.com",
    "webportalorders@gpcorp.com",
  ],
  stores: [
    {
      name: "Tasca Buick GMC Clearwater",
      address: "18200 US Hwy 19 N, Clearwater,FL 33764",
      code: "TASBCL",
    },
    {
      name: "Tasca Buick GMC",
      address: "510 E. Nasa Blvd, Melbourne, FL 32901",
      code: "TASBME",
    },
    {
      name: "Tasca Buick GMC Palm Harbor",
      address: "30777 US Hwy 19 N, Palm Harbor, FL 34684",
      code: "TASBPA",
    },
    {
      name: "Tasca Buick GMC Woonsocket",
      address: "55 Fortin Drive, Woonsocket, RI 02895",
      code: "TASBWO",
    },
    {
      name: "Tasca CDJR Fiat",
      address: "1667 Hartford Ave, Johnston, RI 02919",
      code: "TASCJO",
    },
    {
      name: "Tasca Cadillac",
      address: "510 E. Nasa Blvd, Melbourne, FL 32901",
      code: "TASCME",
    },
    {
      name: "Tasca Chevrolet Wheeling",
      address: "700 W Dundee Rd, Wheeling, IL 60090",
      code: "TASCWH",
    },
    {
      name: "Tasca Chevrolet",
      address: "114 Fortin Drive, Woonsocket, RI 02895",
      code: "TASCWN",
    },
    {
      name: "Tasca Ford Berlin",
      address: "250 Webster Square Rd, Berlin, CT 06037",
      code: "TASFBE",
    },
    {
      name: "Tasca Ford Cranston",
      address: "1300 Pontiac Ave, Cranston, RI 02920",
      code: "TASFCR",
    },
    {
      name: "Tasca Ford Dickson City",
      address: "704 Martin F Gibbons Blvd, Dickson City, PA 18519",
      code: "TASFDI",
    },
    {
      name: "Tasca Ford Seekonk",
      address: "200 Falls River Ave, Seekonk, MA 02771",
      code: "TASFSE",
    },
    {
      name: "Tasca Ford Yonkers",
      address: "900 Central Ave, Yonkers, NY 10704",
      code: "TASFYO",
    },
    {
      name: "Tasca Central Ave Hyundai",
      address: "111 South Central Avenue, Hartsdale, NY 10530",
      code: "TASHCE",
    },
    {
      name: "Tasca Hyundai Fairhaven",
      address: "37 Adlen Rd, Fairhaven, MA 02719",
      code: "TASHFA",
    },
    {
      name: "Tasca Hyundai Stamford",
      address: "85 Magee Ave, Stamford, CT 06902",
      code: "TASHST",
    },
    {
      name: "Tasca Kia",
      address: "1670 Hartford Ave, Johnston, RI 02919",
      code: "TASKJO",
    },
    {
      name: "Tasca Kia South Shore",
      address: "1128 Sunrise Highway, Copiague, NY 11726",
      code: "TASKSO",
    },
    {
      name: "Tasca Kia White Plains",
      address: "468 Tarrytown Rd, White Plains, NY 10607",
      code: "TASKWH",
    },
    {
      name: "Tasca Lincoln",
      address: "1300 Pontiac Ave, Cranston, RI 02920",
      code: "TASLCR",
    },
    {
      name: "Tasca Mazda Cranston RI",
      address: "1300 Pontiac Ave, Cranston, RI 02920",
      code: "TASMCR",
    },
    {
      name: "Tasca Mazda Seekonk",
      address: "200 Fall River Ave, Seekonk, MA 02771",
      code: "TASMSE",
    },
    {
      name: "Tasca Mazda Yonkers",
      address: "900 Central Park Ave, Yonkers, NY 10704",
      code: "TASMYO",
    },
     {
      name: "Tasca Nissan East Providence",
      address: "845 Taunton Ave, East Providence, RI 02914",
      code: "TASNEP",
    },
    {
      name: "Tasca Subaru Yonkers",
      address: "900 Central Park Ave, Yonkers, NY 10704",
      code: "TASSYO",
    },
    {
      name: "Tasca Toyota of Boston",
      address: "700 Morrissey Blvd, Boston, MA 02122",
      code: "TASTBO",
    },
    {
      name: "Tasca Volvo Cars",
      address: "1300 Pontiac Ave, Cranston, RI 02920",
      code: "TASVCR",
    },
    {
      name: "Tasca VW White Plains",
      address: "376 Tarrytown Road, White Plains, NY 10607",
      code: "TASVWP",
    },
    {
      name: "Tasca CDJR Fiat Kingston",
      address: "129 NY-28, Kingston, NY 12401",
      code: "TCDJRK",
    },
    {
      name: "Tasca CDJR White Plains",
      address: "380 Saw Mill River Road, Elmsford, NY 10523",
      code: "TCDJRW",
    },
    {
      name: "Arlington Heights Buick GMC",
      address: "777 W Dundee Rd, Arlington Heights, IL 60004",
      code: "TASBAR",
    },
    {
      name: "Arlington Heights Ford",
      address: "801 W Dundee Road, Arlington Heights, IL 60004",
      code: "ARLFAR",
    },
    {
      name: "Audi Mohegan Lake",
      address: "1791 E Main St, Mohegan Lake, NY 10547",
      code: "AUDMOL",
    },
    {
      name: "Audi Meadowlands",
      address: "4700 West Side Ave, North Bergen, NJ 07047",
      code: "AUDMEA",
    },
    {
      name: "Central Ave CDJR",
      address: "1839 Central Ave, Yonkers, NY 10710",
      code: "CENCYO",
    },    
    {
      name: "Gary Crossley Ford",
      address: "8050 North Church Rd, Kansas City, MO 64158",
      code: "CROFKA",
    },
    {
      name: "Mohegan Lake VW",
      address: "1744 East Main Street, Mohegan Lake, NY 10547",
      code: "MOHVMO",
    },
    {
      name: "Scarsdale Ford",
      address: "887 Central Park Ave, Scarsdale, NY 10583",
      code: "SCAFSC",
    },
    {
      name: "Yonkers Kia",
      address: "1850 Central Park Ave, Yonkers, NY 10710",
      code: "TASKYO",
    },   
    {
      name: "Tasca Corporate Office",
      address: "40 Sharp Drive Unit 3, Cranston, RI 02920",
      code: "TASCOR",
    },
    {
      name: "Yonkers Ford Pro",
      address: "1015 Saw Mill River Rd, Yonkers, NY 10710",
      code: "YONFPR",
    },
    {
      name: "Autopaint RI",
      address: "",
      code: "",
    },
    {
      name: "TAG Management",
      address: "",
      code: "",
    },
    {
      name: "TAG Management - Midwest",
      address: "",
      code: "",
    },
    {
      name: "TAG Management - New York",
      address: "",
      code: "",
    },
  ],
  bypass_codes: [
    "TEST",
    "1-0226",
    "2-0226",
    "8-0226",
    "9-0226",
    "14-0226",
    "15-0226",
    "16-0226",
    "17-0226",
    "20-0226",
    "21-0226",
    "22-0226",
    "24-0226",
    "25-0226",
    "28-0226",
    "30-0226",
    "31-0226",
    "32-0226",
    "33-0226",
    "36-0226",
    "37-0226",
    "38-0226",
    "39-0226",
    "40-0226",
    "42-0226",
    "43-0226",
    "44-0226",
    "45-0226",
    "46-0226",
    "47-0226",
    "48-0226",
    "49-0226",
    "100-0226",
    "200-0226",
    "300-0226",    
  ],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Karen May (PA, NY & NJ)", email: "kmay@gpcorp.com"},
    { name: "Jennifer Warner (FL)", email: "jwarner@gpcorp.com"},
    { name: "Bob Sugden (RI & CT)", phone: "bsugden@gpcorp.com"},
    { name: "Steve Kennedy (MA & MO)", email: "skennedy@gpcorp.com"},
    { name: "Katie Charusch (IL)", email: "kcharusch@gpcorp.com"},
  ],
  route_prefix: "/tasca",
  paypal_not_supported: true,
  password: "TascA",
  
};
