export const config = {
  title: "Vaughn",
  company_logo: "vaughn_automotive.png",
  logo_placements: [
    "Left Chest", 
    "Left Sleeve", 
    "Right Sleeve", 
    "Full Back",
    "Full Front",
    "Front Center-HATS",
    "Left Side-HATS",
    "Right Side-HATS"
  ],
  show_image_preview: true,
  embroideries: {
    hat: ["Vaughn Automotive","GMC"],
    mens: [
     "Chevrolet Bowtie Stacked",
    "Ford",
    "GMC",
    "Toyota Stacked",
    "Vaughn Automotive",
    "Vaughn Value",
    "Vaughn Automotive Toyota",
    "Vaughn Brand Logos",  
],
    womens: [
    "Chevrolet Bowtie Stacked",
    "Ford",
    "GMC",
    "Toyota Stacked",
    "Vaughn Automotive",
    "Vaughn Value",
    "Vaughn Automotive Toyota",
    "Vaughn Brand Logos",   
],
    accessory: [],
    customs: [],
    office: [],
    service: [],
    sales: [],
    detail: [],
    bodyshop: [],
    parts: [],
    tshirts: ["Vaughn Automotive","Vaughn Brand Logos"],
  },
  email_recipients: [
    "rgreenberg@gpcorp.com", 
    "mwhite@vaughnvalue.com",
    "support@gpcorp.com",
    "shanell@gpcorp.com"
],
  stores: [
    {
      name: "Vaughn CDJR Bunkie",
      address: "1120 NW Main Street, Bunkie, LA 71322",
      code: "VAUCBK",
    },
    {
      name: "Vaughn Chevrolet Buick GMC Bunkie",
      address: "1102 NW Main Street, Bunkie, LA 71322",
      code: "VAUCBU",
    },
    {
      name: "Vaughn Chevrolet Lecompte",
      address: "1104 Hwy 71 S, Lecompte, LA 71346",
      code: "VAUCLE",
    },
    {
      name: "Vaughn Toyota of Bastrop",
      address: "2329 E Madison Ave, Bastrop, LA 71220",
      code: "VAUTBA",
    },
    {
      name: "Vaughn Chevrolet Buick Natchitoches",
      address: "1742 Highway 504, Natchitoches, LA 71457",
      code: "VAUCNA",
    },
    {
      name: "Vaughn Ford Lincoln",
      address: "835 Highway 165 South, Oakdale, LA 71463",
      code: "VAUFOA",
    },
    {
      name: "Vaughn Ford",
      address: "4303 Highway 19, Zachary, LA 70791",
      code: "VAUGOZ",
    },
    {
      name: "Vaughn Pre-Owned Alexandria",
      address: "4441 Jackson Street, Alexandria, LA 71303",
      code: "VAUPAL",
    },
    {
      name: "Vaughn Pre-Owned Alexandria",
      address: "4441 Jackson Street, Alexandria, LA 71303",
      code: "VAUPRE",
    },
  ],
  bypass_codes: ["VAUGHN"],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [{ name: "Richard Greenberg", phone: "678-287-1635" }],
  route_prefix: "/vaughn",
  paypal_not_supported: true,
  password: "VaughN",
};