export const catalog = [
    {
    code: "FRIENDSHIP-31SD",
    name: "Friendship Decal",
    fullname: "Stroke Dome Decal - chrome w/black imprint (5.75 in. x 1.3 in.)",
    colors: ["Chrome"],
    type: "customs",
    default_color: "Chrome", 
    description: "Maximum one box (enter '1' in the box below - 250/bx)",
    supportedStores: ["FRICBT"],   
    quantities: [250],
    pricing: {
      base: {
        price: 1.50,
      },
    },
  },
  {
    code: "FRIENDSHIP-31DCI",
    name: "Dog Decal",
    fullname: "Chrome Domecal w/ 4cp imprint (2.25 in. x 2.25 in.)",
    colors: ["Chrome"],
    type: "customs",
    default_color: "Chrome",
    description: "Maximum one box (enter '1' in the box below - 250/bx)",
    supportedStores: ["FRICBT"],    
    quantities: [250],
    pricing: {
      base: {
        price: 1.50,
      },
    },
  },
  {
    code: "FRIENDSHIP-34PE",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame (250 per box)",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Maximum one box (enter '1' in the box below)",
    supportedStores: ["FRICBT"],    
    quantities: [250],
    pricing: {
      base: {
        price: 0.69,
      },
    },
  },
  {
    code: "FRIHPR-FMS2-516400B",
    name: "Custom Paper Floor Mat",
    fullname: "Coated Paper Floor Mat w/black & 288 blue imprint (17 in. x 2 in.)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Minumum three boxes (enter '3' in the box below - 500/bx)",
    supportedStores: ["FRICBT"],    
    quantities: [500],
    pricing: {
      base: {
        price: 0.23,
      },
    },
  },
  {
    code: "FRIENDSHIP-33MRE",
    name: "Aluminum Plate",
    fullname: "Aluminum Plate with Full Color (12 in. x 6 in.)",
    colors: ["Aluminum"],
    type: "customs",
    default_color: "Aluminum",
    description: "Maximum one box (enter '1' in the box below - 50/bx)",
    supportedStores: ["FRICBT"],     
    quantities: [50],
    pricing: {
      base: {
        price: 3.65,
      },
    },
  },
  {
    code: "FRIENDSHIP-PLATE",
    name: "Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate with Full Color (12 in. x 6 in.)",
    colors: ["Yellow"],
    type: "customs",
    default_color: "Yellow",
    description: "Maximum one box (enter '1' in the box below - 250/bx)",
    supportedStores: ["FRICBT"],     
    quantities: [250],
    pricing: {
      base: {
        price: 0.75,
      },
    },
  },
  {
    code: "CP91L",
    name: "Port & Company Beanie",
    fullname: "Port & Company® Fleece-Lined Beanie Cap",
    colors: ["Athletic Oxford","Athletic Red", "Athletic Royal", "Black","Navy","Neon Green","White"],
    type: "hat",
    default_color: "Athletic Oxford",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 0.00 },
    },
  },
  {
    code: "CP95",
    name: "Port Authority® Cotton Beanie",
    fullname: "Port Authority® 100% Cotton Beanie",
    colors: ["Black","Graphite","Navy"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 0.00 },
    },
  },
  {
    code: "NE205",
    name: "New Era® Trucker Cap",
    fullname: "New Era® Snapback Trucker Cap (addt'l logos cost extra)",
    colors: ["Black","Graphite","Grey","Deep Navywt"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 0.00 },
    },
  },
  {
    code: "CP80",
    name: "Port & Co™ Six-Panel Cap",
    fullname: "Port & Co™ Six-Panel Twill Cap",
    colors: [
      "Athletic Gold",
      "Black",
      "Carolina Blue",
      "Charcoal",
      "Coyote Brown",
      "Hunter",
      "Kelly Green",
      "Khaki",
      "Navy",
      "Neon Pink",
      "Neon Yellow",
      "Orange",
      "Purple",
      "Red",
      "Royal",
      "Silver",
      "True Navy",
      "True Red",
      "White",
    ],
    type: "hat",
    default_color: "Athletic Gold",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 0.00 },
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee",
    fullname: "Sport-Tek PosiCharge Competitor Tee",
    colors: [
      "Atomic Blue",
      "Black",
      "Cardinal",
      "Carolina Blue",
      "Coyote Brown",
      "Deep Orange",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Maroon",
      "Neon Pink",
      "Olive Drab Green",
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "tshirts",
    default_color: "Atomic Blue",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
    },
  },
  {
    code: "PC61",
    name: "Port & Company® Tee",
    fullname: "Port & Company® Essential Tee",
    colors: [
      "Athletic Heather",
      "Brown",
      "Candy Pink",
      "Cardinal",
      "Carolina Blue",
      "Colonial Blue",
      "Charcoal",
      "Dk Green",
      "Deep Navy",
      "Gold",
      "Jet Black",
      "Lavender",
      "Medium Grey",
      "Navy",
      "Red",
      "Royal",
      "Turquoise",
      "White",
    ],
    type: "tshirts",
    default_color: "Athletic Heather",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
      "5XLarge": { price: 0.00 },
      "6XLarge": { price: 0.00 },
    },
  },
  {
    code: "PC61P",
    name: "Port & Co Pocket Tee",
    fullname: "Port & Company® Essential Pocket Tee",
    colors: ["Charcoal","Jet Black","Navy","Red","Royal","White"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
    },
  },
  {
    code: "S608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt",
    colors: [
      "Black",
      "Burgundy",
      "Clover Green",
      "Court Green",
      "Dk Green",
      "Light Blue",
      "Light Pink",
      "Navy",
      "Purple",
      "Red",
      "Royal",
      "Steel Grey",
      "Stone",
      "Strong Blue",
      "Teal Green",
      "Ultramarine Blue",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
      "5XLarge": { price: 0.00 },
      "6XLarge": { price: 0.00 },
    },
  },
  {
    code: "L608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Women's Long Sleeve Shirt",
    colors: [
      "Black",
      "Burgundy",
      "Clover Green",
      "Court Green",
      "Dk Green",
      "Light Blue",
      "Light Pink",
      "Navy",
      "Purple",
      "Red",
      "Royal",
      "Steel Grey",
      "Stone",
      "Strong Blue",
      "Teal Green",
      "Ultramarine Blue",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
      "5XLarge": { price: 0.00 },
      "6XLarge": { price: 0.00 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo",
    fullname: "Ladies Nike® Micro Pique Polo",
    colors: [
      "Anthracite", 
      "Black", 
      "Blue Tint",
      "Brilliant Orange",
      "Cool Grey",
      "Court Purple",
      "Game Royal",
      "Gorge Green",
      "Gym Blue",
      "Lucid Green",
      "Mint",
      "Navy",
      "Team Red",
      "Tidal Blue",
      "University Red",
      "Urban Lilac",
      "Valor Blue",
      "Varsity Maize",
      "Vivid Pink",
      "White",
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: [
        "Anthracite", 
        "Black", 
        "Blue Tint",
        "Brilliant Orange",
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gorge Green",
        "Gym Blue",
        "Lucid Green",
        "Mint",
        "Navy",
        "Team Red",
        "Tidal Blue",
        "University Red",
        "Urban Lilac",
        "Valor Blue",
        "Varsity Maize",
        "Vivid Pink",
        "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
   },
  },
  {
    code: "NKDC1963T",
    name: "Nike® Dri-FIT- TALL",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo - TALL SIZES",
    colors: [
        "Anthracite",
        "Black",
        "Cool Grey",
        "Game Royal",
        "Gym Blue",
        "Navy",
        "University Red",
        "Valor Blue",
        "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
       LT: { price: 0.00 },
       XLT: { price: 0.00 },
      "2XLT": { price: 0.00 },
      "3XLT": { price: 0.00 },
      "4XLT": { price: 0.00 },
    },
  },
  {
    code: "BOXLIDS",
    name: "Custom Color Lids",
    fullname: "Custom Color Gift Box Lids",
    colors: ["Black","Blue","Burgundy","Gold","Green","Orange","Pink","Purple","Red","Silver"],
    type: "accessory",
    default_color: "Black",   
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "G1640guar",
    name: "Stitched Leather Keychain",
    fullname: "Stitched Leather Laser Engraved Keychain",
    colors: ["Black", "Brown"],
    type: "accessory",
    default_color: "Black",   
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "CG1542",
    name: "Carbon Fiber Keychain",
    fullname: "Carbon Fiber Leather Keychain",
    colors: ["Black", "Blue", "Burgundy","Red"],
    type: "accessory",
    default_color: "Black",   
    quantities: [100, 250, 500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  }, 
  {
    code: "Q42971",
    name: "Metal Color Series",
    fullname: "Metal Color Series Keychain (2-sided imprint available)",
    colors: ["Blue","Grey","Green","Red"],
    type: "accessory",
    default_color: "Grey",   
    quantities: [100, 250, 500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "321",
    name: "Javalina Executive Pen",
    fullname: "Javalina Executive Pen (more colors available)",
    colors: ["Black","Blue","Green","Red"],
    type: "accessory",
    default_color: "Black",    
    quantities: [100, 250],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "307",
    name: "Macaw® Pen",
    fullname: "Macaw® Pen",
    colors: ["Black","Blue","Lime Green","Orange","Pink","Red"],
    type: "accessory",
    default_color: "Black",    
    quantities: [100, 250],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "42",
    name: "TALL Boy 16 oz. Coolie",
    fullname: "16 oz. Tall Boy Coolie (1-color imprint available)",
    colors: [
      "Black",
      "Burgundy",
      "Brown",
      "Carolina Blue",
      "Forest Green",
      "Gray",
      "Kelly Green",
      "Khaki",
      "Lime Green",
      "Navy",
      "Orange",
      "Red",
      "Magenta",
      "Purple",
      "White",
      "Yellow",
    ],
    type: "accessory",
    default_color: "Black",   
    quantities: [100, 250, 500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },  
  {
    code: "8163",
    name: "15 oz. Mug w/imprint",
    fullname: "15 oz. Ember Mug (Laser engraving & Silk-Screening available)",
    colors: ["Black","Cobalt Blue","Green","Lilac","Red","Royal","White"],
    type: "accessory",
    default_color: "Black",    
    quantities: [100, 250, 500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },  
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain (sold in boxes of 100 & 500)",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    quantities: [100, 500],
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "5470",
    name: "A/P Voucher Jacket",
    fullname: "9 in. x 12 in. A/P Voucher Jacket (DSA-540)",
    colors: ["Blue", "Buff", "Green", "Lavender", "Pink", "White"],
    type: "sales",
    default_color: "Buff",
    quantities: [100, 500],
    pricing: {
      base: {
        price: 0.0,
      },
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Self-Protecting Key Tags #200 (250 per box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "White",    
    pricing: {
      base: {
        price: 0.0,
      },
    },
  },
  {
    code: "FRIHPR-FMS2-516400B",
    name: "Custom Paper Floor Mat",
    fullname: "Coated Paper Floor Mat w/black & 288 blue imprint (17 in. x 2 in.)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    description: "Maximum quantity allowed per order is three boxes. Enter 1, 2, or 3 in the quantity box.",   
    supportedStores: ["FRICBT"],    
    quantities: [500],
    pricing: {
      base: {
        price: 0.23,
      },
    },
  },
  {
    code: "6000WD",
    name: "Seat Cover Wall Dispenser",
    fullname: "Seat Cover Wall Dispenser",
    colors: ["Black"],
    type: "service",
    default_color: "Black",    
    quantities: [1],
    pricing: {
      base: {
        price: 0.0,
      },
    },
  }, 
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250 per pack)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",    
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },
  {
    code: "EIT50",
    name: "Self-Locking Key Tags",
    fullname: "Self-Locking Key Tags (1000 per pack)",
    colors: ["Blue","Green","Orange","Red","Yellow","White"],
    type: "service",
    default_color: "Blue",
    pricing: {
      base: {
        price: 0.00,
      },
    },
  },         
  {
    code: "SDNC",
    name: "Service Numbers",
    fullname: "Mirror Hang Service Numbers (1000 per box)",
    colors: ["Blue","Green","Grey","Lime","Orange","Pink","Purple","Red","Tan","White","Yellow"],  
    type: "service",
    default_color: "Blue",    
    pricing: {
      base: {
        price: 0.0,
      },
    },
  }, 
];