export const catalog = [
  {
    code: "T475",
    name: "Sport-Tek Raglan Polo #T475",
    fullname: "Sport-Tek® Dry Zone® Raglan Polo (T475)",
    colors: ["Black", "True Navy","True Red","True Royal","White"],      
    type: "mens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 22.78 },
      Small: { price: 22.78 },
      Medium: { price: 22.78 },
      Large: { price: 22.78 },
      XLarge: { price: 22.78 },
      "2XLarge": { price: 24.78 },
      "3XLarge": { price: 28.78 },
      "4XLarge": { price: 30.78 },                       
    },
  },  
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Sport-Wick Micropique Polo (ST650)",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Red",
      "True Navy",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge"
    ],
    pricing: {
      Small: { price: 24.96 },
      Medium: { price: 24.96 },
      Large: { price: 24.96 },
      XLarge: { price: 24.96 },
      "2XLarge": { price: 27.96 },
      "3XLarge": { price: 31.96 },
      "4XLarge": { price: 35.96 },
      "5XLarge": { price: 39.96},
      "6XLarge": { price: 41.96},
    },
  },
  {
    code: "TST650",
    name: "Sport-Tek® TALL Polo #TST650",
    fullname: "Sport-Tek® Tall Micropique Sport-Wick® Polo (TST650)",
    colors: [
        "Black", 
        "Blue Lake",
        "Deep Red",
        "True Navy",
        "True Royal",
        "White"
    ],      
    type: "mens",
    default_color: "Black",
    sizes: [
      "LT",
      "XLT", 
      "2XLT", 
      "3XLT", 
      "4XLT",                 
    ],
    pricing: {
       LT: { price: 27.16 },
       XLT: { price: 29.16 },
      "2XLT": { price: 31.16 },
      "3XLT": { price: 33.16 },
      "4XLT": { price: 35.16 },                     
    },
  },  
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo #NKDC1963",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
      "Black",
      "Blue Tint",
      "Gym Blue",
      "Navy",
      "University Red",
      "Valor Blue",      
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 48.02 },
      Medium: { price: 48.02 },
      Large: { price: 48.02 },
      XLarge: { price: 48.02 },
      "2XLarge": { price: 50.02 },
      "3XLarge": { price: 54.02 },
      "4XLarge": { price: 56.02 },
    },
  },
  {
    code: "ST657",
    name: "Sport-Tek Long Sleeve Polo #ST657",
    fullname: "Sport-Tek® Long Sleeve Micropique Polo (ST657)",
    colors: [
      "Black",
      "Deep Red",
      "True Navy",
      "True Royal",
      "White"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",
    ],
    pricing: {
      Small: { price: 29.32 },
      Medium: { price: 29.32 },
      Large: { price: 29.32 },
      XLarge: { price: 29.32 },
      "2XLarge": { price: 31.32 },
      "3XLarge": { price: 35.32 },
      "4XLarge": { price: 37.32 },
    },
  },
  {
    code: "S659",
    name: "Port Authority® Shirt #S659",
    fullname: "Port Authority® Short Sleeve SuperPro™ Oxford Shirt (S659)",
    colors: [
      "Navy", 
      "Oxford Blue", 
      "White"
    ],
    type: "mens",
    default_color: "Navy",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge"
    ],
    pricing: {
      Small: { price: 36.88 },
      Medium: { price: 36.88 },
      Large: { price: 36.88 },
      XLarge: { price: 36.88 },
      "2XLarge": { price: 39.88 },
      "3XLarge": { price: 43.88 },
      "4XLarge": { price: 45.88 },
    },
  },
  {
    code: "W816",
    name: "Port Authority Long Sleeve #W816",
    fullname: "Port Authority Long Sleeve Nailhead Easy Care Shirt (W816)",
    colors: ["Mediterranean Blue", "Swiss Blue","White"],
    type: "mens",
    default_color: "Mediterranean Blue",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 39.48 },
      Medium: { price: 39.48 },
      Large: { price: 39.48 },
      XLarge: { price: 39.48 },
      "2XLarge": { price: 42.50 },
      "3XLarge": { price: 46.50 },
      "4XLarge": { price: 48.50 },
    },
  },
  {
    code: "BB18012",
    name: "Brooks Brothers® Shirt #BB18012",
    fullname: "Brooks Brothers® Wrinkle-Free Stretch Pinpoint Spread Collar Shirt (BB18012)",
    colors: ["Cobalt Blue", "Newport Blue","White"],
    type: "mens",
    default_color: "Cobalt Blue",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 67.00},
      Medium: { price: 67.00 },
      Large: { price: 67.00 },
      XLarge: { price: 67.00 },
      "2XLarge": { price: 70.00 },
      "3XLarge": { price: 74.00 },
      "4XLarge": { price: 76.00 },
    },
  },
  {
    code: "TM1MU410",
    name: "TravisMathew Performance Polo #TM1MU410",
    fullname: "TravisMathew Coto Performance Polo (TM1MU410)",
    colors: [
      "Beryl Grn Hthr",
      "Black",
      "Blue Nights",
      "Brilliant Blue Hthr",
      "Federal Blue",
      "Quiet Shade Gry Hthr",
      "Quiet Shade Gry Blk",
      "Royal Blue",
      "Vintage Indigo Blk",
      "White",
    ],
    type: "mens",
    default_color: "Beryl Grn Hthr",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge"
    ],
    pricing: {
      Small: { price: 69.00 },
      Medium: { price: 69.00 },
      Large: { price: 69.00 },
      XLarge: { price: 69.00 },
      "2XLarge": { price: 73.00 },
      "3XLarge": { price: 78.00 },
    },
  },
  {
    code: "K870",
    name: "Port Authority® 1/4-Zip #K870",
    fullname: "Port Authority® C-FREE® Cypress 1/4-Zip (K870)",
    colors: [
      "Deep Black",
      "Grey Steel",
      "True Navy"
    ],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge"
    ],
    pricing: {
      Small: { price: 44.70 },
      Medium: { price: 44.70 },
      Large: { price: 44.70 },
      XLarge: { price: 44.70 },
      "2XLarge": { price: 47.40 },
      "3XLarge": { price: 51.40 },
      "4XLarge": { price: 53.40 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    description: "$10 upcharge for Heather colors.",
    colors: [
      "Black",
      "Black Charcoal Heather",  
      "Deep Smoke",
      "Dress Blue Navy",
      "Navy Heather",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 42.62 },
      Medium: { price: 42.62 },
      Large: { price: 42.62 },
      XLarge: { price: 42.62 },
      "2XLarge": { price: 45.62 },
      "3XLarge": { price: 49.62 },
      "4XLarge": { price: 51.62 },
      "5XLarge": { price: 55.62 },
      "6XLarge": { price: 57.62 },
    },
  },
  {
    code: "L475",
    name: "Sport-Tek Raglan Polo #L475",
    fullname: "Sport-Tek® Women's Dry Zone® Raglan Polo (L475)",
    colors: [
      "Black", 
      "True Navy",
      "True Red",
      "True Royal",
      "White"
    ],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 22.78 },
      Small: { price: 22.78 },
      Medium: { price: 22.78 },
      Large: { price: 22.78 },
      XLarge: { price: 22.78 },
      "2XLarge": { price: 24.78 },
      "3XLarge": { price: 28.78 },
      "4XLarge": { price: 30.78 },                       
    },
  },
  {
    code: "LST550",
    name: "Sport-Tek® Competitor™ Polo #LST550",
    fullname: "Sport-Tek® Women's PosiCharge® Competitor™ Polo (LST550)",
    colors: [
      "Black", 
      "Carolina Blue",
      "Deep Red",
      "True Navy",
      "True Royal",
      "White"
    ],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 14.52 },
      Small: { price: 14.52 },
      Medium: { price: 14.52 },
      Large: { price: 14.52 },
      XLarge: { price: 14.52 },
      "2XLarge": { price: 17.62 },
      "3XLarge": { price: 21.62 },
      "4XLarge": { price: 23.62 },                       
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Sport-Wick® Polo #LST650",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick® Polo (LST650)",
    colors: [
      "Black", 
      "Blue Lake",
      "Deep Red",
      "True Navy",
      "True Royal",
      "White"
    ],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 24.96 },
      Small: { price: 24.96 },
      Medium: { price: 24.96 },
      Large: { price: 24.96 },
      XLarge: { price: 24.96 },
      "2XLarge": { price: 27.96 },
      "3XLarge": { price: 31.96 },
      "4XLarge": { price: 35.96 },                       
    },
  },
  {
    code: "NKDC1991",
    name: "Nike Dri-FIT Polo #NKDC1991",
    fullname: "Nike Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
    colors: [
      "Black",
      "Blue Tint",
      "Gym Blue",
      "Navy",
      "University Red",
      "Valor Blue",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge"
    ],
    pricing: {
      Small: { price: 48.02 },
      Medium: { price: 48.02 },
      Large: { price: 48.02 },
      XLarge: { price: 48.02 },
      "2XLarge": { price: 50.02 },
    },
  },
  {
    code: "TM1WX002",
    name: "TravisMathew Polo #TM1WX002",
    fullname: "TravisMathew Women's Coto Performance Polo (TM1WX002)",
    colors: [
      "Black",
      "Brilliant Blue Hthr",
      "Quiet Shade Grey Hthr",
      "Quiet Shade Gry Blk",
      "Vintage Indigo Blk"
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge"
    ],
    pricing: {
      Small: { price: 69.00 },
      Medium: { price: 69.00 },
      Large: { price: 69.00 },
      XLarge: { price: 69.00 },
      "2XLarge": { price: 73.00 },
    },
  },
  {
    code: "L540LS",
    name: "Port Authority® Long Sleeve Polo #L540LS",
    fullname: "Port Authority® Women's Silk Touch™ Performance Long Sleeve Polo (L540LS)",
    colors: [
      "Black", 
      "Navy",
      "Red",
      "Royal",  
    ],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 22.34 },
      Small: { price: 22.34 },
      Medium: { price: 22.34 },
      Large: { price: 22.34 },
      XLarge: { price: 22.34 },
      "2XLarge": { price: 25.34 },
      "3XLarge": { price: 29.34 },
      "4XLarge": { price: 31.34 },                       
    },
  },
  {
    code: "LW401",
    name: "Port Authority® Long Sleeve Shirt #LW401",
    fullname: "Port Authority® Women's Long Sleeve Performance Staff Shirt (LW401)",
    colors: ["True Navy"],      
    type: "womens",
    default_color: "True Navy",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 37.30 },
      Small: { price: 37.30 },
      Medium: { price: 37.30 },
      Large: { price: 37.30 },
      XLarge: { price: 37.30 },
      "2XLarge": { price: 40.30 },
      "3XLarge": { price: 44.30 },
      "4XLarge": { price: 46.30 },                       
    },
  },
  {
    code: "BB18001",
    name: "Brooks Brothers® Shirt #BB18001",
    fullname: "Brooks Brothers® Women's Wrinkle-Free Stretch Pinpoint Shirt (BB18001)",
    colors: ["Cobalt Blue","Newport Blue","White"],      
    type: "womens",
    default_color: "Cobalt Blue",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 71.53 },
      Small: { price: 71.53 },
      Medium: { price: 71.53 },
      Large: { price: 71.53 },
      XLarge: { price: 71.53 },
      "2XLarge": { price: 75.43 },
      "3XLarge": { price: 79.43 },
      "4XLarge": { price: 81.43 },                       
    },
  },
  {
    code: "LK584",
    name: "Port Authority® 1/4-Zip #LK584",
    fullname: "Port Authority® Women's Silk Touch™ Performance 1/4-Zip (LK584)",
    colors: ["Black SteelGrey","Navy SteelGrey","Royal SteelGrey","SteelGrey Black"],      
    type: "womens",
    default_color: "Black SteelGrey",
    halfColors: ['Black SteelGrey', 'Navy SteelGrey', 'Royal SteelGrey', 'SteelGrey Black'],
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 23.46 },
      Small: { price: 23.46 },
      Medium: { price: 23.46 },
      Large: { price: 23.46 },
      XLarge: { price: 23.46 },
      "2XLarge": { price: 26.46 },
      "3XLarge": { price: 30.46 },
      "4XLarge": { price: 32.46 },                       
    },
  },
  {
    code: "LST672",
    name: "Sport-Tek® 1/4-Zip #LST672",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick® 1/4-Zip (LST672)",
    colors: ["Black","True Navy","True Royal","White"],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"             
    ],
    pricing: {
      XSmall: {price: 29.38 },
      Small: { price: 29.38 },
      Medium: { price: 29.38 },
      Large: { price: 29.38 },
      XLarge: { price: 29.38 },
      "2XLarge": { price: 32.38 },
      "3XLarge": { price: 36.28 },
      "4XLarge": { price: 38.28 },                       
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Core Soft Shell Jacket (L317)",
    description: "$10 upcharge for Heather colors.",
    colors: [
      "Black",
      "Black Charcoal Heather",  
      "Deep Smoke",
      "Dress Blue Navy",
      "Navy Heather",
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 42.62 },
      Medium: { price: 42.62 },
      Large: { price: 42.62 },
      XLarge: { price: 42.62 },
      "2XLarge": { price: 45.62 },
      "3XLarge": { price: 49.62 },
      "4XLarge": { price: 51.62 },
      
    },
  },
  {
    code: "PC61",
    name: "Port & Company® Tee #PC61",
    fullname: "Port & Company® Essential Tee (PC61)",
    colors: [
      "Candy Pink",
      "Carolina Blue",
      "Colonial Blue",
      "Deep Marine",
      "Deep Navy",
      "Jet Black",
      "Lavender",
      "Light Blue",
      "Royal",           
      "Sangria",      
      "Steel Blue",
      "Stonewashed Blue",
      "Stonewashed Green",
      "Tundra Blue",
      "White"
    ],
    type: "tshirts",
    default_color: "Candy Pink",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 10.49 },
      Medium: { price: 10.49 },
      Large: { price: 10.49 },
      XLarge: { price: 10.49 },
      "2XLarge": { price: 12.99 },
      "3XLarge": { price: 14.99 },
      "4XLarge": { price: 15.99 },
      "5XLarge": { price: 16.99 },
      "6XLarge": { price: 17.99 }
    },
  },
  {
    code: "PC380",
    name: "Port & Co Perf Tee #PC380",
    fullname: "Port & Company Performance Tee (PC380)",
    colors: [
      "Carolina Blue",
      "Charcoal",
      "Deep Navy",
      "Grey Concrete",
      "Jet Black",
      "Kelly",
      "Neon Blue",
      "Neon Pink",
      "Red",
      "Royal",
      "Silver",
      "Team Purple",
      "True Royal",
      "White"
   ],
    type: "tshirts",    
    default_color: "Carolina Blue",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",
    ],
    pricing: {
      Small: { price: 11.99 },
      Medium: { price: 11.99 },
      Large: { price: 11.99 },
      XLarge: { price: 11.99 },
      "2XLarge": { price: 13.99 },
      "3XLarge": { price: 16.99 },
      "4XLarge": { price: 17.99 },
    },
  },
  {
    code: "ST360",
    name: "Sport-Tek® Heather Tee #ST360",
    fullname: "Sport-Tek® Heather Contender™ Tee (ST360)",
    colors: ["Scarlet Hthr", "True Royal Hthr","Vintage Hthr"],
    type: "tshirts",
    default_color: "Scarlet Hthr",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
  ],
    pricing: {
      Small: { price: 12.26 },
      Medium: { price: 12.26 },
      Large: { price: 12.26 },
      XLarge: { price: 12.26 },
      "2XLarge": { price: 14.26 },
      "3XLarge": { price: 18.26 },
      "4XLarge": { price: 20.26 },      
    },
  },
  {
    code: "PC380LS",
    name: "Port & Co Perf L/S Tee #PC380LS",
    fullname: "Port & Co™ Long Sleeve Performance Tee (PC380LS)",
    colors: [
      "Carolina Blue",
      "Charcoal",
      "Deep Navy",
      "Grey Concrete",
      "Jet Black",
      "Red",
      "Royal",
      "Silver",
      "True Royal",
      "White"
   ],
    type: "tshirts",   
    default_color: "Carolina Blue",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",
    ],
    pricing: {
      Small: { price: 14.99 },
      Medium: { price: 14.99 },
      Large: { price: 14.99 },
      XLarge: { price: 14.99 },
      "2XLarge": { price: 16.99 },
      "3XLarge": { price: 18.99 },
      "4XLarge": { price: 19.99 },
    },
  },
  {
    code: "GILNLA-34PEU-367055",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",   
    supportedStores: ["GILNLA","GILVEL","GILHAL","GILNOP","GILSLA","GILVLA"],
    quantities: [2000, 3000, 5000],
    pricing: {
      base: {
        price: 0.49,
      },
    },
  },
  {
    code: "GILNLA-33P-388416A",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge Plastic Plate - White w/black imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",    
    supportedStores: ["GILNLA","GILVEL","GILHAL","GILNOP","GILSLA","GILVLA"],
    quantities: [2000, 3000, 5000],
    pricing: {
      base: {
        price: 0.49,
      },
    },
  },
];