export const catalog = [
  {
    code: "CP91L",
    name: "Port & Company Beanie",
    fullname: "Port & Company® Fleece-Lined Beanie Cap",
    colors: ["Athletic Oxford","Athletic Red", "Athletic Royal", "Black","Navy","Neon Green","White"],
    type: "hat",
    default_color: "Athletic Oxford",    
    sizes: {
      OSFA: 0.00,
    },
  },
  {
    code: "CP95",
    name: "Port Authority® Cotton Beanie",
    fullname: "Port Authority® 100% Cotton Beanie",
    colors: ["Black","Graphite","Navy"],
    type: "hat",
    default_color: "Black",
    sizes: {
      OSFA: 0.00,
    },
  },
  {
    code: "NE205",
    name: "New Era® Trucker Cap",
    fullname: "New Era® Snapback Trucker Cap (addt'l logos cost extra)",
    colors: ["Black","Graphite","Grey","Deep Navywt"],
    type: "hat",
    default_color: "Black",
    sizes: {
      OSFA: 0.00,
    },
  },
  {
    code: "CP80",
    name: "Port & Co™ Six-Panel Cap",
    fullname: "Port & Co™ Six-Panel Twill Cap",
    colors: [
      "Athletic Gold",
      "Black",
      "Carolina Blue",
      "Charcoal",
      "Coyote Brown",
      "Hunter",
      "Kelly Green",
      "Khaki",
      "Navy",
      "Neon Pink",
      "Neon Yellow",
      "Orange",
      "Purple",
      "Red",
      "Royal",
      "Silver",
      "True Navy",
      "True Red",
      "White",
    ],
    type: "hat",
    default_color: "Athletic Gold",
    sizes: {
      OSFA: 0.00,
    },
  },
  {
    code: "C402",
    name: "Port Authority Trucker Cap",
    fullname: "Port Authority® Snapback Trucker Cap",
    colors: [
      "Black",
      "Black GreySteel",
      "Black Tan",
      "Black White",
      "Flame Red",
      "FlameRed White",
      "Grey Steel",
      "Gusty Grey",
      "LightKhaki White",
      "Olive Drab Green",
      "Patriot Blue",
      "PatriotBlue White",
      "True Navy",
      "TruePink White",
      "Woodland Camo",
    ],
    type: "hat",
    default_color: "Black",
    halfColors: [
      'Black GreySteel',
      'Black Tan',
      'Black White',
      'FlameRed White',
      'LightKhaki White',
      'PatriotBlue White',
      'TruePink White',
    ],
    sizes: {
      OSFA: 0.0,
    },
  },
  {
    code: "STC39",
    name: "Sport-Tek® Trucker Cap",
    fullname: "Sport-Tek® YP Classics® Retro Trucker Cap (addt'l logos cost extra)",
    colors: ["Black","Graphite","True Navy True Navy","True Navy White","White"],
    type: "hat",
    default_color: "Black",
    sizes: {
      OSFA: 0.00,
    },
  },
  {
    code: "112",
    name: "Richardson Trucker Cap",
    fullname: "Richardson Snapback Trucker Cap (addt'l logos cost extra)",
    colors: ["Amber Gold","Black","Charcoal","Loden","Maroon","Navy","White"],
    type: "hat",
    default_color: "Amber Gold",
    sizes: {
      OSFA: 0.00,
    },
  },
  {
    code: "PC55P",
    name: "Port & Company Pocket Tee",
    fullname: "Port & Company® Core Blend Pocket Tee",
    colors: ["Ash","Athletic Maroon","Jet Black"],
    type: "tshirts",
    sub_category: "tshirt",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee",
    fullname: "Sport-Tek PosiCharge Competitor Tee",
    colors: [
      "Atomic Blue",
      "Black",
      "Cardinal",
      "Carolina Blue",
      "Coyote Brown",
      "Deep Orange",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Maroon",
      "Neon Pink",
      "Olive Drab Green",
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "tshirts",
    default_color: "Atomic Blue",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "PC61",
    name: "Port & Company® Tee",
    fullname: "Port & Company® Essential Tee",
    colors: [
      "Athletic Heather",
      "Brown",
      "Candy Pink",
      "Cardinal",
      "Carolina Blue",
      "Colonial Blue",
      "Charcoal",
      "Dk Green",
      "Deep Navy",
      "Gold",
      "Jet Black",
      "Lavender",
      "Medium Grey",
      "Navy",
      "Red",
      "Royal",
      "Turquoise",
      "White",
    ],
    type: "tshirts",
    default_color: "Athletic Heather",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "PC61P",
    name: "Port & Co Pocket Tee",
    fullname: "Port & Company® Essential Pocket Tee",
    colors: ["Charcoal","Jet Black","Navy","Red","Royal","White"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,      
    },
  },
  {
    code: "LPC61",
    name: "Port & Co™ Essential Tee",
    fullname: "Port & Co™ Women's Essential Tee",
    colors: [
      "Aquatic Blue",
      "Athletic Maroon",
      "Candy Pink",
      "Charcoal",
      "Jet Black",
      "Kelly Green",
      "Lavender",
      "Natural",
      "Navy",
      "Purple",
      "Red",
      "Royal",
      "White",
    ],
    type: "tshirts",
    default_color: "Aquatic Blue",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
   },
  },
  {
    code: "LST350",
    name: "Sport-Tek® Competitor™ Tee",
    fullname: "Sport-Tek® Women's PosiCharge® Competitor™ Tee",
    colors: [
      "Atomic Blue",
      "Black",
      "Cardinal",
      "Carolina Blue",
      "Deep Orange",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Neon Orange",
      "Neon Pink",
      "Neon Yellow",
      "Silver",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "tshirts",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "PC78H",
    name: "Port & Co™ Sweatshirt",
    fullname: "Port & Co™ Core Fleece Pullover Hooded Sweatshirt",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  }, 
  {
    code: "LPC78H",
    name: "Port & Co™ Sweatshirt",
    fullname: "Port & Co™ Women's Core Fleece Pullover Hooded Sweatshirt",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },   
  {
    code: "J325",
    name: "Port Authority® Vest",
    fullname: "Port Authority® Core Soft Shell Vest",
    colors: ["Battleship Grey","Black","Black Charcoal Heather","Dress Blue Navy"],
    type: "mens",
    default_color: "Battleship Grey",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "L325",
    name: "Port Authority® Vest",
    fullname: "Port Authority® Women's Core Soft Shell Vest",
    colors: ["Battleship Grey","Black","Black Charcoal Heather","Dress Blue Navy","Marshmallow"],
    type: "womens",
    default_color: "Battleship Grey",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "F236",
    name: "Port Authority® Vest",
    fullname: "Port Authority ® Sweater Fleece Vest",
    colors: ["Black Heather","Grey Heather"],
    type: "mens",
    default_color: "Black Heather",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "L236",
    name: "Port Authority® Vest",
    fullname: "Port Authority ® Women's Sweater Fleece Vest",
    colors: ["Black Heather","Grey Heather"],
    type: "womens",
    default_color: "Black Heather",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "BB18000",
    name: "Brooks Brothers® Shirt",
    fullname: "Brooks Brothers® Wrinkle-Free Stretch Pinpoint Shirt",
    colors: ["Cobalt Blue", "Deep Black","Newport Blue","White"],
    type: "mens",
    default_color: "Cobalt Blue",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "BB18002",
    name: "Brooks Brothers® Shirt",
    fullname: "Brooks Brothers® Wrinkle-Free Nailhead Shirt",
    colors: ["Club Green","Cobalt Blue","Deep Black", "Navy Blazer","Newport Blue", "White"],
    type: "mens",
    default_color: "Club Green",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "BB18003",
    name: "Brooks Brothers® Shirt",
    fullname: "Brooks Brothers® Women's Wrinkle-Free Nailhead Shirt",
    colors: ["Club Green","Cobalt Blue","Deep Black", "Navy Blazer","Newport Blue", "White"],
    type: "womens",
    default_color: "Club Green",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "S659",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Short Sleeve SuperPro™ Oxford Shirt",
    colors: ["Black", "Navy","Oxford Blue","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "S608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt",
    colors: [
      "Black",
      "Burgundy",
      "Clover Green",
      "Court Green",
      "Dk Green",
      "Light Blue",
      "Light Pink",
      "Navy",
      "Purple",
      "Red",
      "Royal",
      "Steel Grey",
      "Stone",
      "Strong Blue",
      "Teal Green",
      "Ultramarine Blue",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "L608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Women's Long Sleeve Shirt",
    colors: [
      "Black",
      "Burgundy",
      "Clover Green",
      "Court Green",
      "Dk Green",
      "Light Blue",
      "Light Pink",
      "Navy",
      "Purple",
      "Red",
      "Royal",
      "Steel Grey",
      "Stone",
      "Strong Blue",
      "Teal Green",
      "Ultramarine Blue",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "LK110",
    name: "Port Authority® Mesh Polo",
    fullname: "Port Authority® Women's Dry Zone® UV Micro-Mesh Polo",
    colors: ["Deep Black", "Graphite", "True Royal", "Rich Red","White"],
    type: "womens",
    default_color: "Deep Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,      
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Microqique Polo",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: ["Black", "Grey Concrete", "Iron Grey", "True Red"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Lime Shock",
      "Maroon",
      "Purple",
      "Texas Orange",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "Vegas Gold",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "TST650",
    name: "Sport-Tek® Polo - TALL",
    fullname: "Sport-Tek® TALL Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",      
      "Deep Red",
      "Forest Green",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",      
      "Maroon",
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",    
    sizes: {
      LT: 0.00,
      XLT: 0.00,
      "2XLT": 0.00,
      "3XLT": 0.00,
      "4XLT": 0.00,
     
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Light Pink",
      "Lime Shock",
      "Maroon",
      "Pink Raspberry",
      "Purple",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "ST657",
    name: "Sport-Tek LS Polo",
    fullname: "Sport-Tek® Long Sleeve Micropique Polo",
    colors: [
      "Black",
      "Deep Red",
      "Forest Green",
      "Iron Grey",
      "Maroon",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "L540LS",
    name: "Port Authority® Polo",
    fullname: "Port Authority Womens Long Sleeve Polo",
    colors: [
      "Black",
      "Bright Purple",
      "Carolina Blue",
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "267020",
    name: "Nike® Dri-FIT Classic Polo",
    fullname: "Nike® Dri-FIT Classic Polo",
    colors: ["Black","Court Blue","Light Blue","Midnight Navy","Varsity Red","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  }, 
  {
    code: "286772",
    name: "Nike® Dri-FIT Classic Polo",
    fullname: "Nike® Women's Dri-FIT Classic Polo",
    colors: ["Black","Light Blue","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,          
    },
  },  
  {
    code: "883681",
    name: "Nike® Dri-FIT Legacy Polo",
    fullname: "Nike® Dri-FIT Legacy Polo (addt'l logos cost extra)",
    colors: ["Black","Dark Grey","Game Royal","Gym Red","Light Photo Blue","Midnight Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },  
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo",
    fullname: "Ladies Nike® Micro Pique Polo",
    colors: [
      "Anthracite", 
      "Black", 
      "Blue Tint",
      "Brilliant Orange",
      "Cool Grey",
      "Court Purple",
      "Game Royal",
      "Gorge Green",
      "Gym Blue",
      "Lucid Green",
      "Mint",
      "Navy",
      "Team Red",
      "Tidal Blue",
      "University Red",
      "Urban Lilac",
      "Valor Blue",
      "Varsity Maize",
      "Vivid Pink",
      "White",
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: [
        "Anthracite", 
        "Black", 
        "Blue Tint",
        "Brilliant Orange",
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gorge Green",
        "Gym Blue",
        "Lucid Green",
        "Mint",
        "Navy",
        "Team Red",
        "Tidal Blue",
        "University Red",
        "Urban Lilac",
        "Valor Blue",
        "Varsity Maize",
        "Vivid Pink",
        "White",
    ],
    type: "mens",
    default_color: "Anthracite",    
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
   },
  },
  {
    code: "NKDC1963T",
    name: "Nike® Dri-FIT- TALL",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo - TALL SIZES",
    colors: [
        "Anthracite",
        "Black",
        "Cool Grey",
        "Game Royal",
        "Gym Blue",
        "Navy",
        "University Red",
        "Valor Blue",
        "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
       LT: 0.00,
       XLT: 0.00,
      "2XLT": 0.00,
      "3XLT": 0.00,
      "4XLT": 0.00,
    },
  },
  {
    code: "NKAH6266",
    name: "Nike Textured Polo",
    fullname: "Nike Dri-FIT Hex Textured Polo",
    colors: ["Black","Court Blue","Dark Grey","Game Royal","Gym Red","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00, 
      "3XLarge": 0.00,
      "4XLarge": 0.00,  
    },
  },
  {
    code: "NKBV6042",
    name: "Nike® Essential Polo",
    fullname: "Nike® Dry Essential Solid Polo",
    colors: ["Black", "Game Royal", "Midnight Navy","University Blue", "University Red", "White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },
   {
    code: "TM1MY399",
    name: "TravisMathew Polo",
    fullname: "TravisMathew Bayfront Solid Polo",
    colors: ["Black","Dark Grey","Insignia Blue","Roan Rouge"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,          
    },
  },
  {
    code: "TM1MU410",
    name: "TravisMathew Performance Polo",
    fullname: "TravisMathew Coto Performance Polo",
    colors: ["Beryl Grn Hthr","Black","Blue Nights","Brilliant Blue Hthr","Federal Blue",
    "Quiet Shade Gry Hthr","Quiet Shade Gry Blk","Vintage Indigo Blk","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,          
    },
  },
  {
    code: "OG101",
    name: "OGIO® - Caliber2.0 Polo",
    fullname: "OGIO® - Caliber2.0 Polo",
    colors: ["Blacktop"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "LOG101",
    name: "OGIO® - Jewel Polo",
    fullname: "OGIO® - Jewel Polo",
    colors: ["Blacktop"],
    type: "womens",
    default_color: "Blacktop",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
   {
    code: "A231",
    name: "Adidas Performance Polo",
    fullname: "Adidas Women's Performance Polo",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "NKDC2105",
    name: "Nike Long Sleeve Polo",
    fullname: "Nike Women's Dri-FIT Micro Pique 2.0 Long Sleeve Polo",
    colors: ["Anthracite","Black","Game Royal","Gym Blue","Navy","University Red","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,      
    },
  },
  {
    code: "TM1WW003",
    name: "TravisMathew 1/4-Zip",
    fullname: "TravisMathew Women's Crestview 1/4-Zip",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,      
    },
  },
  {
    code: "A476",
    name: "Adidas 1/4-Zip Pullover",
    fullname: "Women's Lightweight Mélange Quarter-Zip Pullover",
    colors: ["Black Melange"],
    type: "womens",
    default_color: "Black Melange",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,      
    },
  },
  {
    code: "NF0A8ENQ",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Women's Ambition 1/4-Zip",
    colors: ["TNF Black"],
    type: "womens",
    default_color: "TNF Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "K110",
    name: "Port Authority UV Polo",
    fullname: "Port Authority® Dry Zone® UV Micro-Mesh Polo",
    colors: [
      "Carolina Blue",
      "Coastal Blue",
      "Deep Black",
      "Graphite",
      "Gusty Grey",
      "Rich Red",
      "River Blue Navy",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Deep Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "ST740",
    name: "Sport-Tek Polo",
    fullname: "Sport-Tek® UV Micropique Polo",
    colors: ["Black","Deep Red","Graphite","Grey Concrete",
      "True Navy","True Royal","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "A230",
    name: "Adidas Performance Polo",
    fullname: "Adidas Men's Performance Polo",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "NKDC2104",
    name: "Nike Long Sleeve Polo",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Long Sleeve Polo",
    colors: ["Anthracite","Black","Game Royal","Gym Blue","Navy","University Red","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "PC61LS",
    name: "Long Sleeve Tee",
    fullname: "Port & Company® Long Sleeve Essential Tee",
    colors: [
      "Ash", 
      "Athletic Heather", 
      "Cardinal", 
      "Charcoal", 
      "Deep Navy",
      "Jet Black",
      "Navy",
      "Red",
      "Royal",
      "White"
    ],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "PC90H",
    name: "Hooded Sweatshirt",
    fullname: "Port & Company® Essential Fleece Pullover Hooded Sweatshirt",
    colors: ["Athletic Heather","Cardinal","Charcoal",
      "Drk Hthr Gry","Jet Black","Navy","Red","Royal","White"],
    type: "mens",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "F700",
    name: "Raglan Fleece",
    fullname: "Port Authority® C-FREE® Raglan Fleece",
    colors: ["Deep Black", "Grey Steel", "True Navy"],
    type: "mens",
    default_color: "Deep Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "TM1MZ339",
    name: "TravisMathew 1/4-Zip",
    fullname: "TravisMathew Coveside 1/4-Zip",
    colors: ["Black", "Blue Nights", "Drk Gry Hthr", "Light Blue Hthr"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,           
    },
  },  
  {
    code: "K805",
    name: "Port Authority® 1/4-Zip Pullover",
    fullname: "Port Authority® 1/4-Zip Pullover",
    colors: ["Black", "Iron Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "A475",
    name: "Adidas 1/4-Zip Pullover",
    fullname: "Men's Lightweight Mélange Quarter-Zip Pullover",
    colors: ["Black Melange"],
    type: "mens",
    default_color: "Black Melange",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,      
    },
  },
  {
    code: "A708",
    name: "Adidas 1/4-Zip Pullover",
    fullname: "Men's Textured Stripe Quarter-Zip Pullover",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,      
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Ambition 1/4-Zip",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "NF0A8ENJ",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Aim 1/4-Zip Fleece",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "L805",
    name: "Port Authority® Pullover",
    fullname: "Port Authority® Women's Vertical Texture Full-Zip Jacket",
    colors: ["Black", "Iron Grey", "Regatta Blue", "True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black", "Battleship Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Battleship Grey", "Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "NF0A88D5",
    name: "NF® Soft Shell Jacket",
    fullname: "The North Face® Chest Logo Ridgewall Soft Shell Jacket",
    colors: ["Shady Blue","TNF Black","TNF Drk Gry Hthr","Urban Navy Hthr"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "J333",
    name: "Torrent Waterproof Jacket",
    fullname: "Port Authority® Torrent Waterproof Jacket",
    colors: ["Black", "Engine Red","Magnet","True Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },
  {
    code: "NKDR1543",
    name: "Nike® Hooded Jacket",
    fullname: "Nike® Hooded Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },
  {
    code: "J335",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Hooded Core Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      XSmall: 0.00,
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },
  {
    code: "L335",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Women's Hooded Core Soft Shell Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      XSmall: 0.00,
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,     
    },
  },
  {
    code: "NF0A88D4",
    name: "NF® Soft Shell Jacket",
    fullname: "The North Face® Women's Chest Logo Ridgewall Soft Shell Jacket",
    colors: ["TNF Black","TNF Blackberry Wine","TNF Drk Gry Hthr"],
    type: "womens",
    default_color: "TNF Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,         
    },
  },
  {
    code: "BOXLIDS",
    name: "Custom Color Lids",
    fullname: "Custom Color Gift Box Lids",
    colors: ["Black","Blue","Burgundy","Gold","Green","Orange","Pink","Purple","Red","Silver"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "G1640guar",
    name: "Stitched Leather Keychain",
    fullname: "Stitched Leather Laser Engraved Keychain",
    colors: ["Black", "Brown"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "CG1542",
    name: "Carbon Fiber Keychain",
    fullname: "Carbon Fiber Leather Keychain",
    colors: ["Black", "Blue", "Burgundy","Red"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,     
    },
  },
  {
    code: "CG2240",
    name: "Carbon Fiber Strap",
    fullname: "Carbon Fiber Strap Metal Keychain",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,     
    },
  },
  {
    code: "Q42971",
    name: "Metal Color Series",
    fullname: "Metal Color Series Keychain (2-sided imprint available)",
    colors: ["Blue","Grey","Green","Red"],
    type: "accessory",
    default_color: "Grey",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,     
    },
  },
  {
    code: "SET1020",
    name: "Keychain & Pen Set",
    fullname: "Metal Leather Keychain & Ballpoint Pen Set",
    colors: ["Black","Blue","Brown","Burgundy","Green","Orange","Pink","Purple","Red"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "SET2024",
    name: "Keychain Gift Set",
    fullname: "Metal Leather Keychain Gift Set (logo imprinted on box top & keychains)",
    colors: ["Black","Blue","Burgundy","Green","Orange","Pink","Purple","Red"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "SET4055",
    name: "Keychain & Pen Gift Set",
    fullname: "Leather Keychain & Fiber Ballpoint Stylus Gift Set (logo imprinted all pieces)",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "CG2640",
    name: "Leather Loop Keychain",
    fullname: "Leather Loop Metal Keychain",
    colors: ["Black", "Brown"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,     
    },
  },
  {
    code: "04015",
    name: "10 oz. Tumbler",
    fullname: "Perfect Fit Tumbler (Perfect for Keurig Machines & Cup Holders",
    colors: ["Black","Blue","Burgundy","Gunmetal","Navy","Red"],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
    },
  },
  {
    code: "04032",
    name: "20 oz. Revolve Tumbler",
    fullname: "20 oz. Revolve Tumbler",
    colors: ["Black","Blue","Burgundy","Green","Navy","Red","Silver","White"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
    },
  },
  {
    code: "5790",
    name: "20 oz. Himalayan Tumbler",
    fullname: "20 oz. Himalayan Tumbler",
    colors: ["Black","Fuchsia","Gold","Gray","Green","Maroon",
      "Navy","Orange","Purple","Red","Silver","Teal","White"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
    },
  },
  {
    code: "6645",
    name: "16 oz. Stadium Cup",
    fullname: "16 oz. Rally Stadium Cups (large imprint area)",
    colors: ["Black","Blue","Maroon","Red","White"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
    },
  },
  {
    code: "6648",
    name: "20 oz. Stadium Cup",
    fullname: "20 oz. Rally Stadium Cups (large imprint area)",
    colors: ["Black","Blue","Maroon","Red","White"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
    },
  },
  {
    code: "040110",
    name: "Grip Water Bottle",
    fullname: "24 oz. Grip Water Bottle",
    colors: ["Black","Blue","Burgundy","Gold","Green","Navy","Pink","Purple","Red","Silver"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,        
    },
  },
  {
    code: "5706",
    name: "16 oz. Swig Bottle",
    fullname: "16 oz. Swig Stainless Steel Bottles",
    colors: ["Black","Blue","Lime","Navy","Orange","Purple","Red","Silver","White"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
    },
  },  
  {
    code: "5726",
    name: "26 oz. Swig Bottle",
    fullname: "26 oz. Swig Stainless Steel Bottles",
    colors: ["Black","Silver"],
    type: "accessory",
    default_color: "Black",
    sizes: {
       100: 0.00,
    },
  },
  {
    code: "1000B",
    name: "Foam Koozies",
    fullname: "Collapsible Foam Koozies (1-color & 4CP available)",
    colors: ["Colors"],
    type: "accessory",
    default_color: "Colors",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,         
    },
  },  
  {
    code: "42",
    name: "TALL Boy 16 oz. Coolie",
    fullname: "16 oz. Tall Boy Coolie (1-color imprint available)",
    colors: [
      "Black",
      "Burgundy",
      "Brown",
      "Carolina Blue",
      "Forest Green",
      "Gray",
      "Kelly Green",
      "Khaki",
      "Lime Green",
      "Navy",
      "Orange",
      "Red",
      "Magenta",
      "Purple",
      "White",
      "Yellow",
    ],
    type: "accessory",
    default_color: "Black",   
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,         
    },
  },  
  {
    code: "8163",
    name: "15 oz. Mug w/imprint",
    fullname: "15 oz. Ember Mug (Laser engraving & Silk-Screening available)",
    colors: ["Black","Cobalt Blue","Green","Lilac","Red","Royal","White"],
    type: "accessory",
    default_color: "Black",    
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "6301",
    name: "11 oz. Ceramic Mug",
    fullname: "11 oz. Ceramic Coffee Mug",
    colors: ["Black","Green","Navy","White"],
    type: "accessory",
    default_color: "Black",    
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "321",
    name: "Javalina Executive Pen",
    fullname: "Javalina Executive Pen (more colors available)",
    colors: ["Black","Blue","Green","Red"],
    type: "accessory",
    default_color: "Black",    
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "307",
    name: "Macaw® Pen",
    fullname: "Macaw® Pen",
    colors: ["Black","Blue","Lime Green","Orange","Pink","Red"],
    type: "accessory",
    default_color: "Black",    
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "291",
    name: "Aquarius Comfort Pen",
    fullname: "Aquarius Comfort Pen",
    colors: ["Black","Blue","Grey","Red"],
    type: "accessory",
    default_color: "Black",    
    sizes: {
       100: 0.00,
       250: 0.00,
       500: 0.00,
      1000: 0.00,
      1500: 0.00,
    },
  },
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "office",
    default_color: "Blue",
    sizes: {
      100: 0.00,
      500: 0.00,
    },
  },
  {
    code: "5470",
    name: "A/P Voucher Jacket",
    fullname: "9 in. x 12 in. A/P Voucher Jacket (DSA-540)",
    colors: ["Blue", "Buff", "Green", "Lavender", "Pink", "White"],
    type: "sales",
    default_color: "Buff",
    sizes: {
      100: 0.0,
      500: 0.0,
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Self-Protecting Key Tags #200 (250 per box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# boxes": 0.0,
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100 per pack)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# packs": 0.0,
    },
  }, 
  {
    code: "250",
    name: "Poly Key Tag",
    fullname: "Poly Tag Key Tag #250 (250 per box)",
    colors: ["White", "Yellow"],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# boxes": 0.0,
    },
  }, 
  {
    code: "240",
    name: "Poly Stock Stickers",
    fullname: "Poly Stock Stickers #240 (250 per box)",
    colors: ["White", "Yellow"],
    type: "sales",
    default_color: "White",   
    sizes: {
      "# boxes": 0.0,
    },
  }, 
  {
    code: "226",
    name: "Combo Key Tags",
    fullname: "Combo Key Tags - Numbered (125 per box)",
    colors: ["Beige","Blue","Green","Grey","Lilac",
      "Orange","Red","White","Yellow"],   
    type: "sales",
    default_color: "Beige",  
    sizes: {
      "# boxes": 0.00,
    },
  }, 
  {
    code: "DKTB",
    name: "Stock-In Numbers",
    fullname: "Stock-In Numbers (250 per pack)",
    colors: ["White"],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# packs": 0.00,
    },
  }, 
   {
    code: "650B",
    name: "Stock Number Signs",
    fullname: "Stock Number Mini Signs 6in x 3in #650 (250 per pack)",
    colors: ["White", "Yellow"],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# packs": 0.00,
    },
  }, 
  {
    code: "225",
    name: "Top Stripe Key Tags",
    fullname: "Top Stripe Key Tags #225 (250 per pack)",
    colors: ["Black","Blue","Green","Magenta","Orange","Red","Yellow"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "GP415",
    name: "Clip-On Window Flag",
    fullname: "Clip-On U.S. Flag - (12 per pack - 3 pack min.)",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "GP418ACURA",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - ACURA",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BMW",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BMW",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BUICK",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BUICK",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418CHEVROLET",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - CHEVROLET",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418CHRYSLER",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - CHRYSLER",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418DODGE",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - DODGE",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418RAM",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - DODGE RAM",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418FORD",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - FORD",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418FORDCRT",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - FORD CERTIFIED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418GMC",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - GMC",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418GMCERT",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - GM CERTIFIED USED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418HONDA",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - HONDA",
    colors: ["Strong Blue"],
    type: "sales",
    default_color: "Strong Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418HONDACERT",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - HONDA CERTIFIED PRE-OWNED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418HYUNDAI",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - HYUNDAI",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418INFINITI",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - INFINITI",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
    {
    code: "GP418JEEP",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - JEEP",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418KIA",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - KIA",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418LEXUS",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - LEXUS",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418LINCOLN",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - LINCOLN",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418MAZDA",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - MAZDA",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418MERCEDES",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - MERCEDES",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418NISSAN",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - NISSAN",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418TOYOTA",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - TOYOTA",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418VW",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - VOLKSWAGEN",
    colors: ["Navy"],
    type: "sales",
    default_color: "Navy",  
    sizes: {
      1: 0.00,
    },
  },
   {
    code: "GP418ASADV",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - AS ADVERTISED",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BWCHK",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BLACK/WHITE CHECKERED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BLWCHK",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BLUE/WHITE CHECKERED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418RDWCHK",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - RED/WHITE CHECKERED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BESTBUYS",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BEST BUYS HERE",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BHPH",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BUY HERE PAY HERE",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418BHPH2",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - BUY HERE PAY HERE",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418CRFX",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - CARFAX",
    colors: ["Strong Blue"],
    type: "sales",
    default_color: "Strong Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418CERTPRE",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - CERTIFIED PRE-OWNED",
    colors: ["Blue","Red"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418CERTPREO",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - CERTIFIED PRE-OWNED CDJR",
    colors: ["Gold"],
    type: "sales",
    default_color: "Gold",  
    sizes: {
      1: 0.00,
    },
  },    
  {
    code: "GP418GRTMPG",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - GREAT MPG",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418HOTBUYS",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - HOT BUYS",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418HYBRID",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - HYBRID",
    colors: ["Green"],
    type: "sales",
    default_color: "Green",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP418LOOK",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - LOOK",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418RTSALE",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - RED TAG SALE",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418SALE",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - SALE",
    colors: ["Blue","Red"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418PTSALE",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - PATRIOTIC SALE",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418ESPANOL",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - SE HABLA ESPANOL",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418SMILEY",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - SMILEY FACE",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418STPSVNW",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - STOP SAVE NOW",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP418USDCRS",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - USED CARS",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP418WEBYCRS",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - WE BUY CARS",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP418WEFNCE",
    name: "Clip-On Window Flag",
    fullname: "Clip-On Window Flag - WE FINANCE",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CG",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - LEASING (also avail 2-sided, with or w/o sleeves)",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CM",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - LOW PRICES",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CR",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - NEW CARS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CO",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - NEW TRUCKS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CJ",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - OPEN",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38AT",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - PRE OWNED",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CP",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - SALE",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38DO",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - SPECIALS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CI",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - USED CARS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CH",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - USED TRUCKS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CK",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - WE FINANCE",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPNS38CN",
    name: "1-sided Message Flag",
    fullname: "Single-Faced Stock Message Drape Flag - WELCOME",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AE",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - BUICK",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AC",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - CADILLAC",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AA",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - CHEVROLET",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38CVB",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - CHEVROLET",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AB",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - CHEVY TRUCKS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38CTB",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - CHEVY TRUCKS",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38CB",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - CHRYSLER",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38DCB",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - DODGE",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38DCW",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - DODGE",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38RTW",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - RAM TRUCKS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AJ",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - FORD",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AM",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - FORD TRUCKS",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AD",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - GMC",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38BA",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - HYUNDAI",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38OJ",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - JEEP",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38BD",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - KIA",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38BYBK",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - LINCOLN",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38BM",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - MAZDA",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38BB",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - MITSUBISHI",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38AS",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - SUBARU",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GPD38BI",
    name: "1-sided Free Flying Flag",
    fullname: "Single-Faced Free Flying Drape Flag - TOYOTA",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831DPBLYL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - 4 x 4",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CFRWB",
    name: "Swooper Flag",
    fullname: "Swooper Flag - BUY HERE/PAY HERE",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CQRDWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - CERTIFIED PRE-OWNED",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },  
  {
    code: "GP831EMWTBK",
    name: "Swooper Flag",
    fullname: "Swooper Flag - CHECKERED FLAG (BLACK & WHITE)",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831FN",
    name: "Swooper Flag",
    fullname: "Swooper Flag - CHECKERED FLAG (BLACK & YELLOW)",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831EOBLWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - CHECKERED FLAG (BLUE & WHITE)",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831BL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SOLID BLUE",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831RD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SOLID RED",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831WT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - WHITE",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831YL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SOLID YELLOW",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",  
    sizes: {
      1: 0.00,
    },
  },       
  {
    code: "GP831CBBL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - CHRYSLER",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831DY",
    name: "Swooper Flag",
    fullname: "Swooper Flag - DODGE",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831DKRWB",
    name: "Swooper Flag",
    fullname: "Swooper Flag - EASY FINANCE",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831AJBL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - FORD",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },  
  {
    code: "GP831BEBL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - HONDA",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831DLRDYL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - HOT BUYS",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831BDWTRD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - KIA",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831BY",
    name: "Swooper Flag",
    fullname: "Swooper Flag - LINCOLN",
    colors: ["Black"],
    type: "sales",
    default_color: "Black",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831BMBLWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - MAZDA",
    colors: ["Strong Blue"],
    type: "sales",
    default_color: "Strong Blue",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831EXRD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - NISSAN ",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP831CPRDYL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SALE (RED/YELLOW) ",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CPBL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SALE (BLUE/WHITE) ",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CPRD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SALE (RED/WHITE) ",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831DTWTBK",
    name: "Swooper Flag",
    fullname: "Swooper Flag - SE HABLA ESPANOL ",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831DNWTRD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - STOP SAVE NOW ",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831BIRD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - TOYOTA ",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },    
  {
    code: "GP831AWBLWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - TRUCKS (BLUE/WHITE)",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831AURDWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - TRUCKS (RED/WHITE)",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CIBLWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - USED CARS (BLUE/WHITE)",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CIRDWT",
    name: "Swooper Flag",
    fullname: "Swooper Flag - USED CARS (RED/WHITE)",
    colors: ["Red"],
    type: "sales",
    default_color: "Red",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831CIRWB",
    name: "Swooper Flag",
    fullname: "Swooper Flag - USED CARS (RED/WHITE/BLUE)",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
   {
    code: "GP831CKGNYL",
    name: "Swooper Flag",
    fullname: "Swooper Flag - WE FINANCE",
    colors: ["Green"],
    type: "sales",
    default_color: "Green",  
    sizes: {
      1: 0.00,
    },
  },
   {
    code: "GP831CNRWB",
    name: "Swooper Flag",
    fullname: "Swooper Flag - WELCOME",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831ECRWB",
    name: "Swooper Flag",
    fullname: "Swooper Flag - 0% FINANCE",
    colors: ["Blue"],
    type: "sales",
    default_color: "Blue",  
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GP831BNWTRD",
    name: "Swooper Flag",
    fullname: "Swooper Flag - CERTIFIED USED VEHICLES",
    colors: ["White"],
    type: "sales",
    default_color: "White",  
    sizes: {
      1: 0.00,
    },
  },                                             
  {
    code: "30BKHP",
    name: "7.5 in. Numbers - Bk/Htpk",
    fullname: "7.5 in. Numbers - Black/Hot Pink (12 per pack)",
    colors: ["BKHP0","BKHP1","BKHP2","BKHP3","BKHP4","BKHP5","BKHP6","BKHP7","BKHP8","BKHP9","BKHPS","BKHPD","BKHPP"],
    type: "sales",
    default_color: "BKHP0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30SLBK",
    name: "7.5 in. Numbers - Slv/Blk",
    fullname: "7.5 in. Numbers - Silver/Black (12 per pack)",
    colors: ["SLBK0","SLBK1","SLBK2","SLBK3","SLBK4","SLBK5","SLBK6","SLBK7","SLBK8","SLBK9","SLBKS","SLBKD","SLBKP"],
    type: "sales",
    default_color: "SLBK0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30GDBK",
    name: "7.5 in. Numbers - Gld/Blk",
    fullname: "7.5 in. Numbers - Gold/Black (12 per pack)",
    colors: ["GDBK0","GDBK1","GDBK2","GDBK3","GDBK4","GDBK5","GDBK6","GDBK7","GDBK8","GDBK9","GDBKS","GDBKD","GDBKP"],
    type: "sales",
    default_color: "GDBK0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30CBK",
    name: "7.5 in. Numbers - Char/Blk",
    fullname: "7.5 in. Numbers - Chartreuse/Black (12 per pack)",
    colors: ["CBK0","CBK1","CBK2","CBK3","CBK4","CBK5","CBK6","CBK7","CBK8","CBK9","CBKS","CBKP"],
    type: "sales",
    default_color: "CBK0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30YBK",
    name: "7.5 in. Numbers - Ylw/Blk",
    fullname: "7.5 in. Numbers - Yellow/Black (12 per pack)",
    colors: ["YBK0","YBK1","YBK2","YBK3","YBK4","YBK5","YBK6","YBK7","YBK8","YBK9","YBKS","YBKP", "YBKD"],
    type: "sales",
    default_color: "YBK0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30YR",
    name: "7.5 in. Numbers - Yllw/Red",
    fullname: "7.5 in. Numbers - Yellow/Red (12 per pack)",
    colors: ["YR0","YR1","YR2","YR3","YR4","YR5","YR6","YR7","YR8","YR9","YRS","YRP","YRD"],
    type: "sales",
    default_color: "YR0",    
    sizes: {
      "# packs": 0.00,
    },
  },
   {
    code: "30YGR",
    name: "7.5 in. Numbers - Yllw/Grn",
    fullname: "7.5 in. Numbers - Yellow/Green (12 per pack)",
    colors: ["YGR0","YGR1","YGR2","YGR3","YGR4","YGR5","YGR6","YGR7","YGR8","YGR9","YGRS","YGRP","YGRD"],
    type: "sales",
    default_color: "YGR0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30YB",
    name: "7.5 in. Number - Yllw/Blue",
    fullname: "7.5 in. Numbers - Yellow/Blue (12 per pack)",
    colors: ["YB0","YB1","YB2","YB3","YB4","YB5","YB6","YB7","YB8","YB9","YBS","YBP","YBD"],
    type: "sales",
    default_color: "YB0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30WB",
    name: "7.5 in. Number - Wht/Blue",
    fullname: "7.5 in. Numbers - White/Blue (12 per pack)",
    colors: ["WB0","WB1","WB2","WB3","WB4","WB5","WB6","WB7","WB8","WB9","WBS","WBP","WBD"],
    type: "sales",
    default_color: "WB0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30BLW",
    name: "7.5 in. Number - Blue/Wht",
    fullname: "7.5 in. Numbers - Blue/White (12 per pack)",
    colors: ["BLW0","BLW1","BLW2","BLW3","BLW4","BLW5","BLW6","BLW7","BLW8","BLW9","BLWS","BLWP","BLWD"],
    type: "sales",
    default_color: "BLW0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "30RW",
    name: "7.5 in. Numbers - Red/Wht",
    fullname: "7.5 in. Numbers - Red/White (12 per pack)",
    colors: ["RW0","RW1","RW2","RW3","RW4","RW5","RW6","RW7","RW8","RW9","RWS","RWD","RWP"],
    type: "sales",
    default_color: "RW0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "90CBK",
    name: "9.5 in. Numbers - Char/Blk",
    fullname: "9.5 in. Numbers - Chartreuse/Black (12 per pack)",
    colors: ["CBK0","CBK1","CBK2","CBK3","CBK4","CBK5","CBK6","CBK7","CBK8","CBK9","CBKS","CBKD"],
    type: "sales",
    default_color: "CBK0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "90BKHP",
    name: "9.5 in. Numbers - Bk/Htpk",
    fullname: "9.5 in. Numbers - Black/Hot Pink (12 per pack)",
    colors: ["BKHP0","BKHP1","BKHP2","BKHP3","BKHP4","BKHP5","BKHP6","BKHP7","BKHP8","BKHP9","BKHPS","BKHPD","BKHPP"],
    type: "sales",
    default_color: "BKHP0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "90YB",
    name: "9.5 in. Numbers - Yllw/Blue",
    fullname: "9.5 in. Numbers - Yellow/Blue (12 per pack)",
    colors: ["YB0","YB1","YB2","YB3","YB4","YB5","YB6","YB7","YB8","YB9","YBS","YBP","YBD"],
    type: "sales",
    default_color: "YB0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "90YR",
    name: "9.5 in. Numbers - Yllw/Red",
    fullname: "9.5 in. Numbers - Yellow/Red (12 per pack)",
    colors: ["YR0","YR1","YR2","YR3","YR4","YR5","YR6","YR7","YR8","YR9","YRS","YRP","YRD"],
    type: "sales",
    default_color: "YR0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "11CBK",
    name: "11.5 in. Numbers - Chr/Blk",
    fullname: "11.5 in. Numbers - Chartreuse/Black (12 per pack)",
    colors: ["CBK0","CBK1","CBK2","CBK3","CBK4","CBK5","CBK6","CBK7","CBK8","CBK9","CBKS","CBKP"],
    type: "sales",
    default_color: "CBK0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "11YB",
    name: "11.5 in. Number - Yllw/Blue",
    fullname: "11.5 in. Numbers - Yellow/Blue (12 per pack)",
    colors: ["YB0","YB1","YB2","YB3","YB4","YB5","YB6","YB7","YB8","YB9","YBS","YBP","YBD"],
    type: "sales",
    default_color: "YB0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "11YR",
    name: "11.5 in. Number - Yllw/Red",
    fullname: "11.5 in. Numbers - Yellow/Red (12 per pack)",
    colors: ["YR0","YR1","YR2","YR3","YR4","YR5","YR6","YR7","YR8","YR9","YRS","YRP","YRD"],
    type: "sales",
    default_color: "YR0",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "GP199",
    name: "Arch Slogans",
    fullname: "Arch Slogans - 2.75in. x 14in. (12 per pack)",
    colors: ["Slogans","Red Yellow","Blue Yellow","Gold Black","Silver Black"],
    type: "sales",
    default_color: "Slogans",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "B17",
    name: "17 in. Latex Balloons",
    fullname: "17 in. Latex Balloons (72 per bag)",
    colors: ["Black","Blue","Green","Orange","Red","Yellow","Pink","Purple","White","Gold","Silver","Assorted"],
    type: "sales",
    default_color: "Black",   
    sizes: {
      "# bags": 0.00,
    },
  },
  {
    code: "B36",
    name: "36 in. Latex Balloons",
    fullname: "36 in. Latex Balloons (10 per bag)",
    colors: ["Blue","Green","Orange","Red","Yellow","White"],
    type: "sales",
    default_color: "Blue",    
    sizes: {
      "# bags": 0.00,
    },
  },
  {
    code: "CB55",
    name: "5.5 in. Rubber Balloons",
    fullname: "5.5 in. Rubber Chloroprene Balloons (1 ea)",
    colors: ["Blue","Green","Orange","Purple","Red","White","Yellow"],
    type: "sales",
    default_color: "Blue",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "RIBBON",
    name: "Balloon Ribbon (500 yrds)",
    fullname: "Balloon Ribbon (500 yards)",
    colors: ["Silver","White"],
    type: "sales",
    default_color: "Silver",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "STRING",
    name: "Cone of Balloon String",
    fullname: "Cone of Balloon String - 1500 yards",
    colors: ["White"],
    type: "sales",
    default_color: "White",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "PENLIN",
    name: "Triangle Pennants (100 FT)",
    fullname: "Triangle Pennants 48 - 12 in. x 18 in.",
    colors: ["Assorted","RWB"],
    type: "sales",
    default_color: "Assorted",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "BOW22",
    name: "22 in. Giant Bow",
    fullname: "22 in. Giant Magnetic Car Bow (2 ea)",
    colors: ["Blue","Gold","Green","Patriotic","Pink","Red","Silver","White","Red Grn"],
    type: "sales",
    default_color: "Blue",   
    sizes: {
      2: 0.00,
    },
  },
  {
    code: "BOW30",
    name: "30 in. Giant Bow",
    fullname: "30 in. Giant Magnetic Car Bow (2 ea)",
    colors: ["Blue","Gold","Green","Patriotic","Pink","Red","Silver","White","Red Grn"],
    type: "sales",
    default_color: "Blue",   
    sizes: {
      2: 0.00,
    },
  },
  {
    code: "HANG-HT-RDBK-TF",
    name: "Hang Tag - Red Tag Special",
    fullname: "Stock Hang Tags - Red Tag Special - 9in x 12in (50 per pack)",
    colors: ["Fluorr"],
    type: "sales",
    default_color: "Fluorr",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-HT-RDBK-TG",
    name: "Hang Tag - Red Tag Sale",
    fullname: "Stock Hang Tags - Red Tag Sale - 9in x 12in (50 per pack)",
    colors: ["Fluorr"],
    type: "sales",
    default_color: "Fluorr",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-BB",
    name: "Hang Tag - As Advertised",
    fullname: "Stock Hang Tags - As Advertised - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-FF",
    name: "Hang Tag - Financing Available",
    fullname: "Stock Hang Tags - Financing Available - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-SG",
    name: "Hang Tag - Was Now",
    fullname: "Stock Hang Tags - Was Now - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-MH",
    name: "Hang Tag - Sale",
    fullname: "Stock Hang Tags - Sale - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-CG",
    name: "Hang Tag - Clearance",
    fullname: "Stock Hang Tags - Clearance - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-HG",
    name: "Hang Tag - Like New",
    fullname: "Stock Hang Tags - Like New - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-LD",
    name: "Hang Tag - Per Month",
    fullname: "Stock Hang Tags - Per Month - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-SH",
    name: "Hang Tag - List Price",
    fullname: "Stock Hang Tags - List Price - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-NH",
    name: "Hang Tag - Special",
    fullname: "Stock Hang Tags - Special - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-TA",
    name: "Hang Tag - Blank w/outline",
    fullname: "Stock Hang Tags - Blank with outline - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-TE",
    name: "Hang Tag - Blank",
    fullname: "Stock Hang Tags - Blank - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-ME",
    name: "Hang Tag - Rebate",
    fullname: "Stock Hang Tags - Rebate - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "HANG-MF",
    name: "Hang Tag - Reduced",
    fullname: "Stock Hang Tags - Reduced - 9in x 12in (50 per pack)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",   
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "310",
    name: "File Number Labels",
    fullname: "File Right Number Labels (500/box)",
    colors: ["Number 0","Number 1","Number 2","Number 3","Number 4",
      "Number 5","Number 6","Number 7","Number 8","Number 9"],
    type: "sales",
    default_color: "Number 0",
    sizes: {
      500: 0.00,
    },
  },
  {
    code: "ALPLBL",
    name: "ABC Filing Labels",
    fullname: "Alphabetic File Right Labels (270/sheet)",
    colors: ["A","B","C","D","E","F","G","H","I","J","K","L","M",
      "N","O","P","Q","R","S","T","U","V","W","X","Y","Z","Mc"],
    type: "sales",
    default_color: "A",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "MONLBL",
    name: "Month Filing Labels",
    fullname: "File Right Month Labels (270/sheet)",
    colors: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    type: "sales",
    default_color: "Jan",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "3196",
    name: "Certified Ovals",
    fullname: "Certified Ovals (12/pk)",
    colors: ["Style A","Style B","Style C","Style D","Style E","Style F"],
    type: "sales",
    default_color: "Style A",    
    sizes: {
      12: 0.00,
    },
  },
  {
    code: "GP3185",
    name: "5 in. Stars",
    fullname: "5 in. Stars #GP3185 (12/pk)",
    colors: ["Blk Char","Blk Htpk","Blk Yllw","Blu Wht","Prp Char","Red Wht"],
    type: "sales",
    default_color: "Blk Char",
    sizes: {
      12: 0.00,
    },
  }, 
  {
    code: "3192",
    name: "Blue Explosion Years",
    fullname: "7 in. x 9 in. Bright Blue Bursts (2000-2026 avail - 12/pk)",
    colors: ["Blue24", "Blue25","Blue26"],
    type: "sales",
    default_color: "Blue26",    
    sizes: {
      12: 0.00,
    },
  }, 
  {
    code: "3193",
    name: "Chartreuse Bursts",
    fullname: "9 in. x 11 in. Chartreuse Bursts (2000-2026 avail - 12/pk)",
    colors: ["Char24","Char25","Char26"],
    type: "sales",
    default_color: "Char26",    
    sizes: {
      12: 0.00,
    },
  },  
  {
    code: "3184",
    name: "6 in. Happy Face",
    fullname: "6 in. Happy Face (12/pk)",
    colors: ["Happy"],
    type: "sales",
    default_color: "Happy",    
    sizes: {
      12: 0.00,
    },
  }, 
  {
    code: "GP150",
    name: "Happy Face Sunglasses",
    fullname: "6 in. Happy Face w/sunglasses (12/pk)",
    colors: ["Sunglasses"],
    type: "sales",
    default_color: "Sunglasses",    
    sizes: {
      12: 0.00,
    },
  },
  {
    code: "GPBOX",
    name: "Numbers Box",
    fullname: "Numbers Box (holds 7.5 in x 9.5 in. numbers)",
    colors: ["White"],
    type: "sales",
    default_color: "White",    
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "GP788",
    name: "Sticker",
    fullname: "Vehicle Not for Sale Sticker (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    sizes: {
      100: 0.00,
    },
  },  
  {
    code: "GP790",
    name: "Sticker",
    fullname: "Vehicle Not for Sale Sticker (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    sizes: {
      100: 0.0,
    },
  }, 
  {
    code: "AN651V1",
    name: "Sticker",
    fullname: "Vehicle Not for Sale Sticker (250/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",    
    sizes: {
      250: 0.0,
    },
  },
  {
    code: "GP611",
    name: "Sticker",
    fullname: "Smog OK Sticker (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",   
    sizes: {
      100: 0.0,
    },
  },
  {
    code: "GP612",
    name: "Sticker",
    fullname: "Safety OK Sticker (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",   
    sizes: {
      100: 0.0,
    },
  },
  {
    code: "280SH",
    name: "Hold/Sold Tag",
    fullname: "Hold/Sold Tag - 8.5 in x 11 in. (50/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    sizes: {
      50: 0.0,
    },
  },
  {
    code: "DP830",
    name: "Hold/Sold Tag",
    fullname: "Hold/Sold Tag - 8 in x 4 in. (250/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    sizes: {
      250: 0.0,
    },
  }, 
  {
    code: "3046",
    name: "Hold/Sold Tag (small)",
    fullname: "Hold/Sold Tag - 4.5 in x 2.5 in. (250/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",    
    sizes: {
      250: 0.0,
    },
  }, 
  {
    code: "GP839",
    name: "License Plate Envelope",
    fullname: "License Plate Envelope - 13 in x 6.5 in. (100/box)",
    colors: ["Kraft Paper"],
    type: "sales",
    default_color: "Kraft Paper",   
    sizes: {
      100: 0.0,
    },
  }, 
  {
    code: "PB100",
    name: "Poly Bags",
    fullname: "Temp Tag Cover - Plastic (100/pk)",
    colors: ["Clear Plastic"],
    type: "sales",
    default_color: "Clear Plastic",   
    sizes: {
      100: 0.0,
    },
  }, 
  {
    code: "TH100",
    name: "Temp L/P Protector",
    fullname: "License Plate Protector (100/pk)",
    colors: ["Clear"],
    type: "sales",
    default_color: "Clear",   
    sizes: {
      100: 0.0,
    },
  },
  {
    code: "GP955",
    name: "Grease Markers",
    fullname: "Grease Marker (1 each)",
    colors: ["Blue","Green","Pink","Orange","Purple","Red","White","Yellow"],
    type: "sales",
    default_color: "Blue",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "957R",
    name: "Uni-Posca Markers (R)",
    fullname: "Regular Uni-Posca Marker (1 each)",
    colors: ["Green","Orange","Pink","Red","White","Yellow"],
    type: "sales",
    default_color: "Orange",    
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "957L",
    name: "Uni-Posca Markers (L)",
    fullname: "LARGE Uni-Posca Marker (1 each)",
    colors: ["Blue","Pink","Red","White","Yellow"],
    type: "sales",
    default_color: "Blue",    
    sizes: {
      1: 0.00,
    },
  },                                                
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",   
    sizes: {
      500: 0.0,
    },
  },
  {
    code: "55010",
    name: "Steering Wheel Covers",
    fullname: "Steering Wheel Covers (500/bx)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    sizes: {
      500: 0.0,
    },
  },
  {
    code: "600088B",
    name: "Seat Covers (box)",
    fullname: "The Gripper Plastic Seat Covers (250/box)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    sizes: {
      250: 0.0,
    },
  },  
  {
    code: "600088V",
    name: "Seat Covers (roll)",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    sizes: {
      500: 0.0,
    },
  }, 
  {
    code: "6000D",
    name: "Seat Cover Floor Stand",
    fullname: "Seat Cover Floor Stand",
    colors: ["Black"],
    type: "service",
    default_color: "Black",    
    sizes: {
      1: 0.0,
    },
  }, 
  {
    code: "6000WD",
    name: "Seat Cover Wall Dispenser",
    fullname: "Seat Cover Wall Dispenser",
    colors: ["Black"],
    type: "service",
    default_color: "Black",    
    sizes: {
      1: 0.0,
    },
  }, 
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250 per pack)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",    
    sizes: {
      "# packs": 0.00,
    },
  },
  {
    code: "EIT50",
    name: "Self-Locking Key Tags",
    fullname: "Self-Locking Key Tags (1000/pk)",
    colors: ["Blue","Green","Orange","Red","Yellow","White"],
    type: "service",
    default_color: "Blue",
    sizes: {
      1000: 0.00,
    },
  },         
  {
    code: "SDNRG",
    name: "Service Numbers",
    fullname: "Service Dispatch Numbers (1000/box)",
    colors: ["_0000","1000","2000","3000","4000","5000",
      "6000","7000","8000", "9000"],  
    type: "service",
    default_color: "1000",    
    sizes: {
      "1 box": 0.0,
    },
  }, 
  {
    code: "SDNC",
    name: "Service Numbers",
    fullname: "Mirror Hang Service Numbers (1000/bx)",
    colors: ["Blue","Green","Grey","Lime","Orange","Pink","Purple","Red","Tan","White","Yellow"],  
    type: "service",
    default_color: "Blue",    
    sizes: {
      1: 0.0,
    },
  }, 
  {
    code: "SDN0000",
    name: "Service Numbers",
    fullname: "Mirror Hang Service Numbers (1000/bx)",
    colors: ["_0000","1000","2000","3000","4000","5000",
      "6000","7000","8000", "9000"],  
    type: "service",
    default_color: "1000",    
    sizes: {
      1: 0.0,
    },
  }, 
  {
    code: "SDN999",
    name: "Service Numbers",
    fullname: "Mirror Hang Service Numbers (000-999) (1000/bx)",
    colors: ["White"],  
    type: "service",
    default_color: "White",    
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "230",
    name: "Colored Dispatch Numbers",
    fullname: "Colored Dispatch Numbers (1000/pk)",
    colors: ["Blue","Green","Red","White","Yellow"],  
    type: "service",
    default_color: "Blue",    
    sizes: {
      1: 0.0,
    },
  },   
  {
    code: "BGVinyl",
    name: "Vinyl Sheet",
    fullname: "8.5 x 11 Blank Vinyl Sheet #9300 (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",    
    sizes: {
      default: 0.00,
    },
  },
  {
    code: "BGE12-AL",
    name: "Buyers Guide",
    fullname: "Buyers Guide, Blank Front (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",    
    sizes: {
      default: 0.00,
    },
  },
  {
    code: "3198WB",
    name: "Oval Year Stickers - Blue",
    fullname: "Oval Year Stickers - Blue/White (12/pk)",
    colors: ["Blue"],
    variations: [
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",      
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Blue",
    description: "Sold in quantities of one, five, and ten packs",
    discount: [
      { quantity: 1, price: 0.00 },
      { quantity: 5, price: 0.00 },
      { quantity: 10, price: 0.00 },
    ],
    sizes: {
      "1": 0.00,
      "5": 0.00,
      "10": 0.00,
    },
  }, 
  {
    code: "3198SB",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers - Silver/Black (12/pk)",
    colors: ["YR 2016", "YR 2017","YR 2018","YR 2019","YR 2020",
     "YR 2021","YR 2022","YR 2023","YR 2024", "YR 2025","YR 2026"],   
    type: "sales",
    default_color: "YR 2016",    
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "3198BY",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers (Black/Yellow)  (12/pk)",
    colors: ["BY_08","BY_09","BY_10","BY_11","BY_12","BY_13","BY_14","BY_15","BY_16",
      "BY_17","BY_18","BY_19","BY_20","BY_21","BY_22","BY_23","BY_24","BY_25","BY_26"],
    type: "sales",
    default_color: "BY 08",
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "NDESTOCK",
    name: "Night Drop Envelopes",
    fullname: "Night Drop Envelopes (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "box of 500": 0.00,
    },
  },
  {
    code: "7290",
    name: "Inspection Form - 3 Part",
    fullname: "Multi-Point Inspection Form - 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "pack of 250": 0.00,
    },
  },
  {
    code: "7291",
    name: "Inspection Form - 2 Part",
    fullname: "Multi-Point Inspection Form - 2 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      250: 0.00,
    },
  },
  {
    code: "7292",
    name: "Inspection Form - GM",
    fullname: "Multi-Point Inspection Form (GM) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      250: 0.00,
    },
  },
  {
    code: "7293",
    name: "Inspection Form CHRYSLER",
    fullname: "Multi-Point Inspection Form (Chrysler) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      250: 0.00,
    },
  },
  {
    code: "TICKETHOLDER",
    name: "Work Ticket Holders",
    fullname: "Neon Stitched Work Ticket Holders",
    colors: ["Black","Blue","Green","Orange","Pink","Red","Yellow"],
    type: "service",
    default_color: "Black",
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "7320",
    name: "Night Drop Box",
    fullname: "Self-Contained Night Drop Box",
    colors: ["Black"],
    type: "service",
    default_color: "Black",
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "7321",
    name: "Night Drop Box Posts",
    fullname: "24in. Surface Mount Post for Drop Box",
    colors: ["Black"],
    type: "service",
    default_color: "Black",
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "7322",
    name: "Night Drop Box Posts",
    fullname: "36in. In Ground Mount Post for Drop Box",
    colors: ["Black"],
    type: "service",
    default_color: "Black",
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GCAPS",
    name: "Control Caps",
    fullname: "Magnetic Control Caps 10in. x 10in. x 5 in.",
    colors: ["Slogans","Black","Blue","Green","Grey","Orange","Purple","Red","Tan","White","Yellow"],
    type: "service",
    default_color: "Slogans",
    sizes: {
      1: 0.00,
    },
  },
  {
    code: "GUARDFRM",
    name: "Zinc Metal Frames",
    fullname: "Zinc Metal Frame",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    supportedStores: ["GUAPR1","GUAPR2"],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "guardianpp",
    name: "Poly Coated Plates",
    fullname: "Poly Coated Cardboard w/blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["GUAPR1","GUAPR2"],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "GUARDECAL",
    name: "Die Cut Decals",
    fullname: "Vinyl Diecut Decals",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["GUAPR1","GUAPR2"],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
];
