export const catalog = [
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black", "Battleship Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 41.99,
      Medium: 41.99,
      Large: 41.99,
      XLarge: 41.99,
      "2XLarge": 42.99,
      "3XLarge": 43.99,
      "4XLarge": 44.99,
      "5XLarge": 45.99,
      "6XLarge": 46.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Battleship Grey", "Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 41.99,
      Medium: 41.99,
      Large: 41.99,
      XLarge: 41.99,
      "2XLarge": 42.99,
      "3XLarge": 43.99,
      "4XLarge": 44.99,
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Micropique Polo",
    colors: ["Black", "Grey Concrete", "Iron Grey", "True Red"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 25.0,
      Medium: 25.0,
      Large: 25.0,
      XLarge: 25.0,
      "2XLarge": 26.0,
      "3XLarge": 27.0,
      "4XLarge": 28.0,
      "5XLarge": 29.0,
      "6XLarge": 30.0,
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: ["Black", "Grey Concrete", "Iron Grey", "True Red"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 25.0,
      Medium: 25.0,
      Large: 25.0,
      XLarge: 25.0,
      "2XLarge": 26.0,
      "3XLarge": 27.0,
      "4XLarge": 28.0,
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo",
    fullname: "Ladies Nike® Micro Pique Polo",
    colors: ["Anthracite", "Black", "University Red"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 42.99,
      Medium: 42.99,
      Large: 42.99,
      XLarge: 42.99,
      "2XLarge": 43.99,
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Anthracite", "Black", "University Red"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 42.99,
      Medium: 42.99,
      Large: 42.99,
      XLarge: 42.99,
      "2XLarge": 43.99,
      "3XLarge": 44.99,
      "4XLarge": 45.99,
      LT: 45.99,
      XLT: 47.99,
      "2XLT": 49.99,
      "3XLT": 51.99,
      "4XLT": 53.99,
    },
  },
  {
    code: "K805",
    name: "Port Authority® 1/4-Zip Pullover",
    fullname: "Port Authority® 1/4-Zip Pullover",
    colors: ["Black", "Iron Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 32.99,
      Medium: 32.99,
      Large: 32.99,
      XLarge: 32.99,
      "2XLarge": 33.99,
      "3XLarge": 34.99,
      "4XLarge": 35.99,
    },
  },
  {
    code: "L805",
    name: "Port Authority® Pullover",
    fullname: "Port Authority® Women's Vertical Texture Full-Zip Jacket",
    colors: ["Black", "Iron Grey", "Regatta Blue", "True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 32.99,
      Medium: 32.99,
      Large: 32.99,
      XLarge: 32.99,
      "2XLarge": 33.99,
      "3XLarge": 34.99,
      "4XLarge": 35.99,
    },
  },
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    discount: [{ quantity: 1, price: 59.99 }],
    sizes: {
      default: 0.0,
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Key Tag Versa #200 (250/box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "White",
    discount: [{ quantity: 1, price: 19.99 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100/pk)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "White",
    discount: [{ quantity: 1, price: 9.99 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [{ quantity: 1, price: 59.99 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "55010",
    name: "Steering Wheel Covers",
    fullname: "Steering Wheel Covers (500/bx)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    discount: [{ quantity: 1, price: 59.99 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "SDNRG",
    name: "Service Numbers",
    fullname: "Service Dispatch Numbers (1000/bx)",
    colors: [
      "_0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000",
      "9000",
    ],
    type: "service",
    default_color: "1000",
    discount: [{ quantity: 1, price: 84.99 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "GP790",
    name: "Sticker",
    fullname: "Sticker - Vehicle Not for Sale (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",
    discount: [{ quantity: 1, price: 26.14 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "GUARDFRM",
    name: "Zinc Metal Frames",
    fullname: "Zinc Metal Frame",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    discount: [
      { quantity: 500, price: 0.0 },
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "guardianpp",
    name: "Poly Coated Plates",
    fullname: "Poly Coated Cardboard w/blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 500, price: 0.0 },
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "GUARDECAL",
    name: "Die Cut Decals",
    fullname: "Vinyl Diecut Decals",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 500, price: 0.0 },
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
];
