export const catalog = [
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    type: "service",
    default_color: "Plastic",
    pricing: {
      base: {
        price: 73.5,
      },
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 76.44,
      },
    },
  },
  {
    code: "BGVinyl",
    name: "Vinyl Sheet",
    fullname: "8.5 x 11 Blank Vinyl Sheet #9300 (100/pk)",
    type: "sales",
    default_color: "White",
    pricing: {
      base: {
        price: 135,
      },
    },
  },
  {
    code: "BGE12-AL",
    name: "Buyers Guide",
    fullname: "Buyers Guide, Blank Front (100/pk)",
    type: "sales",
    default_color: "White",
    pricing: {
      base: {
        price: 74.95,
      },
    },
  },
  {
    code: "3198WB",
    name: "Oval Year Stickers - Blue",
    fullname: "Oval Year Stickers - Blue/White (12/pk)",
    variations: [
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Blue",
    pricing: {
      base: {
        price: 10.99,
      },
    },
  },
  {
    code: "3198SB",
    name: "Oval Year Stickers - Silver",
    fullname: "Oval Year Stickers - Silver/Black (12/pk)",
    variations: [
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Silver",
    pricing: {
      base: {
        price: 10.99,
      },
    },
  },
  {
    code: "GP955",
    name: "Grease Markers",
    fullname: "Grease Marker (1 each)",
    colors: [
      "Blue",
      "Green",
      "Pink",
      "Orange",
      "Purple",
      "Red",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    pricing: {
      base: {
        price: 10.69,
      },
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Versa-Tags Key Tag #200 (250/bx)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    pricing: {
      base: {
        price: 36.95,
      },
    },
  },
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets (500/box)",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    pricing: {
      base: {
        price: 115.79,
      },
    },
  },
  {
    code: "GP790",
    name: "Not for Sale Sticker",
    fullname: "Sticker - Vehicle Not for Sale (100/pk)",
    type: "sales",
    default_color: "Yellow",
    pricing: {
      base: {
        price: 27.95,
      },
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100/pk)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Blue",
    pricing: {
      base: {
        price: 17.95,
      },
    },
  },
  {
    code: "CP91L",
    name: "Port & Company Beanie #CP91L",
    fullname: "Port & Company® Fleece-Lined Beanie Cap (CP91L)",
    colors: ["Athletic Red", "Athletic Royal", "Black", "Navy"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 12.99 },
    },
  },
  {
    code: "112",
    name: "Richardson Trucker Cap #112",
    fullname: "Richardson Snapback Trucker Cap (addt'l logos cost extra)",
    colors: [
      "Amber Gold",
      "Black",
      "Charcoal",
      "Loden",
      "Maroon",
      "Navy",
      "White",
    ],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 21.99 },
    },
  },
  {
    code: "NE205",
    name: "New Era® Trucker Cap #NE205",
    fullname: "New Era® Snapback Trucker Cap (addt'l logos cost extra)",
    colors: ["Black", "Graphite", "Grey", "Deep Navywt"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 26.99 },
    },
  },
  {
    code: "STC39",
    name: "Sport-Tek® Trucker Cap #STC39",
    fullname:
      "Sport-Tek® YP Classics® Retro Trucker Cap (addt'l logos cost extra)",
    colors: [
      "Black",
      "Graphite",
      "True Navy True Navy",
      "True Navy White",
      "White",
    ],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 21.99 },
    },
  },
  {
    code: "BB18000",
    name: "Brooks Brothers® Shirt #BB18000",
    fullname: "Brooks Brothers® Wrinkle-Free Stretch Pinpoint Shirt (BB18000)",
    colors: ["Cobalt Blue", "Deep Black", "Newport Blue", "White"],
    type: "mens",
    default_color: "Cobalt Blue",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 79.99 },
      Medium: { price: 79.99 },
      Large: { price: 79.99 },
      XLarge: { price: 79.99 },
      "2XLarge": { price: 80.99 },
      "3XLarge": { price: 81.99 },
      "4XLarge": { price: 82.99 },
    },
  },
  {
    code: "BB18002",
    name: "Brooks Brothers® Shirt #BB18002",
    fullname: "Brooks Brothers® Wrinkle-Free Nailhead Shirt (BB18002)",
    colors: ["Cobalt Blue", "White"],
    type: "mens",
    default_color: "Cobalt Blue",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 79.99 },
      Medium: { price: 79.99 },
      Large: { price: 79.99 },
      XLarge: { price: 79.99 },
      "2XLarge": { price: 80.99 },
      "3XLarge": { price: 81.99 },
      "4XLarge": { price: 82.99 },
    },
  },
  {
    code: "BB18003",
    name: "Brooks Brothers® Shirt #BB18003",
    fullname: "Brooks Brothers® Women's Wrinkle-Free Nailhead Shirt (BB18003)",
    colors: ["Cobalt Blue", "White"],
    type: "womens",
    default_color: "Cobalt Blue",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 79.99 },
      Medium: { price: 79.99 },
      Large: { price: 79.99 },
      XLarge: { price: 79.99 },
      "2XLarge": { price: 80.99 },
      "3XLarge": { price: 81.99 },
      "4XLarge": { price: 82.99 },
    },
  },
  {
    code: "S659",
    name: "Port Authority® Shirt #S659",
    fullname: "Port Authority® Short Sleeve SuperPro™ Oxford Shirt (S659)",
    colors: ["Black", "Navy", "Oxford Blue", "White"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 35.99 },
      Medium: { price: 35.99 },
      Large: { price: 35.99 },
      XLarge: { price: 35.99 },
      "2XLarge": { price: 37.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 41.99 },
    },
  },
  {
    code: "S608",
    name: "Port Authority® Shirt #S608",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt (S608)",
    colors: ["White"],
    type: "mens",
    default_color: "White",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 34.99 },
      Medium: { price: 34.99 },
      Large: { price: 34.99 },
      XLarge: { price: 34.99 },
      "2XLarge": { price: 35.99 },
      "3XLarge": { price: 36.99 },
      "4XLarge": { price: 37.99 },
      "5XLarge": { price: 38.99 },
      "6XLarge": { price: 39.99 },
    },
  },
  {
    code: "L608",
    name: "Port Authority® Shirt #L608",
    fullname: "Port Authority® Women's Long Sleeve Shirt (L608)",
    colors: ["White"],
    type: "womens",
    default_color: "White",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 34.99 },
      Medium: { price: 34.99 },
      Large: { price: 34.99 },
      XLarge: { price: 34.99 },
      "2XLarge": { price: 35.99 },
      "3XLarge": { price: 36.99 },
      "4XLarge": { price: 37.99 },
      "5XLarge": { price: 38.99 },
      "6XLarge": { price: 39.99 },
    },
  },
  {
    code: "PC61",
    name: "Port & Company® Tee #PC61",
    fullname: "Port & Company® Essential Tee (PC61)",
    colors: [
      "Athletic Heather",
      "Cardinal",
      "Charcoal",
      "Jet Black",
      "Medium Grey",
      "Navy",
      "Red",
      "Royal",
      "White",
    ],
    type: "mens",
    default_color: "Jet Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 14.99 },
      Medium: { price: 14.99 },
      Large: { price: 14.99 },
      XLarge: { price: 14.99 },
      "2XLarge": { price: 16.99 },
      "3XLarge": { price: 18.99 },
      "4XLarge": { price: 20.99 },
      "5XLarge": { price: 22.99 },
      "6XLarge": { price: 24.99 },
    },
  },
  {
    code: "267020",
    name: "Nike® Dri-FIT Classic Polo #267020",
    fullname: "Nike® Dri-FIT Classic Polo (267020)",
    colors: ["Black", "Court Blue", "Light Blue", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 50.99 },
      "3XLarge": { price: 52.99 },
      "4XLarge": { price: 54.99 },
    },
  },
  {
    code: "286772",
    name: "Nike® Dri-FIT Classic Polo #286772",
    fullname: "Nike® Women's Dri-FIT Classic Polo (286772)",
    colors: ["Black", "Light Blue", "White"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 50.99 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike® Dri-FIT Polo (addt'l logos cost extra)",
    colors: [
      "Anthracite",
      "Black",
      "Cool Grey",
      "Navy",
      "University Red",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 41.99 },
      "3XLarge": { price: 43.99 },
      "4XLarge": { price: 45.99 },
    },
  },
  {
    code: "883681",
    name: "Nike® Dri-FIT Legacy Polo #883681",
    fullname: "Nike® Dri-FIT Legacy Polo (addt'l logos cost extra)",
    colors: [
      "Black",
      "Dark Grey",
      "Game Royal",
      "Gym Red",
      "Light Photo Blue",
      "Midnight Navy",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 62.99 },
      Medium: { price: 62.99 },
      Large: { price: 62.99 },
      XLarge: { price: 62.99 },
      "2XLarge": { price: 64.99 },
      "3XLarge": { price: 66.99 },
      "4XLarge": { price: 68.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo #NKDC1991",
    fullname: "Ladies Nike® Micro Pique Polo (addt'l logos cost extra)",
    colors: ["Anthracite", "Black", "Cool Grey", "Navy", "White"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 41.99 },
    },
  },
  {
    code: "NKAH6266",
    name: "Nike Textured Polo #NKAH6266",
    fullname: "Nike Dri-FIT Hex Textured Polo (NKAH6266)",
    colors: [
      "Black",
      "Court Blue",
      "Dark Grey",
      "Game Royal",
      "Gym Red",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 67 },
      Medium: { price: 67 },
      Large: { price: 67 },
      XLarge: { price: 67 },
      "2XLarge": { price: 69 },
      "3XLarge": { price: 71 },
      "4XLarge": { price: 73 },
    },
  },
  {
    code: "NKBV6042",
    name: "Nike® Essential Polo #NKBV6042",
    fullname: "Nike® Dry Essential Solid Polo (NKBV6042)",
    colors: [
      "Black",
      "Game Royal",
      "Midnight Navy",
      "University Blue",
      "University Red",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 56 },
      Medium: { price: 56 },
      Large: { price: 56 },
      XLarge: { price: 56 },
      "2XLarge": { price: 58 },
      "3XLarge": { price: 60 },
      "4XLarge": { price: 62 },
    },
  },
  {
    code: "TM1MY399",
    name: "TravisMathew Polo #TM1MY399",
    fullname: "TravisMathew Bayfront Solid Polo (TM1MY399)",
    colors: ["Black", "Dark Grey", "Insignia Blue", "Roan Rouge"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 96.49 },
      Medium: { price: 96.49 },
      Large: { price: 96.49 },
      XLarge: { price: 96.49 },
      "2XLarge": { price: 98.49 },
      "3XLarge": { price: 100.49 },
    },
  },
  {
    code: "TM1MU410",
    name: "TravisMathew Performance Polo #TM1MU410",
    fullname: "TravisMathew Coto Performance Polo (TM1MU410)",
    colors: [
      "Beryl Grn Hthr",
      "Black",
      "Blue Nights",
      "Brilliant Blue Hthr",
      "Federal Blue",
      "Quiet Shade Gry Hthr",
      "Quiet Shade Gry Blk",
      "Vintage Indigo Blk",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 79.99 },
      Medium: { price: 79.99 },
      Large: { price: 79.99 },
      XLarge: { price: 79.99 },
      "2XLarge": { price: 81.99 },
      "3XLarge": { price: 83.99 },
    },
  },
  {
    code: "OG101",
    name: "OGIO® - Caliber2.0 Polo #OG101",
    fullname: "OGIO® - Caliber2.0 Polo (OG101)",
    colors: ["Blacktop"],
    type: "mens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 32.99 },
      Medium: { price: 32.99 },
      Large: { price: 32.99 },
      XLarge: { price: 32.99 },
      "2XLarge": { price: 33.99 },
      "3XLarge": { price: 34.99 },
      "4XLarge": { price: 35.99 },
    },
  },
  {
    code: "LOG101",
    name: "OGIO® - Jewel Polo #LOG101",
    fullname: "OGIO® - Jewel Polo (LOG101)",
    colors: ["Blacktop"],
    type: "womens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 32.99 },
      Medium: { price: 32.99 },
      Large: { price: 32.99 },
      XLarge: { price: 32.99 },
      "2XLarge": { price: 33.99 },
      "3XLarge": { price: 34.99 },
      "4XLarge": { price: 35.99 },
    },
  },
  {
    code: "TM1WW003",
    name: "TravisMathew 1/4-Zip #TM1WW003",
    fullname: "TravisMathew Women's Crestview 1/4-Zip (TM1WW003)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 80.73 },
      Medium: { price: 80.73 },
      Large: { price: 80.73 },
      XLarge: { price: 80.73 },
      "2XLarge": { price: 82.73 },
    },
  },
  {
    code: "K110",
    name: "Port Authority UV Polo #K110",
    fullname: "Port Authority® Dry Zone® UV Micro-Mesh Polo (K110)",
    colors: [
      "Carolina Blue",
      "Coastal Blue",
      "Deep Black",
      "Graphite",
      "Gusty Grey",
      "Rich Red",
      "River Blue Navy",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 26.99 },
      "3XLarge": { price: 28.99 },
      "4XLarge": { price: 30.99 },
      "5XLarge": { price: 32.99 },
      "6XLarge": { price: 34.99 },
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee #ST350",
    fullname: "Sport-Tek PosiCharge Competitor Tee (ST350)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 10.99 },
      Medium: { price: 10.99 },
      Large: { price: 10.99 },
      XLarge: { price: 10.99 },
      "2XLarge": { price: 11.99 },
      "3XLarge": { price: 12.99 },
      "4XLarge": { price: 13.99 },
    },
  },
  {
    code: "ST740",
    name: "Sport-Tek Polo #ST740",
    fullname: "Sport-Tek® UV Micropique Polo (ST740)",
    colors: [
      "Black",
      "Deep Red",
      "Graphite",
      "Grey Concrete",
      "True Navy",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 29.99 },
      Medium: { price: 29.99 },
      Large: { price: 29.99 },
      XLarge: { price: 29.99 },
      "2XLarge": { price: 31.99 },
      "3XLarge": { price: 33.99 },
      "4XLarge": { price: 35.99 },
    },
  },
  {
    code: "PC61LS",
    name: "Long Sleeve Tee #PC61LS",
    fullname: "Port & Company® Long Sleeve Essential Tee (PC61LS)",
    colors: [
      "Ash",
      "Athletic Heather",
      "Cardinal",
      "Charcoal",
      "Deep Navy",
      "Jet Black",
      "Navy",
      "Red",
      "Royal",
      "White",
    ],
    type: "mens",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 23.99 },
      Medium: { price: 23.99 },
      Large: { price: 23.99 },
      XLarge: { price: 23.99 },
      "2XLarge": { price: 25.99 },
      "3XLarge": { price: 27.99 },
      "4XLarge": { price: 29.99 },
    },
  },
  {
    code: "PC90H",
    name: "Hooded Sweatshirt #PC90H",
    fullname: "Port & Company® Essential Fleece Hooded Sweatshirt (PC90H)",
    colors: [
      "Athletic Heather",
      "Cardinal",
      "Charcoal",
      "Drk Hthr Gry",
      "Jet Black",
      "Navy",
      "Red",
      "Royal",
      "White",
    ],
    type: "mens",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 31.98 },
      Medium: { price: 31.98 },
      Large: { price: 31.98 },
      XLarge: { price: 31.98 },
      "2XLarge": { price: 33.98 },
      "3XLarge": { price: 35.98 },
      "4XLarge": { price: 37.98 },
    },
  },
  {
    code: "F700",
    name: "Raglan Fleece #F700",
    fullname: "Port Authority® C-FREE® Raglan Fleece (F700)",
    colors: ["Deep Black", "Grey Steel", "True Navy"],
    type: "mens",
    default_color: "Deep Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 41.98 },
      Medium: { price: 41.98 },
      Large: { price: 41.98 },
      XLarge: { price: 41.98 },
      "2XLarge": { price: 43.98 },
      "3XLarge": { price: 45.98 },
      "4XLarge": { price: 47.98 },
    },
  },
  {
    code: "TM1MZ339",
    name: "TravisMathew 1/4-Zip #TM1MZ339",
    fullname: "TravisMathew Coveside 1/4-Zip (TM1MZ339)",
    colors: ["Black", "Blue Nights", "Drk Gry Hthr", "Light Blue Hthr"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 104 },
      Medium: { price: 104 },
      Large: { price: 104 },
      XLarge: { price: 104 },
      "2XLarge": { price: 106 },
      "3XLarge": { price: 108 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Women's Core Soft Shell Jacket (L317)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 50.99 },
      "3XLarge": { price: 51.99 },
      "4XLarge": { price: 52.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 50.99 },
      "3XLarge": { price: 51.99 },
      "4XLarge": { price: 52.99 },
      "5XLarge": { price: 53.99 },
      "6XLarge": { price: 54.99 },
    },
  },
  {
    code: "J333",
    name: "Torrent Waterproof Jacket #J333",
    fullname: "Port Authority® Torrent Waterproof Jacket (J333)",
    colors: ["Black", "Engine Red", "Magnet", "True Navy", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 64.99 },
      Medium: { price: 64.99 },
      Large: { price: 64.99 },
      XLarge: { price: 64.99 },
      "2XLarge": { price: 66.99 },
      "3XLarge": { price: 68.99 },
      "4XLarge": { price: 70.99 },
    },
  },
  {
    code: "NKDR1543",
    name: "Nike® Hooded Jacket #NKDR1543",
    fullname: "Nike® Hooded Soft Shell Jacket (NKDR1543)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 124 },
      Medium: { price: 124 },
      Large: { price: 124 },
      XLarge: { price: 124 },
      "2XLarge": { price: 126 },
      "3XLarge": { price: 128 },
      "4XLarge": { price: 130 },
    },
  },
  {
    code: "J335",
    name: "Port Authority® Jacket #J335",
    fullname: "Port Authority® Hooded Soft Shell Jacket (J335)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      XSmall: { price: 58.04 },
      Small: { price: 58.04 },
      Medium: { price: 58.04 },
      Large: { price: 58.04 },
      XLarge: { price: 58.04 },
      "2XLarge": { price: 60.04 },
      "3XLarge": { price: 62.04 },
      "4XLarge": { price: 64.04 },
    },
  },
  {
    code: "L335",
    name: "Port Authority® Jacket #L335",
    fullname: "Port Authority® Women's Hooded Soft Shell Jacket (L335)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      XSmall: { price: 58.04 },
      Small: { price: 58.04 },
      Medium: { price: 58.04 },
      Large: { price: 58.04 },
      XLarge: { price: 58.04 },
      "2XLarge": { price: 60.04 },
      "3XLarge": { price: 62.04 },
      "4XLarge": { price: 64.04 },
    },
  },
  {
    code: "HENPRO-FOB-414917C",
    name: "Leather Key Fob (red stitch) - Porsche N ATL",
    fullname: "Metal & Black Leather Fob - red stitch (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.99,
      },
    },
  },
  {
    code: "HENPRO-FOB-415104C",
    name: "Leather Key Fob (white stitch) - Porsche N ATL",
    fullname:
      "Metal & Black Leather Fob - white stitch (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.99,
      },
    },
  },
  {
    code: "HENPMA-FOB-497832C",
    name: "Leather Key Fob (red stitch) - Porsche Marietta",
    fullname: "Metal & Black Leather Fob - red stitch (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.99,
      },
    },
  },
  {
    code: "HENPMA-FOB-498046C",
    name: "Leather Key Fob (white stitch) - Porsche Marietta",
    fullname:
      "Metal & Black Leather Fob - white stitch (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.99,
      },
    },
  },
  {
    code: "HENLAT-GPLLKR-456506L",
    name: "Leather Key Fob - Lexus ATL",
    fullname: "Black Laser Engraved Leather Fob  (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.19,
      },
    },
  },
  {
    code: "HENLAT-FOB-501621A",
    name: "Leather Key Fob - Lexus ATL",
    fullname:
      "Metal & Black Leather Fob w/black color fill (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.19,
      },
    },
  },
  {
    code: "HENLAL-FOB-509389L",
    name: "Leather Key Fob - Land Rover - N ATL",
    fullname:
      "Black Leather Fob w/laser engraved imprint (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.99,
      },
    },
  },
  {
    code: "HENLDU-GPLLKR-473091L",
    name: "Leather Key Fob - Lexus Gwinnett",
    fullname: "Black Laser Engraved Leather Fob (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.19,
      },
    },
  },
  {
    code: "HENLDU-G1640-427215L",
    name: "Leather Key Fob - Lexus Gwinnett",
    fullname: "Black Laser Engraved Leather Fob (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.19,
      },
    },
  },
  {
    code: "HENADU-GPLLKR-497621L",
    name: "Leather Key Fob (green stitch) - Land Rover Gwinnett",
    fullname:
      "Black Laser Engraved Leather Fob - green stitch (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.49,
      },
    },
  },
  {
    code: "HENCDU-G1640-475097LL",
    name: "Leather Key Fob - Cadillac Duluth",
    fullname: "Black Laser Engraved Leather Fob (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.29,
      },
    },
  },
  {
    code: "CG1640",
    name: "Laser Engraved Keychain",
    fullname: "Brushed Zinc/Leather Key Tag (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.19,
      },
    },
  },
  {
    code: "HENFAT-FOB-506092",
    name: "Laser Engraved Keychain",
    fullname:
      "Chrome Keychain w/laser engraved imprint (must order min. of 250)",
    type: "accessory",
    default_color: "Metal",
    pricing: {
      base: {
        price: 3.59,
      },
    },
  },
  {
    code: "HENFAT-FOB-505249",
    name: "Laser Engraved Keychain",
    fullname: "Blue Banner Keychain (must order min. of 250)",
    type: "accessory",
    default_color: "Metal",
    pricing: {
      base: {
        price: 3.59,
      },
    },
  },
  {
    code: "HENMMO-FOB-502771L",
    name: "Matte Black Keychain - Southlake Mazda Buick GMC",
    fullname: "Matte Black Keychain (must order min. of 250)",
    type: "accessory",
    default_color: "Black",
    pricing: {
      base: {
        price: 3.59,
      },
    },
  },
  {
    code: "HENLAT-34MLF-379167A",
    name: "Zinc Metal Frame",
    fullname: "Zinc Metal Frame w/glossy black imprint",
    type: "customs",
    default_color: "Metal",
    supportedStores: ["HENLAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.99,
      },
    },
  },
  {
    code: "HENLAT-G24-367503A",
    name: "Poly Coated Plate",
    fullname: "Poly Coated Plate w/black imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENLAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.79,
      },
    },
  },
  {
    code: "HENLAL-G24-373653SA",
    name: "Poly Coated Plate",
    fullname: "Poly Coated Plate w/black imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENLAL"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.79,
      },
    },
  },
  {
    code: "HENLAT-33GT-497684Z",
    name: "Plastic Plate",
    fullname: "Plastic plate w/full color imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENLAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.89,
      },
    },
  },
  {
    code: "HENLAT-33P-391710A",
    name: "Plastic Plate",
    fullname: "Plastic plate w/black imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENLAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.99,
      },
    },
  },
  {
    code: "HENPRO-33P-458858A",
    name: "Test Drive Plate",
    fullname: "TEST DRIVE - Plastic Plate w/black imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENPRO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.99,
      },
    },
  },
  {
    code: "HENPMA-33P-497831A",
    name: "Test Drive Plate",
    fullname: "TEST DRIVE - Plastic Plate w/black imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENPMA"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.99,
      },
    },
  },
  {
    code: "HENPRO-34MLF-426579A",
    name: "Black Metal Frame",
    fullname: "Black Metal Frame w/white imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENPRO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.0279,
      },
    },
  },
  {
    code: "HENPMA-34MLF-497830A",
    name: "Black Metal Frame",
    fullname: "Black Metal Frame w/white imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENPMA"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.0279,
      },
    },
  },
  {
    code: "HENFAT31DD",
    name: "Die Cut Decal",
    fullname: "Decal Thermo Die Cut Decal",
    colors: ["Black", "Silver", "White"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENFAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.75,
      },
    },
  },
  {
    code: "HENMMO-31DD-504444A",
    name: "Die Cut Decal",
    fullname: "Black Vinyl Die Cut Decal",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENMMO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.89,
      },
    },
  },
  {
    code: "HENFAT-34MRE-419207",
    name: "Aluminum Embossed Plate",
    fullname: "Aluminum Plate w/black imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENFAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 3.59,
      },
    },
  },
  {
    code: "HENFAT-34MRE-418853",
    name: "Aluminum Embossed Plate",
    fullname: "White Aluminum Plate w/blue imprint",
    type: "customs",
    default_color: "White",
    supportedStores: ["HENFAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 3.59,
      },
    },
  },
  {
    code: "HENFAT-34MLF-445719",
    name: "Zinc Metal Frame",
    fullname: "Standard Zinc Metal Frame",
    type: "customs",
    default_color: "Metal",
    supportedStores: ["HENFAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 3.69,
      },
    },
  },
  {
    code: "HENLDU-33P3DS-379346A",
    name: "3D Plastic Plate",
    fullname: "Black 3D Plastic Plate w/matte silver imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENLDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 2.39,
      },
    },
  },
  {
    code: "HENLDU-34MLF-366502A",
    name: "Zinc Metal Frame",
    fullname: "Zinc Metal Frame w/black imprint",
    type: "customs",
    default_color: "Metal",
    supportedStores: ["HENLDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 3.35,
      },
    },
  },
  {
    code: "HENCDU-34MLF-485630A",
    name: "Black Metal Frame",
    fullname: "Black Metal Frame w/white imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENCDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 3.59,
      },
    },
  },
  {
    code: "HENLDU-33P-497607A",
    name: "Certified Tag",
    fullname: "Lexus Certified Tag",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENLDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.79,
      },
    },
  },
  {
    code: "HENADU-33P-492576A",
    name: "Land Rover Tag",
    fullname: "Land Rover Black Tag",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENADU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.29,
      },
    },
  },
  {
    code: "HENLDU-33G24-373661B",
    name: "Poly Coated Plate",
    fullname: "White Poly Coated Plate w/black & 36 metallic imprint",
    type: "customs",
    default_color: "White",
    supportedStores: ["HENLDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.89,
      },
    },
  },
  {
    code: "HENCDU-G24-365677B",
    name: "Drive Out Tag",
    fullname: "White Poly Coated Plate w/black & 36 metallic gold imprint",
    type: "customs",
    default_color: "White",
    supportedStores: ["HENCDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENFAT-280C-497703",
    name: "Hang Tag",
    fullname: "VIP OFFER Hang Tag",
    type: "service",
    default_color: "White",
    quantities: [500, 1000],
    pricing: {
      base: {
        price: 0.89,
        discount: {
          1000: 0.69,
        },
      },
    },
  },
  {
    code: "HENFAT-280C-491902",
    name: "Hang Tag",
    fullname: "SOLD Hang Tag",
    type: "service",
    default_color: "White",
    quantities: [1000, 2500],
    pricing: {
      base: {
        price: 0.89,
        discount: {
          2500: 0.69,
        },
      },
    },
  },
  {
    code: "HENFAT-33G24-443352",
    name: "Poly Coated Plate",
    fullname: "Poly Coated Cardboard w/black/blue imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENFAT"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.89,
      },
    },
  },
  {
    code: "HENADU-G24-385877A",
    name: "Poly Coated Plate",
    fullname: "Poly Coated Cardboard w/dark green imprint",
    type: "customs",
    default_color: "Dk Green",
    supportedStores: ["HENADU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.99,
      },
    },
  },
  {
    code: "HENHWO-31DD-343372",
    name: "Die Cut Decal",
    fullname: "Black & 285 Blue Die Cut Decal (screened on clear)",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENHWO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.89,
      },
    },
  },
  {
    code: "HENHWO-33P-376460B",
    name: "Drive Out Tag",
    fullname: "Poly Coated Cardboard w/black & 293 blue imprint",
    type: "customs",
    default_color: "White",
    supportedStores: ["HENHWO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.95,
      },
    },
  },
  {
    code: "HENCDU-33P-370807A",
    name: "Hennessy Cadillac Tag",
    fullname: "Poly Coated Cardboard w/cool gray 11 imprint",
    type: "customs",
    default_color: "White",
    supportedStores: ["HENCDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENHWO-34CP-377796A",
    name: "Chrome Plated Frame",
    fullname: "Chrome Plated Frame w/black imprint",
    type: "customs",
    default_color: "Chrome Plated",
    supportedStores: ["HENHWO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 3.35,
      },
    },
  },
  {
    code: "HENADU-34CF-437447A",
    name: "Chrome Faced Frame",
    fullname: "Chrome Faced Frame w/black imprint",
    type: "customs",
    default_color: "Chrome",
    supportedStores: ["HENADU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.49,
      },
    },
  },
  {
    code: "HENMMO-34CF-503744A",
    name: "Chrome Faced Frame",
    fullname: "Chrome Faced Frame w/black imprint",
    type: "customs",
    default_color: "Chrome",
    supportedStores: ["HENMMO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENMMO-34CF-503933A",
    name: "Chrome Faced Frame",
    fullname: "Chrome Faced Frame w/black imprint",
    type: "customs",
    default_color: "Chrome",
    supportedStores: ["HENMMO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENLAL-34CF-459349A",
    name: "Chrome Faced Frame",
    fullname: "Chrome Faced Frame w/black imprint",
    type: "customs",
    default_color: "Chrome Faced",
    supportedStores: ["HENLAL"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENCDU-34CF-370808A",
    name: "Chrome Faced Frame",
    fullname: "Chrome Faced Frame w/black imprint",
    type: "customs",
    default_color: "Chrome",
    supportedStores: ["HENCDU"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENMMO-THC-477566A",
    name: "Domecal Hitch Cover",
    fullname: "Domecal Hitch Cover",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENMMO"],
    quantities: [250],
    pricing: {
      base: {
        price: 4.49,
      },
    },
  },
  {
    code: "HENHWO-33P3D-376461A",
    name: "3D Tag",
    fullname: "3D Black Plate w/white imprint",
    type: "customs",
    default_color: "Black",
    supportedStores: ["HENHWO"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 2.39,
      },
    },
  },
  {
    code: "HENFAT-1830-478437",
    name: "Service Due Sticker",
    fullname: "Service Due Sticker w/QR code",
    type: "service",
    default_color: "White",
    quantities: [5000, 10000],
    pricing: {
      base: {
        price: 0.21,
        discount: {
          10000: 0.19,
        },
      },
    },
  },
  {
    code: "HENCDU-STKR-506185Z",
    name: "Caution Sticker - Cadillac Duluth",
    fullname: "40 Mineral Orange Vinyl Sticker w/black imprint",
    type: "service",
    default_color: "Orange",
    quantities: [1500],
    pricing: {
      base: {
        price: 0.89,
      },
    },
  },
  {
    code: "HENCDU-CERT-481428Z",
    name: "SVC Certificate - Cadillac Duluth",
    fullname: "Free Service Certificate",
    type: "service",
    default_color: "Black",
    quantities: [500],
    pricing: {
      base: {
        price: 0.39,
      },
    },
  },
  {
    code: "HENCDU-PEN-495480A",
    name: "Blue Maxiglide Pen - Cadillac Duluth",
    fullname: "Blue Maxiglide Pure Pen w/white imprint (#582)",
    type: "accessory",
    default_color: "Blue",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 0.79,
      },
    },
  },
  {
    code: "HENFAT-MUG-505968",
    name: "15oz. Mug w/imprint",
    fullname: "Royal 15oz. Ember Mug w/silver imprint",
    type: "accessory",
    default_color: "Royal",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 2.89,
      },
    },
  },
  {
    code: "HENFAT-MUG-492907",
    name: "15oz. Mug w/imprint",
    fullname: "Black 15oz. Mug w/laser engraved imprint",
    type: "accessory",
    default_color: "Black",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 16.99,
      },
    },
  },
  {
    code: "HENCDU-KOOZIE-508516A",
    name: "Black Kan-Tastic - Cadillac Duluth",
    fullname: "Black Kan-Tastic w/white imprint (#34)",
    type: "accessory",
    default_color: "Black",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 0.99,
      },
    },
  },
  {
    code: "HENCDU-BOTTLE-508517A",
    name: "Black 24oz Bottle - Cadillac Duluth",
    fullname: "Black 24oz Stainless Steel Bottle w/white imprint (#50240)",
    type: "accessory",
    default_color: "Black",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 17.99,
      },
    },
  },
  {
    code: "HENFAT-TOTE-493101",
    name: "Vinyl Tote w/imprint",
    fullname: "Vinyl Tote w/full color imprint",
    type: "accessory",
    default_color: "Black",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 1.69,
      },
    },
  },
  {
    code: "HENPMA-TOTE-2ML8410",
    name: "Matte Tote 8 x 10 x 4",
    fullname: "White Matte Laminated Euro Tote w/black imprint (8x10x4)",
    type: "accessory",
    default_color: "White",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 1.39,
      },
    },
  },
  {
    code: "HENPMA-TOTE-2L13510",
    name: "Laminated Tote 13 x 10 x 5",
    fullname: "White Gloss Laminated Euro Tote w/black imprint (13x10x5)",
    type: "accessory",
    default_color: "White",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 1.55,
      },
    },
  },
  {
    code: "HENPMA-TOTE-2L16612",
    name: "Laminated Tote 16 x 12 x 6",
    fullname: "White Gloss Laminated Euro Tote w/black imprint (16x12x6)",
    type: "accessory",
    default_color: "White",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 1.69,
      },
    },
  },
  {
    code: "HENFAT-TOTE-492717",
    name: "Laminated Tote w/imprint",
    fullname: "Black Gloss Laminated Tote w/white imprint",
    type: "accessory",
    default_color: "Black",
    quantities: [100, 250, 500, 1000, 1500],
    pricing: {
      base: {
        price: 2.29,
      },
    },
  },
];
