export const catalog = [
  {
    code: "CP95",
    name: "Port Authority® Beanie #CP95",
    fullname: "Port Authority® 100% Cotton Beanie (CP95)",
    colors: ["Navy"],
    type: "hat",
    default_color: "Navy",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 8.49 },
    },
  },
  {
    code: "CGM211",
    name: "Callaway Performance Polo #CGM211",
    fullname: "Callaway Core Performance Polo (CGM211)",
    colors: ["Black","Peacoat","Smoked Pearl"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 43.99 },
      "3XLarge": { price: 44.99 },
      "4XLarge": { price: 45.99 },
    },
  },
  {
    code: "CGW212",
    name: "Callaway Performance Polo #CGW212",
    fullname: "Ladies Callaway Core Performance Polo (CGW212)",
    colors: ["Black","Peacoat","Smoked Pearl"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 43.99 },
      "3XLarge": { price: 44.99 },
    },
  },
  {
    code: "CGM670",
    name: "Callaway Long Sleeve Polo #CGM670",
    fullname: "Callaway Long Sleeve Core Performance Polo (CGM670)",
    colors: ["Black","Peacoat","Smoked Pearl"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 46.99 },
      Medium: { price: 46.99 },
      Large: { price: 46.99 },
      XLarge: { price: 46.99 },
      "2XLarge": { price: 47.99 },
      "3XLarge": { price: 48.99 },
      "4XLarge": { price: 49.99 },
    },
  },
  {
    code: "CGW708",
    name: "Callaway 3/4 Sleeve Polo #CGW708",
    fullname: "Callaway 3/4 Sleeve Polo (CGW708)",
    colors: ["Peacoat"],
    type: "womens",
    default_color: "Peacoat",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 46.99 },
      Medium: { price: 46.99 },
      Large: { price: 46.99 },
      XLarge: { price: 46.99 },
      "2XLarge": { price: 47.99 },
      "3XLarge": { price: 48.99 },
    },
  },
  {
    code: "LOG101",
    name: "OGIO® - Jewel Polo #LOG101",
    fullname: "OGIO® - Jewel Polo (LOG101)",
    colors: ["Blacktop","Navy","Rogue Grey"],
    type: "womens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 34.99 },
      Medium: { price: 34.99 },
      Large: { price: 34.99 },
      XLarge: { price: 34.99 },
      "2XLarge": { price: 35.99 },
      "3XLarge": { price: 36.99 },
      "4XLarge": { price: 37.99 },
    },
  },
  {
    code: "PC61P",
    name: "Port & Company® Pocket Tee #PC61P",
    fullname: "Port & Company® Essential Pocket Tee (PC61P)",
    colors: ["Jet Black"],
    type: "mens",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 15.99 },
      Medium: { price: 15.99 },
      Large: { price: 15.99 },
      XLarge: { price: 15.99 },
      "2XLarge": { price: 17.99 },
      "3XLarge": { price: 18.99 },
      "4XLarge": { price: 19.99 },
    },
  },
  {
    code: "18500",
    name: "Gildan® Hooded Sweatshirt #18500",
    fullname: "Gildan® Heavy Blend™ Hooded Sweatshirt (18500)",
    colors: ["Black","Navy"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge"],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 25.99 },
      "3XLarge": { price: 26.99 },
      "4XLarge": { price: 27.99 },
      "5XLarge": { price: 28.99 },
    },
  },
  {
    code: "EB204",
    name: "Eddie Bauer® Fleece Vest #EB204",
    fullname: "Eddie Bauer® Fleece Vest (EB204)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 54.99 },
      Medium: { price: 54.99 },
      Large: { price: 54.99 },
      XLarge: { price: 54.99 },
      "2XLarge": { price: 55.99 },
      "3XLarge": { price: 57.99 },
      "4XLarge": { price: 58.99 },      
    },
  },
  {
    code: "OG755",
    name: "OGIO® Commuter Jacket #OG755",
    fullname: "OGIO® Commuter Full-Zip Soft Shell (OG755)",
    colors: ["Blacktop"],
    type: "mens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 79.99 },
      Medium: { price: 79.99 },
      Large: { price: 79.99 },
      XLarge: { price: 79.99 },
      "2XLarge": { price: 81.99 },
      "3XLarge": { price: 83.99 },
      "4XLarge": { price: 84.99 },
    },
  },
  {
    code: "LOG755",
    name: "OGIO® Commuter Jacket #LOG755",
    fullname: "OGIO® Women's Commuter Full-Zip Soft Shell (LOG755)",
    colors: ["Blacktop"],
    type: "womens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 79.99 },
      Medium: { price: 79.99 },
      Large: { price: 79.99 },
      XLarge: { price: 79.99 },
      "2XLarge": { price: 81.99 },
      "3XLarge": { price: 83.99 },
      "4XLarge": { price: 84.99 },
    },
  },  
  {
    code: "HOFAPA-438-491792A",
    name: "Panther Pen",
    fullname: "White Panther Pen w/reflex blue imprint (#438)",
    colors: ["White"],
    type: "accessory",
    default_color: "White",
    quantities: [5000],
    pricing: {
      base: {
        price: 0.45,
      },
    },
  },
  {
    code: "HOFAPA-FOB-507902L",
    name: "Silverline 'U' Keychain",
    fullname: "Silverline 'U' Keychain w/laser engraved imprint (#CG-3033)",
    colors: ["Silver"],
    type: "accessory",
    default_color: "Silver",
    quantities: [1000, 1500],
    pricing: {
      base: {
        price: 3.65,
        discount: {
          1500: 3.49,
        },
      },
    },
  },
   {
    code: "HOFAPA-LAPELPIN-484175Z",
    name: "Lapel Pin with Imprint",
    fullname: "White Lapel Pin w/full color imprint",
    colors: ["White"],
    type: "accessory",
    default_color: "White",
    quantities: [2000],
    pricing: {
      base: {
        price: 1.69,
      },
    },
  },
  {
    code: "HOFAPA-33P-484091A",
    name: ".15 Gauge Plastic Plate",
    fullname: "White Plastic Plate w/black imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["HOFAPA"],
    quantities: [5000],
    pricing: {
      base: {
        price: 0.49,
      },
    },
  },
  {
    code: "HOFAPA-34MLF-496173A",
    name: "Black Metal Frame",
    fullname: "Black Metal Frame w/acrylic insterts & white imprint",
    colors: ["Black Metal"],
    type: "customs",
    default_color: "Black Metal",
    supportedStores: ["HOFAPA"],
    quantities: [300, 500],
    pricing: {
      base: {
        price: 6.99,
        discount: {
          500: 6.49,
        },
      },
    },
  },
  {
    code: "HOFAPA-33AP-496163A",
    name: "Black Acrylic Frame",
    fullname: "Black Acrylic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["HOFAPA"],
    quantities: [300, 500],
    pricing: {
      base: {
        price: 6.99,
        discount: {
          500: 6.49,
        },
      },
    },
  },
  {
    code: "HOFAPA-0201-507790Z",
    name: "Non-Expandable Cardstock Folder",
    fullname: "9-7/8 x 6 Non-Expandable White Marble Crush Cardstock w/full color imprint",
    colors: ["White"],
    type: "sales",
    default_color: "White",
    quantities: [2500],
    pricing: {
      base: {
        price: 1.19,
      },
    },
  },
   {
    code: "HOFAPA-0211-489788Z",
    name: "Expandable Cardstock Folder",
    fullname: "9-7/8 x 6 White Expandable Marble Crush Cardstock w/full color imprint",
    colors: ["White"],
    type: "sales",
    default_color: "White",
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 1.19,
        discount: {
          5000: 1.09,
        },
      },
    },
  },
]