export const catalog = [
 {
    code: "K540",
    name: "Port Authority Silk Touch Polo #K540",
    fullname: "Port Authority® Silk Touch™ Performance Polo (K540)",
    colors: [
      "Black",
      "Gusty Grey",
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",
      "White",      
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge"
    ],
    pricing: {
      Small: { price: 17.76 },
      Medium: { price: 17.76 },
      Large: { price: 17.76 },
      XLarge: { price: 17.76 },
      "2XLarge": { price: 19.76 },
      "3XLarge": { price: 23.76 },
      "4XLarge": { price: 25.76 },
      "5XLarge": { price: 29.76 },
      "6XLarge": { price: 31.76 },
    },
  },
  {
    code: "L540",
    name: "Port Authority® Silk Touch™ Polo #L540",
    fullname: "Port Authority® Silk Touch™ Performance Polo (L540)",
    colors: [
      "Black",      
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",
      "White",      
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      XSmall: { price: 17.76 },
      Small: { price: 17.76 },
      Medium: { price: 17.76 },
      Large: { price: 17.76 },
      XLarge: { price: 17.76 },
      "2XLarge": { price: 19.76 },
      "3XLarge": { price: 23.76 },
      "4XLarge": { price: 25.76 },      
    },
  },
  {
    code: "K200",
    name: "Port Authority Wearever Polo #K200",
    fullname: "Port Authority® Wearever Signature Pique Polo (K200)",
    colors: [
      "Awareness Pink",
      "Deep Black",
      "Gusty Grey", 
      "Red",     
      "River Blue Navy",      
      "True Royal",      
      "White",      
    ],
    type: "mens",
    default_color: "Awareness Pink",
    sizes: [      
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge", 
      "5XLarge",
      "6XLarge"     
    ],
    pricing: {
      Small: { price: 16.98 },
      Medium: { price: 16.98 },
      Large: { price: 16.98 },
      XLarge: { price: 16.98 },
      "2XLarge": { price: 18.98 },
      "3XLarge": { price: 22.98 },
      "4XLarge": { price: 24.98 },
      "5XLarge": { price: 28.98 },
      "6XLarge": { price:30.98 },      
    },
  },
  {
    code: "LK200",
    name: "Port Authority Wearever Polo #LK200",
    fullname: "Port Authority® Wearever Signature Pique Polo (LK200)",
    colors: [
      "Awareness Pink",
      "Deep Black",
      "Gusty Grey", 
      "Red",     
      "River Blue Navy",      
      "True Royal",      
      "White",      
    ],
    type: "womens",
    default_color: "Awareness Pink",
    sizes: [  
      "XSmall",    
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge", 
      "5XLarge",
      "6XLarge"     
    ],
    pricing: {
      XSmall: { price: 16.98 },
      Small: { price: 16.98 },
      Medium: { price: 16.98 },
      Large: { price: 16.98 },
      XLarge: { price: 16.98 },
      "2XLarge": { price: 18.98 },
      "3XLarge": { price: 22.98 },
      "4XLarge": { price: 24.98 },
      "5XLarge": { price: 28.98 },
      "6XLarge": { price:30.98 },      
    },
  },
];
