export const catalog = [
  {
    code: "S608",
    name: "Port Authority® Shirt #S608",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt (S608)",
    colors: [
      "Black",      
      "Navy",      
      "Red",
      "Royal",      
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge", 
      "5XLarge", 
      "6XLarge"
    ],
    pricing: {
      Small: { price: 30.16 },
      Medium: { price: 30.16 },
      Large: { price: 30.16 },
      XLarge: { price: 30.16 },
      "2XLarge": { price: 32.16},
      "3XLarge": { price: 36.16 },
      "4XLarge": { price: 38.16 },
      "5XLarge": { price: 42.16 },
      "6XLarge": { price: 44.16 },
    },
  },
  {
    code: "K540",
    name: "Port Authority Silk Touch Polo #K540",
    fullname: "Port Authority® Silk Touch™ Performance Polo (K540)",
    colors: [
      "Black",
      "Gusty Grey",
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",
      "White",      
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge"
    ],
    pricing: {
      Small: { price: 17.76 },
      Medium: { price: 17.76 },
      Large: { price: 17.76 },
      XLarge: { price: 17.76 },
      "2XLarge": { price: 19.76 },
      "3XLarge": { price: 23.76 },
      "4XLarge": { price: 25.76 },
      "5XLarge": { price: 29.76 },
      "6XLarge": { price: 31.76 },
    },
  },
  {
    code: "K200",
    name: "Port Authority Wearever Polo #K200",
    fullname: "Port Authority® Wearever Signature Pique Polo (K200)",
    colors: [
      "Awareness Pink",
      "Deep Black",
      "Gusty Grey", 
      "Red",     
      "River Blue Navy",      
      "True Royal",      
      "White",      
    ],
    type: "mens",
    default_color: "Awareness Pink",
    sizes: [      
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge", 
      "5XLarge",
      "6XLarge"     
    ],
    pricing: {
      Small: { price: 16.98 },
      Medium: { price: 16.98 },
      Large: { price: 16.98 },
      XLarge: { price: 16.98 },
      "2XLarge": { price: 18.98 },
      "3XLarge": { price: 22.98 },
      "4XLarge": { price: 24.98 },
      "5XLarge": { price: 28.98 },
      "6XLarge": { price: 30.98 },      
    },
  },
  {
    code: "OG143",
    name: "OGIO® Slate Poloo #OG143",
    fullname: "OGIO® Slate Polo (OG143)",
    colors: [
      "Blacktop",      
      "Gear Grey",           
      "Navy",    
    ],
    type: "mens",
    default_color: "Blacktop",
    sizes: [      
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",          
    ],
    pricing: {
      Small: { price: 41.36 },
      Medium: { price: 41.36 },
      Large: { price: 41.36 },
      XLarge: { price: 41.36 },
      "2XLarge": { price: 43.36 },
      "3XLarge": { price: 47.36 },
      "4XLarge": { price: 49.36 },          
    },
  },
  {
    code: "K540LS",
    name: "Port Authority Long Sleeve Polo #K540LS",
    fullname: "Port Authority® Silk Touch™ Performance Long Sleeve Polo (K540LS)",
    colors: [
      "Black",      
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",      
      "White",      
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 22.34 },
      Medium: { price: 22.34 },
      Large: { price: 22.34 },
      XLarge: { price: 22.34 },
      "2XLarge": { price: 24.34 },
      "3XLarge": { price: 28.34 },
      "4XLarge": { price: 30.34 },      
    },
  },
  {
    code: "L608",
    name: "Port Authority® Shirt #L608",
    fullname: "Port Authority® Women's Long Sleeve Shirt (L608)",
    colors: [
      "Black",      
      "Navy",      
      "Red",
      "Royal",     
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge", 
      "5XLarge", 
      "6XLarge"
    ],
    pricing: {
      XSmall: { price: 30.16 },
      Small: { price: 30.16 },
      Medium: { price: 30.16 },
      Large: { price: 30.16 },
      XLarge: { price: 30.16 },
      "2XLarge": { price: 32.16},
      "3XLarge": { price: 36.16 },
      "4XLarge": { price: 38.16 },
      "5XLarge": { price: 42.16 },
      "6XLarge": { price: 44.16 },
    },
  },
  {
    code: "L540",
    name: "Port Authority® Silk Touch™ Polo #L540",
    fullname: "Port Authority® Silk Touch™ Performance Polo (L540)",
    colors: [
      "Black",      
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",
      "White",      
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      XSmall: { price: 17.76 },
      Small: { price: 17.76 },
      Medium: { price: 17.76 },
      Large: { price: 17.76 },
      XLarge: { price: 17.76 },
      "2XLarge": { price: 19.76 },
      "3XLarge": { price: 23.76 },
      "4XLarge": { price: 25.76 },      
    },
  },  
  {
    code: "LK200",
    name: "Port Authority Wearever Polo #LK200",
    fullname: "Port Authority® Wearever Signature Pique Polo (LK200)",
    colors: [
      "Awareness Pink",
      "Deep Black",
      "Gusty Grey", 
      "Red",     
      "River Blue Navy",      
      "True Royal",      
      "White",      
    ],
    type: "womens",
    default_color: "Awareness Pink",
    sizes: [  
      "XSmall",    
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge", 
      "5XLarge",
      "6XLarge"     
    ],
    pricing: {
      XSmall: { price: 16.98 },
      Small: { price: 16.98 },
      Medium: { price: 16.98 },
      Large: { price: 16.98 },
      XLarge: { price: 16.98 },
      "2XLarge": { price: 18.98 },
      "3XLarge": { price: 22.98 },
      "4XLarge": { price: 24.98 },
      "5XLarge": { price: 28.98 },
      "6XLarge": { price:30.98 },      
    },
  },
  {
    code: "L500LS",
    name: "Port Authority® Long Sleeve Polo #L500LS",
    fullname: "Port Authority® Women's Silk Touch™ Long Sleeve Polo (L500LS)",
    colors: [
      "Black",      
      "Navy",
      "Red",
      "Royal",            
      "White",      
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      XSmall: { price: 27.92 },
      Small: { price: 27.92 },
      Medium: { price: 27.92 },
      Large: { price: 27.92 },
      XLarge: { price: 27.92 },
      "2XLarge": { price: 29.92 },
      "3XLarge": { price: 33.92 },
      "4XLarge": { price: 35.92 },      
    },
  },
];
