export const catalog = [
  {
    code: "PC01",
    name: "Port & Co™ Blend Tee $18.50",
    fullname: "Port & Co™ Core Blend Recycled Tee (PC01)",
    colors: [
      "Athletic Heather",
      "Charcoal",
      "Drk Hthr Gry",
      "Jet Black",
      "Navy",
      "Navy Blue Hthr",
      "True Royal",
    ],
    type: "mens",
    default_color: "Athletic Heather",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 18.5 },
      Medium: { price: 18.5 },
      Large: { price: 18.5 },
      XLarge: { price: 18.5 },
      "2XLarge": { price: 20.5 },
      "3XLarge": { price: 24.0 },
    },
  },
  {
    code: "BC3001",
    name: "BELLA+CANVAS® Tee $21.25",
    fullname: "BELLA+CANVAS® Unisex Jersey Short Sleeve Tee (BC3001)",
    colors: ["Ash", "Black", "Dark Grey", "Navy", "True Royal", "White"],
    type: "mens",
    default_color: "Ash",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 21.25 },
      Medium: { price: 21.25 },
      Large: { price: 21.25 },
      XLarge: { price: 21.25 },
      "2XLarge": { price: 23.5 },
      "3XLarge": { price: 25.0 },
    },
  },
  {
    code: "29LS",
    name: "Jerzees® Long Sleeve Tee $23.00",
    fullname:
      "Jerzees® Dri-Power® 50/50 Cotton/Poly Long Sleeve T-Shirt (29LS)",
    colors: [
      "Ash",
      "Athletic Heather",
      "Black",
      "Charcoal Grey",
      "JNavy",
      "Royal",
      "Sandstone",
      "Vintage Hthr Navy",
      "White",
    ],
    type: "mens",
    default_color: "Ash",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 23.0 },
      Medium: { price: 23.0 },
      Large: { price: 23.0 },
      XLarge: { price: 23.0 },
      "2XLarge": { price: 25.0 },
      "3XLarge": { price: 28.0 },
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo $33.00",
    fullname: "Sport-Tek® Micropique Polo (ST650)",
    colors: [
      "Black",
      "Grey Concrete",
      "Iron Grey",
      "True Navy",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 33.0 },
      Medium: { price: 33.0 },
      Large: { price: 33.0 },
      XLarge: { price: 33.0 },
      "2XLarge": { price: 35.5 },
      "3XLarge": { price: 37.5 },
      "4XLarge": { price: 39.99 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo $49.99",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
      "Anthracite",
      "Black",
      "Cool Grey",
      "Game Royal",
      "Gym Blue",
      "Navy",
      "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 51.99 },
      "3XLarge": { price: 54.99 },
      "4XLarge": { price: 56.99 },
    },
  },
  {
    code: "TM1MU410",
    name: "TravisMathew Polo $74.99",
    fullname: "TravisMathew Coto Performance Polo (TM1MU410)",
    colors: [
      "Black",
      "Blue Nights",
      "Quiet Shade Gry Hthr",
      "Quiet Shade Gry Blk",
      "Vintage Indigo Blk",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 74.99 },
      Medium: { price: 74.99 },
      Large: { price: 74.99 },
      XLarge: { price: 74.99 },
      "2XLarge": { price: 76.99 },
      "3XLarge": { price: 78.99 },
    },
  },
  {
    code: "PC90",
    name: "Port & Co™ Sweatshirt $25.99",
    fullname: "Port & Co™ Essential Fleece Crewneck Sweatshirt (PC90)",
    colors: [
      "Ash",
      "Athletic Heather",
      "Charcoal",
      "Jet Black",
      "Navy",
      "Royal",
      "White",
    ],
    type: "mens",
    default_color: "Ash",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 25.99 },
      Medium: { price: 25.99 },
      Large: { price: 25.99 },
      XLarge: { price: 25.99 },
      "2XLarge": { price: 27.99 },
      "3XLarge": { price: 30.99 },
      "4XLarge": { price: 32.99 },
    },
  },
  {
    code: "NKFD9863",
    name: "Nike® Club Fleece Crew $59.99",
    fullname: "Nike Club Fleece Sleeve Swoosh Crew (NKFD9863)",
    colors: [
      "Anthracite",
      "Black",
      "Drk Gry Hthr",
      "Game Royal",
      "Midnight Navy",
      "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 59.99 },
      Medium: { price: 59.99 },
      Large: { price: 59.99 },
      XLarge: { price: 59.99 },
      "2XLarge": { price: 61.99 },
      "3XLarge": { price: 64.99 },
      "4XLarge": { price: 66.99 },
    },
  },
  {
    code: "NEA137",
    name: "New Era® Tri-Blend Hoodie $35.99",
    fullname: "New Era® Tri-Blend Hoodie (NEA137)",
    colors: ["Black Solid", "Graphite", "Shadow Grey", "True Navy"],
    type: "mens",
    default_color: "Black Solid",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 35.99 },
      Medium: { price: 35.99 },
      Large: { price: 35.99 },
      XLarge: { price: 35.99 },
      "2XLarge": { price: 37.99 },
      "3XLarge": { price: 40.99 },
      "4XLarge": { price: 42.99 },
    },
  },
  {
    code: "NL9307",
    name: "Next Level Apparel® Hoodie $46.00",
    fullname: "Next Level Apparel® Heavyweight Hoodie (NL9307)",
    colors: ["Black", "Bone", "HthrGry", "Midnight Navy", "Tan"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 46.0 },
      Medium: { price: 46.0 },
      Large: { price: 46.0 },
      XLarge: { price: 46.0 },
      "2XLarge": { price: 48.0 },
      "3XLarge": { price: 50.0 },
    },
  },
  {
    code: "F219",
    name: "Port Authority® Vest $36.99",
    fullname: "Port Authority® Value Fleece Vest (F219)",
    colors: ["Black", "Iron Grey", "True Navy", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 43.99 },
    },
  },
  {
    code: "OG741",
    name: "OGIO® Soft Shell Vest $68.99",
    fullname: "OGIO® Kinetic Soft Shell Vest (OG741)",
    colors: ["Blacktop", "River Blue Navy", "Sahara"],
    type: "mens",
    default_color: "Blacktop",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 68.99 },
      Medium: { price: 68.99 },
      Large: { price: 68.99 },
      XLarge: { price: 68.99 },
      "2XLarge": { price: 70.99 },
      "3XLarge": { price: 72.99 },
      "4XLarge": { price: 75.99 },
    },
  },
  {
    code: "CT102286",
    name: "Carhartt® Gilliam Vest $98.99",
    fullname: "Carhartt® Gilliam Vest (CT102286)",
    colors: ["Black", "Navy", "Shadow Grey"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 98.99 },
      Medium: { price: 98.99 },
      Large: { price: 98.99 },
      XLarge: { price: 98.99 },
      "2XLarge": { price: 100.99 },
      "3XLarge": { price: 102.99 },
    },
  },
  {
    code: "F218",
    name: "Port Authority® Pullover $39.99",
    fullname: "Port Authority® Value Fleece 1/4-Zip Pullover (F218)",
    colors: ["Black", "Iron Grey", "True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 41.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 47.99 },
    },
  },
  {
    code: "CN9492",
    name: "Nike® 1/4-Zip Fleece $67.99",
    fullname: "Nike® Therma-FIT 1/4-Zip Fleece (CN9492)",
    colors: ["Team Anthracite", "Team Black", "Team Navy", "Team Royal"],
    type: "mens",
    default_color: "Team Anthracite",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 67.99 },
      Medium: { price: 67.99 },
      Large: { price: 67.99 },
      XLarge: { price: 67.99 },
      "2XLarge": { price: 69.99 },
      "3XLarge": { price: 72.99 },
      "4XLarge": { price: 74.99 },
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip $77.99",
    fullname: "The North Face® Ambition 1/4-Zip (NF0A8ENR)",
    colors: ["Meld Grey Hthr", "Shady Blue", "Smoked Pearl Gry", "TNF Black"],
    type: "mens",
    default_color: "Meld Grey Hthr",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 77.99 },
      Medium: { price: 77.99 },
      Large: { price: 77.99 },
      XLarge: { price: 77.99 },
      "2XLarge": { price: 79.99 },
      "3XLarge": { price: 82.99 },
    },
  },
  {
    code: "NEA228",
    name: "New Era® Power 1/2-Zip $43.99",
    fullname: "New Era® Power 1/2-Zip (NEA228)",
    colors: ["Black", "Shadow Gry Hthr", "True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 43.99 },
      Medium: { price: 43.99 },
      Large: { price: 43.99 },
      XLarge: { price: 43.99 },
      "2XLarge": { price: 45.99 },
      "3XLarge": { price: 48.99 },
      "4XLarge": { price: 50.99 },
    },
  },
  {
    code: "OG813",
    name: "OGIO® Luuma 1/2-Zip $68.99",
    fullname: "OGIO® Luuma 1/2-Zip Fleece (OG813)",
    colors: ["Blacktop", "Pearl Grey Heather", "River Blue Navy"],
    type: "mens",
    default_color: "Blacktop",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 68.99 },
      Medium: { price: 68.99 },
      Large: { price: 68.99 },
      XLarge: { price: 68.99 },
      "2XLarge": { price: 70.99 },
      "3XLarge": { price: 73.99 },
      "4XLarge": { price: 75.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket $47.99",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    colors: ["Black", "Battleship Grey", "Dress Blue Navy", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 47.99 },
      Medium: { price: 47.99 },
      Large: { price: 47.99 },
      XLarge: { price: 47.99 },
      "2XLarge": { price: 49.99 },
      "3XLarge": { price: 52.99 },
      "4XLarge": { price: 54.99 },
    },
  },
  {
    code: "OG740",
    name: "OGIO® Kinetic Jacket $77.99",
    fullname: "OGIO® Kinetic Soft Shell Jacket (OG740)",
    colors: ["Blacktop", "River Blue Navy", "Sahara"],
    type: "mens",
    default_color: "Blacktop",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 77.99 },
      Medium: { price: 77.99 },
      Large: { price: 77.99 },
      XLarge: { price: 77.99 },
      "2XLarge": { price: 79.99 },
      "3XLarge": { price: 83.99 },
      "4XLarge": { price: 85.99 },
    },
  },
  {
    code: "NKDX6716",
    name: "Nike® Full-Zip Jacket $98.99",
    fullname: "Nike® Storm-FIT Full-Zip Jacket (NKDX6716)",
    colors: ["Anthracite", "Black", "College Navy", "Stone"],
    type: "mens",
    default_color: "Anthracite",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 98.99 },
      Medium: { price: 98.99 },
      Large: { price: 98.99 },
      XLarge: { price: 98.99 },
      "2XLarge": { price: 100.99 },
      "3XLarge": { price: 102.99 },
      "4XLarge": { price: 105.99 },
    },
  },
  {
    code: "LPC55",
    name: "Port & Co™ Blend Tee $20.00",
    fullname: "Port & Co™ Women's Core Blend Tee (LPC55)",
    colors: [
      "Athletic Heather",
      "Charcoal",
      "Jet Black",
      "Navy",
      "Royal",
      "White",
    ],
    type: "womens",
    default_color: "Athletic Heather",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 20.0 },
      Medium: { price: 20.0 },
      Large: { price: 20.0 },
      XLarge: { price: 20.0 },
      "2XLarge": { price: 22.0 },
    },
  },
  {
    code: "LPC61",
    name: "Port & Co™ Essential Tee $20.50",
    fullname: "Port & Co™ Women's Essential Tee (LPC61)",
    colors: ["Athletic Heather", "Jet Black", "Navy", "Royal", "White"],
    type: "womens",
    default_color: "Athletic Heather",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 20.5 },
      Medium: { price: 20.5 },
      Large: { price: 20.5 },
      XLarge: { price: 20.5 },
      "2XLarge": { price: 22.5 },
    },
  },
  {
    code: "AL2303",
    name: "Allmade® V-Neck Tee $22.00",
    fullname: "Allmade® Women's Recycled Blend V-Neck Tee (AL2303)",
    colors: [
      "Reloaded Char Hthr",
      "Remade Gray Hthr",
      "Reused Royal Hthr",
      "Salvaged Navy Hthr",
    ],
    type: "womens",
    default_color: "Reloaded Char Hthr",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 22.0 },
      Medium: { price: 22.0 },
      Large: { price: 22.0 },
      XLarge: { price: 22.0 },
      "2XLarge": { price: 24.0 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo $33.00",
    fullname: "Sport-Tek® Womens Micropique Polo (LST650)",
    colors: [
      "Black",
      "Grey Concrete",
      "Iron Grey",
      "True Navy",
      "True Royal",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 33.0 },
      Medium: { price: 33.0 },
      Large: { price: 33.0 },
      XLarge: { price: 33.0 },
      "2XLarge": { price: 35.5 },
      "3XLarge": { price: 37.5 },
      "4XLarge": { price: 39.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo $49.99",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
    colors: [
      "Anthracite",
      "Black",
      "Cool Grey",
      "Game Royal",
      "Gym Blue",
      "Navy",
      "White",
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 51.99 },
    },
  },
  {
    code: "838957",
    name: "Nike® Dri-FIT Polo $69.99",
    fullname: "Nike Women's Dri-FIT Legacy Polo (838957)",
    colors: ["Black", "Dark Grey", "Game Royal", "Midnight Navy"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 69.99 },
      Medium: { price: 69.99 },
      Large: { price: 69.99 },
      XLarge: { price: 69.99 },
      "2XLarge": { price: 71.99 },
    },
  },
  {
    code: "DT6105",
    name: "District® Fleece Crew $31.99",
    fullname: "District® Women's V.I.T.™ Fleece Crew (DT6105)",
    colors: ["Black", "Gardenia", "Hthrd Charcoal", "Light Gry Hthr"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 31.99 },
      Medium: { price: 31.99 },
      Large: { price: 31.99 },
      XLarge: { price: 31.99 },
      "2XLarge": { price: 33.99 },
      "3XLarge": { price: 35.99 },
      "4XLarge": { price: 37.99 },
    },
  },
  {
    code: "DT6101",
    name: "District® Fleece Hoodie $34.99",
    fullname: "District® Women's V.I.T.™ Fleece Hoodie (DT6101)",
    colors: ["Black", "Deep Royal", "Light Gry Hthr", "White"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 34.99 },
      Medium: { price: 34.99 },
      Large: { price: 34.99 },
      XLarge: { price: 34.99 },
      "2XLarge": { price: 36.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 41.99 },
    },
  },
  {
    code: "NL9307",
    name: "Next Level Apparel® Hoodie $46.00",
    fullname: "Next Level Apparel® Heavyweight Hoodie (NL9307)",
    colors: ["Black", "Bone", "HthrGry", "Midnight Navy", "Tan"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 46.0 },
      Medium: { price: 46.0 },
      Large: { price: 46.0 },
      XLarge: { price: 46.0 },
      "2XLarge": { price: 48.0 },
      "3XLarge": { price: 50.0 },
    },
  },
  {
    code: "LNEA500",
    name: "New Era® Terry Hoodie $59.99",
    fullname: "New Era® Women's French Terry Pullover Hoodie (LNEA500)",
    colors: [
      "Black",
      "Black Twist",
      "Drk Ryl Twst",
      "Lt Grph Twst",
      "True Navy",
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 59.99 },
      Medium: { price: 59.99 },
      Large: { price: 59.99 },
      XLarge: { price: 59.99 },
      "2XLarge": { price: 61.99 },
      "3XLarge": { price: 63.99 },
      "4XLarge": { price: 65.99 },
    },
  },
  {
    code: "L219",
    name: "Port Authority® Vest $36.99",
    fullname: "Port Authority® Women's Value Fleece Vest (L219)",
    colors: ["Black", "Iron Grey", "True Navy", "True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 43.99 },
    },
  },
  {
    code: "LST941",
    name: "Sport-Tek® Vest $49.99",
    fullname: "Sport-Tek® Womens Teknical Hybrid Vest (LST941)",
    colors: ["Black", "Iron Grey", "Silver", "True Navy", "True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 51.99 },
      "3XLarge": { price: 53.99 },
      "4XLarge": { price: 55.99 },
    },
  },
  {
    code: "LST357",
    name: "Sport-Tek® 1/4-Zip $31.99",
    fullname:
      "Sport-Tek® Women's PosiCharge® Competitor™ 1/4-Zip Pullover (LST357)",
    colors: ["Black", "Iron Grey", "True Navy", "True Royal", "White"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 31.99 },
      Medium: { price: 31.99 },
      Large: { price: 31.99 },
      XLarge: { price: 31.99 },
      "2XLarge": { price: 33.99 },
      "3XLarge": { price: 36.99 },
      "4XLarge": { price: 38.99 },
    },
  },
  {
    code: "LK210",
    name: "Port Authority® 1/4-Zip $44.99",
    fullname:
      "Port Authority® Women's Wearever Signature Double Pique 1/4-Zip (LK210)",
    colors: ["Deep Black", "Gusty Grey", "River Blue Navy", "Storm Grey"],
    type: "womens",
    default_color: "Deep Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 44.99 },
      Medium: { price: 44.99 },
      Large: { price: 44.99 },
      XLarge: { price: 44.99 },
      "2XLarge": { price: 46.99 },
      "3XLarge": { price: 49.99 },
      "4XLarge": { price: 51.99 },
    },
  },
  {
    code: "LOG861",
    name: "OGIO® Transcend 1/4-Zip $64.99",
    fullname: "OGIO® Women's Transcend 1/4-Zip (LOG861)",
    colors: ["Blacktop", "Opal White", "River Blue Navy", "Tarmac Grey"],
    type: "womens",
    default_color: "Blacktop",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 64.99 },
      Medium: { price: 64.99 },
      Large: { price: 64.99 },
      XLarge: { price: 64.99 },
      "2XLarge": { price: 66.99 },
      "3XLarge": { price: 69.99 },
      "4XLarge": { price: 71.99 },
    },
  },
  {
    code: "L224",
    name: "Port Authority® 1/2-Zip $34.99",
    fullname: "Port Authority® Women's Microfleece 1/2-Zip Pullover (L224)",
    colors: ["Black", "Pearl Grey", "True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 34.99 },
      Medium: { price: 34.99 },
      Large: { price: 34.99 },
      XLarge: { price: 34.99 },
      "2XLarge": { price: 36.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 41.99 },
    },
  },
  {
    code: "LNEA228",
    name: "New Era® Power 1/2-Zip $46.99",
    fullname: "New Era® Women's Power 1/2-Zip (LNEA228)",
    colors: ["Black", "Shadow Gry Hthr", "True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 46.99 },
      Medium: { price: 46.99 },
      Large: { price: 46.99 },
      XLarge: { price: 46.99 },
      "2XLarge": { price: 47.99 },
      "3XLarge": { price: 49.99 },
      "4XLarge": { price: 50.99 },
    },
  },
  {
    code: "NKDX6720",
    name: "Nike® Fleece 1/2-Zip $70.99",
    fullname: "Nike® Women's Club Fleece Sleeve Swoosh 1/2-Zip (NKDX6720)",
    colors: [
      "Anthracite",
      "Black",
      "Drk Gry Hthr",
      "Game Royal",
      "Midnight Navy",
      "White",
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 70.99 },
      Medium: { price: 70.99 },
      Large: { price: 70.99 },
      XLarge: { price: 70.99 },
      "2XLarge": { price: 73.99 },
    },
  },

  {
    code: "L317",
    name: "Port Authority® Jacket $47.99",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket (L317)",
    colors: ["Black", "Battleship Grey", "Dress Blue Navy", "True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 47.99 },
      Medium: { price: 47.99 },
      Large: { price: 47.99 },
      XLarge: { price: 47.99 },
      "2XLarge": { price: 49.99 },
      "3XLarge": { price: 52.99 },
      "4XLarge": { price: 54.99 },
    },
  },
  {
    code: "TW530",
    name: "Port Authority® Golf Towel $19.00",
    fullname: "Port Authority® Grommeted Microfiber Golf Towel (TW530)",
    colors: ["Black", "Deep Smoke", "Royal", "True Navy", "White"],
    type: "accessory",
    default_color: "Black",
    description: `85/15 poly/nylon microfiber. Fully hemmed. Corner grommet with carabiner.
    
Dimensions: 16 in. x 26 in.`,
    pricing: {
      base: {
        price: 19.0,
      },
    },
  },
  {
    code: "TB850",
    name: "Port Authority® Travel Blanket $35.00",
    fullname: "Port Authority® Fleece & Poly Travel Blanket (TB850)",
    colors: ["Black", "Lead Grey", "True Navy", "True Royal"],
    type: "accessory",
    default_color: "Black",
    description: `100% polyester fleece, 100% polyester woven backing. Attached elastic band to secure the rolled-up blanket.
    
Dimensions: 50 in. x 60 in.`,
    pricing: {
      base: {
        price: 35.0,
      },
    },
  },
  {
    code: "BP70",
    name: "Port Authority® Picnic Blanket $45.00",
    fullname: "Port Authority® Picnic Blanket (BP70)",
    colors: ["Grey Steel", "True Black", "True Royal"],
    type: "accessory",
    default_color: "Grey Steel",
    description: `100% polyester fleece, 100% polyester woven backing. Water-resistant woven backing. Zips around itself for easy folding.`,
    pricing: {
      base: {
        price: 45.0,
      },
    },
  },
  {
    code: "BG428",
    name: "Port Authority® Tote $19.00",
    fullname: "Port Authority® Cotton Canvas Shopper Tote (BG428)",
    colors: ["Deep Black", "Natural"],
    type: "accessory",
    default_color: "Deep Black",
    description: "100% cotton canvas. Dimensions: 12.5 in. x 14.5 in. x 4 in.",

    pricing: {
      base: {
        price: 19.0,
      },
    },
  },
  {
    code: "BG226",
    name: "Port Authority® Backpack $36.00",
    fullname: "Port Authority® Daily Commute Backpack (BG226)",
    colors: ["Black", "Grey Smoke"],
    type: "accessory",
    default_color: "Black",
    description: `POLYESTER; Padded air mesh shoulder straps. Padded back panel. Laptop dimensions: 15h x 12w x 1d. Fits most 15 in. laptops. 
    
Dimensions: 17.75h x 11.5w x 5d.`,
    pricing: {
      base: {
        price: 36.0,
      },
    },
  },
  {
    code: "91005",
    name: "OGIO® Convert Pack $90.00",
    fullname: "OGIO® Convert Pack (91005)",
    colors: ["Black", "Tarmac"],
    type: "accessory",
    default_color: "Black",
    description: `POLYESTER; Dedicated laptop compartment with large slip pocket for documents and a padded pocket for tablets. Detachable shoulder strap. 
    Backpack straps stow neatly behind the back panel with ease. Multiple zippered pockets. Laptop sleeve: 15h x 10.5w x 1d. 
    Fits most 15 in. laptops. 
    
Dimensions: 18h x 11w x 5d.`,
    pricing: {
      base: {
        price: 90.0,
      },
    },
  },
  {
    code: "BG305",
    name: "Port Authority® Computer Case $26.75",
    fullname: "Port Authority® Value Computer Case (BG305)",
    colors: ["Black", "Dark Charcoal", "Twilight Blue"],
    type: "accessory",
    default_color: "Black",
    description: `POLYESTER; 600 denier polyester canvas. Web carrying handles. Protective padding on sides and bottom. FITS MOST 15 in. laptops.`,
    pricing: {
      base: {
        price: 26.75,
      },
    },
  },
  {
    code: "BG309",
    name: "Port Authority® Briefcase $34.50",
    fullname: "Port Authority® Vector Briefcase (BG309)",
    colors: ["Grey Heather", "Navy Heather"],
    type: "accessory",
    default_color: "Grey Heather",
    description: `POLYESTER; Adjustable, padded shoulder strap. Large front side zippered pocket for easy decoration. 
    Luggage trolley strap on back.
    
Laptop sleeve dimensions 8h x 15w. Fits most 15 in. laptops.
    `,
    pricing: {
      base: {
        price: 34.5,
      },
    },
  },
  {
    code: "93023",
    name: "OGIO® Slim Briefcase $52.00",
    fullname: "OGIO® Slim Brief (93023)",
    colors: ["Blacktop"],
    type: "accessory",
    default_color: "Blacktop",
    description: `POLYESTER; Dedicated laptop and tablet sleeves. Webbing haul handles.
    Removable, adjustable webbing shoulder strap. Dimensions 11h x 16.75w x 1.5d.
    Fits most 16 in. laptops.`,
    pricing: {
      base: { price: 52.0 },
    },
  },
  {
    code: "CP90",
    name: "Port Authority® Knit Cap $18.50",
    fullname: "Port Authority® Knit Cap (CP90)",
    colors: [
      "Athletic Oxford",
      "Athletic Royal",
      "Black",
      "Black AthleticOxford",
      "Charcoal Heather",
      "Navy",
      "White",
      "Woodland Brown",
    ],
    type: "hat",
    default_color: "Athletic Oxford",
    halfColors: ["Black AthleticOxford"],
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 18.5 },
    },
  },
  {
    code: "CP80",
    name: "Port & Co™ Six-Panel Cap $19.00",
    fullname: "Port & Co™ Six-Panel Twill Cap (CP80)",
    colors: [
      "Black",
      "Charcoal",
      "Khaki",
      "Oyster",
      "Royal",
      "Silver",
      "True Navy",
      "White",
    ],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 19.0 },
    },
  },
  {
    code: "C402",
    name: "Port Authority Trucker Cap $21.00",
    fullname: "Port Authority® Snapback Trucker Cap (C402)",
    colors: [
      "Black",
      "Black GreySteel",
      "HthrGry PatriotBlue",
      "PatriotBlue White",
      "TrueNavy White",
      "RichNavy TrueKhaki",
      "Woodland Brown",
      "White",
    ],
    type: "hat",
    halfColors: [
      "Black GreySteel",
      "HthrGry PatriotBlue",
      "PatriotBlue White",
      "TrueNavy White",
      "RichNavy TrueKhaki",
    ],
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 21.0 },
    },
  },
  {
    code: "NE215",
    name: "New Era® 9TWENTY® Snapback Cap $27.00",
    fullname: "New Era® 9TWENTY® Unstructured Mesh Snapback Cap (NE215)",
    colors: ["Black Stone", "DeepNavy Stone", "Graphite Stone", "Royal Stone"],
    type: "hat",
    halfColors: [
      "Black Stone",
      "DeepNavy Stone",
      "Graphite Stone",
      "Royal Stone",
    ],
    default_color: "Black Stone",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 27.0 },
    },
  },
  {
    code: "NE910",
    name: "New Era® Pom Beanie $31.00",
    fullname: "New Era® Marled Knit Pom Beanie (NE910)",
    colors: ["Black", "Deep Navy", "Royal"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 31.0 },
    },
  },
];
