export const catalog = [
  {
    code: "PC01",
    name: "Port & Co™ Blend Tee $18.50",
    fullname: "Port & Co™ Core Blend Recycled Tee (PC01)",
    colors: [
      "Athletic Heather",
      "Charcoal",
      "Drk Hthr Gry",
      "Jet Black",
      "Navy",
      "Navy Blue Hthr",      
      "True Royal",      
    ],
    type: "mens",
    default_color: "Athletic Heather",
    sizes: {
      Small: 18.50,
      Medium: 18.50,
      Large: 18.50,
      XLarge: 18.50,
      "2XLarge": 20.50,
      "3XLarge": 24.00,            
    },
  },
  {
    code: "BC3001",
    name: "BELLA+CANVAS® Tee $21.25",
    fullname: "BELLA+CANVAS® Unisex Jersey Short Sleeve Tee (BC3001)",
    colors: [
      "Ash",
      "Black",
      "Dark Grey",
      "Navy",
      "True Royal",
      "White",                 
    ],
    type: "mens",
    default_color: "Ash",
    sizes: {
      Small: 21.25,
      Medium: 21.25,
      Large: 21.25,
      XLarge: 21.25,
      "2XLarge": 23.50,
      "3XLarge": 25.00,            
    },
  },
  {
    code: "29LS",
    name: "Jerzees® Long Sleeve Tee $23.00",
    fullname: "Jerzees® Dri-Power® 50/50 Cotton/Poly Long Sleeve T-Shirt (29LS)",
    colors: [
      "Ash",
      "Athletic Heather",
      "Black",
      "Charcoal Grey",
      "JNavy",
      "Royal",
      "Sandstone",
      "Vintage Hthr Navy", 
      "White",         
    ],
    type: "mens",
    default_color: "Ash",
    sizes: {
      Small: 23.00,
      Medium: 23.00,
      Large: 23.00,
      XLarge: 23.00,
      "2XLarge": 25.00,
      "3XLarge": 28.00,            
    },
  },        
  {
    code: "ST650",
    name: "Sport-Tek® Polo $33.00",
    fullname: "Sport-Tek® Micropique Polo (ST650)",
    colors: [
      "Black",      
      "Grey Concrete",
      "Iron Grey",      
      "True Navy",      
      "True Royal",      
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 33.00,
      Medium: 33.00,
      Large: 33.00,
      XLarge: 33.00,
      "2XLarge": 35.50,
      "3XLarge": 37.50,
      "4XLarge": 39.99,      
    },
  },  
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo $49.99",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
        "Anthracite", 
        "Black",                
        "Cool Grey",        
        "Game Royal",
        "Gym Blue", 
        "Navy",    
        "White",       
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,
      "3XLarge": 54.99,
      "4XLarge": 56.99,
   },
  },  
  {
    code: "TM1MU410",
    name: "TravisMathew Polo $74.99",
    fullname: "TravisMathew Coto Performance Polo (TM1MU410)",
    colors: [
        "Black",
        "Blue Nights",
        "Quiet Shade Gry Hthr",
        "Quiet Shade Gry Blk",
        "Vintage Indigo Blk",
        "White"
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 74.99,
      Medium: 74.99,
      Large: 74.99,
      XLarge: 74.99,
      "2XLarge": 76.99,
      "3XLarge": 78.99,          
    },
  },
  {
    code: "PC90",
    name: "Port & Co™ Sweatshirt $25.99",
    fullname: "Port & Co™ Essential Fleece Crewneck Sweatshirt (PC90)",
    colors: ["Ash","Athletic Heather","Charcoal","Jet Black","Navy","Royal","White"],
    type: "mens",
    default_color: "Ash",
    sizes: {
      Small: 25.99,
      Medium: 25.99,
      Large: 25.99,
      XLarge: 25.99,
      "2XLarge": 27.99,
      "3XLarge": 30.99,
      "4XLarge": 32.99,
    },
  },
  {
    code: "NKFD9863",
    name: "Nike® Club Fleece Crew $59.99",
    fullname: "Nike Club Fleece Sleeve Swoosh Crew (NKFD9863)",
    colors: ["Anthracite","Black","Drk Gry Hthr","Game Royal","Midnight Navy","White"],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 59.99,
      Medium: 59.99,
      Large: 59.99,
      XLarge: 59.99,
      "2XLarge": 61.99,
      "3XLarge": 64.99,
      "4XLarge": 66.99,
    },
  },  
  {
    code: "NEA137",
    name: "New Era® Tri-Blend Hoodie $35.99",
    fullname: "New Era® Tri-Blend Hoodie (NEA137)",
    colors: ["Black Solid","Graphite","Shadow Grey","True Navy"],
    type: "mens",
    default_color: "Black Solid",
    sizes: {
      Small: 35.99,
      Medium: 35.99,
      Large: 35.99,
      XLarge: 35.99,
      "2XLarge": 37.99,
      "3XLarge": 40.99,
      "4XLarge": 42.99,
    },
  },
  {
    code: "NL9307",
    name: "Next Level Apparel® Hoodie $46.00",
    fullname: "Next Level Apparel® Heavyweight Hoodie (NL9307)",
    colors: ["Black","Bone","HthrGry","Midnight Navy","Tan"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 46.00,
      Medium: 46.00,
      Large: 46.00,
      XLarge: 46.00,
      "2XLarge": 48.00,
      "3XLarge": 50.00,      
    },
  },  
  {
    code: "F219",
    name: "Port Authority® Vest $36.99",
    fullname: "Port Authority® Value Fleece Vest (F219)",
    colors: ["Black","Iron Grey","True Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 36.99,
      Medium: 36.99,
      Large: 36.99,
      XLarge: 36.99,
      "2XLarge": 38.99,
      "3XLarge": 41.99,
      "4XLarge": 43.99,
    },
  },
  {
    code: "OG741",
    name: "OGIO® Soft Shell Vest $68.99",
    fullname: "OGIO® Kinetic Soft Shell Vest (OG741)",
    colors: ["Blacktop","River Blue Navy","Sahara"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 68.99,
      Medium: 68.99,
      Large: 68.99,
      XLarge: 68.99,
      "2XLarge": 70.99,
      "3XLarge": 72.99,
      "4XLarge": 75.99,
    },
  },
  {
    code: "CT102286",
    name: "Carhartt® Gilliam Vest $98.99",
    fullname: "Carhartt® Gilliam Vest (CT102286)",
    colors: ["Black","Navy","Shadow Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 98.99,
      Medium: 98.99,
      Large: 98.99,
      XLarge: 98.99,
      "2XLarge": 100.99,
      "3XLarge": 102.99,      
    },
  },
  {
    code: "F218",
    name: "Port Authority® Pullover $39.99",
    fullname: "Port Authority® Value Fleece 1/4-Zip Pullover (F218)",
    colors: ["Black","Iron Grey","True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 41.99,
      "3XLarge": 45.99,
      "4XLarge": 47.99,
    },
  },
  {
    code: "CN9492",
    name: "Nike® 1/4-Zip Fleece $67.99",
    fullname: "Nike® Therma-FIT 1/4-Zip Fleece (CN9492)",
    colors: ["Team Anthracite","Team Black","Team Navy","Team Royal"],
    type: "mens",
    default_color: "Team Anthracite",
    sizes: {
      Small: 67.99,
      Medium: 67.99,
      Large: 67.99,
      XLarge: 67.99,
      "2XLarge": 69.99,
      "3XLarge": 72.99,
      "4XLarge": 74.99,
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip $77.99",
    fullname: "The North Face® Ambition 1/4-Zip (NF0A8ENR)",
    colors: ["Meld Grey Hthr","Shady Blue","Smoked Pearl Gry","TNF Black"],
    type: "mens",
    default_color: "Meld Grey Hthr",
    sizes: {
      Small: 77.99,
      Medium: 77.99,
      Large: 77.99,
      XLarge: 77.99,
      "2XLarge": 79.99,
      "3XLarge": 82.99,      
    },
  },
  {
    code: "NEA228",
    name: "New Era® Power 1/2-Zip $43.99",
    fullname: "New Era® Power 1/2-Zip (NEA228)",
    colors: ["Black","Shadow Gry Hthr","True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 43.99,
      Medium: 43.99,
      Large: 43.99,
      XLarge: 43.99,
      "2XLarge": 45.99,
      "3XLarge": 48.99,
      "4XLarge": 50.99,       
    },
  },
  {
    code: "OG813",
    name: "OGIO® Luuma 1/2-Zip $68.99",
    fullname: "OGIO® Luuma 1/2-Zip Fleece (OG813)",
    colors: ["Blacktop","Pearl Grey Heather","River Blue Navy"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 68.99,
      Medium: 68.99,
      Large: 68.99,
      XLarge: 68.99,
      "2XLarge": 70.99,
      "3XLarge": 73.99,
      "4XLarge": 75.99,       
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket $47.99",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    colors: ["Black", "Battleship Grey","Dress Blue Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 47.99,
      Medium: 47.99,
      Large: 47.99,
      XLarge: 47.99,
      "2XLarge": 49.99,
      "3XLarge": 52.99,
      "4XLarge": 54.99,
    },
  },
  {
    code: "OG740",
    name: "OGIO® Kinetic Jacket $77.99",
    fullname: "OGIO® Kinetic Soft Shell Jacket (OG740)",
    colors: ["Blacktop","River Blue Navy","Sahara"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 77.99,
      Medium: 77.99,
      Large: 77.99,
      XLarge: 77.99,
      "2XLarge": 79.99,
      "3XLarge": 83.99,
      "4XLarge": 85.99,       
    },
  },
  {
    code: "NKDX6716",
    name: "Nike® Full-Zip Jacket $98.99",
    fullname: "Nike® Storm-FIT Full-Zip Jacket (NKDX6716)",
    colors: ["Anthracite","Black","College Navy","Stone"],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 98.99,
      Medium: 98.99,
      Large: 98.99,
      XLarge: 98.99,
      "2XLarge": 100.99,
      "3XLarge": 102.99,
      "4XLarge": 105.99,
    },
  },
  {
    code: "LPC55",
    name: "Port & Co™ Blend Tee $20.00",
    fullname: "Port & Co™ Women's Core Blend Tee (LPC55)",
    colors: [
      "Athletic Heather",
      "Charcoal",
      "Jet Black",
      "Navy",
      "Royal",
      "White",
    ],
    type: "womens",
    default_color: "Athletic Heather",
    sizes: {
      Small: 20.00,
      Medium: 20.00,
      Large: 20.00,
      XLarge: 20.00,
      "2XLarge": 22.00,     
    },
  },   
  {
    code: "LPC61",
    name: "Port & Co™ Essential Tee $20.50",
    fullname: "Port & Co™ Women's Essential Tee (LPC61)",
    colors: [
      "Athletic Heather",
      "Jet Black",
      "Navy",
      "Royal",
      "White",
    ],
    type: "womens",
    default_color: "Athletic Heather",
    sizes: {
      Small: 20.50,
      Medium: 20.50,
      Large: 20.50,
      XLarge: 20.50,
      "2XLarge": 22.50,     
    },
  },   
  {
    code: "AL2303",
    name: "Allmade® V-Neck Tee $22.00",
    fullname: "Allmade® Women's Recycled Blend V-Neck Tee (AL2303)",
    colors: [
      "Reloaded Char Hthr",
      "Remade Gray Hthr",
      "Reused Royal Hthr",
      "Salvaged Navy Hthr",
    ],
    type: "womens",
    default_color: "Reloaded Char Hthr",
    sizes: {
      Small: 22.00,
      Medium: 22.00,
      Large: 22.00,
      XLarge: 22.00,
      "2XLarge": 24.00,      
    },
  },    
  {
    code: "LST650",
    name: "Sport-Tek® Polo $33.00",
    fullname: "Sport-Tek® Womens Micropique Polo (LST650)",
    colors: [
      "Black",      
      "Grey Concrete",
      "Iron Grey",      
      "True Navy",      
      "True Royal",      
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 33.00,
      Medium: 33.00,
      Large: 33.00,
      XLarge: 33.00,
      "2XLarge": 35.50,
      "3XLarge": 37.50,
      "4XLarge": 39.99,
    },
  },    
  {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo $49.99",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
     colors: [
        "Anthracite", 
        "Black",                
        "Cool Grey",        
        "Game Royal",
        "Gym Blue", 
        "Navy",    
        "White",       
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,      
    },
  },
  {
    code: "838957",
    name: "Nike® Dri-FIT Polo $69.99",
    fullname: "Nike Women's Dri-FIT Legacy Polo (838957)",
    colors: [
      "Black",      
      "Dark Grey",
      "Game Royal",      
      "Midnight Navy",   
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 69.99,
      Medium: 69.99,
      Large: 69.99,
      XLarge: 69.99,
      "2XLarge": 71.99,          
    },
  },   
  {
    code: "DT6105",
    name: "District® Fleece Crew $31.99",
    fullname: "District® Women's V.I.T.™ Fleece Crew (DT6105)",
    colors: ["Black","Gardenia","Hthrd Charcoal","Light Gry Hthr"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 31.99,
      Medium: 31.99,
      Large: 31.99,
      XLarge: 31.99,
      "2XLarge": 33.99,
      "3XLarge": 35.99,
      "4XLarge": 37.99,
    },
  },
   {
    code: "DT6101",
    name: "District® Fleece Hoodie $34.99",
    fullname: "District® Women's V.I.T.™ Fleece Hoodie (DT6101)",
    colors: ["Black","Deep Royal","Light Gry Hthr","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 36.99,
      "3XLarge": 39.99,
      "4XLarge": 41.99,
    },
  },
  {
    code: "NL9307",
    name: "Next Level Apparel® Hoodie $46.00",
    fullname: "Next Level Apparel® Heavyweight Hoodie (NL9307)",
    colors: ["Black","Bone","HthrGry","Midnight Navy","Tan"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 46.00,
      Medium: 46.00,
      Large: 46.00,
      XLarge: 46.00,
      "2XLarge": 48.00,
      "3XLarge": 50.00,      
    },
  },  
   {
    code: "LNEA500",
    name: "New Era® Terry Hoodie $59.99",
    fullname: "New Era® Women's French Terry Pullover Hoodie (LNEA500)",
    colors: ["Black","Black Twist","Drk Ryl Twst","Lt Grph Twst","True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 59.99,
      Medium: 59.99,
      Large: 59.99,
      XLarge: 59.99,
      "2XLarge": 61.99,
      "3XLarge": 63.99,
      "4XLarge": 65.99,
    },
  },  
  {
    code: "L219",
    name: "Port Authority® Vest $36.99",
    fullname: "Port Authority® Women's Value Fleece Vest (L219)",
    colors: ["Black","Iron Grey","True Navy","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 36.99,
      Medium: 36.99,
      Large: 36.99,
      XLarge: 36.99,
      "2XLarge": 38.99,
      "3XLarge": 41.99,
      "4XLarge": 43.99,
    },
  },
  {
    code: "LST941",
    name: "Sport-Tek® Vest $49.99",
    fullname: "Sport-Tek® Womens Teknical Hybrid Vest (LST941)",
    colors: ["Black","Iron Grey","Silver","True Navy","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,
      "3XLarge": 53.99,
      "4XLarge": 55.99,
    },
  },
  {
    code: "LST357",
    name: "Sport-Tek® 1/4-Zip $31.99",
    fullname: "Sport-Tek® Women's PosiCharge® Competitor™ 1/4-Zip Pullover (LST357)",
    colors: ["Black","Iron Grey","True Navy","True Royal","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 31.99,
      Medium: 31.99,
      Large: 31.99,
      XLarge: 31.99,
      "2XLarge": 33.99,
      "3XLarge": 36.99,
      "4XLarge": 38.99,
    },
  },
   {
    code: "LK210",
    name: "Port Authority® 1/4-Zip $44.99",
    fullname: "Port Authority® Women's Wearever Signature Double Pique 1/4-Zip (LK210)",
    colors: ["Deep Black","Gusty Grey","River Blue Navy","Storm Grey"],
    type: "womens",
    default_color: "Deep Black",
    sizes: {
      Small: 44.99,
      Medium: 44.99,
      Large: 44.99,
      XLarge: 44.99,
      "2XLarge": 46.99,
      "3XLarge": 49.99,
      "4XLarge": 51.99,
    },
  }, 
  {
    code: "LOG861",
    name: "OGIO® Transcend 1/4-Zip $64.99",
    fullname: "OGIO® Women's Transcend 1/4-Zip (LOG861)",
    colors: ["Blacktop","Opal White","River Blue Navy","Tarmac Grey"],
    type: "womens",
    default_color: "Blacktop",
    sizes: {
      Small: 64.99,
      Medium: 64.99,
      Large: 64.99,
      XLarge: 64.99,
      "2XLarge": 66.99,
      "3XLarge": 69.99,
      "4XLarge": 71.99,
    },
  },
  {
    code: "L224",
    name: "Port Authority® 1/2-Zip $34.99",
    fullname: "Port Authority® Women's Microfleece 1/2-Zip Pullover (L224)",
    colors: ["Black","Pearl Grey","True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 36.99,
      "3XLarge": 39.99,
      "4XLarge": 41.99,
    },
  }, 
  {
    code: "LNEA228",
    name: "New Era® Power 1/2-Zip $46.99",
    fullname: "New Era® Women's Power 1/2-Zip (LNEA228)",
    colors: ["Black","Shadow Gry Hthr","True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 47.99,
      "3XLarge": 49.99,
      "4XLarge": 50.99,
    },
  }, 
  {
    code: "NKDX6720",
    name: "Nike® Fleece 1/2-Zip $70.99",
    fullname: "Nike® Women's Club Fleece Sleeve Swoosh 1/2-Zip (NKDX6720)",
    colors: ["Anthracite","Black","Drk Gry Hthr","Game Royal","Midnight Navy","White"],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 70.99,
      Medium: 70.99,
      Large: 70.99,
      XLarge: 70.99,
      "2XLarge": 73.99,      
    },
  }, 
  
  {
    code: "L317",
    name: "Port Authority® Jacket $47.99",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket (L317)",
    colors: ["Black", "Battleship Grey","Dress Blue Navy","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 47.99,
      Medium: 47.99,
      Large: 47.99,
      XLarge: 47.99,
      "2XLarge": 49.99,
      "3XLarge": 52.99,
      "4XLarge": 54.99,
    },
  },  
  {
    code: "TW530",
    name: "Port Authority® Golf Towel $19.00",
    fullname: "Port Authority® Grommeted Microfiber Golf Towel (TW530)",
    colors: ["Black", "Deep Smoke","Royal","True Navy","White"],
    type: "accessory",
    default_color: "Black",
    description: 
    `85/15 poly/nylon microfiber. Fully hemmed. Corner grommet with carabiner. Dimensions: 16 in. x 26 in.`,
    sizes: {
      "1": 19.00,      
    },
  },
  {
    code: "TB850",
    name: "Port Authority® Travel Blanket $35.00",
    fullname: "Port Authority® Fleece & Poly Travel Blanket (TB850)",
    colors: ["Black", "Lead Grey","True Navy","True Royal"],
    type: "accessory",
    default_color: "Black",
    description: 
    `100% polyester fleece, 100% polyester woven backing. Attached elastic band to secure the rolled-up blanket. Dimensions: 50 in. x 60 in.`,
    sizes: {
      "1": 35.00,      
    },
  },
   {
    code: "BP70",
    name: "Port Authority® Picnic Blanket $45.00",
    fullname: "Port Authority® Picnic Blanket (BP70)",
    colors: ["Grey Steel","True Black","True Royal"],
    type: "accessory",
    default_color: "Grey Steel",
    description:
    `100% polyester fleece, 100% polyester woven backing. Water-resistant woven backing. Zips around itself for easy folding.`,
    sizes: {
      "1": 45.00,      
    },
  },  
  {
    code: "BG428",
    name: "Port Authority® Tote $19.00",
    fullname: "Port Authority® Cotton Canvas Shopper Tote (BG428)",
    colors: ["Deep Black","Natural"],
    type: "accessory",
    default_color: "Deep Black",
    description: "100% cotton canvas. Dimensions: 12.5 in. x 14.5 in. x 4 in.",
    sizes: {
      "1": 19.00,      
    },
  },
  {
    code: "BG226",
    name: "Port Authority® Backpack $36.00",
    fullname: "Port Authority® Daily Commute Backpack (BG226)",
    colors: ["Black","Grey Smoke"],
    type: "accessory",
    default_color: "Black",
    description: 
    `POLYESTER; Padded air mesh shoulder straps. Padded back panel. Laptop dimensions: 15h x 12w x 1d. Fits most 15 in. laptops. 
     Dimensions: 17.75h x 11.5w x 5d.`,
    sizes: {
      "1": 36.00,      
    },
  },
  {
    code: "91005",
    name: "OGIO® Convert Pack $90.00",
    fullname: "OGIO® Convert Pack (91005)",
    colors: ["Black","Tarmac"],
    type: "accessory",
    default_color: "Black",
    description: 
    `POLYESTER; Dedicated laptop compartment with large slip pocket for documents and a padded pocket for tablets. Detachable shoulder strap. 
     Backpack straps stow neatly behind the back panel with ease. Multiple zippered pockets. Laptop sleeve: 15h x 10.5w x 1d. 
     Fits most 15 in. laptops. Dimensions: 18h x 11w x 5d.`,
    sizes: {
      "1": 90.00,      
    },
  },
  {
    code: "BG305",
    name: "Port Authority® Computer Case $26.75",
    fullname: "Port Authority® Value Computer Case (BG305)",
    colors: ["Black","Dark Charcoal","Twilight Blue"],
    type: "accessory",
    default_color: "Black",
    description: 
    `POLYESTER; 600 denier polyester canvas. Web carrying handles. Protective padding on sides and bottom. FITS MOST 15 in. laptops.`,
    sizes: {
      "1": 26.75,      
    },
  },  
  {
    code: "BG309",
    name: "Port Authority® Briefcase $34.50",
    fullname: "Port Authority® Vector Briefcase (BG309)",
    colors: ["Grey Heather","Navy Heather"],
    type: "accessory",
    default_color: "Grey Heather",
    description: 
    `POLYESTER; Adjustable, padded shoulder strap. Large front side zippered pocket for easy decoration. 
     Luggage trolley strap on back. Laptop sleeve dimensions 8h x 15w. Fits most 15 in. laptops.`,
    sizes: {
      "1": 34.50,      
    },
  },   
  {
    code: "93023",
    name: "OGIO® Slim Briefcase $52.00",
    fullname: "OGIO® Slim Brief (93023)",
    colors: ["Blacktop"],
    type: "accessory",
    default_color: "Blacktop",
    description:
    `POLYESTER; Dedicated laptop and tablet sleeves. Webbing haul handles. Removable, adjustable webbing 
     shoulder strap. Dimensions 11h x 16.75w x 1.5d. Fits most 16 in. laptops.`,
    sizes: {
      "1": 52.00,      
   },
  },  
  {
    code: "CP90",
    name: "Port Authority® Knit Cap $18.50",
    fullname: "Port Authority® Knit Cap (CP90)",
    colors: [
      "Athletic Oxford",
      "Athletic Royal",
      "Black",
      "Black AthleticOxford",
      "Charcoal Heather",
      "Navy",
      "White",      
      "Woodland Brown",
    ],
    type: "hat",
    default_color: "Athletic Oxford",
    halfColors: ['Black AthleticOxford'],
    sizes: {
      OSFA: 18.50,
    },
  },  
  {
    code: "CP80",
    name: "Port & Co™ Six-Panel Cap $19.00",
    fullname: "Port & Co™ Six-Panel Twill Cap (CP80)",
    colors: [
      "Black",      
      "Charcoal",      
      "Khaki",
      "Oyster",
      "Royal",
      "Silver",
      "True Navy",      
      "White",
    ],
    type: "hat",
    default_color: "Black",
    sizes: {
      OSFA: 19.00,
    },
  },
  {
    code: "C402",
    name: "Port Authority Trucker Cap $21.00",
    fullname: "Port Authority® Snapback Trucker Cap (C402)",
    colors: [
      "Black",
      "Black GreySteel",
      "HthrGry PatriotBlue",
      "PatriotBlue White",
      "TrueNavy White",
      "RichNavy TrueKhaki",
      "Woodland Brown",
      "White"
    ],
    type: "hat",
    halfColors: [
      'Black GreySteel',
      'HthrGry PatriotBlue',
      'PatriotBlue White',
      'TrueNavy White',
      'RichNavy TrueKhaki'
    ],
    default_color: "Black",    
    sizes: {
      OSFA: 21.00,
    },
  },
  {
    code: "NE215",
    name: "New Era® 9TWENTY® Snapback Cap $27.00",
    fullname: "New Era® 9TWENTY® Unstructured Mesh Snapback Cap (NE215)",
    colors: [
      "Black Stone",
      "DeepNavy Stone",
      "Graphite Stone",
      "Royal Stone",      
    ],
    type: "hat",
    halfColors: [
      'Black Stone',
      'DeepNavy Stone',
      'Graphite Stone',
      'Royal Stone',      
    ],
    default_color: "Black Stone",    
    sizes: {
      OSFA: 27.00,
    },
  },
  {
    code: "NE910",
    name: "New Era® Pom Beanie $31.00",
    fullname: "New Era® Marled Knit Pom Beanie (NE910)",
    colors: [
      "Black",
      "Deep Navy",
      "Royal",            
    ],
    type: "hat",
    default_color: "Black",    
    sizes: {
      OSFA: 31.00,
    },
  },
]
