export const catalog = [
    {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo #NKDC1991",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
     colors: [
        "Anthracite", 
        "Black",                
        "Cool Grey",        
        "Game Royal",
        "Gym Blue", 
        "Navy",    
        "White",       
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,      
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo #NKDC1963",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
        "Anthracite", 
        "Black",                
        "Cool Grey",        
        "Game Royal",
        "Gym Blue", 
        "Navy",    
        "White",       
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,
      "3XLarge": 54.99,
      "4XLarge": 56.99,
   },
  },
  {
    code: "838957",
    name: "Nike Women's Polo #838957",
    fullname: "Nike Women's Dri-FIT Legacy Polo (838957)",
    colors: [
      "Black",      
      "Dark Grey",
      "Game Royal",      
      "Midnight Navy",   
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 69.99,
      Medium: 69.99,
      Large: 69.99,
      XLarge: 69.99,
      "2XLarge": 71.99,          
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Microqique Polo #LST650",
    fullname: "Sport-Tek® Womens Micropique Polo (LST650)",
    colors: [
      "Black",      
      "Grey Concrete",
      "Iron Grey",      
      "True Navy",      
      "True Royal",      
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 33.00,
      Medium: 33.00,
      Large: 33.00,
      XLarge: 33.00,
      "2XLarge": 35.50,
      "3XLarge": 37.50,
      "4XLarge": 39.99,
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Microqique Polo #ST650",
    fullname: "Sport-Tek® Micropique Polo (ST650)",
    colors: [
      "Black",      
      "Grey Concrete",
      "Iron Grey",      
      "True Navy",      
      "True Royal",      
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 33.00,
      Medium: 33.00,
      Large: 33.00,
      XLarge: 33.00,
      "2XLarge": 35.50,
      "3XLarge": 37.50,
      "4XLarge": 39.99,      
    },
  },  
  {
    code: "TM1MU410",
    name: "TravisMathew Polo #TM1MU410",
    fullname: "TravisMathew Coto Performance Polo (TM1MU410)",
    colors: [
        "Black",
        "Blue Nights",
        "Quiet Shade Gry Hthr",
        "Quiet Shade Gry Blk",
        "Vintage Indigo Blk",
        "White"
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 74.99,
      Medium: 74.99,
      Large: 74.99,
      XLarge: 74.99,
      "2XLarge": 76.99,
      "3XLarge": 78.99,          
    },
  },
  {
    code: "CJ1614",
    name: "Nike Club Fleece Crew #CJ1614",
    fullname: "Nike Club Fleece Crew (CJ1614)",
    colors: ["Anthracite","Black","Drk Gry Hthr","Navy","Royal","White"],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 59.99,
      Medium: 59.99,
      Large: 59.99,
      XLarge: 59.99,
      "2XLarge": 61.99,
      "3XLarge": 64.99,
      "4XLarge": 66.99,
    },
  },
  {
    code: "PC90",
    name: "Port & Co™ Sweatshirt #PC90",
    fullname: "Port & Co™ Essential Fleece Crewneck Sweatshirt (PC90)",
    colors: ["Ash","Athletic Heather","Charcoal","Jet Black","Navy","Royal","White"],
    type: "mens",
    default_color: "Ash",
    sizes: {
      Small: 25.99,
      Medium: 25.99,
      Large: 25.99,
      XLarge: 25.99,
      "2XLarge": 27.99,
      "3XLarge": 30.99,
      "4XLarge": 32.99,
    },
  },
  {
    code: "NEA137",
    name: "New Era® Tri-Blend Hoodie #NEA137",
    fullname: "New Era® Tri-Blend Hoodie (NEA137)",
    colors: ["Black Solid","Graphite","Shadow Grey","True Navy"],
    type: "mens",
    default_color: "Black Solid",
    sizes: {
      Small: 35.99,
      Medium: 35.99,
      Large: 35.99,
      XLarge: 35.99,
      "2XLarge": 37.99,
      "3XLarge": 40.99,
      "4XLarge": 42.99,
    },
  },
  {
    code: "LST357",
    name: "Sport-Tek® 1/4-Zip Pullover #LST357",
    fullname: "Sport-Tek® Women's PosiCharge® Competitor™ 1/4-Zip Pullover (LST357)",
    colors: ["Black","Iron Grey","True Navy","True Royal","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 31.99,
      Medium: 31.99,
      Large: 31.99,
      XLarge: 31.99,
      "2XLarge": 33.99,
      "3XLarge": 36.99,
      "4XLarge": 38.99,
    },
  },
  {
    code: "LOG861",
    name: "OGIO® Transcend 1/4-Zip #LOG861",
    fullname: "OGIO® Women's Transcend 1/4-Zip (LOG861)",
    colors: ["Blacktop","Opal White","River Blue Navy","Tarmac Grey"],
    type: "womens",
    default_color: "Blacktop",
    sizes: {
      Small: 64.99,
      Medium: 64.99,
      Large: 64.99,
      XLarge: 64.99,
      "2XLarge": 66.99,
      "3XLarge": 69.99,
      "4XLarge": 71.99,
    },
  },
  {
    code: "LK210",
    name: "Port Authority® Wearever 1/4-Zip #LK210",
    fullname: "Port Authority® Women's Wearever Signature Double Pique 1/4-Zip (LK210)",
    colors: ["Deep Black","Gusty Grey","River Blue Navy","Storm Grey"],
    type: "womens",
    default_color: "Deep Black",
    sizes: {
      Small: 44.99,
      Medium: 44.99,
      Large: 44.99,
      XLarge: 44.99,
      "2XLarge": 46.99,
      "3XLarge": 49.99,
      "4XLarge": 51.99,
    },
  }, 
  {
    code: "L224",
    name: "Port Authority® 1/2-Zip Pullover #L224",
    fullname: "Port Authority® Women's Microfleece 1/2-Zip Pullover (L224)",
    colors: ["Black","Pearl Grey","True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 36.99,
      "3XLarge": 39.99,
      "4XLarge": 41.99,
    },
  }, 
  {
    code: "OG741",
    name: "OGIO® Soft Shell Vest #OG741",
    fullname: "OGIO® Kinetic Soft Shell Vest (OG741)",
    colors: ["Blacktop","River Blue Navy","Sahara"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 68.99,
      Medium: 68.99,
      Large: 68.99,
      XLarge: 68.99,
      "2XLarge": 70.99,
      "3XLarge": 72.99,
      "4XLarge": 75.99,
    },
  },
  {
    code: "F219",
    name: "Port Authority® Vest #F219",
    fullname: "Port Authority® Value Fleece Vest (F219)",
    colors: ["Black","Iron Grey","True Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 36.99,
      Medium: 36.99,
      Large: 36.99,
      XLarge: 36.99,
      "2XLarge": 38.99,
      "3XLarge": 41.99,
      "4XLarge": 43.99,
    },
  },
  {
    code: "CT102286",
    name: "Carhartt® Gilliam Vest #CT102286",
    fullname: "Carhartt® Gilliam Vest (CT102286)",
    colors: ["Black","Navy","Shadow Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 98.99,
      Medium: 98.99,
      Large: 98.99,
      XLarge: 98.99,
      "2XLarge": 100.99,
      "3XLarge": 102.99,      
    },
  },
  {
    code: "F218",
    name: "Port Authority® Pullover #F218",
    fullname: "Port Authority® Value Fleece 1/4-Zip Pullover (F218)",
    colors: ["Black","Iron Grey","True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 41.99,
      "3XLarge": 45.99,
      "4XLarge": 47.99,
    },
  },
  {
    code: "CN9492",
    name: "Nike 1/4-Zip Fleece #CN9492",
    fullname: "Nike Therma-FIT 1/4-Zip Fleece (CN9492)",
    colors: ["Team Anthracite","Team Black","Team Navy","Team Royal"],
    type: "mens",
    default_color: "Team Anthracite",
    sizes: {
      Small: 67.99,
      Medium: 67.99,
      Large: 67.99,
      XLarge: 67.99,
      "2XLarge": 69.99,
      "3XLarge": 72.99,
      "4XLarge": 74.99,
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip #NF0A8ENR",
    fullname: "The North Face® Ambition 1/4-Zip (NF0A8ENR)",
    colors: ["Meld Grey Hthr","Shady Blue","Smoked Pearl Gry","TNF Black"],
    type: "mens",
    default_color: "Meld Grey Hthr",
    sizes: {
      Small: 77.99,
      Medium: 77.99,
      Large: 77.99,
      XLarge: 77.99,
      "2XLarge": 79.99,
      "3XLarge": 82.99,      
    },
  },
  {
    code: "NEA228",
    name: "New Era® Power 1/2-Zip #NEA228",
    fullname: "New Era® Power 1/2-Zip (NEA228)",
    colors: ["Black","Shadow Gry Hthr","True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 43.99,
      Medium: 43.99,
      Large: 43.99,
      XLarge: 43.99,
      "2XLarge": 45.99,
      "3XLarge": 48.99,
      "4XLarge": 50.99,       
    },
  },
  {
    code: "OG813",
    name: "OGIO® Luuma 1/2-Zip Fleece #OG813",
    fullname: "OGIO® Luuma 1/2-Zip Fleece (OG813)",
    colors: ["Blacktop","Pearl Grey Heather","River Blue Navy"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 68.99,
      Medium: 68.99,
      Large: 68.99,
      XLarge: 68.99,
      "2XLarge": 70.99,
      "3XLarge": 73.99,
      "4XLarge": 75.99,       
    },
  },
  {
    code: "OG740",
    name: "OGIO® Kinetic Jacket #OG740",
    fullname: "OGIO® Kinetic Soft Shell Jacket (OG740)",
    colors: ["Blacktop","River Blue Navy","Sahara"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 77.99,
      Medium: 77.99,
      Large: 77.99,
      XLarge: 77.99,
      "2XLarge": 79.99,
      "3XLarge": 83.99,
      "4XLarge": 85.99,       
    },
  },
  {
    code: "NKDX6716",
    name: "Nike Full-Zip Jacket #NKDX6716",
    fullname: "Nike Storm-FIT Full-Zip Jacket (NKDX6716)",
    colors: ["Anthracite","Black","College Navy","Stone"],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 98.99,
      Medium: 98.99,
      Large: 98.99,
      XLarge: 98.99,
      "2XLarge": 100.99,
      "3XLarge": 102.99,
      "4XLarge": 105.99,
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    colors: ["Black", "Battleship Grey","Dress Blue Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 47.99,
      Medium: 47.99,
      Large: 47.99,
      XLarge: 47.99,
      "2XLarge": 49.99,
      "3XLarge": 52.99,
      "4XLarge": 54.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket (L317)",
    colors: ["Black", "Battleship Grey","Dress Blue Navy","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 47.99,
      Medium: 47.99,
      Large: 47.99,
      XLarge: 47.99,
      "2XLarge": 49.99,
      "3XLarge": 52.99,
      "4XLarge": 54.99,
    },
  },
]
