export const catalog = [
    {
    code: "NKBV6044",
    name: "Nike® 1/2-Zip Cover-Up #NKBV6044",
    fullname: "Nike® Dry 1/2-Zip Cover-Up (NKBV6044)",
    colors: ["Gym Blue", "Navy Heather"],
    type: "mens",
    default_color: "Gym Blue",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 40.75 },
      Medium: { price: 40.75 },
      Large: { price: 40.75 },
      XLarge: { price: 40.75 },
      "2XLarge": { price: 41.75 },
      "3XLarge": { price:42.75 },
      "4XLarge": { price: 43.75 },
    },
  },
  {
    code: "PC55P",
    name: "Port & Company Pocket Tee #PC55P",
    fullname: "Port & Company® Core Blend Pocket Tee (PC55P)",
    colors: ["Navy"],
    type: "tshirts",
    sub_category: "tshirt",
    default_color: "Navy",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge", 
      "5XLarge", 
      "6XLarge"
    ],
    pricing: {
      Small: { price: 17.99 },
      Medium: { price: 17.99 },
      Large: { price: 17.99},
      XLarge: { price: 17.99 },
      "2XLarge": { price: 19.99 },
      "3XLarge": { price: 20.99 },
      "4XLarge": { price: 22.99 },
      "5XLarge": { price: 23.99 },
      "6XLarge": { price: 24.99 },
    },
  },
  {
    code: "600088V",
    name: "Seat Covers (roll)",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    quantities: [500],
    pricing: {
      base: {
        price: 73.50,
      },
    },
  },
  {
    code: "ROLMAT-34MLF-504929B",
    name: "Standard Zinc Metal Frame",
    fullname: "Standard Zinc Metal Frame w/black & 877 silver imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["ROLMAT"],    
    quantities: [500],
    pricing: {
      base: {
        price: 3.89,
      },
    },
  },
]