export const catalog = [
  {
    code: "K110",
    name: "Port Authority UV Polo #K110",
    fullname: "Port Authority® Dry Zone® UV Micro-Mesh Polo (K110)",
    colors: ["Deep Black"],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 24.95 },
      Medium: { price: 24.95 },
      Large: { price: 24.95 },
      XLarge: { price: 24.95 },
      "2XLarge": { price: 26.95 },
      "3XLarge": { price: 28.95 },
      "4XLarge": { price: 30.95 },
   },
  },
  {
    code: "OG101",
    name: "OGIO® - Caliber2.0 Polo #OG101",
    fullname: "OGIO® - Caliber2.0 Polo (OG101)",
    colors: ["Blacktop", "Rogue Grey"],
    type: "mens",
    default_color: "Blacktop",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge"],
    pricing: {
      Small: { price: 35.99 },
      Medium: { price: 35.99 },
      Large: { price: 35.99 },
      XLarge: { price: 35.99 },
      "2XLarge": { price: 37.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 41.99 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike® Dri-FIT Polo (NKDC1963)",
    colors: [
      "Black",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge"
    ],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 44.99 },
      "3XLarge": { price: 46.99 },
      "4XLarge": { price: 48.99 },
    },
  },
  {
    code: "K805",
    name: "Port Authority® Full-Zip #K805",
    fullname: "Port Authority® Vertical Texture 1/4-Zip Pullover (K805)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",    
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 29.99 },
      Medium: { price: 29.99 },
      Large: { price: 29.99 },
      XLarge: { price: 29.99 },
      "2XLarge": { price: 31.99 },
      "3XLarge": { price: 32.99 },
      "4XLarge": { price: 33.99 },
    },
  },
  {
    code: "L805",
    name: "Port Authority® Full-Zip #L805",
    fullname: "Port Authority® Women's Vertical Texture Full-Zip Jacket (L805)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 29.99 },
      Medium: { price: 29.99 },
      Large: { price: 29.99 },
      XLarge: { price: 29.99 },
      "2XLarge": { price: 31.99 },
      "3XLarge": { price: 32.99 },
      "4XLarge": { price: 33.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",    
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 45.99 },
      Medium: { price: 45.99 },
      Large: { price: 45.99 },
      XLarge: { price: 45.99 },
      "2XLarge": { price: 47.99 },
      "3XLarge": { price: 48.99 },
      "4XLarge": { price: 49.99 },
      "5XLarge": { price: 50.99 },
      "6XLarge": { price: 51.99 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Core Soft Shell Jacket (L317)",    
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 45.99 },
      Medium: { price: 45.99 },
      Large: { price: 45.99 },
      XLarge: { price: 45.99 },
      "2XLarge": { price: 47.99 },
      "3XLarge": { price: 48.99 },
      "4XLarge": { price: 49.99 },
      
    },
  },
  {
    code: "PC55P",
    name: "Port & Company Pocket Tee #PC55P",
    fullname: "Port & Company® Core Blend Pocket Tee (PC55P)",
    colors: ["Navy"],
    type: "tshirts",    
    default_color: "Navy",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge", 
      "5XLarge", 
      "6XLarge"
    ],
    pricing: {
      Small: { price: 17.99 },
      Medium: { price: 17.99 },
      Large: { price: 17.99},
      XLarge: { price: 17.99 },
      "2XLarge": { price: 19.99 },
      "3XLarge": { price: 20.99 },
      "4XLarge": { price: 22.99 },
      "5XLarge": { price: 23.99 },
      "6XLarge": { price: 24.99 },
    },
  },
  {
    code: "600088V",
    name: "Seat Covers (roll)",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    quantities: [1, 2, 3, 4, 5],
    pricing: {
      base: {
        price: 73.50,
      },
    },
  },
  {
    code: "ROLMAT-34MLF-504929B",
    name: "Standard Zinc Metal Frame",
    fullname: "Standard Zinc Metal Frame w/black & 877 silver imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["ROLMAT"],    
    quantities: [500],
    pricing: {
      base: {
        price: 3.89,
      },
    },
  },
]