export const catalog = [
  {
    code: "PC61",
    name: "Port & Company® Tee #PC61",
    fullname: "Port & Company® Essential Tee",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
      "5XLarge": 0.00,
      "6XLarge": 0.00,
    },
  },
  {
    code: "PC61P",
    name: "Port & Company® Pocket Tee #PC61P",
    fullname: "Port & Company® Essential Pocket Tee",
    colors: [
      "Ash",
      "Athletic Heather",
      "Athletic Maroon",
      "Brown",
      "Charcoal",
      "Dk Green",
      "Deep Navy",
      "Jet Black",
      "Light Blue",
      "Lime",
      "Natural",
      "Navy",
      "Orange",
      "Red",
      "Royal",
      "Safety Green",
      "Safety Orange",
      "Sand",
      "White",
    ],
    type: "tshirts",
    default_color: "Ash",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,      
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Lime Shock",
      "Maroon",
      "Purple",
      "Texas Orange",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "Vegas Gold",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 25.0,
      Medium: 25.0,
      Large: 25.0,
      XLarge: 25.0,
      "2XLarge": 26.0,
      "3XLarge": 27.0,
      "4XLarge": 28.0,
      "5XLarge": 29.0,
      "6XLarge": 30.0,
    },
  },
  {
    code: "TST650",
    name: "Sport-Tek® Polo - TALL #TST650",
    fullname: "Sport-Tek® TALL Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",      
      "Deep Red",
      "Forest Green",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",      
      "Maroon",
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",    
    sizes: {
      LT: 27.99,
      XLT:29.99,
      "2XLT": 30.99,
      "3XLT": 32.99,
      "4XLT": 34.99,
     
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt #LST650",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Light Pink",
      "Lime Shock",
      "Maroon",
      "Pink Raspberry",
      "Purple",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 25.00,
      Medium: 25.00,
      Large: 25.00,
      XLarge: 25.00,
      "2XLarge": 26.00,
      "3XLarge": 27.00,
      "4XLarge": 28.00,
    },
  },
  {
    code: "ST657",
    name: "Sport-Tek LS Polo #ST657",
    fullname: "Sport-Tek® Long Sleeve Micropique Polo",
    colors: [
      "Black",
      "Deep Red",
      "Forest Green",
      "Iron Grey",
      "Maroon",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 29.0,
      Medium: 29.0,
      Large: 29.0,
      XLarge: 29.0,
      "2XLarge": 30.0,
      "3XLarge": 31.0,
      "4XLarge": 32.0,
    },
  },
  {
    code: "L540LS",
    name: "Port Authority® Polo #L540LS",
    fullname: "Port Authority Womens Long Sleeve Polo",
    colors: [
      "Black",
      "Bright Purple",
      "Carolina Blue",
      "Navy",
      "Red",
      "Royal",
      "Steel Grey",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 22.0,
      Medium: 22.0,
      Large: 22.0,
      XLarge: 22.0,
      "2XLarge": 23.0,
      "3XLarge": 24.0,
      "4XLarge": 24.0,
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: [
      "Battleship Grey",
      "Black",
      "Black Charcoal Heather",
      "Deep Smoke",
      "Dress Blue Navy",
      "Forest Green",
      "Maroon",
      "Navy Heather",
      "Pearl Grey Heather",
      "Rich Red",
      "True Royal",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 41.0,
      Medium: 41.0,
      Large: 41.0,
      XLarge: 41.0,
      "2XLarge": 42.0,
      "3XLarge": 43.0,
      "4XLarge": 44.0,
      "5XLarge": 45.0,
      "6XLarge": 46.0,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: [
      "Battleship Grey",
      "Black",
      "Black Charcoal Heather",
      "Deep Smoke",
      "Dress Blue Navy",
      "Navy Heather",
      "Pearl Grey Heather",
      "Rich Red",
      "True Royal",
      "Very Berry",
    ],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 41.00,
      Medium: 41.00,
      Large: 41.00,
      XLarge: 41.00,
      "2XLarge": 42.00,
      "3XLarge": 43.00,
      "4XLarge": 44.00,
    },
  },
  {
    code: "K805",
    name: "Port Authority® Pullover #K805",
    fullname: "Port Authority® Vertical Texture 1/4-Zip Pullover",
    colors: ["Black", "Iron Grey", "Regatta Blue", "True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 32.00,
      Medium: 32.00,
      Large: 32.00,
      XLarge: 32.00,
      "2XLarge": 33.00,
      "3XLarge": 34.00,
      "4XLarge": 35.00,
    },
  },
  {
    code: "L805",
    name: "Port Authority® Pullover #L805",
    fullname: "Port Authority® Women's Vertical Texture Full-Zip Jacket",
    colors: ["Black", "Iron Grey", "Regatta Blue", "True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 32.00,
      Medium: 32.00,
      Large: 32.00,
      XLarge: 32.00,
      "2XLarge": 33.00,
      "3XLarge": 34.00,
      "4XLarge": 35.00,
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    description: "Enter a qty of '1' to order one box",   
    sizes: {
      500: 46.00,
    },
  },
  {
    code: "SDNRG",
    name: "Service Hang Numbers",
    fullname: "Service Hang Numbers (1000/bx)",
    colors: ["White"],
    variations: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000", 
      "9000",
    ],  
    type: "service",
    default_color: "white",    
    discount: [
      { quantity: 1, price: 51.00 },
    ],    
    sizes: {
      "# boxes": 51.00,      
    },
  },
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250 per bag)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",    
    sizes: {
      "# bags": 6.95,
    },
  },
  {
    code: "600088V",
    name: "Seat Covers (roll)",
    fullname: "No-Slip Plastic Seat Covers (500 per roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    sizes: {
      "# rolls": 48.00,
    },
  }, 
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Self-Protecting Key Tags #200 (250 per box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# boxes": 19.99,
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100 per pack)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# packs": 9.99,
    },
  },
   {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain (500 per box)",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "office",
    default_color: "Blue",
    sizes: {
      "# boxes": 89.99,      
    },
  }, 
  {
    code: "GP790",
    name: "Sticker",
    fullname: "Vehicle Not for Sale Sticker (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    sizes: {
      "# packs": 24.99,
    },
  }, 
  {
    code: "3198WB",
    name: "Oval Year Stickers - Blue",
    fullname: "Oval Year Stickers - Blue/White (12/pk)",
    colors: ["Blue"],
    variations: [
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",      
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Blue",      
    sizes: {
      "# packs": 7.99,
    },
  }, 
  {
    code: "3198SB",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers - Silver/Black (12/pk)",
    colors: ["silver"], 
    variations: [
      "YR 2016", 
      "YR 2017",
      "YR 2018",
      "YR 2019",
      "YR 2020",
      "YR 2021",
      "YR 2022",
      "YR 2023",
      "YR 2024", 
      "YR 2025",
      "YR 2026",
    ],   
    type: "sales",
    default_color: "silver",    
    sizes: {
      "# packs": 7.99,
    },
  },
  {
    code: "3198BY",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers - Black/Yellow (12/pk)",
    colors: ["BY_08","BY_09","BY_10","BY_11","BY_12","BY_13","BY_14","BY_15","BY_16",
      "BY_17","BY_18","BY_19","BY_20","BY_21","BY_22","BY_23","BY_24","BY_25","BY_26"],
    type: "sales",
    default_color: "BY 08",
    sizes: {
      "# packs": 7.99,
    },
  },
  {
    code: "30BKHP",
    name: "7.5 in. Numbers - Bk/Htpk",
    fullname: "7.5 in. Numbers - Black/Hot Pink (12 per pack)",
    colors: ["BKHP0","BKHP1","BKHP2","BKHP3","BKHP4","BKHP5","BKHP6","BKHP7","BKHP8","BKHP9","BKHPS","BKHPD","BKHPP"],
    type: "sales",
    default_color: "BKHP0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30SLBK",
    name: "7.5 in. Numbers - Slv/Blk",
    fullname: "7.5 in. Numbers - Silver/Black (12 per pack)",
    colors: ["SLBK0","SLBK1","SLBK2","SLBK3","SLBK4","SLBK5","SLBK6","SLBK7","SLBK8","SLBK9","SLBKS","SLBKD","SLBKP"],
    type: "sales",
    default_color: "SLBK0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30GDBK",
    name: "7.5 in. Numbers - Gld/Blk",
    fullname: "7.5 in. Numbers - Gold/Black (12 per pack)",
    colors: ["GDBK0","GDBK1","GDBK2","GDBK3","GDBK4","GDBK5","GDBK6","GDBK7","GDBK8","GDBK9","GDBKS","GDBKD","GDBKP"],
    type: "sales",
    default_color: "GDBK0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30CBK",
    name: "7.5 in. Numbers - Char/Blk",
    fullname: "7.5 in. Numbers - Chartreuse/Black (12 per pack)",
    colors: ["CBK0","CBK1","CBK2","CBK3","CBK4","CBK5","CBK6","CBK7","CBK8","CBK9","CBKS","CBKP"],
    type: "sales",
    default_color: "CBK0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30YBK",
    name: "7.5 in. Numbers - Ylw/Blk",
    fullname: "7.5 in. Numbers - Yellow/Black (12 per pack)",
    colors: ["YBK0","YBK1","YBK2","YBK3","YBK4","YBK5","YBK6","YBK7","YBK8","YBK9","YBKS","YBKP", "YBKD"],
    type: "sales",
    default_color: "YBK0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30YR",
    name: "7.5 in. Numbers - Yllw/Red",
    fullname: "7.5 in. Numbers - Yellow/Red (12 per pack)",
    colors: ["YR0","YR1","YR2","YR3","YR4","YR5","YR6","YR7","YR8","YR9","YRS","YRP","YRD"],
    type: "sales",
    default_color: "YR0",    
    sizes: {
      "# packs": 2.99,
    },
  },
   {
    code: "30YGR",
    name: "7.5 in. Numbers - Yllw/Grn",
    fullname: "7.5 in. Numbers - Yellow/Green (12 per pack)",
    colors: ["YGR0","YGR1","YGR2","YGR3","YGR4","YGR5","YGR6","YGR7","YGR8","YGR9","YGRS","YGRP","YGRD"],
    type: "sales",
    default_color: "YGR0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30YB",
    name: "7.5 in. Number - Yllw/Blue",
    fullname: "7.5 in. Numbers - Yellow/Blue (12 per pack)",
    colors: ["YB0","YB1","YB2","YB3","YB4","YB5","YB6","YB7","YB8","YB9","YBS","YBP","YBD"],
    type: "sales",
    default_color: "YB0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30WB",
    name: "7.5 in. Number - Wht/Blue",
    fullname: "7.5 in. Numbers - White/Blue (12 per pack)",
    colors: ["WB0","WB1","WB2","WB3","WB4","WB5","WB6","WB7","WB8","WB9","WBS","WBP","WBD"],
    type: "sales",
    default_color: "WB0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30BLW",
    name: "7.5 in. Number - Blue/Wht",
    fullname: "7.5 in. Numbers - Blue/White (12 per pack)",
    colors: ["BLW0","BLW1","BLW2","BLW3","BLW4","BLW5","BLW6","BLW7","BLW8","BLW9","BLWS","BLWP","BLWD"],
    type: "sales",
    default_color: "BLW0",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "30RW",
    name: "7.5 in. Numbers - Red/Wht",
    fullname: "7.5 in. Numbers - Red/White (12 per pack)",
    colors: ["RW0","RW1","RW2","RW3","RW4","RW5","RW6","RW7","RW8","RW9","RWS","RWD","RWP"],
    type: "sales",
    default_color: "RW0",    
    sizes: {
      "# packs": 2.99,
    },
  },
];
