export const catalog = [
  {
    code: "C402",
    name: "Port Authority Trucker Cap #C402",
    fullname: "Port Authority® Snapback Trucker Cap (C402)",
    colors: [
      "Black",
      "Black Tan",     
      "FlameRed Black",
      "FlameRed White",
      "HthrGry PatriotBlue",
      "PatriotBlue White",
      "Purple White",
      "Woodland Camo",     
    ],
    type: "hat",
    default_color: "Black",
    description:"One size fits all",
    halfColors: [
      'Black Tan',
      'FlameRed Black',
      'FlameRed White',
      'HthrGry PatriotBlue',
      'PatriotBlue White',
      'Purple White',    
    ],
    sizes: {
      "12+": 14.99,
      "24+": 13.99,
      "50+": 12.99,
      "100+": 12.00,
    },
  },
  {
    code: "C818",
    name: "Port Authority Snapback Cap #C818",
    fullname: "Port Authority® Double Mesh Snapback Sandwich Bill Cap (C818)",
    colors: [
      "Black Red",
      "Black ShockBlue",     
      "Black Silver",          
    ],
    type: "hat",
    default_color: "Black Red",
    description:"One size fits all",
    halfColors: [
      'Black Red',
      'Black ShockBlue',     
      'Black Silver',    
    ],
    sizes: {
      "12+": 11.25,
      "24+": 10.99,      
    },
  },
  {
    code: "CP90",
    name: "Port & Co™ Knit Cap #CP90",
    fullname: "Port & Co™ Knit Cap (CP90)",
    colors: [
      "Black",
      "Athletic Oxford",
      "Athletic Purple",
      "Athletic Red",
      "Athletic Royal",
      "Charcoal Heather",
      "Navy",      
    ],
    type: "hat",
    default_color: "Black",
    description: "One size fits all",
    sizes: {
      "12+": 10.99,
      "24+": 10.50,
      "50+": 10.00,
      "100+": 8.99,
    },
  },
  {
    code: "CP90L",
    name: "Port & Co™ Fleece-Lined Cap #CP90L",
    fullname: "Port & Co™ Fleece-Lined Knit Cap (CP90L)",
    colors: [
      "Black",
      "Athletic Oxford",      
      "Athletic Red",
      "Athletic Royal",      
      "Navy", 
      "Neon Pink Glo",     
    ],
    type: "hat",
    default_color: "Black",
    description: "One size fits all",
    sizes: {
      "12+": 13.99,
      "24+": 12.75,
      "50+": 12.00,
      "100+": 11.00,
    },
  },
  {
    code: "NKFB6444",
    name: "Nike Dri-FIT Cap #NKFB6444",
    fullname: "Nike Dri-FIT Tech Fine-Ripstop Cap (NKFB6444)",
    colors: [
      "Anthracite",
      "Black",      
      "College Navy",
      "Gym Blue",      
      "University Red", 
      "White",     
    ],
    type: "hat",
    default_color: "Anthracite",    
    sizes: {
      "M/L": 27.99,      
    },
  },
  {
    code: "CP80",
    name: "Port & Co™ Six-Panel Cap #CP80",
    fullname: "Port & Co™ Six-Panel Twill Cap",
    colors: [      
      "Black",      
      "Purple",
      "Red",
      "Royal",      
      "White",
    ],
    type: "hat",
    default_color: "Black",
    sizes: {
      "12+": 13.99,
      "24+": 12.99,
      "50+": 11.99,
    },
  },
  {
    code: "PC381",
    name: "Port & Co™ Blend Tee #PC381",
    fullname: "Port & Co™ Performance Blend Tee (PC381)",
    colors: [
        "Charcoal",
        "Deep Navy",
        "Jet Black",
        "Medium Grey", 
        "Purple",        
        "Red",
        "True Royal",           
    ],
    type: "tshirts",
    default_color: "Charcoal",
    sizes: {
      Small: 9.99,
      Medium: 9.99,
      Large: 9.99,
      XLarge: 9.99,
      "2XLarge": 11.49,
      "3XLarge": 12.99,
      "4XLarge": 13.99,
   },
  },
  {
    code: "PC61",
    name: "Port & Company® Tee #PC61",
    fullname: "Port & Company® Essential Tee (PC61)",
    colors: [
      "Athletic Heather",      
      "Charcoal",
      "Jet Black",
      "Navy",
      "Purple",
      "Rich Red",
      "Royal",      
    ],
    type: "tshirts",
    default_color: "Athletic Heather",
    sizes: {
      Small: 8.99,
      Medium: 8.99,
      Large: 8.99,
      XLarge: 8.99,
      "2XLarge": 11.49,
      "3XLarge": 12.49,
      "4XLarge": 13.49,      
    },
  },
  {
    code: "64000",
    name: "Gildan Softstyle® T-Shirt #64000",
    fullname: "Gildan Softstyle® T-Shirt (64000)",
    colors: [
      "Black",      
      "Dark Heather",      
      "Purple",      
      "Royal",      
    ],
    type: "tshirts",
    default_color: "Black",
    sizes: {
      Small: 10.75,
      Medium: 10.75,
      Large: 10.75,
      XLarge: 10.75,
      "2XLarge": 12.75,
      "3XLarge": 13.75,
      "4XLarge": 14.75,      
    },
  },
  {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo #NKDC1991",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
     colors: [
        "Anthracite", 
        "Black",                
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gym Blue", 
        "Navy",    
        "University Red",       
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 44.99,
      Medium: 44.99,
      Large: 44.99,
      XLarge: 44.99,
      "2XLarge": 46.99,      
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo #NKDC1963",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
        "Anthracite", 
        "Black",                
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gym Blue", 
        "Navy",    
        "University Red",       
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 44.99,
      Medium: 44.99,
      Large: 44.99,
      XLarge: 44.99,
      "2XLarge": 46.99,
      "3XLarge": 49.99,
      "4XLarge": 51.99,
   },
  },
  {
    code: "NKBV6042",
    name: "Nike® Dry Essential Polo #NKBV6042",
    fullname: "Nike® Dry Essential Solid Polo (NKBV6042)",
    colors: ["Black", "Game Royal", "Midnight Navy","University Red", "White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 51.99,
      Medium: 51.99,
      Large: 51.99,
      XLarge: 51.99,
      "2XLarge": 53.99,
      "3XLarge":56.99,
      "4XLarge": 58.99,     
    },
  },
  {
    code: "NKBV6043",
    name: "Nike® Dry Essential Polo #NKBV6043",
    fullname: "Nike® Women's Dry Essential Solid Polo (NKBV6043)",
    colors: ["Black", "Game Royal", "Midnight Navy", "University Red", "White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 51.99,
      Medium: 51.99,
      Large: 51.99,
      XLarge: 51.99,
      "2XLarge": 53.99,          
    },
  },
  {
    code: "OG126",
    name: "Ogio® Onyx Polo #OG126",
    fullname: "Ogio® Onyx Polo (OG126)",
    colors: ["Blacktop","Electric Blue","Navy","Petrol Grey","White"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 37.50,
      Medium: 37.50,
      Large: 37.50,
      XLarge: 37.50,
      "2XLarge": 38.50,
      "3XLarge": 42.50,
      "4XLarge": 44.99,          
    },
  },
  {
    code: "LOG126",
    name: "Ogio® Onyx Polo #LOG126",
    fullname: "Ogio® Women's Onyx Polo (LOG126)",
    colors: ["Blacktop","Electric Blue","Navy","Petrol Grey","White"],
    type: "womens",
    default_color: "Blacktop",
    sizes: {
      Small: 37.50,
      Medium: 37.50,
      Large: 37.50,
      XLarge: 37.50,
      "2XLarge": 38.50,
      "3XLarge": 42.50,
      "4XLarge": 44.99,          
    },
  },
  {
    code: "A230",
    name: "Adidas Performance Polo #A230",
    fullname: "Adidas Men's Performance Polo (A230)",
    colors: ["Black","Collegiate Red","Collegiate Royal","Collegiate Purple","Navy","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 46.50,
      "3XLarge": 48.50,
      "4XLarge": 50.99,
    },
  },
  {
    code: "A231",
    name: "Adidas Performance Polo #A231",
    fullname: "Adidas Women's Performance Polo (A231)",
    colors: ["Black","Collegiate Red","Collegiate Royal","Collegiate Purple","Navy","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
       Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 46.50,
      "3XLarge": 48.50,    
    },
  },
  {
    code: "104197",
    name: "Tribute Polo #104197",
    fullname: "Tribute Polo Men's (104197)",
    colors: ["Black","Cabernet","Dark Pine","Dark Purple","Dark Royal","Midas","Navy","Smoke"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 36.99,
      Medium: 36.99,
      Large: 36.99,
      XLarge: 36.99,
      "2XLarge": 38.50,
      "3XLarge": 39.50,
      "4XLarge": 41.99,
      "5XLarge": 43.99,
    },
  },
  {
    code: "CGM441",
    name: "Callawy Ottoman Polo #CGM441",
    fullname: "Callaway Ottoman Polo (CGM441)",
    colors: ["Black","Magnetic Blue","Peacoat","Salsa","Smoked Pearl","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 42.99,
      Medium: 42.99,
      Large: 42.99,
      XLarge: 42.99,
      "2XLarge": 45.99,
      "3XLarge": 46.99,
      "4XLarge": 47.99,      
    },
  },
  {
    code: "CGM451",
    name: "Callaway Opti-Vent Polo #CGM451",
    fullname: "Callaway Opti-Vent Polo (CGM451)",
    colors: ["Black","Medium Blue","Peacoat","Purple Magic","Quiet Shade","Salsa","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 37.99,
      Medium: 37.99,
      Large: 37.99,
      XLarge: 37.99,
      "2XLarge": 39.99,
      "3XLarge": 40.99,
      "4XLarge": 41.99,      
    },
  },  
  {
    code: "104198",
    name: "Tribute Polo #104198",
    fullname: "Tribute Polo Women's (104198)",
    colors: ["Black","Cabernet","Dark Pine","Dark Purple","Dark Royal","Midas","Navy","Smoke"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 36.99,
      Medium: 36.99,
      Large: 36.99,
      XLarge: 36.99,
      "2XLarge": 38.50,
      "3XLarge": 39.50,
      "4XLarge": 41.99,
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Microqique Polo",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: ["Black","Grey Concrete", "Iron Grey", "Purple","True Navy","True Royal","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 25.99,
      Medium: 25.99,
      Large: 25.99,
      XLarge: 25.99,
      "2XLarge": 27.50,      
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Sport-Wick Micropique Polo (ST650)",
    colors: [
      "Black",     
      "Grey Concrete",
      "Iron Grey",      
      "Maroon",
      "Purple",      
      "True Navy",      
      "True Royal",      
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 25.99,
      Medium: 25.99,
      Large: 25.99,
      XLarge: 25.99,
      "2XLarge": 27.50,
      "3XLarge": 30.50,
      "4XLarge": 32.50,
      "5XLarge": 34.50,      
    },
  },
  {
    code: "NKDC2104",
    name: "Nike Long Sleeve Polo #NKDC2104",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Long Sleeve Polo (NKDC2104)",
    colors: ["Anthracite","Black","Game Royal","Gym Blue","Navy","University Red"],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 54.99,
      Medium: 54.99,
      Large: 54.99,
      XLarge: 54.99,
      "2XLarge": 56.99,
      "3XLarge": 59.99,
      "4XLarge": 60.99,
    },
  },
  {
    code: "NKDC2105",
    name: "Nike Long Sleeve Polo #NKDC2105",
    fullname: "Nike Women's Dri-FIT Micro Pique 2.0 Long Sleeve Polo (NKDC2105)",
    colors: ["Anthracite","Black","Game Royal","Gym Blue","Navy","University Red"],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 54.99,
      Medium: 54.99,
      Large: 54.99,
      XLarge: 54.99,
      "2XLarge": 56.99,      
    },
  },
  {
    code: "29M",
    name: "Jerzees® Dri-Power® Tee #29M",
    fullname: "Jerzees® Dri-Power® 50/50 Cotton/Poly T-Shirt (29M)",
    colors: ["Charcoal Grey","JNavy","Royal"], 
    type: "tshirts",
    default_color: "Charcoal Grey",
    sizes: {
      Small: 8.49,
      Medium: 8.49,
      Large: 8.49,
      XLarge: 8.49,
      "2XLarge": 11.25,
      "3XLarge": 13.99,
      "4XLarge": 14.99, 
      "5XLarge": 15.99,
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee #ST350",
    fullname: "Sport-Tek® PosiCharge® Competitor Tee (ST350)",
    colors: [
      "Black",      
      "Grey Concrete",
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",     
    ],
    type: "tshirts",
    default_color: "Black",
    sizes: {
      Small: 10.99,
      Medium: 10.99,
      Large: 10.99,
      XLarge: 10.99,
      "2XLarge": 12.99,
      "3XLarge": 13.99,
      "4XLarge": 14.99,
    },
  },
  {
    code: "W816",
    name: "Port Authority Long Sleeve #W816",
    fullname: "Port Authority Long Sleeve Nailhead Easy Care Shirt (W816)",
    colors: ["Deep Black","Mediterranean Blue", "White"],
    type: "mens",
    default_color: "Deep Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 41.99,
      "3XLarge": 45.99, 
      "4XLarge": 47.99,           
    },
  },
  {
    code: "NKBV6044",
    name: "Nike® 1/2-Zip Cover-Up #NKBV6044",
    fullname: "Nike® Dry 1/2-Zip Cover-Up (NKBV6044)",
    colors: ["Black","Gym Blue"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 76.99,
      Medium: 76.99,
      Large: 76.99,
      XLarge: 76.99,
      "2XLarge": 78.99,
      "3XLarge": 80.99,
      "4XLarge": 82.99,          
    },
  }, 
  {
    code: "ST850",
    name: "Sport-Tek® 1/4-Zip #ST850",
    fullname: "Sport-Tek® Sport-Wick® Stretch 1/4-Zip Pullover (ST850)",
    colors: ["Black","Charcoal Grey","True Red","True Royal","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 37.50,
      Medium: 37.50,
      Large: 37.50,
      XLarge: 37.50,
      "2XLarge": 39.99,
      "3XLarge": 41.99,
      "4XLarge": 43.99,          
    },
  },
  {
    code: "ST860",
    name: "Sport-Tek® 1/4-Zip #ST860",
    fullname: "Sport-Tek® Sport-Wick® Textured 1/4-Zip Pullover (ST860)",
    colors: ["Black","Deep Red","Iron Grey","True Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 35.99,
      Medium: 35.99,
      Large: 35.99,
      XLarge: 35.99,
      "2XLarge": 38.99,
      "3XLarge": 39.99,
      "4XLarge": 40.99,          
    },
  },
  {
    code: "LST850",
    name: "Sport-Tek® 1/4-Zip Pullover #LST850",
    fullname: "Sport-Tek® Women's Sport-Wick® Stretch 1/4-Zip Pullover (LST850)",
    colors: ["Black","Charcoal Grey","True Red","True Royal","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 37.50,
      Medium: 37.50,
      Large: 37.50,
      XLarge: 37.50,
      "2XLarge": 39.99,
      "3XLarge": 41.99,
      "4XLarge": 43.99,          
    },
  },
  {
    code: "LST860",
    name: "Sport-Tek® 1/4-Zip #LST860",
    fullname: "Sport-Tek® Women's Sport-Wick® Textured 1/4-Zip Pullover (LST860)",
    colors: ["Black","Deep Red","Iron Grey","Pink Raspberry","True Navy","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 35.99,
      Medium: 35.99,
      Large: 35.99,
      XLarge: 35.99,
      "2XLarge": 38.99,
      "3XLarge": 39.99,
      "4XLarge": 40.99,          
    },
  },
  {
    code: "K805",
    name: "Port Authority® Full-Zip #K805",
    fullname: "Port Authority® Vertical Texture 1/4-Zip Pullover (K805)",
    colors: ["Black","Iron Grey","True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 32.99,
      Medium: 32.99,
      Large: 32.99,
      XLarge: 32.99,
      "2XLarge": 34.99,
      "3XLarge": 36.99,
      "4XLarge": 38.99,          
    },
  },
  {
    code: "L805",
    name: "Port Authority® Full-Zip #L805",
    fullname: "Port Authority® Women's Vertical Texture Full-Zip Jacket (L805)",
    colors: ["Black","Iron Grey","True Navy"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 32.99,
      Medium: 32.99,
      Large: 32.99,
      XLarge: 32.99,
      "2XLarge": 34.99,
      "3XLarge": 36.99,
      "4XLarge": 38.99,          
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    colors: ["Black", "Battleship Grey","Dress Blue Navy","Rich Red","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 41.99,
      "3XLarge": 43.99,
      "4XLarge": 45.99,
      "5XLarge": 47.99,
      "6XLarge": 49.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket (L317)",
    colors: ["Black", "Battleship Grey","Dress Blue Navy","Rich Red","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 41.99,
      "3XLarge": 43.99,
      "4XLarge": 45.99,
    },
  },
  {
    code: "J333",
    name: "Port Authority® Jacket #J333",
    fullname: "Port Authority® Torrent Waterproof Jacket (J333)",
    colors: ["Black", "Deep Red","Magnet","True Navy","True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 62.99,
      Medium: 62.99,
      Large: 62.99,
      XLarge: 62.99,
      "2XLarge": 64.99,
      "3XLarge": 67.99,
      "4XLarge": 68.99,      
    },
  },
  {
    code: "L333",
    name: "Port Authority® Jacket #L333",
    fullname: "Port Authority® Women's Torrent Waterproof Jacket (L333)",
    colors: ["Black", "Deep Red","Magnet","True Navy","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 62.99,
      Medium: 62.99,
      Large: 62.99,
      XLarge: 62.99,
      "2XLarge": 64.99,
      "3XLarge": 67.99,
      "4XLarge": 68.99,      
    },
  },
  {
    code: "MATFME-34CPSS-452477A",
    name: "Chrome Plated Plate",
    fullname: "Screen Printed Chrome Plated Frame w/black imprint",
    colors: ["Chrome"],
    type: "customs",
    default_color: "Chrome",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["MATFME"],
    sizes: {
      "1000": .39,
      "1500": .39,
      "2500": .39,
    },
  },
  {
    code: "BOWHSL-34PE-487072A",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["BOWHSL"],
    sizes: {
      "1000": .59,
      "1500": .59,
      "2500": .59,
    },
  },
  {
    code: "BOWCME-34PEU-451316A",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["BOWCME"],
    sizes: {
      "1000": .59,
      "1500": .59,
      "2500": .59,
    },
  },
  {
    code: "BOWCSL-34PEU-450934A",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["BOWCSL"],
    sizes: {
      "1000": .59,
      "1500": .59,
      "2500": .59,
    },
  },    
  {
    code: "MATFME-33P-401384A",
    name: "15 Gauge Vinyl Plate",
    fullname: "15 Gauge Vinyl Plate - White w/294 blue imprint",
    colors: ["Blue"],
    type: "customs",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["MATFME"],
    sizes: {
      "1000": .49,
      "1500": .49,
      "2500": .49,
    },
  },
  {
    code: "BOWHSL-33P-518072A",
    name: "15 Gauge Vinyl Plate",
    fullname: "15 Gauge Vinyl Plate - White w/reflex blue imprint",
    colors: ["Blue"],
    type: "customs",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["BOWHSL"],
    sizes: {
      "1000": .49,
      "1500": .49,
      "2500": .49,
    },
  },
  {
    code: "BOWCSL-33GT-450935Z",
    name: "15 Gauge Vinyl Plate",
    fullname: "15 Gauge Vinyl Plate - White w/4CP imprint",
    colors: ["Blue"],
    type: "customs",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["BOWCSL"],
    sizes: {
      "1000": .49,
      "1500": .49,
      "2500": .49,
    },
  }, 
  {
    code: "BOWCME-33GT-451336Z",
    name: "15 Gauge Vinyl Plate",
    fullname: "15 Gauge Vinyl Plate - White w/4CP imprint",
    colors: ["Blue"],
    type: "customs",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",
    supportedStores: ["BOWCME"],
    sizes: {
      "1000": .49,
      "1500": .49,
      "2500": .49,
    },
  },       
  {
    code: "MATFME-31DD-402399A",
    name: "Thermo Die Cut Decal",
    fullname: "Thermo Die Cut Decal (3.75 in x 1.33 in.)",
    colors: ["Black","White"],
    type: "customs",
    default_color: "Black",    
    description: "BLACK WILL NOT SHOW ON WHITE DECAL; Sold in quantities of 1000, 1500 & 2500",
    supportedStores: ["MATFME"],
    sizes: {
      "1000": .64,
      "1500": .64,
      "2500": .64,
    },
  },
   {
    code: "BOWHSL-31DD-487075A",
    name: "Thermo Die Cut Decal",
    fullname: "Thermo Die Cut Decal (5 in x 1.77 in.)",
    colors: ["Black","White"],
    type: "customs",
    default_color: "Black",
    description: "BLACK WILL NOT SHOW ON WHITE DECAL; Sold in quantities of 1000, 1500 & 2500",
    supportedStores: ["BOWHSL"],
    sizes: {
      "1000": .64,
      "1500": .64,
      "2500": .64,
    },
  },
  {
    code: "MATFME-31DD-486762A",
    name: "Theromo Die Cut Decal",
    fullname: "Thermo Die Cut Decal (5 in x 1.61 in.)",
    colors: ["Black","White"],
    type: "customs",
    default_color: "Black",
    description: "BLACK WILL NOT SHOW ON WHITE DECAL; Sold in quantities of 1000, 1500 & 2500",
    supportedStores: ["MATFME"],
    sizes: {
      "1000": .64,
      "1500": .64,
      "2500": .64,
    },
  },
  {
    code: "BOWCSL-31DD-450936A",
    name: "Thermo Die Cut Decal",
    fullname: "Thermo Die Cut Decal (5 in x .72 in.)",
    colors: ["Black","White"],
    type: "customs",
    default_color: "Black",
    description: "BLACK WILL NOT SHOW ON WHITE DECAL; Sold in quantities of 1000, 1500 & 2500",
    supportedStores: ["BOWCSL"],
    sizes: {
      "1000": .64,
      "1500": .64,
      "2500": .64,
    },
  },
  {
    code: "BOWCME-31DD-451310A",
    name: "Thermo Die Cut Decal",
    fullname: "Thermo Die Cut Decal (6 in x .80 in.)",
    colors: ["Black","White"],
    type: "customs",
    default_color: "Black",
    description: "BLACK WILL NOT SHOW ON WHITE DECAL; Sold in quantities of 1000, 1500 & 2500",
    supportedStores: ["BOWCME"],
    sizes: {
      "1000": .64,
      "1500": .64,
      "2500": .64,
    },
  },
  {
    code: "BOWCME-THC-510784B",
    name: "Domecal Trailer Hitch Cover",
    fullname: "White Domecal Trailer Hitch Cover w/reflex blue & 877 metallic silver imprint",
    colors: ["Blue"],
    type: "customs",
    default_color: "Blue",
    description: "Sold in quantities of 1000; Enter '1' for one shipment of 1000",
    supportedStores: ["BOWCME"],
    sizes: {
      "1000": .61,      
    },
  },
  {
    code: "MATFME-TOTE-504401A",
    name: "Reflective Tote Bag",
    fullname: "Clear Eva Reflective Tote Bag w/black imprint (12 in. x 12 in.)",
    colors: ["Clear"],
    type: "accessory",
    default_color: "Clear",
    description: "Sold in quantities of 1000; Enter '1' for one shipment of 1000",    
    sizes: {
      "1000": 3.50,      
    },
  },
  {
    code: "MATFME-CG1240-470649L",
    name: "Leather Strap Key Tag",
    fullname: "Laser Engraved Zinc Leather Strap Key Tag (2-sided)",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black", 
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",   
    sizes: {
       "1000": 2.99,
       "1500": 2.75,
       "2500": 2.25,
   },
  }, 
  {
    code: "MATFME-Q42971-404913A",
    name: "Metal Key Ring",
    fullname: "Metal Color Series Key Ring w/white imprint",
    colors: ["Blue"],
    type: "accessory",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",    
    sizes: {
       "1000": 2.05,
       "1500": 1.99,
       "2500": 1.55,
   },
  },
  {
    code: "MATFME-RCM-446180A",
    name: "Metal Key Ring",
    fullname: "Metal Key Ring w/reflex blue imprint",
    colors: ["White"],
    type: "accessory",
    default_color: "White", 
    description: "Sold in boxes of 1000; Enter '1' for shipment of 1000",   
    sizes: {
       "1000": 1.29,
    },
  }, 
  {
    code: "MATFME-321-452483A",
    name: "Javalina Executive Pen",
    fullname: "Javalina Pen w/white imprint",
    colors: ["Blue"],
    type: "accessory",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500; Enter '1' for shipment of 1000, etc.",    
    sizes: {
       "1000": .61,
       "1500": .59,
       "2500": .54,
   },
  },
  {
    code: "BOWCME-GP3031-425944B",
    name: "Non-Woven Shopper Tote",
    fullname: "Royal Blue Non-Woven Shopper Tote w/871 gold & white imprint ",
    colors: ["Blue"],
    type: "accessory",
    default_color: "Blue",
    description: "Sold in quantities of 500; Enter '1' for shipment of 500, etc.",    
    sizes: {
       "500": 1.85,       
   },
  },
  {
    code: "MATFME-284-515528A",
    name: "Vinyl Document Folder",
    fullname: "Royal Blue Guesseted Vinyl doc Folder w/white imprint",
    colors: ["Royal Blue"],
    type: "sales",
    default_color: "Royal Blue",
    description: "Sold in quantities of 1000; Enter '1' for shipment of 1000",    
    sizes: {
       "1000": 2.25,       
   },
  },
   {
    code: "BOWCME-0801-474526B",
    name: "White Quick Ship Folder",
    fullname: "White Quick Ship Folder w/reflex blue & 872 metallic gold imprint",
    colors: ["White"],
    type: "sales",
    default_color: "White",
    description: "Sold in quantities of 1000; Enter '1' for shipment of 1000",    
    sizes: {
       "1000": 1.75,       
   },
  },
  {
    code: "MATFME-DEALJACKET-502487A",
    name: "Custom Deal Jacket",
    fullname: "Custom Deal Jacket (DSA-500)",
    colors: ["Blue","White"],
    type: "sales",
    default_color: "Blue",
    description: "Sold in quantities of 1000, 1500 and 2500",    
    sizes: {
       "1000": .44,
       "1500": .44,
       "2500": .44,
   },
  },
  {
    code: "226",
    name: "Combo Key Tags",
    fullname: "Combo Key Tags - Numbered (125/bx)",
    colors: [
      "Beige",
      "Blue",
      "Green",
      "Grey",
      "Lilac",
      "Orange",
      "Red",
      "White",
      "Yellow",
    ],   
    type: "sales",
    default_color: "Beige",
    description: "Sold in quantities of 1, 5 or 10 boxes", 
    sizes: {
      "1": 67.99,
      "5": 67.99,
      "10": 62.99,
    },
  },
  {
    code: "GP200",
    name: "Stock Key Tags",
    fullname: "Self-Protecting Key Tags (250/bx)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    description: "Sold in quantities of 1, 5 or 10 boxes",    
    sizes: {
      "1": 33.99,
      "5": 31.99,
      "10": 29.99,
    },
  },        
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain (500/bx)",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    description: "Sold in quantities of 1,5 or 10 boxes", 
    sizes: {
      "1": 115.76,
      "5": 115.76,
      "10": 105.00,
    },
  },   
  {
    code: "VT400",
    name: "Stock Windshield Sticker",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100/pk)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Blue",
    description: "Sold in quantities of 1, 5 or 10 packs",    
    sizes: {
      "1": 15.99,
      "5": 15.99,
      "10": 12.99,
    },
  }, 
  {
    code: "BOWHSL-1830-490972A",
    name: "Service Due Sticker",
    fullname: "White Vinyl Service Due Sticker w/black imprint (1.5 in. x 2.25 in.)",
    description: "GREY DOES NOT PRINT; 2500 per box",
    colors: ["White"],
    type: "service",
    default_color: "White",    
    sizes: {
       "2500": .15,
    },
  }, 
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250/pk)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",
    description: "Sold in quantities of 1, 5 or 10 packs",    
    sizes: {
      "1": 16.99,
      "5": 12.99,
      "10": 10.99,
    },
  },
  {
    code: "BOWCME-1830-491490Z",
    name: "Service Due Sticker",
    fullname: "White Vinyl Service Due Sticker w/full color imprint (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    description: "GREY DOES NOT PRINT. Sold in quantities of 2500; Enter '1' for one shipment of 2500",    
    sizes: {
      "2500": .15,      
    },
  },
  {
    code: "SDNRG",
    name: "Service Hang Numbers",
    fullname: "Service Hang Numbers (1000/bx)",
    colors: ["White"],
    variations: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000", 
      "9000",
    ],  
    type: "service",
    default_color: "white",
    description: "Sold in quantities of 1, 5 or 10 boxes", 
    discount: [
      { quantity: 1, price: 84.99 },
      { quantity: 5, price: 83.99 },
      { quantity: 10, price: 79.99 },
    ],    
    sizes: {
      "1": 84.99,
      "5": 83.99,
      "10": 79.99,
    },
  },
  {
    code: "3198WB",
    name: "Oval Year Stickers - Blue",
    fullname: "Oval Year Stickers - Blue/White (12/pk)",
    colors: ["Blue"],
    variations: [
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",      
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Blue",
    description: "Sold in quantities of 1, 5, or 10 packs; Enter '1' for one shipment of one pack, etc.", 
    discount: [
      { quantity: 1, price: 11.99 },
      { quantity: 5, price: 10.99 },
      { quantity: 10, price: 10.99 },
    ],
    sizes: {
      "1": 11.99,
      "5": 10.99,
      "10": 10.99,
    },
  }, 
  {
    code: "HANG-SG",
    name: "Hang Tag - Was Now",
    fullname: "Stock Hang Tags - Was Now - 9in x 12in (50/pk)",
    colors: ["Fluorg","Fluorp","Fluorr","Fluory"],
    type: "sales",
    default_color: "Fluorg",
    description: "Sold in quantities of 1, 5, or 10 packs; Enter '1' for one shipment of one pack, etc.",   
    sizes: {
      "1": 29.45,
      "5": 29.45,
      "10": 27.45,
    },
  },
];