export const catalog = [
  {
    code: "A230",
    name: "Adidas Performance Polo #A230",
    fullname: "Adidas Men's Performance Polo (A230)",
    colors: ["Black","Collegiate Red","Collegiate Royal","Collegiate Purple","Navy","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 46.50,
      "3XLarge": 48.50,
      "4XLarge": 50.99,
    },
  },
  {
    code: "A231",
    name: "Adidas Performance Polo #A231",
    fullname: "Adidas Women's Performance Polo (A231)",
    colors: ["Black","Collegiate Red","Collegiate Royal","Collegiate Purple","Navy","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
       Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 46.50,
      "3XLarge": 48.50,    
    },
  },
  {
    code: "NKBV6042",
    name: "Nike® Essential Polo #NKBV6042",
    fullname: "Nike® Dry Essential Solid Polo (NKBV6042)",
    colors: ["Black", "Game Royal", "Midnight Navy","University Red", "White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 51.99,
      Medium: 51.99,
      Large: 51.99,
      XLarge: 51.99,
      "2XLarge": 53.99,
      "3XLarge":56.99,
      "4XLarge": 58.99,     
    },
  },
  {
    code: "NKBV6043",
    name: "Nike® Essential Polo #NKBV6043",
    fullname: "Nike® Women's Dry Essential Solid Polo (NKBV6043)",
    colors: ["Black", "Game Royal", "Midnight Navy", "University Red", "White"],
    type: "womens",
    default_color: "Black",
    sizes: {
     Small: 51.99,
      Medium: 51.99,
      Large: 51.99,
      XLarge: 51.99,
      "2XLarge": 53.99,          
    },
  },
   {
    code: "W816",
    name: "Port Authority Long Sleeve Shirt #W816",
    fullname: "Port Authority Long Sleeve Nailhead Easy Care Shirt (W816)",
    colors: ["Deep Black","Mediterranean Blue", "White"],
    type: "mens",
    default_color: "Deep Black",
    sizes: {
     Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 41.99,
      "3XLarge": 45.99, 
      "4XLarge": 47.99,           
    },
  },
  {
    code: "NKBV6044",
    name: "Nike® Dry 1/2-Zip Cover-Up #NKBV6044",
    fullname: "NNike® Dry 1/2-Zip Cover-Up (NKBV6044)",
    colors: ["Black","Gym Blue"],
    type: "mens",
    default_color: "Black",
    sizes: {
     Small: 76.99,
      Medium: 76.99,
      Large: 76.99,
      XLarge: 76.99,
      "2XLarge": 78.99,
      "3XLarge": 80.99,
      "4XLarge": 82.99,          
    },
  }, 
  {
    code: "ST850",
    name: "SSport-Tek® 1/4-Zip Pullover #ST850",
    fullname: "Sport-Tek® Sport-Wick® Stretch 1/4-Zip Pullover (ST850)",
    colors: ["Black","Charcoal Grey","True Red","True Royal","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
     Small: 37.50,
      Medium: 37.50,
      Large: 37.50,
      XLarge: 37.50,
      "2XLarge": 39.99,
      "3XLarge": 41.99,
      "4XLarge": 43.99,          
    },
  }, 
];