export const catalog = [
    {
    code: "MCDONALD-PFRAMEI",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Enter '1' for a shipment of 250, 500 or 1000 frames",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "MCDONALD-MFRAMEI",
    name: "Chrome Metal Frame",
    fullname: "Black Powder Coated Zinc Metal Frame w/ white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Enter '1' for a shipment of 250, 500 or 1000 frames",
    discount: [
      { quantity: 250, price: 1.99 },  
      { quantity: 500, price: 1.99 }, 
      { quantity: 1000, price: 1.99 },     
    ],
    sizes: {
      250: 1.99, 
      500: 1.99,
      1000: 1.99,      
    },
  },
  {
    code: "MCDONALD-CPMO",
    name: "Chrome Plastic Nameplate",
    fullname: "Chrome-Plated Plastic Nameplates",
    colors: ["Chrome"],
    type: "customs",
    default_color: "Chrome",
    description: "Enter '1' for a shipment of 250, 500 or 1000 nameplates",
    discount: [
      { quantity: 250, price: .49 },  
      { quantity: 500, price: .49 }, 
      { quantity: 1000, price: .49 },     
    ],
    sizes: {
      250: .49, 
      500: .49,
      1000: .49,      
    },
  },
  {
    code: "MCDONALD-BPMO",
    name: "Black Plastic Nameplate",
    fullname: "Black Plastic Nameplates",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: "Enter '1' for a shipment of 250, 500 or 1000 nameplates",
    discount: [
      { quantity: 250, price: .49 },  
      { quantity: 500, price: .49 }, 
      { quantity: 1000, price: .49 },     
    ],
    sizes: {
      250: .49, 
      500: .49,
      1000: .49,      
    },
  },
  {
    code: "MCDONALD-33GT",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "GENOLI-33P-513164A",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "AUDPCO-33GT-513166Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },  
  {
    code: "MCDADE-33GT-513167Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "POLDEN-33GT-513165Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },  
  {
    code: "MCDMLA-33GT-513170Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "MCDMLO-33GT-513168Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },  
  {
    code: "MCDHLI-33GT-513176Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "MCDNHI-33GT-513172Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "MCDTCO-33GT-513173Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "MCDVLI-33GT-513174Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "MCDVLT-33GT-513175Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    description: "Enter '1' for a shipment of 250, 500 or 1000 plates",
    discount: [
      { quantity: 250, price: .50 },  
      { quantity: 500, price: .50 }, 
      { quantity: 1000, price: .50 },     
    ],
    sizes: {
      250: .50, 
      500: .50,
      1000: .50,      
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",    
    sizes: {
      "# boxes": 46.00,
    },
  },
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    sizes: {
      "# rolls": 48.00,
    },
  },
  {
    code: "SDNRG",
    name: "Service Hang Numbers",
    fullname: "Service Hang Numbers (1000/bx)",
    colors: ["White"],
    variations: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000", 
      "9000",
    ],  
    type: "service",
    default_color: "white",        
    sizes: {
      "# boxes": 51.00,      
    },
  },
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250/pk)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",      
    sizes: {
      "# packs": 6.95,      
    },
  },
  {
    code: "55010",
    name: "Steering Wheel Covers",
    fullname: "Steering Wheel Covers (500/bx)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    sizes: {
      "# boxes": 51.99,
    },
  },
  {
    code: "EIT50",
    name: "Self-Locking Key Tags",
    fullname: "Self-Locking Key Tags (1000/pk)",
    colors: ["Blue","Green","Orange","Red","Yellow","White"],
    type: "service",
    default_color: "Blue",
    sizes: {
      "# packs": 19.99,
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Self-Protecting Key Tags #200 (250 per box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",    
    sizes: {
      "# boxes": 19.99,
    },
  }, 
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100 per pack)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "White",    
    sizes: {
      "# packs": 9.99,
    },
  }, 
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain (500/box)",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "office",
    default_color: "Blue",
    sizes: {
      "# boxes": 89.99,      
    },
  },
  {
    code: "GP790",
    name: "Sticker",
    fullname: "Vehicle Not for Sale Sticker (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    sizes: {
      "# packs": 24.99,
    },
  }, 
  {
    code: "3198WB",
    name: "Oval Year Stickers - Blue",
    fullname: "Oval Year Stickers - Blue/White (12/pk)",
    colors: ["Blue"],
    variations: [
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",      
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Blue",
    sizes: {
      "# packs": 2.99,
   },
  }, 
  {
    code: "3198SB",
    name: "Oval Year Stickers - Silver",
    fullname: "Oval Year Stickers - Silver/Black (12/pk)",
    colors: [
      "YR 2016", 
      "YR 2017",
      "YR 2018",
      "YR 2019",
      "YR 2020",
      "YR 2021",
      "YR 2022",
      "YR 2023",
      "YR 2024", 
      "YR 2025",
      "YR 2026",
    ],   
    type: "sales",
    default_color: "YR 2016",    
    sizes: {
      "# packs": 2.99,
    },
  },
  {
    code: "3198BY",
    name: "Oval Year Stickers - Yellow",
    fullname: "Oval Year Stickers - Black/Yellow (12/pk)",
    colors: [
      "BY_08",
      "BY_09",
      "BY_10",
      "BY_11",
      "BY_12",
      "BY_13",
      "BY_14",
      "BY_15",
      "BY_16",
      "BY_17",
      "BY_18",
      "BY_19",
      "BY_20",
      "BY_21",
      "BY_22",
      "BY_23",
      "BY_24",
      "BY_25",
      "BY_26",
    ],
    type: "sales",
    default_color: "BY 08",
    sizes: {
      "# packs": 2.99,
    },
  },  
]