export const catalog = [
    {    
    code: "104197",
    name: "Tribute Polo #104197",
    fullname: "Tribute Men's Polo (104197)",
    colors: [
        "Black",             
        "Smoke",  
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",
      "5XLarge",
    ],
    pricing: {
      Small: { price: 30.00 },
      Medium: { price: 30.00 },
      Large: { price: 30.00 },
      XLarge: { price: 30.00 },
      "2XLarge": { price: 30.00 },
      "3XLarge": { price: 35.00 },
      "4XLarge": { price: 35.00 },
      "5XLarge": { price: 35.00 },
   },
  }, 
   {    
    code: "104198",
    name: "Tribute Polo #104198",
    fullname: "Tribute Women's Polo (104198)",
    colors: [
        "Black",             
        "Smoke",  
    ],
    type: "womens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",      
    ],
    pricing: {
      XSmall: { price: 30.00 },
      Small: { price: 30.00 },
      Medium: { price: 30.00 },
      Large: { price: 30.00 },
      XLarge: { price: 30.00 },
      "2XLarge": { price: 30.00 },
      "3XLarge": { price: 35.00 },
      "4XLarge": { price: 35.00 },      
   },
  },
  {    
    code: "S500T",
    name: "Port Authority Shirt #S500T",
    fullname: "Port Authority® Short Sleeve Twill Shirt (S500T)",
    colors: [
        "Black",              
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",      
    ],
    pricing: {
      XSmall: { price: 27.95 },
      Small: { price: 27.95 },
      Medium: { price: 27.95 },
      Large: { price: 27.95 },
      XLarge: { price: 27.95 },
      "2XLarge": { price: 29.60 },
      "3XLarge": { price: 32.95 },
      "4XLarge": { price: 35.60 },      
   },
  },
  {    
    code: "104939",
    name: "Long Sleeve Dress Shirt #104939",
    fullname: "Flight Long Sleeve Woven Dress Shirt (104939)",
    colors: [
        "Black",      
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 42.00 },
      Medium: { price: 42.00 },
      Large: { price: 42.00 },
      XLarge: { price: 42.00 },
      "2XLarge": { price: 42.00 },
      "3XLarge": { price: 46.70 },
      "4XLarge": { price: 46.70 },      
   },
  }, 
  {    
    code: "K829",
    name: "Port Authority 1/4-Zip #K829",
    fullname: "Port Authority® Fairway Stretch 1/4-Zip (K829)",
    colors: [
        "Deep Black",
        "Shadow Grey",      
    ],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 38.00 },
      Medium: { price: 38.00 },
      Large: { price: 38.00 },
      XLarge: { price: 38.00 },
      "2XLarge": { price: 38.95 },
      "3XLarge": { price: 42.25 },
      "4XLarge": { price: 43.95 },      
   },
  },
  {    
    code: "J324",
    name: "Port Authority Jacket #J324",
    fullname: "Port Authority® Welded Soft Shell Jacket (J324)",
    colors: [
        "Black",
        "Deep Smoke",      
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 48.00 },
      Medium: { price: 48.00 },
      Large: { price: 48.00 },
      XLarge: { price: 48.00 },
      "2XLarge": { price: 49.70 },
      "3XLarge": { price: 53.00 },
      "4XLarge": { price: 54.70 },      
   },
  },
  {    
    code: "L324",
    name: "Port Authority Jacket #L324",
    fullname: "Port Authority® Women's Welded Soft Shell Jacket (L324)",
    colors: [
        "Battleship Grey",
        "Black",      
    ],
    type: "womens",
    default_color: "Battleship Grey",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 48.00 },
      Medium: { price: 48.00 },
      Large: { price: 48.00 },
      XLarge: { price: 48.00 },
      "2XLarge": { price: 49.70 },
      "3XLarge": { price: 53.00 },
      "4XLarge": { price: 54.70 },      
   },
  },                  
  {
    code: "MCDONALD-PFRAMEI",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "MCDONALD-MFRAMEI",
    name: "Black Metal Frame",
    fullname: "Black Powder Coated Zinc Metal Frame w/ white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 1.99,
      },
    },
  },
  {
    code: "MCDONALD-CPMO",
    name: "Chrome Plastic Nameplate",
    fullname: "Chrome-Plated Plastic Nameplates",
    colors: ["Chrome"],
    type: "customs",
    default_color: "Chrome",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.49,
      },
    },
  },
  {
    code: "MCDONALD-BPMO",
    name: "Black Plastic Nameplate",
    fullname: "Black Plastic Nameplates",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.49,
      },
    },
  },
  {
    code: "MCDONALD-33GT",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "GENOLI-33P-513164A",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "AUDPCO-33GT-513166Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },  
  {
    code: "MCDADE-33GT-513167Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "POLDEN-33GT-513165Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },  
  {
    code: "MCDMLA-33GT-513170Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "MCDMLO-33GT-513168Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  }, 
  {
    code: "MCDMLI-33GT-513169Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [500],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },   
  {
    code: "MCDHLI-33GT-513176Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "MCDNHI-33GT-513172Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "MCDTCO-33GT-513173Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "MCDVLI-33GT-513174Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "MCDVLT-33GT-513175Z",
    name: ".20 Gauge Plastic Plate",
    fullname: ".20 Gauge White Plastic Plate (4CP)",
    colors: ["White"],
    type: "customs",
    default_color: "White",    
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 0.50,
      },
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",    
    pricing: {
      base: {
        price: 46.00,
      },
    },
  },
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    pricing: {
      base: {
        price: 48.00,
      },
    },
  },
  {
    code: "SDNRG",
    name: "Service Hang Numbers",
    fullname: "Service Hang Numbers (1000/bx)",
    colors: ["White"],
    variations: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000", 
      "9000",
    ],  
    type: "service",
    default_color: "white",        
    pricing: {
      base: {
        price: 51.00,
      },
    },
  },
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250/pk)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",      
    pricing: {
      base: {
        price: 6.95,
      },
    },
  },
  {
    code: "55-010",
    name: "Steering Wheel Covers",
    fullname: "Steering Wheel Covers (500/bx)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    pricing: {
      base: {
        price: 51.99,
      },
    },
  },
  {
    code: "EIT50",
    name: "Self-Locking Key Tags",
    fullname: "Self-Locking Key Tags (1000/pk)",
    colors: [
      "Blue",
      "Green",
      "Orange",
      "Red",
      "Yellow",
      "White",
    ],
    type: "service",
    default_color: "Blue",
    pricing: {
      base: {
        price: 19.99,
      },
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Self-Protecting Key Tags #200 (250 per box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",    
    pricing: {
      base: {
        price: 19.99,
      },
    },
  }, 
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100 per pack)",
    colors: [
      "Blue", 
      "Green", 
      "Orange", 
      "Red", 
      "White", 
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",    
    pricing: {
      base: {
        price: 9.99,
      },
    },
  }, 
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain (500/box)",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "office",
    default_color: "Blue",
    pricing: {
      base: {
        price: 89.99,
      },
    },
  },
  {
    code: "GP790",
    name: "Not for Sale Sticker",
    fullname: "Vehicle Not for Sale Sticker (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",   
    pricing: {
      base: {
        price: 24.99,
      },
    },
  }, 
  {
    code: "3198WB",
    name: "Oval Year Stickers - Blue",
    fullname: "Oval Year Stickers - Blue/White (12/pk)",
    colors: ["Blue"],
    variations: [
      "2007",
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",      
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Blue",
    pricing: {
      base: {
        price: 2.99,
      },
   },
  }, 
  {
    code: "3198SB",
    name: "Oval Year Stickers - Silver",
    fullname: "Oval Year Stickers - Silver/Black (12/pk)",
    colors: ["Silver"],
    variations: [
      "2010",
      "2011",
      "2012",
      "2013",
      "2014",
      "2015",
      "2016", 
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024", 
      "2025",
      "2026",
    ],   
    type: "sales",
    default_color: "Silver",    
    pricing: {
      base: {
        price: 2.99,
      },
    },
  },
  {
    code: "3198BY",
    name: "Oval Year Stickers - Yellow",
    fullname: "Oval Year Stickers - Yellow/Black (12/pk)",
    colors: ["Yellow"],
    variations: [
      "2008",
      "2009",
      "2010",
      "2011",
      "2012",
      "2013",
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023",
      "2024",
      "2025",
      "2026",
    ],
    type: "sales",
    default_color: "Yellow",
    pricing: {
      base: {
        price: 2.99,
      },
    },
  },
  {
    code: "BOW30",
    name: "30 in. Giant Bow",
    fullname: "30 in. Giant Magnetic Car Bow (sold in pairs)",
    colors: [
      "Blue",
      "Gold",
      "Green",
      "Patriotic",
      "Pink",
      "Red",
      "Silver",
      "White",
      "Red Grn"
    ],
    halfColors: ["Red Grn"],
    type: "sales",
    default_color: "Blue",   
    pricing: {
      base: {
        price: 32.99,
      },
    },
  },  
]