export const catalog = [
  {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo #NKDC1991",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
    colors: ["Black","Game Royal","White"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge"
    ],
    pricing: {
      Small: { price: 38.79 },
      Medium: { price: 38.79 },
      Large: { price: 38.79 },
      XLarge: { price: 38.79 },
      "2XLarge": { price: 40.29 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Black", "Game Royal", "White"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 38.79 },
      Medium: { price: 38.79 },
      Large: { price: 38.79 },
      XLarge: { price: 38.79 },
      "2XLarge": { price: 40.29 },
      "3XLarge": { price: 43.29 },
      "4XLarge": { price: 45.29 },     
    },
  },
  {
    code: "NKDC2104",
    name: "Nike Long Sleeve Polo",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Long Sleeve Polo",
    colors: ["Black", "Game Royal", "White"],
    type: "mens",
    default_color: "Black",
    sizes: [
    "Small", 
    "Medium", 
    "Large", 
    "XLarge", 
    "2XLarge", 
    "3XLarge", 
    "4XLarge"
],
    pricing: {
      Small: { price: 45.00 },
      Medium: { price: 45.00 },
      Large: { price: 45.00 },
      XLarge: { price: 45.00 },
      "2XLarge": { price: 45.00 },
      "3XLarge": { price: 45.00 },
      "4XLarge": { price: 45.00 },
    },
  },
  {
    code: "NKDC2105",
    name: "Nike Long Sleeve Polo",
    fullname: "Nike Women's Dri-FIT Micro Pique 2.0 Long Sleeve Polo",
    colors: ["Black", "Game Royal", "White"],
    type: "womens",
    default_color: "Black",
    sizes: [
    "Small", 
    "Medium", 
    "Large", 
    "XLarge", 
    "2XLarge"
],
    pricing: {
      Small: { price: 45.00 },
      Medium: { price: 45.00},
      Large: { price: 45.00 },
      XLarge: { price: 45.00 },
      "2XLarge": { price: 45.00 },
    },
  },
  {
    code: "NKBV6044",
    name: "Nike® 1/2-Zip Cover-Up #NKBV6044",
    fullname: "Nike® Dry 1/2-Zip Cover-Up (NKBV6044)",
    colors: ["Black", "Gym Blue"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 76.99 },
      Medium: { price: 76.99 },
      Large: { price: 76.99 },
      XLarge: { price: 76.99 },
      "2XLarge": { price: 77.99 },
      "3XLarge": { price: 78.99 },
      "4XLarge": { price: 79.99 },
    },
  },  
];