export const catalog = [
  {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo #NKDC1991",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo (NKDC1991)",
    colors: ["Black","University Red","White"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge"
    ],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 44.99 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Black", "University Red", "White"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 44.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 46.99 },     
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black","Rich Red", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 44.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 46.99 },
      "5XLarge": { price: 47.99 },
      "6XLarge": { price: 48.99 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket (L317)",
    colors: ["Black","Rich Red","True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 42.99 },
      Medium: { price: 42.99 },
      Large: { price: 42.99 },
      XLarge: { price: 42.99 },
      "2XLarge": { price: 44.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 46.99 },
    },
  },
];