export const catalog = [
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    pricing: {
      base: {
        price: 0.0,
      },
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 0.0,
      },
    },
  },
  {
    code: "K110",
    name: "Port Authority UV Polo",
    fullname: "Port Authority® Dry Zone® UV Micro-Mesh Polo",
    colors: ["Deep Black", "Graphite", "True Royal"],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      Small: { price: 8.24 },
      Medium: { price: 8.24 },
      Large: { price: 8.24 },
      XLarge: { price: 8.24 },
      "2XLarge": { price: 9.21 },
      "3XLarge": { price: 11.15 },
      "4XLarge": { price: 12.12 },
      "5XLarge": { price: 14.06 },
      "6XLarge": { price: 15.03 },
    },
  },
  {
    code: "LK110",
    name: "Port Authority UV Polo",
    fullname: "Port Authority® Women's Dry Zone® UV Micro-Mesh Polo",
    colors: ["Deep Black", "Graphite", "True Royal"],
    type: "womens",
    default_color: "Deep Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge",
    ],
    pricing: {
      Small: { price: 8.24 },
      Medium: { price: 8.24 },
      Large: { price: 8.24 },
      XLarge: { price: 8.24 },
      "2XLarge": { price: 9.21 },
      "3XLarge": { price: 11.15 },
      "4XLarge": { price: 12.12 },
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek Competitor Tee",
    fullname: "Sport-Tek® PosiCharge® Competitor™ Tee",
    colors: ["Black", "Iron Grey"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 0.0 },
      Medium: { price: 0.0 },
      Large: { price: 0.0 },
      XLarge: { price: 0.0 },
      "2XLarge": { price: 0.0 },
      "3XLarge": { price: 0.0 },
      "4XLarge": { price: 0.0 },
    },
  },
  {
    code: "C402",
    name: "Port Authority Trucker Cap",
    fullname: "Port Authority® Snapback Trucker Cap",
    colors: ["Black White"],
    type: "mens",
    default_color: "Black White",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 0.0 },
    },
  },
];