export const catalog = [
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Sport-Wick Polo",
    colors: ["Black", "Iron Grey", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 22.99 },
      Medium: { price: 22.99 },
      Large: { price: 22.99 },
      XLarge: { price: 22.99 },
      "2XLarge": { price: 24.98 },
      "3XLarge": { price: 28.98 },
      "4XLarge": { price: 30.98 },
      "5XLarge": { price: 34.98 },
      "6XLarge": { price: 36.98 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick Polo",
    colors: ["Black", "Iron Grey", "White"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 22.99 },
      Medium: { price: 22.99 },
      Large: { price: 22.99 },
      XLarge: { price: 22.99 },
      "2XLarge": { price: 24.98 },
      "3XLarge": { price: 28.98 },
      "4XLarge": { price: 30.98 },
    },
  },
  {
    code: "TST650",
    name: "Sport-Tek® Tall Polo Shirt",
    fullname: "Sport-Tek® Tall Micropique Sport-Wick Polo",
    colors: ["Black", "Iron Grey", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
      LT: { price: 24.98 },
      XLT: { price: 26.98 },
      "2XLT": { price: 28.98 },
      "3XLT": { price: 30.98 },
      "4XLT": { price: 32.98 },
    },
  },
  {
    code: "ST657",
    name: "Sport-Tek® Long Sleeve Polo Shirt",
    fullname: "Sport-Tek® Long Sleeve Sport-Wick Polo",
    colors: ["Black", "Iron Grey", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 26.99 },
      Medium: { price: 26.99 },
      Large: { price: 26.99 },
      XLarge: { price: 26.99 },
      "2XLarge": { price: 28.99 },
      "3XLarge": { price: 29.99 },
      "4XLarge": { price: 31.99 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike® Dri-FIT Micropique 2.0 Polo",
    colors: ["Anthracite", "Black", "University Red", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 40.99 },
      LT: { price: 40.99 },
      XLT: { price: 42.99 },
      "2XLT": { price: 43.99 },
      "3XLT": { price: 44.99 },
      "4XLT": { price: 45.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo",
    fullname: "Nike® Women's Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Anthracite", "Black", "University Red", "White"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 37.99 },
      Medium: { price: 37.99 },
      Large: { price: 37.99 },
      XLarge: { price: 37.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 40.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 37.99 },
      Medium: { price: 37.99 },
      Large: { price: 37.99 },
      XLarge: { price: 37.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 40.99 },
      "5XLarge": { price: 41.99 },
      "6XLarge": { price: 42.99 },
    },
  },
  {
    code: "K805",
    name: "Port Authority® 1/4-Zip Pullover",
    fullname: "Port Authority® 1/4-Zip Pullover",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 30.99 },
      Medium: { price: 30.99 },
      Large: { price: 30.99 },
      XLarge: { price: 30.99 },
      "2XLarge": { price: 32.99 },
      "3XLarge": { price: 33.99 },
      "4XLarge": { price: 34.99 },
      "5XLarge": { price: 35.99 },
      "6XLarge": { price: 36.99 },
    },
  },
  {
    code: "L805",
    name: "Port Authority® 1/4-Zip Pullover",
    fullname: "Port Authority Women's Vertical Texture Full-Zip Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 30.99 },
      Medium: { price: 30.99 },
      Large: { price: 30.99 },
      XLarge: { price: 30.99 },
      "2XLarge": { price: 32.99 },
      "3XLarge": { price: 33.99 },
      "4XLarge": { price: 34.99 },
    },
  },
];