export const catalog = [
    {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Lime Shock",
      "Maroon",
      "Purple",
      "Texas Orange",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "Vegas Gold",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
      "5XLarge": { price: 0.00 },
      "6XLarge": { price: 0.00 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Womens Micropique Polo",
    colors: [
      "Black",
      "Blue Lake",
      "Deep Orange",
      "Deep Red",
      "Forest Green",
      "Gold",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Light Pink",
      "Lime Shock",
      "Maroon",
      "Pink Raspberry",
      "Purple",
      "Tropic Blue",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 0.00 },
      Medium: { price: 0.00 },
      Large: { price: 0.00 },
      XLarge: { price: 0.00 },
      "2XLarge": { price: 0.00 },
      "3XLarge": { price: 0.00 },
      "4XLarge": { price: 0.00 },
    },
  },
];