export const catalog = [
    {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Micropique Polo (ST650)",
    colors: [
      "Black",   
      "Deep Red",
      "Forest Green",      
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",  
      "Purple",      
      "True Navy",
      "True Red",      
      "True Royal",
      "Vegas Gold",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge", 
      "5XLarge", 
      "6XLarge",
    ],
    pricing: {
      XSmall: { price: 26.99 },
      Small: { price: 26.99 },
      Medium: { price: 26.99 },
      Large: { price: 26.99 },
      XLarge: { price: 26.99 },
      "2XLarge": { price: 28.99 },
      "3XLarge": { price: 32.99 },
      "4XLarge": { price: 34.99 },
      "5XLarge": { price: 37.99 },
      "6XLarge": { price: 39.25 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt #LST650",
    fullname: "Sport-Tek® Womens Micropique Polo (LST650)",
    colors: [
      "Black",   
      "Deep Red",
      "Forest Green",      
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Pink Raspberry",  
      "Purple",      
      "True Navy",
      "True Red",      
      "True Royal",      
      "White",
    ],
    type: "womens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: { price: 26.99 },
      Small: { price: 26.99},
      Medium: { price: 26.99 },
      Large: { price: 26.99 },
      XLarge: { price: 26.99 },
      "2XLarge": { price: 28.99 },
      "3XLarge": { price: 32.99 },
      "4XLarge": { price: 34.99 },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
      "Anthracite",
      "Black",      
      "Cool Grey",
      "Court Purple",      
      "Game Royal",
      "Gorge Green",
      "Gym Blue",     
      "Navy",     
      "University Red",
      "Urban Lilac",
      "Valor Blue",
      "Varsity Maize",
      "Vivid Pink",
      "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: { price: 49.99 },
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 51.99 },
      "3XLarge": { price: 55.99 },
      "4XLarge": { price: 57.99 },
    },
  },
  {
    code: "NKDC1963T",
    name: "Nike® Dri-FIT- TALL #NKDC1963T",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo - TALL SIZES (NKDC1963T)",
    colors: [
      "Anthracite",
      "Black",
      "Cool Grey",
      "Game Royal",
      "Gym Blue",
      "Navy",
      "University Red",
      "Valor Blue",
      "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
      LT: { price: 57.99 },
      XLT: { price: 57.99 },
      "2XLT": { price: 59.99 },
      "3XLT": { price: 61.99 },
      "4XLT": { price: 63.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo #NKDC1991",
    fullname: "Ladies Nike® Micro Pique Polo (NKDC1991)",
    colors: [
      "Anthracite",
      "Black",      
      "Cool Grey",
      "Court Purple",
      "Game Royal",
      "Gorge Green",
      "Gym Blue",      
      "Navy",
      "University Red",
      "Urban Lilac",
      "Valor Blue",
      "Varsity Maize",
      "Vivid Pink",
      "White",
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 49.99 },
      Medium: { price: 49.99 },
      Large: { price: 49.99 },
      XLarge: { price: 49.99 },
      "2XLarge": { price: 51.99 },
    },
  },
  {
    code: "L100",
    name: "Port Authority® Classic Polo #L100",
    fullname: "Port Authority® Women's Core Classic Pique Polo (L100)",
    colors: [
      "Bright Kelly Green",
      "Deep Black",
      "Deep Forest Green",
      "Graphite",
      "Gusty Grey",
      "Pink Azalea",
      "Rich Red",
      "River Blue Navy",
      "True Royal",
      "White",
    ],
    type: "womens",
    default_color: "Bright Kelly Green",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      XSmall: {price: 18.99 },
      Small: { price: 18.99 },
      Medium: { price: 18.99 },
      Large: { price: 18.99 },
      XLarge: { price: 18.99 },
      "2XLarge": { price: 20.99 },
      "3XLarge": { price: 24.99 },
      "4XLarge": { price: 26.99 },
      "5XLarge": { price: 29.99 },
      "6XLarge": { price: 31.25 },
    },
  },
  {
    code: "T474",
    name: "Sport-Tek® Dri-Mesh® Polo #T474",
    fullname: "Sport-Tek® Dri-Mesh® Pro Polo (T474)",
    colors: [
      "Black",
      "Engine Red",
      "Dark Green",
      "Navy",
      "Royal",
      "Steel",
      "White",      
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 33.99 },
      Small: { price: 33.99 },
      Medium: { price: 33.99 },
      Large: { price: 33.99 },
      XLarge: { price: 33.99 },
      "2XLarge": { price: 35.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 41.99 },      
    },
  },
  {
    code: "L474",
    name: "Sport-Tek® Dri-Mesh® Polo #L474",
    fullname: "Sport-Tek® Women's Dri-Mesh® Pro Polo (L474)",
    colors: [
      "Black",
      "Engine Red",
      "Dark Green",
      "Navy",
      "Pink Raspberry",
      "Royal",
      "Steel",
      "White",      
    ],
    type: "womens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 33.99 },
      Small: { price: 33.99 },
      Medium: { price: 33.99 },
      Large: { price: 33.99 },
      XLarge: { price: 33.99 },
      "2XLarge": { price: 35.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 41.99 },      
    },
  },  
  {
    code: "ST520",
    name: "Sport-Tek® Posi-UV® Polo #ST520",
    fullname: "Sport-Tek® Posi-UV® Pro Polo (ST520)",
    colors: [
      "Black",   
      "Dark Smoke Grey", 
      "Forest Green",  
      "True Navy",
      "True Red",
      "True Royal",           
      "White",  
   ],
    type: "mens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 19.99},
      Small: { price: 19.99 },
      Medium: { price: 19.99 },
      Large: { price: 19.99 },
      XLarge: { price: 19.99 },
      "2XLarge": { price: 21.99 },
      "3XLarge": { price: 25.99 },
      "4XLarge": { price: 27.99 },
    },
  },
  {
    code: "ST520LS",
    name: "Sport-Tek® Long Sleeve Polo #ST520LS",
    fullname: "Sport-Tek® Posi-UV® Pro Long Sleeve Polo (ST520LS)",
    colors: [
      "Black",   
      "Dark Smoke Grey", 
      "Forest Green",  
      "True Navy",
      "True Red",
      "True Royal",           
      "White",  
   ],
    type: "mens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 23.99},
      Small: { price: 23.99 },
      Medium: { price: 23.99 },
      Large: { price: 23.99 },
      XLarge: { price: 23.99 },
      "2XLarge": { price: 25.99 },
      "3XLarge": { price: 29.99 },
      "4XLarge": { price: 31.99 },
    },
  },
  {
    code: "LW701",
    name: "Port Authority® 3/4-Sleeve Blouse #LW701",
    fullname: "Port Authority® Women's 3/4-Sleeve Tunic Blouse (LW701)",
    colors: [
      "Black",   
      "Deep Olive", 
      "Ivory Chiffon",  
      "Misty Sage",
      "Rose Quartz",
      "Sterling Grey",
      "True Blue",
      "True Navy",          
    ],
    type: "womens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 36.99},
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 42.99 },
      "4XLarge": { price: 44.99 },
    },
  },
  {
    code: "ST357",
    name: "Sport-Tek® 1/4-Zip Pullover #ST357",
    fullname: "Sport-Tek® PosiCharge® Competitor™ 1/4-Zip Pullover (ST357)",
    colors: [
      "Black",   
      "Deep Red",
      "Grey Concrete",      
      "Iron Grey",       
      "True Navy",
      "True Red",           
      "True Royal",
      "White",  
   ],
    type: "mens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 19.99 },
      Small: { price: 19.99 },
      Medium: { price: 19.99 },
      Large: { price: 19.99 },
      XLarge: { price: 19.99 },
      "2XLarge": { price: 21.99 },
      "3XLarge": { price: 25.99 },
      "4XLarge": { price: 27.99 },
    },
  },
  {
    code: "LST357",
    name: "Sport-Tek® 1/4-Zip Pullover #LST357",
    fullname: "Sport-Tek® Women's PosiCharge® Competitor™ 1/4-Zip Pullover (LST357)",
    colors: [
      "Black", 
      "Grey Concrete",      
      "Iron Grey",       
      "True Navy",
      "True Red",           
      "True Royal",
      "White",  
   ],
    type: "womens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: {price: 19.99 },
      Small: { price: 19.99 },
      Medium: { price: 19.99 },
      Large: { price: 19.99 },
      XLarge: { price: 19.99 },
      "2XLarge": { price: 21.99 },
      "3XLarge": { price: 25.99 },
      "4XLarge": { price: 27.99 },
    },
  },
  {
    code: "ST860",
    name: "Sport-Tek® 1/4-Zip Pullover #ST860",
    fullname: "Sport-Tek® Sport-Wick® Textured 1/4-Zip Pullover (ST860)",
    colors: [
      "Black",   
      "Deep Red",      
      "Iron Grey",       
      "True Navy",           
      "True Royal",  
   ],
    type: "mens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: { price: 39.99 },
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 41.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 47.99 },
    },
  },
  {
    code: "LST860",
    name: "Sport-Tek® 1/4-Zip Pullover #LST860",
    fullname: "Sport-Tek® Women's Sport-Wick® Textured 1/4-Zip Pullover (LST860)",
    colors: [
      "Black",   
      "Deep Red",      
      "Iron Grey",       
      "True Navy",
      "True Royal",           
      "Pink Raspberry",  
   ],
    type: "womens",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: { price: 39.99 },
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 41.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 47.99 },
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee #ST350",
    fullname: "Sport-Tek PosiCharge Competitor Tee (ST350)",
    description: '*Up to size 4XL only: Forest Green, Kelly Green, Neon Pink, Purple',
    colors: [
      "Black",   
      "Forest Green",
      "Grey Concrete",
      "Iron Grey",
      "Kelly Green",
      "Neon Pink",           
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "tshirts",
    default_color: "Black",
    sizes: [
      "XSmall",
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge",
      "5XLarge",
      "6XLarge",
    ],
    pricing: {
      XSmall: {price: 11.25 },
      Small: { price: 11.25 },
      Medium: { price: 11.25 },
      Large: { price: 11.25 },
      XLarge: { price: 11.25 },
      "2XLarge": { price: 13.25 },
      "3XLarge": { price: 17.25 },
      "4XLarge": { price: 19.25 },
      "5XLarge": { price: 23.25 },
      "6XLarge": { price: 25.25 },
    },
  },
  {
    code: "ST350LS",
    name: "Sport-Tek® Long Sleeve Tee #ST350LS",
    fullname: "Sport-Tek® Long Sleeve PosiCharge® Competitor™ Tee (ST350LS)",
    colors: [
      "Black",   
      "Forest Green",
      "Grey Concrete",
      "Iron Grey",      
      "Neon Pink",           
      "Purple",
      "True Navy",
      "True Red",
      "True Royal",
      "White",
    ],
    type: "tshirts",
    default_color: "Black",
    sizes: ["XSmall","Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      XSmall: { price: 13.25 },
      Small: { price: 13.25 },
      Medium: { price: 13.25 },
      Large: { price: 13.25 },
      XLarge: { price: 13.25 },
      "2XLarge": { price: 15.25 },
      "3XLarge": { price: 18.25 },
      "4XLarge": { price: 20.25 },
    },
  },
  {
    code: "DOWCHA-34PEU-431961A",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    supportedStores: ["DOWCHA"],
    default_color: "Black",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .75,
        discount: {
          2500: .65,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "ROSBHA-34CF-492025A",
    name: "Chrome Faced Frame",
    fullname: "Chrome Faced Plastic Frame",
    colors: ["Chrome Faced"],
    type: "customs",
    supportedStores: ["ROSBHA"],
    default_color: "Chrome Faced",    
    quantities: [500, 1000, 2500],
    pricing: {
      base: {
        price: 1.40,
        discount: {
          1000: 1.39,
          2500: 1.36,
        }, 
      },
    },
  },
  {
    code: "DOWCHA-33P-432413B",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge White Plastic Plate w/534 blue & 186 red",
    colors: ["White"],
    type: "customs",
    supportedStores: ["DOWCHA"],
    default_color: "White",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .70,
        discount: {
          2500: .63,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "ROSBHA-33GT-506328Z",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge White Plastic Plate w/full color imprint",
    colors: ["White"],
    type: "customs",
    supportedStores: ["ROSBHA"],
    default_color: "White",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .70,
        discount: {
          2500: .63,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "DOWDHA-33GT-492348Z",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge 4CP White Plastic Plate",
    colors: ["White"],
    type: "customs",
    supportedStores: ["DOWDHA"],
    default_color: "White",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .70,
        discount: {
          2500: .63,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "DOWCMO-33GT-518391Z",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge 4CP White Plastic Plate",
    colors: ["White"],
    type: "customs",
    supportedStores: ["DOWCMO"],
    default_color: "White",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .70,
        discount: {
          2500: .63,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "DOWBGO-33GT-506329Z",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge 4CP White Plastic Plate",
    colors: ["White"],
    type: "customs",
    supportedStores: ["DOWBGO"],
    default_color: "White",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .70,
        discount: {
          2500: .63,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "ROSBHA-33GT-506328Z",
    name: ".15 Gauge Plastic Plate",
    fullname: ".15 Gauge 4CP White Plastic Plate",
    colors: ["White"],
    type: "customs",
    supportedStores: ["ROSBHA"],
    default_color: "White",    
    quantities: [1500, 2500, 5000],
    pricing: {
      base: {
        price: .70,
        discount: {
          2500: .63,
          5000: .60,
        }, 
      },
    },
  },
  {
    code: "DOWCHA-31DD-520514A",
    name: "Block Decal - White",
    fullname: "Block Decal (White - No Outline) - 5 in. x .5125 in.",
    description: 'Grey does not print.',
    colors: ["White"],
    type: "customs",
    supportedStores: ["DOWCHA"],
    default_color: "White",    
    quantities: [1000, 2500, 5000],
    pricing: {
      base: {
        price: .60,
        discount: {
          2500: .55,
          5000: .50,
        }, 
      },
    },
  },
  {
    code: "DOWCHA-31DD-491422A",
    name: "Block Decal - Black",
    fullname: "Block Decal (Black - No Outline) - 5 in. x .5125 in.",
    colors: ["Black"],
    type: "customs",
    supportedStores: ["DOWCHA"],
    default_color: "Black",    
    quantities: [1000, 2500, 5000],
    pricing: {
      base: {
        price: .60,
        discount: {
          2500: .55,
          5000: .50,
        }, 
      },
    },
  },
  {
    code: "DOWCHA-31DD-433238A",
    name: "Cursive Decal - Black",
    fullname: "Black Cursive Decal - 8.5 in. x 1.41 in.",
    colors: ["Black"],
    type: "customs",
    supportedStores: ["DOWCHA"],
    default_color: "Black",    
    quantities: [1000, 2500, 5000],
    pricing: {
      base: {
        price: .60,
        discount: {
          2500: .55,
          5000: .50,
        }, 
      },
    },
  },
];