export const catalog = [
  {
    code: "NKFB6448",
    name: "Nike Mesh Back Cap #NKFB6448",
    fullname: "Nike Stretch-to-Fit Mesh Back Cap",
    colors: [
      "Anthr White",
      "Blk Blk",
      "Blk Game Royal",
      "Blk White",
      "Cool Grey White",
      "Gym Blue White",
      "Navy White",
      "Team Red White",
      "White White",
    ],
    type: "hat",
    default_color: "Blk Blk",
    sizes: ["S_M", "M_L", "L_XL"],
    pricing: {
      S_M: { price: 30.0 },
      M_L: { price: 30.0 },
      L_XL: { price: 30.0 },
    },
  },
  {
    code: "STC38",
    name: "Sport-Tek Trucker Cap #STC38",
    fullname: "Sport-Tek® YP Classics® 5-Panel Trucker Mesh Back Cap",
    colors: [
      "Blk Blk",
      "Blk White",
      "Graphite Graphite",
      "Graphite White",
      "Heather Grey Black",
      "Heather Grey White",
      "Silver Black",
      "True Navy True Navy",
      "True Navy White",
      "True Red White",
      "True Royal White",
      "White Black Black",
      "White True Navy",
    ],
    type: "hat",
    default_color: "Blk Blk",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 9.00 },
    },
  },
  {
    code: "C402",
    name: "Port Authority Trucker Cap #C402",
    fullname: "Port Authority® Snapback Trucker Cap",
    colors: [
      "Black",
      "Black GreySteel",
      "Black Tan",
      "Black White",
      "FlameRed White",
      "Grey Steel",
      "Gusty Grey",
      "LightKhaki White",
      "Olive Drab Green",
      "Patriot Blue",
      "PatriotBlue White",
      "True Navy",
      "TruePink White",
      "Woodland Camo",
    ],
    type: "hat",
    default_color: "Black",
    halfColors: [
      'Black GreySteel',
      'Black Tan',
      'Black White',
      'FlameRed White',
      'LightKhaki White',
      'PatriotBlue White',
      'TruePink White',
    ],
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 15.99 },
    },
  }, 
  {
    code: "PC55",
    name: "Port & Company Blend Tee #PC55",
    fullname: "Port & Company Core Blend Tee",
    colors: ["Charcoal", "Jet Black", "Navy"],
    type: "mens",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 11.99 },
      Medium: { price: 11.99 },
      Large: { price: 11.99 },
      XLarge: { price: 11.99 },
      "2XLarge": { price: 13.99 },
      "3XLarge": { price: 14.99 },
      "4XLarge": { price: 15.99 },
      "5XLarge": { price: 16.99 },
      "6XLarge": { price: 17.99 },
    },
  },
  {
    code: "PC61",
    name: "Port & Company Tee #PC61",
    fullname: "Port & Company Essential Tee",
    colors: ["Candy Pink", "Charcoal", "Jet Black", "Medium Grey", "Navy"],
    type: "mens",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 8.99 },
      Medium: { price: 8.99 },
      Large: { price: 8.99 },
      XLarge: { price: 8.99 },
      "2XLarge": { price: 10.99 },
      "3XLarge": { price: 11.99 },
      "4XLarge": { price: 12.99 },
      "5XLarge": { price: 13.99 },
      "6XLarge": { price: 15.99 },
    },
  },
  {
    code: "PC61P",
    name: "Port & Comp Pocket Tee #PC61P",
    fullname: "Port & Company Essential Pocket Tee",
    colors: ["Charcoal", "Jet Black", "Navy"],
    type: "mens",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 10.99 },
      Medium: { price: 10.99 },
      Large: { price: 10.99 },
      XLarge: { price: 10.99 },
      "2XLarge": { price: 12.99 },
      "3XLarge": { price: 13.99 },
      "4XLarge": { price: 14.99 },
    },
  },
  {
    code: "PC380",
    name: "Port & Co Perf Tee #PC380",
    fullname: "Port & Company Performance Tee",
    colors: ["Deep Navy"],
    type: "mens",
    sub_category: "tshirt",
    default_color: "Deep Navy",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 8.99 },
      Medium: { price: 8.99 },
      Large: { price: 8.99 },
      XLarge: { price: 8.99 },
      "2XLarge": { price: 9.99 },
      "3XLarge": { price: 10.99 },
      "4XLarge": { price: 11.99 },
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee #ST350",
    fullname: "Sport-Tek PosiCharge Competitor Tee",
    colors: ["Black", "Iron Grey", "True Navy", "Neon Pink"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 12.99 },
      Medium: { price: 12.99 },
      Large: { price: 12.99 },
      XLarge: { price: 12.99 },
      "2XLarge": { price: 14.99 },
      "3XLarge": { price: 15.99 },
      "4XLarge": { price: 16.99 },
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Micropique Sport-Wick Polo",
    colors: [
      "Black",
      "True Royal",
      "Iron Grey",
      "Grey Concrete",
      "White",
      "True Navy",
      "Blue Lake",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 25.99 },
      "3XLarge": { price: 26.99 },
      "4XLarge": { price: 27.99 },
      "5XLarge": { price: 28.99 },
      "6XLarge": { price: 29.99 },
    },
  },
  {
    code: "TST650",
    name: "Sport-Tek® TALL Polo Shirt #TST650",
    fullname: "Sport-Tek® Tall Micropique Sport-Wick Polo",
    colors: [
      "Black",
      "True Royal",
      "Iron Grey",
      "Grey Concrete",
      "White",
      "True Navy",
      "Blue Lake",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
      LT: { price: 27.99 },
      XLT: { price: 28.99 },
      "2XLT": { price: 29.99 },
      "3XLT": { price: 31.99 },
      "4XLT": { price: 32.99 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt #LST650",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick Polo",
    colors: [
      "Black",
      "True Royal",
      "Iron Grey",
      "Grey Concrete",
      "White",
      "True Navy",
      "Blue Lake",
    ],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 25.99 },
      "3XLarge": { price: 26.99 },
      "4XLarge": { price: 27.99 },
      "5XLarge": { price: 28.99 },
      "6XLarge": { price: 29.99 },
    },
  },
  // {
  //   code: 'CP80',
  //   name: 'Twill Cap',
  //   fullname: 'Port & Company® Six-Panel Twill Cap',
  //   colors: ['Black', 'True Red', 'Navy', 'Hunter', 'Royal', 'Charcoal', 'Woodland Brown'],
  //   type: 'hat',
  //   default_color: 'Black',
  //   sizes: {
  //     'One Size Fits All': 14.29
  //   }
  // },
  {
    code: "04032",
    name: "20oz. Revolve Tumbler",
    fullname: "20 oz. Revolve Tumbler",
    colors: [
      "Black",
      "Blue",
      "Burgundy",
      "Green",
      "Navy",
      "Red",
      "Silver",
      "White",
    ],
    type: "accessory",
    default_color: "Black",
    sizes: ["20 oz."],
    pricing: {
      "20 oz.": { price: 14.99 },
    },
  },
  {
    code: "04015",
    name: "10oz. Perfect-Fit Tumbler",
    fullname: "10 oz. Perfect-Fit Tumbler",
    colors: ["Black", "Blue", "Burgundy", "Gunmetal", "Navy", "Red"],
    type: "accessory",
    default_color: "Black",
    sizes: ["10 oz."],
    pricing: {
      "10 oz.": { price: 12.99 },
    },
  },
  {
    code: "1640",
    name: "Logo Key Chain",
    fullname: "Brushed Zinc/Leather/Big Logo Key Chain",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    quantities: [1],
    pricing: {
      base: {
        price: 6.99,
      },
    },
  },
  {
    code: "1240",
    name: "Key Tag",
    fullname: "Zinc Strap Key Tag",
    colors: ["Grey"],
    type: "accessory",
    default_color: "Grey",
    quantities: [1],
    pricing: {
      base: {
        price: 6.99,
      },
    },
  },
  {
    code: "2240",
    name: "Key Chain",
    fullname: "Carbon Fiber Strap Metal Key Chain",
    colors: ["Grey"],
    type: "accessory",
    default_color: "Grey",
    quantities: [1],
    pricing: {
      base: {
        price: 6.99,
      },
    },
  },
  // {
  //   code: 'C402',
  //   name: 'Snapback',
  //   fullname: 'Port Authority® Snapback Trucker Cap',
  //   colors: ['Black', 'Navy', 'Black White', 'Patriot Royal', 'Red White', 'Royal White', 'Grey Steel', 'Pink White', 'Woodland Camo', 'Khaki White'],
  //   type: 'hat',
  //   halfColors: ['Black White', 'Red White', 'Royal White', 'Pink White', 'Khaki White'],
  //   default_color: 'Black',
  //   sizes: {
  //     'One Size Fits All': 14.29
  //   }
  // },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo Shirt",
    colors: [
        "Anthracite", 
        "Black", 
        "Blue Tint",
        "Brilliant Orange",
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gorge Green",
        "Gym Blue",
        "Lucid Green",
        "Mint",
        "Navy",
        "Team Red",
        "Tidal Blue",
        "University Red",
        "Urban Lilac",
        "Valor Blue",
        "Varsity Maize",
        "Vivid Pink",
        "White",      
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 43.99 },
      Medium: { price: 43.99 },
      Large: { price: 43.99 },
      XLarge: { price: 43.99 },
      "2XLarge": { price: 44.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 46.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1991",
    fullname: "Nike® Women's Dri-FIT Micro Pique Polo Shirt",
    colors: [
        "Anthracite", 
        "Black", 
        "Blue Tint",
        "Brilliant Orange",
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gorge Green",
        "Gym Blue",
        "Lucid Green",
        "Mint",
        "Navy",
        "Team Red",
        "Tidal Blue",
        "University Red",
        "Urban Lilac",
        "Valor Blue",
        "Varsity Maize",
        "Vivid Pink",
        "White",
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 43.99 },
      Medium: { price: 43.99 },
      Large: { price: 43.99 },
      XLarge: { price: 43.99 },
      "2XLarge": { price: 44.99 },
      "3XLarge": { price: 45.99 },
      "4XLarge": { price: 46.99 },
    },
  },
  {
    code: "CGW437",
    name: "Callaway Opti-Vent Polo #CGW437",
    fullname: "Callaway Ladies Opti-Vent Polo",
    colors: ["Peacoat", "Salsa", "White"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 44.99 },
      Medium: { price: 44.99 },
      Large: { price: 44.99 },
      XLarge: { price: 44.99 },
      "2XLarge": { price: 46.99 },
      "3XLarge": { price: 47.99 },
      "4XLarge": { price: 48.99 },
    },
  },
  {
    code: "CGM451",
    name: "Callaway Opti-Vent Polo #CGM451",
    fullname: "Callaway Opti-Vent Polo",
    colors: ["Peacoat", "Salsa", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 44.99 },
      Medium: { price: 44.99 },
      Large: { price: 44.99 },
      XLarge: { price: 44.99 },
      "2XLarge": { price: 46.99 },
      "3XLarge": { price: 47.99 },
      "4XLarge": { price: 48.99 },
    },
  },
  {
    code: "JST62",
    name: "Sport-Tek® V-Neck Wind Shirt #JST62",
    fullname: "Sport-Tek® Tipped V-Neck Raglan Wind Shirt",
    colors: ["Blk Graphite","Blk True Red","Black White","Graphite White","True Navy White","True Royal White"],
    type: "mens",
    default_color: "Blk Graphite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 28.96 },
      Medium: { price: 28.96 },
      Large: { price: 28.96 },
      XLarge: { price: 28.96 },
      "2XLarge": { price: 29.96 },
      "3XLarge": { price: 30.96 },
      "4XLarge": { price: 31.96 },
      "5XLarge": { price: 32.96 },
      "6XLarge": { price: 33.96 },
    },
  },
  {
    code: "L331",
    name: "Port Authority® Rain Jacket #L331",
    fullname: "Port Authority® All-Conditions Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 75.99 },
      Medium: { price: 75.99 },
      Large: { price: 75.99 },
      XLarge: { price: 75.99 },
      "2XLarge": { price: 76.99 },
      "3XLarge": { price: 77.99 },
      "4XLarge": { price: 78.99 },
    },
  },
  {
    code: "JST72",
    name: "Sport-Tek® V-Neck Wind Shirt #JST72",
    fullname: "Sport-Tek® Raglan Wind Shirt",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 25.99 },
      Medium: { price: 25.99 },
      Large: { price: 25.99 },
      XLarge: { price: 25.99 },
      "2XLarge": { price: 26.99 },
      "3XLarge": { price: 27.99 },
      "4XLarge": { price: 28.99 },
      "5XLarge": { price: 29.99 },
      "6XLarge": { price: 30.99 },
    },
  }, 
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Black", "Battleship Grey"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 44.99 },
      Medium: { price: 44.99 },
      Large: { price: 44.99 },
      XLarge: { price: 44.99 },
      "2XLarge": { price: 45.99 },
      "3XLarge": { price: 46.99 },
      "4XLarge": { price: 47.99 },
      "5XLarge": { price: 48.99 },
      "6XLarge": { price: 49.99 },
    },
  },
  {
    code: "K805",
    name: "Port Authority® 1/4-Zip Pullover #K805",
    fullname: "Port Authority® 1/4-Zip Pullover",
    colors: ["Black", "Regatta Blue", "True Navy", "Iron Grey"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 35.99 },
      Medium: { price: 35.99 },
      Large: { price: 35.99 },
      XLarge: { price: 35.99 },
      "2XLarge": { price: 36.99 },
      "3XLarge": { price: 37.99 },
      "4XLarge": { price: 38.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black", "Battleship Grey"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 44.99 },
      Medium: { price: 44.99 },
      Large: { price: 44.99 },
      XLarge: { price: 44.99 },
      "2XLarge": { price: 45.99 },
      "3XLarge": { price: 46.99 },
      "4XLarge": { price: 47.99 },
      "5XLarge": { price: 48.99 },
      "6XLarge": { price: 49.99 },
    },
  },
  {
    code: "J331",
    name: "Port Authority® Rain Jacket #J331",
    fullname: "Port Authority® All-Conditions Jacket",
    colors: ["Black","Direct Blue"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 75.99 },
      Medium: { price: 75.99 },
      Large: { price: 75.99 },
      XLarge: { price: 75.99 },
      "2XLarge": { price: 76.99 },
      "3XLarge": { price: 77.99 },
      "4XLarge": { price: 78.99 },
    },
  },
  {
    code: "L805",
    name: "Port Authority® Full-Zip Jacket #L805",
    fullname: "Port Authority® Women's Full-Zip Jacket",
    colors: ["Black", "Regatta Blue", "True Navy", "Iron Grey"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 35.99 },
      Medium: { price: 35.99 },
      Large: { price: 35.99 },
      XLarge: { price: 35.99 },
      "2XLarge": { price: 36.99 },
      "3XLarge": { price: 37.99 },
      "4XLarge": { price: 38.99 },
    },
  },
  {
    code: "STIFMO-STKR-462741B",
    name: "Vinyl Sticker w/QR code",
    fullname: "White Vinyl Sticker w/black & reflex blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFMO"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 0.59,
        discount: {
          5000: 0.49,
        }
      },
    },
  },
  {
    code: "STIFMO-31SD-433769B",
    name: "Chrome Stroke Domecal",
    fullname: "Chrome Stroke Domecal w/black & 294 blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFMO"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 1.39,
        discount: {
          5000: 1.25,
        }
      },
    },
  },
  {
    code: "STIFMO-33P-400001Z",
    name: "TAG APPLIED FOR Plate",
    fullname: "TAG APPLIED FOR plate w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFMO"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 0.87,
        discount: {
          5000: 0.79,
        }
      },
    },
  },
  {
    code: "STIFMO-33GT-410883Z",
    name: "Front Plastic Plate",
    fullname: "Plastic Plate w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFMO"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 0.87,
        discount: {
          5000: 0.79,
        }
      },
    },
  },
  {
    code: "STIFSO-THC-509701Z",
    name: "White Domecal",
    fullname: "White Domecal THC w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFSO"],
    quantities: [250, 500],
    pricing: {
      base: {
        price: 4.67,
        discount: {
          500: 3.99,
        }
      },
    },
  },
  {
    code: "STIFSO-NOTEPAD-509241Z",
    name: "Notepad - 4in. x 6in.",
    fullname: "Notepad w/full color imprint (25 sheets/pad)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFSO"],
    quantities: [500],
    pricing: {
      base: {
        price: 1.46,
      },
    },
  },
  {
    code: "STIFSO-CLIPBOARD-502574A",
    name: "Letter Clipboard w/imprint",
    fullname: "Round Top Clipboard w/reflex blue imprint (item #CB912RT)",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFSO"],
    quantities: [250, 500],
    pricing: {
      base: {
        price: 5.98,
        discount: {
          500: 5.79,
        }
      },
    },
  },
  {
    code: "STIFSO-RULER-502658A",
    name: "12 in. Ruler w/imprint",
    fullname: "Translucent Blue Ruler w/white imprint (item #RUL12)",
    colors: ["Blue"],
    type: "customs",
    default_color: "Blue",
    supportedStores: ["STIFSO"],
    quantities: [500],
    pricing: {
      base: {
        price: 1.26,
      },
    },
  },
  {
    code:"STIFSO-33GT-504866Z",
    name: "Drive Out Plate",
    fullname: "Plastic Drive Out Plate w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIFSO"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 0.92,
        discount: {
          5000: 0.85,
        }
      },
    },
  },
  {
    code:"STICPR-33GT-423219Z",
    name: "Drive Out Plate",
    fullname: "Plastic Drive Out Plate w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STICPR"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 0.85,
        discount: {
          5000: 0.79,
        }
      },
    },
  },
  {
    code:"STICPR-ADD101-441065Z",
    name: "Add Forms",
    fullname: "White Add Forms w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STICPR"],
    quantities: [500, 1000],
    pricing: {
      base: {
        price: 0.69,
        discount: {
          1000: 0.59,
        }
      },
    },
  },
  {
    code: "STICPR-31SD-423222A",
    name: "Chrome Stroke Domecal",
    fullname: "Chrome Stroke Domecal w/black imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STICPR"],
    quantities: [2500, 5000],
    pricing: {
      base: {
        price: 1.09,
        discount: {
          5000: 0.99,
        }
      },
    },
  },
  {
    code: "STIHCO-AT4C-436766Z",
    name: "Metal Plates",
    fullname: "White Aluminum Plate w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIHCO"],
    quantities: [500, 1000],
    pricing: {
      base: {
        price: 3.64,
        discount: {
          1000: 3.29,
        }
      },
    },
  },
  {
    code: "STIHCO-31SD-436768Z",
    name: "White Stroke Domecal",
    fullname: "White Stroke Domecal w/full color imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["STIHCO"],
    quantities: [500, 1000],
    pricing: {
      base: {
        price: 2.75,
        discount: {
          1000: 2.29,
        }
      },
    },
  },
];