export const catalog = [
  {
    code: "TAMHDA-33P3D-444019A",
    name: "Hard Front 3D Plates",
    fullname: "Hard Front 3D Plates",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.64,
        discount: {
          1000: 1.49,
          1500: 1.44,
          2500: 1.34,
        },
      },
    },
  },
  {
    code: "TAMHDA-33P-444017B",
    name: "Soft Drive Out Plates",
    fullname: "Soft Plates",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.84,
        discount: {
          1000: 0.65,
          1500: 0.59,
          2500: 0.54,
        },
      },
    },
  },
  {
    code: "TAMHDA-31DD-444021A",
    name: "Die Cut Decals",
    fullname: "Die Cut Decals",
    colors: ["Black", "White"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.79,
        discount: {
          1000: 0.59,
          1500: 0.54,
          2500: 0.49,
        },
      },
    },
  },
  {
    code: "TAMHDA-THC-444025B",
    name: "Trailer Hitch Covers",
    fullname: "Trailer Hitch Covers",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 3.79,
        discount: {
          500: 3.54,
          1000: 3.25,
        },
      },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
      Small: { price: 38.99 },
      Medium: { price: 38.99 },
      Large: { price: 38.99 },
      XLarge: { price: 38.99 },
      "2XLarge": { price: 40.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 42.99 },
      LT: { price: 42.99 },
      XLT: { price: 44.99 },
      "2XLT": { price: 45.99 },
      "3XLT": { price: 46.99 },
      "4XLT": { price: 47.99 },
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Micropique Sport-Wick Polo (ST650)",
    colors: ["Iron Grey", "True Red", "Black", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 26.99 },
      "3XLarge": { price: 28.99 },
      "4XLarge": { price: 30.99 },
      "5XLarge": { price: 32.99 },
      "6XLarge": { price: 34.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Core Soft Shell Jacket (J317)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 40.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 42.99 },
      "5XLarge": { price: 43.99 },
      "6XLarge": { price: 44.99 },
    },
  },
  {
    code: "J7710",
    name: "Port Authority® Slicker #J7710",
    fullname: "Port Authority® Northwest Slicker (J7710)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 60.99 },
      Medium: { price: 60.99 },
      Large: { price: 60.99 },
      XLarge: { price: 60.99 },
      "2XLarge": { price: 62.99 },
      "3XLarge": { price: 63.99 },
      "4XLarge": { price: 64.99 },
    },
  },
  {
    code: "L7710",
    name: "Port Authority® Slicker #L7710",
    fullname: "Port Authority® Ladies Northwest Slicker (L7710)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 60.99 },
      Medium: { price: 60.99 },
      Large: { price: 60.99 },
      XLarge: { price: 60.99 },
      "2XLarge": { price: 62.99 },
      "3XLarge": { price: 63.99 },
      "4XLarge": { price: 64.99 },
    },
  },
  {
    code: "MCK01086",
    name: "Cutter & Buck® 1/4-Zip #MCK01086",
    fullname: "Cutter & Buck® Eco Mens 1/4-Zip (MCK01086)",
    colors: ["Black", "Tour Blue"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 63.99 },
      Medium: { price: 63.99 },
      Large: { price: 63.99 },
      XLarge: { price: 63.99 },
      "2XLarge": { price: 64.50 },
      "3XLarge": { price: 64.99 },
      "4XLarge": { price: 65.50 },
    },
  },
  {
    code: "OE701",
    name: "OGIO® Fulcrum 1/4-Zip #OE701",
    fullname: "OGIO® Fulcrum 1/4-Zip (OE701)",
    colors: ["Blacktop"],
    type: "mens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 76.99 },
      Medium: { price: 76.99 },
      Large: { price: 76.99 },
      XLarge: { price: 76.99 },
      "2XLarge": { price: 77.99 },
      "3XLarge": { price: 78.99 },
      "4XLarge": { price: 79.99 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt #LST650",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick Polo (LST650)",
    colors: ["Iron Grey", "True Red", "Black", "True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 26.99 },
      "3XLarge": { price: 28.99 },
      "4XLarge": { price: 30.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo #NKDC1991",
    fullname: "Nike Women's Micro Pique 2.0 Polo (NKDC1991)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 38.99 },
      Medium: { price: 38.99 },
      Large: { price: 38.99 },
      XLarge: { price: 38.99 },
      "2XLarge": { price: 40.99 },
    },
  },
  {
    code: "LCK00151",
    name: 'Cutter & Buck® 1/4" Zip #LCK00151',
    fullname: 'Cutter & Buck® Eco Ladies 1/4" Zip (LCK00151)',
    colors: ["Black", "Tour Blue"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 63.99 },
      Medium: { price: 63.99 },
      Large: { price: 63.99 },
      XLarge: { price: 63.99 },
      "2XLarge": { price: 64.50 },
      "3XLarge": { price: 64.99 },
      "4XLarge": { price: 65.50 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket (L317)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 40.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 42.99 },
    },
  },
  {
    code: "CP91L",
    name: "Port & Company Beanie Cap #CP91L",
    fullname: "Port & Company Fleece-Lined Beanie Cap (CP91L)",
    colors: ["Black"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      "OSFA": { price: 10.99 },
    },
  },
  {
    code: "NE1100",
    name: "New Era Interception Cap #NE1100",
    fullname: "New Era Interception Cap (NE1100)",
    colors: ["Graphite_Black"],
    type: "hat",
    default_color: "Graphite_Black",
    halfColors: ['Graphite Black'],
    sizes: ["Small", "Medium", "Large"],
    pricing: {
      Small: { price: 14.99 },
      Medium: { price: 14.99 },
      Large: { price: 14.99 },
    },
  },
];