export const catalog = [
  {
    code: "TAMHDA-33P3D-444019A",
    name: "Hard Front 3D Plates",
    fullname: "Hard Front 3D Plates",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 1.59,
        discount: {
          1000: 1.44,
          1500: 1.39,
          2500: 1.29,
        },
      },
    },
  },
  {
    code: "TAMHDA-33P-444017B",
    name: "Soft Drive Out Plates",
    fullname: "Soft Plates",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.79,
        discount: {
          1000: 0.59,
          1500: 0.55,
          2500: 0.49,
        },
      },
    },
  },
  {
    code: "TAMHDA-31DD-444021A",
    name: "Die Cut Decals",
    fullname: "Die Cut Decals",
    colors: ["Black", "White"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [500, 1000, 1500, 2500],
    pricing: {
      base: {
        price: 0.79,
        discount: {
          1000: 0.49,
          1500: 0.54,
          2500: 0.49,
        },
      },
    },
  },
  {
    code: "TAMHDA-THC-444025B",
    name: "Trailer Hitch Covers",
    fullname: "Trailer Hitch Covers",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    supportedStores: ["TAMCDA","TAMBDA","TAMSMO","TAMHDA","TAMKDI","TAMNMO","TAMKWE","ONLINE"],
    quantities: [250, 500, 1000],
    pricing: {
      base: {
        price: 3.79,
        discount: {
          500: 3.54,
          1000: 3.25,
        },
      },
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike® Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "LT", "XLT", "2XLT", "3XLT", "4XLT"],
    pricing: {
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 40.99 },
      LT: { price: 40.99 },
      XLT: { price: 42.99 },
      "2XLT": { price: 43.99 },
      "3XLT": { price: 44.99 },
      "4XLT": { price: 45.99 },
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Micropique Sport-Wick Polo",
    colors: ["Iron Grey", "True Red", "Black", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 24.99 },
      Medium: { price: 24.99 },
      Large: { price: 24.99 },
      XLarge: { price: 24.99 },
      "2XLarge": { price: 26.99 },
      "3XLarge": { price: 28.99 },
      "4XLarge": { price: 30.99 },
      "5XLarge": { price: 32.99 },
      "6XLarge": { price: 34.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge", "5XLarge", "6XLarge"],
    pricing: {
      Small: { price: 37.99 },
      Medium: { price: 37.99 },
      Large: { price: 37.99 },
      XLarge: { price: 37.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 40.99 },
      "5XLarge": { price: 41.99 },
      "6XLarge": { price: 42.99 },
    },
  },
  {
    code: "J7710",
    name: "Port Authority® Slicker",
    fullname: "Port Authority® Northwest Slicker",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 58.98 },
      Medium: { price: 58.98 },
      Large: { price: 58.98 },
      XLarge: { price: 58.98 },
      "2XLarge": { price: 60.98 },
      "3XLarge": { price: 61.98 },
      "4XLarge": { price: 62.98 },
    },
  },
  {
    code: "L7710",
    name: "Port Authority® Slicker",
    fullname: "Port Authority® Ladies Northwest Slicker",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 58.98 },
      Medium: { price: 58.98 },
      Large: { price: 58.98 },
      XLarge: { price: 58.98 },
      "2XLarge": { price: 60.98 },
      "3XLarge": { price: 61.98 },
      "4XLarge": { price: 62.98 },
    },
  },
  {
    code: "MCK01086",
    name: "Cutter & Buck® 1/4-Zip",
    fullname: "Cutter & Buck® Eco Mens 1/4-Zip",
    colors: ["Black", "Tour Blue"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 59.99 },
      Medium: { price: 59.99 },
      Large: { price: 59.99 },
      XLarge: { price: 59.99 },
      "2XLarge": { price: 61.99 },
      "3XLarge": { price: 62.99 },
      "4XLarge": { price: 63.99 },
    },
  },
  {
    code: "OE701",
    name: "OGIO® Fulcrum 1/4-Zip",
    fullname: "OGIO® Fulcrum 1/4-Zip",
    colors: ["Blacktop"],
    type: "mens",
    default_color: "Blacktop",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 74.99 },
      Medium: { price: 74.99 },
      Large: { price: 74.99 },
      XLarge: { price: 74.99 },
      "2XLarge": { price: 75.99 },
      "3XLarge": { price: 76.99 },
      "4XLarge": { price: 77.99 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick Polo",
    colors: ["Iron Grey", "True Red", "Black", "True Royal"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 22.99 },
      Medium: { price: 22.99 },
      Large: { price: 22.99 },
      XLarge: { price: 22.99 },
      "2XLarge": { price: 24.99 },
      "3XLarge": { price: 26.99 },
      "4XLarge": { price: 27.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo",
    fullname: "Nike Women's Micro Pique 2.0 Polo",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 36.99 },
      Medium: { price: 36.99 },
      Large: { price: 36.99 },
      XLarge: { price: 36.99 },
      "2XLarge": { price: 38.99 },
    },
  },
  {
    code: "LCK00151",
    name: 'Cutter & Buck® 1/4" Zip',
    fullname: 'Cutter & Buck® Eco Ladies 1/4" Zip',
    colors: ["Black", "Tour Blue"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 59.99 },
      Medium: { price: 59.99 },
      Large: { price: 59.99 },
      XLarge: { price: 59.99 },
      "2XLarge": { price: 61.99 },
      "3XLarge": { price: 62.99 },
      "4XLarge": { price: 63.99 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Ladies Core Soft Shell Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 37.99 },
      Medium: { price: 37.99 },
      Large: { price: 37.99 },
      XLarge: { price: 37.99 },
      "2XLarge": { price: 38.99 },
      "3XLarge": { price: 39.99 },
      "4XLarge": { price: 40.99 },
    },
  },
  {
    code: "CP91L",
    name: "Port & Company Beanie Cap",
    fullname: "Port & Company Fleece-Lined Beanie Cap",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      "OSFA": { price: 10.99 },
    },
  },
  {
    code: "NE1100",
    name: "New Era Interception Cap",
    fullname: "New Era Interception Cap",
    colors: ["Graphite_Black"],
    type: "mens",
    default_color: "Graphite_Black",
    sizes: ["Small", "Medium", "Large"],
    pricing: {
      Small: { price: 13.98 },
      Medium: { price: 13.98 },
      Large: { price: 13.98 },
    },
  },
];