export const catalog = [
  {
    code: "L540",
    name: "Port Authority® Polo #L540",
    fullname: "Port Authority® Women's Silk Touch™ Performance Polo (L540)",
    colors: ["Black"],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge",      
    ],
    pricing: {
      Small: { price: 18.00 },
      Medium: { price: 18.00 },
      Large: { price: 18.00 },
      XLarge: { price: 18.00 },
      "2XLarge": { price: 18.00 },
      "3XLarge": { price: 18.00 },
      "4XLarge": { price: 18.00 },      
    },
  },
  {
    code: "K110",
    name: "Port Authority UV Polo #K110",
    fullname: "Port Authority® Dry Zone® UV Micro-Mesh Polo (K110)",
    colors: ["Deep Black"],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge", 
      "3XLarge", 
      "4XLarge", 
      "5XLarge", 
      "6XLarge"
    ],
    pricing: {
      Small: { price: 18.00 },
      Medium: { price: 18.00 },
      Large: { price: 18.00 },
      XLarge: { price: 18.00 },
      "2XLarge": { price: 18.00 },
      "3XLarge": { price: 18.00 },
      "4XLarge": { price: 18.00 },
      "5XLarge": { price: 18.00 },
      "6XLarge": { price: 18.00 },
    },
  },
  {
    code: "5000",
    name: "Gildan® 100% Cotton T-Shirt #5000",
    fullname: "Gildan® Heavy Cotton™ 100% Cotton T-Shirt (5000)",
    colors: ["Black"],      
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge", 
      "4XLarge",
      "5XLarge",         
    ],
    pricing: {
      Small: { price: 14.50 },
      Medium: { price: 14.50 },
      Large: { price: 14.50 },
      XLarge: { price: 14.50 },
      "2XLarge": { price: 14.50 },
      "3XLarge": { price: 14.50 },
      "4XLarge": { price: 14.50 },
      "5XLarge": { price: 14.50 },                
    },
  },
  {
    code: "K110LS",
    name: "Port Authority® Long Sleeve Polo #K110LS",
    fullname: "Port Authority® Dry Zone® UV Micro-Mesh Long Sleeve Polo (K110LS)",
    colors: ["Deep Black"],
    type: "mens",
    default_color: "Deep Black",
    sizes: [
      "Small",
      "Medium",
      "Large",
      "XLarge",
      "2XLarge",
      "3XLarge",
      "4XLarge"
    ],
    pricing: {
      Small: { price: 20.75 },
      Medium: { price: 20.75 },
      Large: { price: 20.75 },
      XLarge: { price: 20.75 },
      "2XLarge": { price: 20.75 },
      "3XLarge": { price: 20.75 },
      "4XLarge": { price: 20.75 },
    },
  },
  {
    code: "L540LS",
    name: "Port Authority® Polo #L540LS",
    fullname: "Port Authority Womens Long Sleeve Polo (L540LS)",
    colors: ["Black"],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"      
    ],
    pricing: {
      Small: { price: 24.00 },
      Medium: { price: 24.00 },
      Large: { price: 24.00 },
      XLarge: { price: 24.00 },
      "2XLarge": { price: 24.00 },
      "3XLarge": { price: 24.00 }, 
      "4XLarge": { price: 24.00 },          
    },
  },
 {
    code: "5400",
    name: "Gildan® Long Sleeve T-Shirt #5400",
    fullname: "Gildan® Heavy Cotton™ 100% Cotton Long Sleeve T-Shirt (5400)",
    colors: ["Black"],      
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",          
    ],
    pricing: {
      Small: { price: 18.00 },
      Medium: { price: 18.00 },
      Large: { price: 18.00 },
      XLarge: { price: 18.00 },
      "2XLarge": { price: 18.00 },
      "3XLarge": { price: 18.00 },                
    },
  },
  {
    code: "SF000",
    name: "Gildan® Crewneck Sweatshirt #SF000",
    fullname: "Gildan® Softstyle® Crewneck Sweatshirt (SF000)",
    colors: ["Black"],      
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"        
    ],
    pricing: {
      Small: { price: 23.00 },
      Medium: { price: 23.00 },
      Large: { price: 23.00 },
      XLarge: { price: 23.00 },
      "2XLarge": { price: 23.00 },
      "3XLarge": { price: 23.00 },
      "4XLarge": { price: 23.00 },                 
    },
  },
  {
    code: "PC590Q",
    name: "Port & Co™ 1/4-Zip Sweatshirt #PC590Q",
    fullname: "Port & Co™ Performance Fleece 1/4-Zip Pullover Sweatshirt (PC590Q)",
    colors: ["Jet Black"],      
    type: "mens",
    default_color: "Jet Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"        
    ],
    pricing: {
      Small: { price: 29.00 },
      Medium: { price: 29.00 },
      Large: { price: 29.00 },
      XLarge: { price: 29.00 },
      "2XLarge": { price: 29.00 },
      "3XLarge": { price: 29.00 },
      "4XLarge": { price: 29.00 },                 
    },
  },
  {
    code: "OE550",
    name: "OGIO® Radius 1/4-Zip #OE550",
    fullname: "OGIO® Radius 1/4-Zip (OE550)",
    colors: ["Blacktop"],      
    type: "mens",
    default_color: "Blacktop",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge"        
    ],
    pricing: {
      Small: { price: 49.00 },
      Medium: { price: 49.00 },
      Large: { price: 49.00 },
      XLarge: { price: 49.00 },
      "2XLarge": { price: 49.00 },
      "3XLarge": { price: 49.00 },
      "4XLarge": { price: 49.00 },                 
    },
  },
  {
    code: "88184",
    name: "Two-Layer Soft Shell Jacket #88184",
    fullname: "Core365 Cruise Two-Layer Fleece Bonded Soft Shell Jacket (88184)",
    colors: ["Black"],      
    type: "mens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",
      "4XLarge",
      "5XLarge"        
    ],
    pricing: {
      Small: { price: 55.00 },
      Medium: { price: 55.00 },
      Large: { price: 55.00 },
      XLarge: { price: 55.00 },
      "2XLarge": { price: 55.00 },
      "3XLarge": { price: 55.00 },
      "4XLarge": { price: 55.00 },
      "5XLarge": { price: 55.00 },                 
    },
  },
  {
    code: "78184",
    name: "Two-Layer Soft Shell Jacket #78184",
    fullname: "Core365 Cruise Two-Layer Fleece Bonded Soft Shell Jacket (78184)",
    colors: ["Black"],      
    type: "womens",
    default_color: "Black",
    sizes: [
      "Small", 
      "Medium", 
      "Large", 
      "XLarge", 
      "2XLarge",
      "3XLarge",             
    ],
    pricing: {
      Small: { price: 55.00 },
      Medium: { price: 55.00 },
      Large: { price: 55.00 },
      XLarge: { price: 55.00 },
      "2XLarge": { price: 55.00 },
      "3XLarge": { price: 55.00 },                       
    },
  },
];