export const catalog = [
  {
    code: "A230",
    name: "Adidas Performance Polo",
    fullname: "Adidas Men's Performance Polo",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
       Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "A231",
    name: "Adidas Performance Polo",
    fullname: "Adidas Women's Performance Polo",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "A475",
    name: "Adidas 1/4-Zip Pullover",
    fullname: "Men's Lightweight Mélange Quarter-Zip Pullover",
    colors: ["Black Melange"],
    type: "mens",
    default_color: "Black Melange",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 40.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,      
    },
  },
  {
    code: "A476",
    name: "Adidas 1/4-Zip Pullover",
    fullname: "Women's Lightweight Mélange Quarter-Zip Pullover",
    colors: ["Black Melange"],
    type: "womens",
    default_color: "Black Melange",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 40.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,      
    },
  },
  {
    code: "A708",
    name: "Adidas 1/4-Zip Pullover",
    fullname: "Men's Textured Stripe Quarter-Zip Pullover",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 44.99,
      Medium: 44.99,
      Large: 44.99,
      XLarge: 44.99,
      "2XLarge": 45.99,
      "3XLarge": 46.99,
      "4XLarge": 47.99,      
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Ambition 1/4-Zip",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 56.99,
      Medium: 56.99,
      Large: 56.99,
      XLarge: 56.99,
      "2XLarge": 57.99,
      "3XLarge": 58.99,     
    },
  },
  {
    code: "NF0A8ENJ",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Aim 1/4-Zip Fleece",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 69.00,
      Medium: 69.00,
      Large: 69.00,
      XLarge: 69.00,
      "2XLarge": 70.00,
      "3XLarge": 71.00,     
    },
  },
  {
    code: "NF0A8ENQ",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Women's Ambition 1/4-Zip",
    colors: ["TNF Black"],
    type: "womens",
    default_color: "TNF Black",
    sizes: {
      Small: 56.99,
      Medium: 56.99,
      Large: 56.99,
      XLarge: 56.99,
      "2XLarge": 57.99,
      "3XLarge": 58.99,     
    },
  },
  {
    code: "PC78H",
    name: "Port & Co™ Sweatshirt",
    fullname: "Port & Co™ Core Fleece Pullover Hooded Sweatshirt",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 15.99,
      Medium: 15.99,
      Large: 15.99,
      XLarge: 15.99,
      "2XLarge": 16.99,
      "3XLarge": 17.99,
      "4XLarge": 18.99,     
    },
  }, 
  {
    code: "LPC78H",
    name: "Port & Co™ Sweatshirt",
    fullname: "Port & Co™ Women's Core Fleece Pullover Hooded Sweatshirt",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 15.99,
      Medium: 15.99,
      Large: 15.99,
      XLarge: 15.99,
      "2XLarge": 16.99,
      "3XLarge": 17.99,
      "4XLarge": 18.99,     
    },
  },   
];