export const catalog = [
  {
    code: "A230",
    name: "Adidas Performance Polo",
    fullname: "Adidas Men's Performance Polo",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
       Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,
      "4XLarge": 0.00,
    },
  },
  {
    code: "A231",
    name: "Adidas Performance Polo",
    fullname: "Adidas Women's Performance Polo",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 0.00,
      Medium: 0.00,
      Large: 0.00,
      XLarge: 0.00,
      "2XLarge": 0.00,
      "3XLarge": 0.00,     
    },
  },
  {
    code: "A475",
    name: "Adidas Quarter-Zip Pullover",
    fullname: "Men's Lightweight Mélange Quarter-Zip Pullover",
    colors: ["Black Melange"],
    type: "mens",
    default_color: "Black Melange",
    sizes: {
      Small: 39.99,
      Medium: 39.99,
      Large: 39.99,
      XLarge: 39.99,
      "2XLarge": 40.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,      
    },
  },
  {
    code: "A708",
    name: "Adidas Quarter-Zip Pullover",
    fullname: "Men's Textured Stripe Quarter-Zip Pullover",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 44.99,
      Medium: 44.99,
      Large: 44.99,
      XLarge: 44.99,
      "2XLarge": 45.99,
      "3XLarge": 46.99,
      "4XLarge": 47.99,      
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Ambition 1/4-Zip",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 56.99,
      Medium: 56.99,
      Large: 56.99,
      XLarge: 56.99,
      "2XLarge": 57.99,
      "3XLarge": 58.99,     
    },
  },
  {
    code: "NF0A8ENJ",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Aim 1/4-Zip Fleece",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: {
      Small: 69.00,
      Medium: 69.00,
      Large: 69.00,
      XLarge: 69.00,
      "2XLarge": 70.00,
      "3XLarge": 71.00,     
    },
  },
  {
    code: "NF0A8ENQ",
    name: "The North Face® 1/4-Zip",
    fullname: "The North Face® Women's Ambition 1/4-Zip",
    colors: ["TNF Black"],
    type: "womens",
    default_color: "TNF Black",
    sizes: {
      Small: 56.99,
      Medium: 56.99,
      Large: 56.99,
      XLarge: 56.99,
      "2XLarge": 57.99,
      "3XLarge": 58.99,     
    },
  },
  {
    code: "PC78H",
    name: "Port & Co™ Sweatshirt",
    fullname: "Port & Co™ Core Fleece Pullover Hooded Sweatshirt",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: {
      Small: 15.99,
      Medium: 15.99,
      Large: 15.99,
      XLarge: 15.99,
      "2XLarge": 16.99,
      "3XLarge": 17.99,
      "4XLarge": 18.99,     
    },
  },
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets - Plain",
    colors: [
      "Blue",
      "Buff",
      "Fuchsia",
      "Green",
      "Grey",
      "Lavender",
      "Pink",
      "Salmon",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue",
    discount: [{ quantity: 100, price: 0.00 },
               { quantity: 500, price: 0.00 }],
    sizes: {
      100: 0.00,
      500: 0.00,
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Key Tag Versa #200 (250/box)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "White",
    discount: [{ quantity: 250, price: 0.00 }],
    sizes: {
      250: 0.0,
    },
  },
  {
    code: "30BKHP",
    name: "7.5 in. Numbers - Bk/Htpk",
    fullname: "7.5 in. Numbers - Black/Hot Pink (12/pk)",
    colors: ["BKHP0","BKHP1","BKHP2","BKHP3","BKHP4","BKHP5","BKHP6","BKHP7","BKHP8","BKHP9","BKHPS","BKHPD","BKHPP"],
    type: "sales",
    default_color: "BKHP0",
    discount: [{ quantity: 12, price: 0.00 }],
    sizes: {
      12: 0.00,
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [{ quantity: 500, price: 0.00 }],
    sizes: {
      500: 0.0,
    },
  },
  {
    code: "55010",
    name: "Steering Wheel Covers",
    fullname: "Steering Wheel Covers (500/bx)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    discount: [{ quantity: 500, price: 0.00 }],
    sizes: {
      500: 0.0,
    },
  },
   {
    code: "SDNRG",
    name: "Service Numbers",
    fullname: "Service Dispatch Numbers (1000/bx)",
    colors: ["_0000","1000","2000","3000","4000","5000",
      "6000","7000","8000", "9000"],  
    type: "service",
    default_color: "1000",
    discount: [{ quantity: 1, price: 0.00 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "GUARDFRM",
    name: "Zinc Metal Frames",
    fullname: "Zinc Metal Frame",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    supportedStores: ["GENGNO","COUNHA","COUHGR","NORVNO","VOLCNO"],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "guardianpp",
    name: "Poly Coated Plates",
    fullname: "Poly Coated Cardboard w/blue imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["GENGNO","COUNHA","COUHGR","NORVNO","VOLCNO"],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "GUARDECAL",
    name: "Die Cut Decals",
    fullname: "Vinyl Diecut Decals",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    supportedStores: ["GENGNO","COUNHA","COUHGR","NORVNO","VOLCNO"],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
    },
  },
];