export const catalog = [
  {
    code: "A230",
    name: "Adidas Performance Polo #A230",
    fullname: "Adidas Men's Performance Polo (A230)",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 26.99 },
      Medium: { price: 26.99 },
      Large: { price: 26.99 },
      XLarge: { price: 26.99 },
      "2XLarge": { price: 27.99 },
      "3XLarge": { price: 28.99 },
      "4XLarge": { price: 29.99 },
    },
  },
  {
    code: "A231",
    name: "Adidas Performance Polo #A231",
    fullname: "Adidas Women's Performance Polo (A231)",
    colors: ["Black","Collegiate Red","Collegiate Royal"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 26.99 },
      Medium: { price: 26.99 },
      Large: { price: 26.99 },
      XLarge: { price: 26.99 },
      "2XLarge": { price: 27.99 },
      "3XLarge": { price: 28.99 },
    },
  },
  {
    code: "A475",
    name: "Adidas 1/4-Zip Pullover #A475",
    fullname: "Men's Lightweight Mélange Quarter-Zip Pullover (A475)",
    colors: ["Black Melange"],
    type: "mens",
    default_color: "Black Melange",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 40.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 42.99 },
    },
  },
  {
    code: "A476",
    name: "Adidas 1/4-Zip Pullover #A476",
    fullname: "Women's Lightweight Mélange Quarter-Zip Pullover (A476)",
    colors: ["Black Melange"],
    type: "womens",
    default_color: "Black Melange",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 39.99 },
      Medium: { price: 39.99 },
      Large: { price: 39.99 },
      XLarge: { price: 39.99 },
      "2XLarge": { price: 40.99 },
      "3XLarge": { price: 41.99 },
      "4XLarge": { price: 42.99 },
    },
  },
  {
    code: "A708",
    name: "Adidas 1/4-Zip Pullover #A708",
    fullname: "Men's Textured Stripe Quarter-Zip Pullover (A708)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 44.99 },
      Medium: { price: 44.99 },
      Large: { price: 44.99 },
      XLarge: { price: 44.99 },
      "2XLarge": { price: 45.99 },
      "3XLarge": { price: 46.99 },
      "4XLarge": { price: 47.99 },
    },
  },
  {
    code: "NF0A8ENR",
    name: "The North Face® 1/4-Zip #NF0A8ENR",
    fullname: "The North Face® Ambition 1/4-Zip (NF0A8ENR)",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 56.99 },
      Medium: { price: 56.99 },
      Large: { price: 56.99 },
      XLarge: { price: 56.99 },
      "2XLarge": { price: 57.99 },
      "3XLarge": { price: 58.99 },
    },
  },
  {
    code: "NF0A8ENJ",
    name: "The North Face® 1/4-Zip #NF0A8ENJ",
    fullname: "The North Face® Aim 1/4-Zip Fleece (NF0A8ENJ)",
    colors: ["TNF Black"],
    type: "mens",
    default_color: "TNF Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 69.00 },
      Medium: { price: 69.00 },
      Large: { price: 69.00 },
      XLarge: { price: 69.00 },
      "2XLarge": { price: 70.00 },
      "3XLarge": { price: 71.00 },
    },
  },
  {
    code: "NF0A8ENQ",
    name: "The North Face® 1/4-Zip #NF0A8ENQ",
    fullname: "The North Face® Women's Ambition 1/4-Zip (NF0A8ENQ)",
    colors: ["TNF Black"],
    type: "womens",
    default_color: "TNF Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 56.99 },
      Medium: { price: 56.99 },
      Large: { price: 56.99 },
      XLarge: { price: 56.99 },
      "2XLarge": { price: 57.99 },
      "3XLarge": { price: 58.99 },
    },
  },
  {
    code: "ST672",
    name: "Sport-Tek® Micropique 1/4-Zip #ST672",
    fullname: "Sport-Tek® Micropique Sport-Wick® 1/4-Zip (ST672)",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 19.99 },
      Medium: { price: 19.99 },
      Large: { price: 19.99 },
      XLarge: { price: 19.99 },
      "2XLarge": { price: 20.99 },
      "3XLarge": { price: 21.99 },
      "4XLarge": { price: 22.99 },
    },
  },
  {
    code: "LST672",
    name: "Sport-Tek® Micropique 1/4-Zip #LST672",
    fullname: "Sport-Tek® Women's Micropique Sport-Wick® 1/4-Zip (LST672)",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 19.99 },
      Medium: { price: 19.99 },
      Large: { price: 19.99 },
      XLarge: { price: 19.99 },
      "2XLarge": { price: 20.99 },
      "3XLarge": { price: 21.99 },
      "4XLarge": { price: 22.99 },
    },
  },
  {
    code: "PC78H",
    name: "Port & Co™ Sweatshirt #PC78H",
    fullname: "Port & Co™ Core Fleece Hooded Sweatshirt (PC78H)",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 15.99 },
      Medium: { price: 15.99 },
      Large: { price: 15.99 },
      XLarge: { price: 15.99 },
      "2XLarge": { price: 16.99 },
      "3XLarge": { price: 17.99 },
      "4XLarge": { price: 18.99 },
    },
  }, 
  {
    code: "LPC78H",
    name: "Port & Co™ Sweatshirt #LPC78H",
    fullname: "Port & Co™ Women's Core Fleece Hooded Sweatshirt (LPC78H)",
    colors: ["Jet Black"],
    type: "tshirts",
    default_color: "Jet Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 15.99 },
      Medium: { price: 15.99 },
      Large: { price: 15.99 },
      XLarge: { price: 15.99 },
      "2XLarge": { price: 16.99 },
      "3XLarge": { price: 17.99 },
      "4XLarge": { price: 18.99 },
    },
  },   
];
