export const catalog = [
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
      "Anthracite",
      "Black",
      "Blue Tint",
      "Brilliant Orange",
      "Cool Grey",
      "Court Purple",
      "Game Royal",
      "Gorge Green",
      "Gym Blue",
      "Lucid Green",
      "Mint",
      "Navy",
      "Team Red",
      "Tidal Blue",
      "University Red",
      "Urban Lilac",
      "Valor Blue",
      "Varsity Maize",
      "Vivid Pink",
      "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 47.50 },
      Medium: { price: 47.50 },
      Large: { price: 47.50 },
      XLarge: { price: 47.50 },
      "2XLarge": { price: 50.00 },
      "3XLarge": { price: 51.99 },
      "4XLarge": { price: 53.99 },
    },
  },
  {
    code: "NKDC1963T",
    name: "Nike® Dri-FIT- TALL #NKDC1963",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo - TALL SIZES (NKDC1963)",
    colors: [
      "Anthracite",
      "Black",
      "Cool Grey",
      "Game Royal",
      "Gym Blue",
      "Navy",
      "University Red",
      "Valor Blue",
      "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: ["3XLT", "4XLT"],
    pricing: {
      "3XLT": { price: 59.99 },
      "4XLT": { price: 61.99 },
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Micropique Polo (ST650)",
    colors: ["Grey Concrete"],
    type: "mens",
    default_color: "Grey Concrete",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 25.99 },
      Medium: { price: 25.99 },
      Large: { price: 25.99 },
      XLarge: { price: 25.99 },
      "2XLarge": { price: 27.99 },
      "3XLarge": { price: 30.99 },
    },
  },
  {
    code: "NKDC2104",
    name: "Nike Long Sleeve Polo #NKDC2104",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Long Sleeve Polo (NKDC2104)",
    colors: ["Anthracite", "Black", "Game Royal", "Gym Blue", "Navy", "University Red", "White"],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 56.99 },
      Medium: { price: 56.99 },
      Large: { price: 56.99 },
      XLarge: { price: 56.99 },
      "2XLarge": { price: 58.99 },
      "3XLarge": { price: 61.99 },
      "4XLarge": { price: 63.99 },
    },
  },
  {
    code: "S608",
    name: "Port Authority® Shirt #S608 ",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt (S608)",
    colors: [
      "Black",
      "Light Blue",
      "Red",
      "Royal",
      "Steel Grey",
      "Ultramarine Blue",
      "White",
    ],
    type: "mens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 32.99 },
      Medium: { price: 32.99 },
      Large: { price: 32.99 },
      XLarge: { price: 32.99 },
      "2XLarge": { price: 34.99 },
      "3XLarge": { price: 37.99 },
      "4XLarge": { price: 39.99 },
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo #NKDC1991",
    fullname: "Ladies Nike® Micro Pique Polo (NKDC1991)",
    colors: [
      "Anthracite",
      "Black",
      "Blue Tint",
      "Brilliant Orange",
      "Cool Grey",
      "Court Purple",
      "Game Royal",
      "Gorge Green",
      "Gym Blue",
      "Lucid Green",
      "Mint",
      "Navy",
      "Team Red",
      "Tidal Blue",
      "University Red",
      "Urban Lilac",
      "Valor Blue",
      "Varsity Maize",
      "Vivid Pink",
      "White"
    ],
    type: "womens",
    default_color: "Anthracite",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 47.50 },
      Medium: { price: 47.50 },
      Large: { price: 47.50 },
      XLarge: { price: 47.50 },
      "2XLarge": { price: 50.00 },
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt #LST650",
    fullname: "Sport-Tek® Womens Micropique Polo (LST650)",
    colors: ["Grey Concrete"],
    type: "womens",
    default_color: "Grey Concrete",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 25.99 },
      Medium: { price: 25.99 },
      Large: { price: 25.99 },
      XLarge: { price: 25.99 },
      "2XLarge": { price: 27.99 },
      "3XLarge": { price: 30.99 },
    },
  },
  {
    code: "NKDC2105",
    name: "Nike Long Sleeve Polo #NKDC2105",
    fullname: "Nike Women's Dri-FIT Micro Pique 2.0 Long Sleeve Polo (NKDC2105)",
    colors: ["Anthracite", "Black", "Game Royal", "Gym Blue", "Navy", "University Red", "White"],
    type: "womens",
    default_color: "Black",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge"],
    pricing: {
      Small: { price: 56.99 },
      Medium: { price: 56.99 },
      Large: { price: 56.99 },
      XLarge: { price: 56.99 },
      "2XLarge": { price: 58.99 },
    },
  },
  {
    code: "J325",
    name: "Port Authority® Vest #J325",
    fullname: "Port Authority® Soft Shell Vest (J325)",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather", "Dress Blue Navy"],
    type: "mens",
    default_color: "Battleship Grey",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 47.99 },
      Medium: { price: 47.99 },
      Large: { price: 47.99 },
      XLarge: { price: 47.99 },
      "2XLarge": { price: 49.99 },
      "3XLarge": { price: 50.99 },
      "4XLarge": { price: 51.99 },
    },
  },
  {
    code: "L325",
    name: "Port Authority® Vest #L325",
    fullname: "Port Authority® Women's Core Soft Shell Vest (L325)",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather", "Dress Blue Navy", "Marshmallow"],
    type: "womens",
    default_color: "Battleship Grey",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 47.99 },
      Medium: { price: 47.99 },
      Large: { price: 47.99 },
      XLarge: { price: 47.99 },
      "2XLarge": { price: 49.99 },
      "3XLarge": { price: 50.99 },
      "4XLarge": { price: 51.99 },
    },
  },
  {
    code: "F236",
    name: "Port Authority® Vest #F236",
    fullname: "Port Authority ® Sweater Fleece Vest (F236)",
    colors: ["Black Heather", "Grey Heather"],
    type: "mens",
    default_color: "Black Heather",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 47.99 },
      Medium: { price: 47.99 },
      Large: { price: 47.99 },
      XLarge: { price: 47.99 },
      "2XLarge": { price: 49.99 },
      "3XLarge": { price: 50.99 },
      "4XLarge": { price: 51.99 },
    },
  },
  {
    code: "L236",
    name: "Port Authority® Vest #L236",
    fullname: "Port Authority ® Women's Sweater Fleece Vest (L236)",
    colors: ["Black Heather", "Grey Heather"],
    type: "womens",
    default_color: "Black Heather",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 47.99 },
      Medium: { price: 47.99 },
      Large: { price: 47.99 },
      XLarge: { price: 47.99 },
      "2XLarge": { price: 49.99 },
      "3XLarge": { price: 50.99 },
      "4XLarge": { price: 51.99 },
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Soft Shell Jacket (J317)",
    colors: [
      "Battleship Grey",
      "Black",
      "Black Charcoal Heather",
      "Deep Smoke",
      "Dress Blue Navy",
      "Forest Green",
      "Maroon",
      "Navy Heather",
      "Pearl Grey Heather",
      "Rich Red",
      "True Royal"
    ],
    type: "mens",
    default_color: "Battleship Grey",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 44.00 },
      Medium: { price: 44.00 },
      Large: { price: 44.00 },
      XLarge: { price: 44.00 },
      "2XLarge": { price: 45.99 },
      "3XLarge": { price: 47.99 },
      "4XLarge": { price: 48.99 },
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Women's Soft Shell Jacket (L317)",
    colors: [
      "Battleship Grey",
      "Black",
      "Black Charcoal Heather",
      "Deep Smoke",
      "Dress Blue Navy",
      "Navy Heather",
      "Pearl Grey Heather",
      "Rich Red",
      "True Royal",
      "Very Berry"
    ],
    type: "womens",
    default_color: "Battleship Grey",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge", "4XLarge"],
    pricing: {
      Small: { price: 44.00 },
      Medium: { price: 44.00 },
      Large: { price: 44.00 },
      XLarge: { price: 44.00 },
      "2XLarge": { price: 45.99 },
      "3XLarge": { price: 47.99 },
      "4XLarge": { price: 48.99 },
    },
  },
  {
    code: "CP80",
    name: "Port & Co™ Twill Cap #CP80",
    fullname: "Port & Co™ Six-Panel Twill Cap (CP80)",
    colors: ["Black", "Charcoal", "Neon Pink", "Purple", "Royal", "True Red"],
    type: "hat",
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 11.99 },
    },
  },
  {
    code: "C402",
    name: "Port Authority Trucker Cap #C402",
    fullname: "Port Authority® Snapback Trucker Cap (C402)",
    colors: ["Black", "FlameRed", "FlameRed Black", "FlameRed White", "White"],
    type: "hat",
    halfColors: ['FlameRed Black', 'FlameRed White'],
    default_color: "Black",
    sizes: ["OSFA"],
    pricing: {
      OSFA: { price: 13.99 },
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee #ST350",
    fullname: "Sport-Tek PosiCharge Competitor Tee (ST350)",
    colors: ["Iron Grey"],
    type: "tshirts",
    default_color: "Iron Grey",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 15.99 },
      Medium: { price: 15.99 },
      Large: { price: 15.99 },
      XLarge: { price: 15.99 },
      "2XLarge": { price: 16.99 },
      "3XLarge": { price: 17.99 },
    },
  },
  {
    code: "LST350",
    name: "Sport-Tek PosiCharge Tee #LST350",
    fullname: "Sport-Tek Women's PosiCharge Competitor Tee (LST350)",
    colors: ["Iron Grey"],
    type: "tshirts",
    default_color: "Iron Grey",
    sizes: ["Small", "Medium", "Large", "XLarge", "2XLarge", "3XLarge"],
    pricing: {
      Small: { price: 15.99 },
      Medium: { price: 15.99 },
      Large: { price: 15.99 },
      XLarge: { price: 15.99 },
      "2XLarge": { price: 16.99 },
      "3XLarge": { price: 17.99 },
    },
  },
  {
    code: "VAUCBU-6303RC-477213Z",
    name: "Vinyl Key Fob",
    fullname: "Opaque White Soft Vinyl Fob w/full color imprint",
    colors: ["White"],
    type: "accessory",
    default_color: "White",
    description: "Sold in quantities of 1500",
    quantities: [1500],
    pricing: {
      base: {
        price: 0.84,
      },
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Self-Protecting Key Tags (#GP200)",    
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue", 
    description: '250/box; 1 box: $36.95, 10 boxes: $30.00',   
    quantities: [1, 10],
    pricing: {
      base: {
        price: 36.95,
        discount: {
          10: 30.00,
        },
      },
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa (#VT400)",    
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Blue",
    description: '100 per pk; 1 pack: $17.95, 10 packs: $12.00',
    quantities: [1, 10],
    pricing: {
      base: {
        price: 17.95,
        discount: {
          10: 12.00,
        },
      },
    },
  },
  {
    code: "SDNRG",
    name: "Service Hang Numbers",
    fullname: "Service Hang Numbers (#SDNRG)",
    description: '1000 per box',
    colors: ["White"],
    variations: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000",
      "9000",
    ],
    type: "service",
    default_color: "white",
    pricing: {
      base: {
        price: 81.00,
      },
    },
  },
  {
    code: "SDNC",
    name: "Service Numbers",
    fullname: "Mirror Hang Service Numbers (#SDNC)",
    description:'1000 per box',
    colors: [
      "Blue",
      "Green",
      "Grey",
      "Lime",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "service",
    default_color: "Blue",
    pricing: {
      base: {
        price: 91.00,
      },
    },
  },
  {
    code: "EIT50",
    name: "Self-Locking Key Tags",
    fullname: "Self-Locking Key Tags (#EIT50)",
    colors: ["Blue", "Green", "Orange", "Red", "Yellow", "White"],
    description: '1000 per pack',
    type: "service",
    default_color: "Blue",
    quantities: [1,2,3,4,5,6,7,8,9,10],
    pricing: {
      base: {
        price: 36.99,
      },
    },
  },
  {
    code: "600088V",
    name: "Seat Covers (roll)",
    fullname: "No-Slip Plastic Seat Covers (#600088V)",
    description: '500 seat covers per roll',
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    pricing: {
      base: {
        price: 73.50,
      },
    },
  },
  {
    code: "55-010",
    name: "Steering Wheel Covers",
    fullname: "Steering Wheel Covers (#55-010)",
    description:'500 covers per box',
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",    
    pricing: {
      base: {
        price: 59.99,
      },
    },
  },
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (#3044)",
    description: '250 rings per pack',
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",
    pricing: {
      base: {
        price: 15.99,
      },
    },
  },
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (#3088)",
    description: '500 mats per box',
    colors: ["White"],
    type: "service",
    default_color: "White",    
    pricing: {
      base: {
        price: 76.44,
      },
    },
  },
  {
    code: "NDESTOCK",
    name: "Night Drop Envelopes",
    fullname: "Night Drop Envelopes (#NDESTOCK)",
    description:'500 per box',
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 99.00,
      },
    },
  },
  {
    code: "TH100",
    name: "Temp L/P Protector #TH100",
    fullname: "License Plate Protector (100/pk)",
    colors: ["Clear"],
    type: "sales",
    default_color: "Clear",
    description: '1 pack: $99.00, 10 packs: $80.00',
    quantities: [1, 10],
    pricing: {
      base: {
        price: 99.00,
        discount: {
          10: 80.00,
        },
      },
    },
  },
  {
    code: "7290",
    name: "Inspection Form - 3 Part",
    fullname: "Multi-Point Inspection Form - 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 34.14,
      },
    },
  },
  {
    code: "7291",
    name: "Inspection Form - 2 Part",
    fullname: "Multi-Point Inspection Form - 2 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 38.14,
      },
    },
  },
  {
    code: "7292",
    name: "Inspection Form - GM",
    fullname: "Multi-Point Inspection Form (GM) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 34.14,
      },
    },
  },
  {
    code: "7293",
    name: "Inspection Form CHRYSLER",
    fullname: "Multi-Point Inspection Form (Chrysler) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 45.00,
      },
    },
  },
  {
    code: "7294-01",
    name: "Inspection Form MAZDA",
    fullname: "Multi-Point Inspection Form (Mazda) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 34.14,
      },
    },
  },
  {
    code: "7294-05",
    name: "Inspection Form NISSAN",
    fullname: "Multi-Point Inspection Form (Nissan) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 45.00,
      },
    },
  },
  {
    code: "7296-0200",
    name: "Inspection Form TOYOTA",
    fullname: "Multi-Point Inspection Form (Toyota) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 45.00,
      },
    },
  },
  {
    code: "7298",
    name: "Inspection Form HONDA",
    fullname: "Multi-Point Inspection Form (Honda) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    pricing: {
      base: {
        price: 34.14,
      },
    },
  },
  {
    code: "VAUCBU-34PEU-521637B",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white & 186 red imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    description: '3000: $0.65 ea',
    supportedStores: ["VAUCBU"],
    quantities: [3000],
    pricing: {
      base: {
        price: .65,        
      }
    }
  },
  {
    code: "VAUCBU-33MRE-521638B",
    name: "White Aluminum Plate",
    fullname: "Painted White Aluminum Plate w/black & 186 red imprint",
    colors: ["Black Red"],
    type: "customs",
    default_color: "Black Red",
    description: '1000: $2.05 ea, 2500: $1.95 ea',
    halfColors: ["Black Red"],
    supportedStores: ["VAUCBU"],
    quantities: [1000, 2500],
     pricing: {
      base: {
        price: 2.05,
        discount: {
          2500: 1.95,          
        }
      }
    }
  },
  {
    code: "VAUCBU-33P-521639A",
    name: "White Plastic Plate",
    fullname: "White Plastic Frame w/021 orange imprint",
    colors: ["Orange"],
    type: "customs",
    default_color: "Orange",
    description: '2000 plates: $0.65 ea',
    supportedStores: ["VAUCBU"],
    quantities: [2000],
    pricing: {
      base: {
        price: .65,        
      }
    }
  },
  {
    code: "VAUCBU-31DD-521386A",
    name: "Vinyl Die Cut Decals ",
    fullname: "White Vinyl Die Cut Decal (12 in. x 1.71 in.)",
    description: 'Grey does not print.',
    colors: ["White"],
    type: "customs",
    supportedStores: ["VAUCBU"],
    default_color: "White", 
    description: '1000: $0.42 ea, 1500: $0.40 ea, 2500: $0.38 ea',   
    quantities: [1000, 1500, 2500],
    pricing: {
      base: {
        price: .42,
        discount: {
          1500: .40,
          2500: .38,
        }, 
      },
    },
  },
]