export const catalog = [
  {
   code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt #NKDC1963",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo (NKDC1963)",
    colors: [
        "Anthracite", 
        "Black", 
        "Blue Tint",
        "Brilliant Orange",
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gorge Green",
        "Gym Blue",
        "Lucid Green",
        "Mint",
        "Navy",
        "Team Red",
        "Tidal Blue",
        "University Red",
        "Urban Lilac",
        "Valor Blue",
        "Varsity Maize",
        "Vivid Pink",
        "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      Small: 46.50,
      Medium: 46.50,
      Large: 46.50,
      XLarge: 46.50,
      "2XLarge": 49.00,
      "3XLarge": 50.99,
      "4XLarge": 52.99,
     },
  },
  {
    code: "NKDC1963T",
    name: "Nike® Dri-FIT- TALL #NKDC1963",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo - TALL SIZES (NKDC1963)",
    colors: [
        "Anthracite",
        "Black",
        "Cool Grey",
        "Game Royal",
        "Gym Blue",
        "Navy",
        "University Red",
        "Valor Blue",
        "White",
    ],
    type: "mens",
    default_color: "Anthracite",
    sizes: {
      "3XLT": 58.99,
      "4XLT": 60.99,
    },
  },
  {
    code: "ST650",
    name: "Sport-Tek® Polo Shirt #ST650",
    fullname: "Sport-Tek® Micropique Polo (ST650)",
    colors: ["Grey Concrete"],
    type: "mens",
    default_color: "Grey Concrete",
    sizes: {
      Small: 24.99,
      Medium: 24.99,
      Large: 24.99,
      XLarge: 24.99,
      "2XLarge": 26.99,
      "3XLarge": 29.99,
   },
  },
  {
    code: "NKDC2104",
    name: "Nike Long Sleeve Polo #NKDC2104",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Long Sleeve Polo (NKDC2104)",
    colors: ["Anthracite","Black","Game Royal","Gym Blue","Navy","University Red","White"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 55.99,
      Medium: 55.99,
      Large: 55.99,
      XLarge: 55.99,
      "2XLarge": 57.99,
      "3XLarge": 60.99,
      "4XLarge": 62.99,
    },
  },
  {
    code: "NKDC1991",
    name: "Ladies Nike® Polo #NKDC1991",
    fullname: "Ladies Nike® Micro Pique Polo (NKDC1991)",
    colors: [
        "Anthracite", 
        "Black", 
        "Blue Tint",
        "Brilliant Orange",
        "Cool Grey",
        "Court Purple",
        "Game Royal",
        "Gorge Green",
        "Gym Blue",
        "Lucid Green",
        "Mint",
        "Navy",
        "Team Red",
        "Tidal Blue",
        "University Red",
        "Urban Lilac",
        "Valor Blue",
        "Varsity Maize",
        "Vivid Pink",
        "White"
      ],
    type: "womens",
    default_color: "Anthracite",
    sizes: {
      Small: 46.50,
      Medium: 46.50,
      Large: 46.50,
      XLarge: 46.50,
      "2XLarge": 49.00,
    },
  },
  {
    code: "LST650",
    name: "Sport-Tek® Polo Shirt #LST650",
    fullname: "Sport-Tek® Womens Micropique Polo (LST650)",
    colors: ["Grey Concrete"],
    type: "womens",
    default_color: "Grey Concrete",
    sizes: {
      Small: 24.99,
      Medium: 24.99,
      Large: 24.99,
      XLarge: 24.99,
      "2XLarge": 26.99,
      "3XLarge": 29.99,
    },
  },
  {
    code: "NKDC2105",
    name: "Nike Long Sleeve Polo #NKDC2105",
    fullname: "Nike Women's Dri-FIT Micro Pique 2.0 Long Sleeve Polo (NKDC2105)",
    colors: ["Anthracite","Black","Game Royal","Gym Blue","Navy","University Red","White"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 55.99,
      Medium: 55.99,
      Large: 55.99,
      XLarge: 55.99,
      "2XLarge": 57.99,      
    },
  },
  {
    code: "J325",
    name: "Port Authority® Vest #J325",
    fullname: "Port Authority® Soft Shell Vest (J325)",
    colors: ["Battleship Grey","Black","Black Charcoal Heather","Dress Blue Navy"],
    type: "mens",
    default_color: "Battleship Grey",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 48.99,
      "3XLarge": 49.99,
      "4XLarge": 50.99,
    },
  },
  {
    code: "L325",
    name: "Port Authority® Vest #L325",
    fullname: "Port Authority® Women's Core Soft Shell Vest (L325)",
    colors: ["Battleship Grey","Black","Black Charcoal Heather","Dress Blue Navy","Marshmallow"],
    type: "womens",
    default_color: "Battleship Grey",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 48.99,
      "3XLarge": 49.99,
      "4XLarge": 50.99,
    },
  },
  {
    code: "F236",
    name: "Port Authority® Vest #F236",
    fullname: "Port Authority ® Sweater Fleece Vest (F236)",
    colors: ["Black Heather","Grey Heather"],
    type: "mens",
    default_color: "Black Heather",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 48.99,
      "3XLarge": 49.99,
      "4XLarge": 50.99,
    },
  },
  {
    code: "L236",
    name: "Port Authority® Vest #L236",
    fullname: "Port Authority ® Women's Sweater Fleece Vest (L236)",
    colors: ["Black Heather","Grey Heather"],
    type: "womens",
    default_color: "Black Heather",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 48.99,
      "3XLarge": 49.99,
      "4XLarge": 50.99,
    },
  },  
    {
    code: "J317",
    name: "Port Authority® Jacket #J317",
    fullname: "Port Authority® Soft Shell Jacket (J317)",
    colors: [
      "Battleship Grey",
      "Black",
      "Black Charcoal Heather",
      "Deep Smoke",
      "Dress Blue Navy",
      "Forest Green",
      "Maroon",
      "Navy Heather",
      "Pearl Grey Heather",
      "Rich Red",
      "True Royal"
    ],
    type: "mens",
    default_color: "Battleship Grey",
    sizes: {
      Small: 43.00,
      Medium: 43.00,
      Large: 43.00,
      XLarge: 43.00,
      "2XLarge": 44.99,
      "3XLarge": 46.99,
      "4XLarge": 47.99,      
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket #L317",
    fullname: "Port Authority® Women's Soft Shell Jacket (L317)",
    colors: [
      "Battleship Grey", 
      "Black",
      "Black Charcoal Heather",
      "Deep Smoke",
      "Dress Blue Navy",      
      "Navy Heather",
      "Pearl Grey Heather",
      "Rich Red",
      "True Royal",
      "Very Berry"
    ],
    type: "womens",
    default_color: "Battleship Grey",
    sizes: {
      Small: 43.00,
      Medium: 43.00,
      Large: 43.00,
      XLarge: 43.00,
      "2XLarge": 44.99,
      "3XLarge": 46.99,
      "4XLarge": 47.99,
    },
  },
  {
    code: "CP80",
    name: "Port & Co™ Twill Cap #CP80",
    fullname: "Port & Co™ Six-Panel Twill Cap (CP80)",
    colors: ["Black","Charcoal","Neon Pink","Purple","Royal","True Red"],
    type: "hat",
    default_color: "Black",
    sizes: {
      OSFA: 10.99,
    },
  },
   {
    code: "C402",
    name: "Port Authority Trucker Cap #C402",
    fullname: "Port Authority® Snapback Trucker Cap (C402)",
    colors: ["Black","FlameRed","FlameRed Black","FlameRed White","White"],
    type: "hat",
    halfColors: ['FlameRed Black', 'FlameRed White'],
    default_color: "Black",    
    sizes: {
      OSFA: 12.99,
    },
  },
  {
    code: "ST350",
    name: "Sport-Tek PosiCharge Tee #ST350",
    fullname: "Sport-Tek PosiCharge Competitor Tee (ST350)",
    colors: ["Iron Grey"],
    type: "tshirts",
    default_color: "Iron Grey",
    sizes: {
      Small: 14.99,
      Medium: 14.99,
      Large: 14.99,
      XLarge: 14.99,
      "2XLarge": 15.99,
      "3XLarge": 16.99,      
    },
  },
  {
    code: "LST350",
    name: "Sport-Tek PosiCharge Tee #LST350",
    fullname: "Sport-Tek Women's PosiCharge Competitor Tee (LST350)",
    colors: ["Iron Grey"],
    type: "tshirts",
    default_color: "Iron Grey",
    sizes: {
      Small: 14.99,
      Medium: 14.99,
      Large: 14.99,
      XLarge: 14.99,
      "2XLarge": 15.99,
      "3XLarge": 16.99,      
    },
  },
  {
    code: "VAUCBU-6303RC-477213Z",
    name: "Vinyl Key Fob",
    fullname: "Opaque White Soft Vinyl Fob w/full color imprint",
    colors: ["White"],
    type: "accessory",
    default_color: "White",
    description: "Sold in quantities of 1500",    
    sizes: {
       "1500": .84,       
   },
  },
  {
    code: "GP200",
    name: "Key Tags #GP200",
    fullname: "Self-Protecting Key Tags #200 (250/bx)",
    colors: [
      "Blue",
      "Gray",
      "Green",
      "Lilac",
      "Lime Green",
      "Orange",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],
    type: "sales",
    default_color: "Blue", 
    description: "Sold in quantities of 1 or 10 boxes",    
    sizes: {
      "1": 36.95,
      "10": 30.00,
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers #VT400",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100/pk)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Blue", 
    description: "Sold in quantities of 1 or 10 packs",  
    sizes: {
      "1": 17.95,
      "10": 12.00,
    },
  }, 
  {
    code: "SDNRG",
    name: "Service Hang Numbers #SDNRG",
    fullname: "Service Hang Numbers (1000/bx)",
    colors: ["White"],
    variations: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000", 
      "9000",
    ],  
    type: "service",
    default_color: "white",    
    discount: [
      { quantity: 1, price: 81.00 },
    ],    
    sizes: {
      "1 box": 81.00,      
    },
  },
  {
    code: "SDNC",
    name: "Service Numbers #SDNC",
    fullname: "Mirror Hang Service Numbers (1000/bx)",
    colors: [
      "Blue",
      "Green",
      "Grey",
      "Lime",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Tan",
      "White",
      "Yellow",
    ],  
    type: "service",
    default_color: "Blue",    
    sizes: {
      "1 box": 91.00,
    },
  }, 
  {
    code: "TH100",
    name: "Temp L/P Protector #TH100",
    fullname: "License Plate Protector (100/pk)",
    colors: ["Clear"],
    type: "sales",
    default_color: "Clear",
    description: "Sold in quantities of 1 or 10 packs", 
    discount: [
      { quantity: 1, price: 99.00 },
      { quantity: 10, price: 80.00 },
    ],    
    sizes: {
      1: 99.00,
      10: 80.00,
    },
  },
  {
    code: "7290",
    name: "Inspection Form - 3 Part",
    fullname: "Multi-Point Inspection Form - 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 34.14,
    },
  },
  {
    code: "7291",
    name: "Inspection Form - 2 Part",
    fullname: "Multi-Point Inspection Form - 2 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 38.14,
    },
  },
  {
    code: "7292",
    name: "Inspection Form - GM",
    fullname: "Multi-Point Inspection Form (GM) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 34.14,
    },
  },
  {
    code: "7293",
    name: "Inspection Form CHRYSLER",
    fullname: "Multi-Point Inspection Form (Chrysler) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 45.00,
    },
  },
  {
    code: "7294-01",
    name: "Inspection Form MAZDA",
    fullname: "Multi-Point Inspection Form (Mazda) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 34.14,
    },
  },
  {
    code: "7294-05",
    name: "Inspection Form NISSAN",
    fullname: "Multi-Point Inspection Form (Nissan) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 45.00,
    },
  },
  {
    code: "7296-0200",
    name: "Inspection Form TOYOTA",
    fullname: "Multi-Point Inspection Form (Toyota) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 45.00,
    },
  },
  {
    code: "7298",
    name: "Inspection Form HONDA",
    fullname: "Multi-Point Inspection Form (Honda) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    sizes: {
      "# packs": 34.14,
    },
  },
]