import { Config } from "../lib/interfaces";
export const config: Config = {
  title: "Cannon Motor Company",
  company_logo: "cannon_logo.png",
  logo_placements: [],
  show_modification_thumbnail: false,
  minimum_apparel_order: false,
  render_logo_preview: false,
  embroideries: {
    hat: [],
    mens: [],
    womens: [],
    accessory: [],
    customs: [],
  },
  stores: [
    "Cannon Ford of Cleveland",
    "Cannon Ford of Starkville",
    "Cannon Chevrolet Buick GMC",
    "Cannon Chevrolet Greenwood",
    "Cannon Chevrolet Buick GMC of West Point",
    "Cannon Chevrolet Buick Cadillac of Oxford",
    "Cannon Honda",
    "Cannon CDJR of Cleveland",
    "Cannon Ford of Pascagoula",
    "Cannon CDJR Greenwood",
    "Cannon Preowned Grenada",
    "Cannon Toyota of Vicksburg",
    "Cannon Toyota of Mosspoint",
    "Cannon Ford Nissan of Pascagula",
    "Cannon CDJR of West Point",
    "Cannon Preowned of Jackson",
    "Cannon Preowned Calhoun City",
    "Cannon Nissan of Greenwood",
    "Cannon Nissan of Jackson",
    "Cannon Nissan of Oxford",
    "Grenada Nissan",
    "Cannon Chevrolet Nissan of Laurel",
    "Cannon GMC Vicksburg",
    "Cannon CDJR Senatobia",
  ],
  bypass_codes: ["CANNJA"],
};
