import { Config } from "../lib/interfaces";

export const config: Config = {
  title: "New Customer",
  company_logo: "hennessy.png",
  logo_placements: ["Left Chest", "Right Sleeve"],
  show_modification_thumbnail: true,
  minimum_apparel_order: true,
  render_logo_preview: true,
  embroideries: {
    hat: [
      "Cadillac",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche",
      "Porsche",
      "Porsche Atlanta NW",
      "Porsche North Atl",
    ],
    mens: [
      "Cadillac",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche",
      "Porsche",
      "Porsche Atlanta NW",
      "Porsche North Atl",
    ],
    womens: [
      "Cadillac",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche",
      "Porsche",
      "Porsche Atlanta NW",
      "Porsche North Atl",
    ],
    accessory: [
      "Cadillac",
      "Hennessy Ford",
      "Hennessy Ford Lincoln",
      "Hennessy Honda",
      "Hennessy Mazda GMC",
      "Hennessy Porsche",
      "Porsche",
      "Porsche Atlanta NW",
      "Porsche North Atl",
    ],
    customs: [],
  },
  stores: [
    "Hennessy Jaguar Land Rover, 3040 Piedmont Rd NE, Atlanta, GA 30305",
    "Hennessy Cadillac, 3377 Satellite Blvd, Duluth, GA 30096",
    "Hennessy Ford, 5675 Peachtree Industrial Blvd, Atlanta, GA 30341",
    "Hennessy Honda, 8931 Highway 92, Woodstock, GA 30189",
    "Hennessy Jaguar, 3423 Old Norcross Rd, Duluth, GA 30096",
    "Hennessy Land Rover, 1505 Mansell Rd, Alpharetta, GA 30004",
    "Hennessy Lexus, 5955 Peachtree Industrial Blvd, Atlanta, GA 30341",
    "Hennessy Lexus Duluth, 3383 Satellite Blvd, Duluth, GA 30096",
    "Hennessy Mazda Buick GMC, 7261 Jonesboro Rd, Morrow, GA 30260",
    "Hennessy Porsche Marietta, 2501 Windy Hill Rd SE, Marietta, GA 30067",
    "Hennessy Porsche, 990 Mansell Rd, Roswell, GA 30076",
  ],
  bypass_codes: [],
  server_hostname: "https://mxfj3q6m01.execute-api.us-east-1.amazonaws.com",
  account_reps: [
    { name: "Andrew Sarazua", phone: "678-287-1604" },
    { name: "John Boston", phone: "678-287-1601" },    
  ],
};
