import { CatalogItem } from "../lib/interfaces";
export const GuardianCatalog: CatalogItem[] = [
  {
    code: "1640",
    name: "Logo Key Chains",
    fullname: "Brushed Zinc/Leather/Big Logo Key Chain",
    colors: ["Black Leather"],
    type: "accessory",
    default_color: "Black",
    sizes: {
      Default: 6.99,
    },
  },
  {
    code: "6303",
    name: "Logo Key Chain",
    fullname: "Soft Touch Key Fob Rectangle",
    colors: ["Blue", "White"],
    type: "accessory",
    default_color: "Blue",
    sizes: {
      Default: 6.99,
    },
  },
  {
    code: "321",
    name: "Javalina Pen",
    fullname: "Javalina Pen with White Imprint",
    colors: ["Blue"],
    type: "accessory",
    default_color: "Blue",
    sizes: {
      Default: 6.99,
    },
  },
  {
    code: "rectangle_dd",
    name: "Decals",
    fullname: "Rectangular Domecal",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.49 },
      { quantity: 2500, price: 0.45 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "31dd",
    name: " Decals",
    fullname: "31DD Thermal Die-Cut Decals",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.49 },
      { quantity: 2500, price: 0.45 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "plastic_plate",
    name: "Soft Drive Out Plates",
    fullname: "Soft Plates",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.49 },
      { quantity: 2500, price: 0.45 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "cf_frame",
    name: "Chrome Faced Frames",
    fullname: "Chrome Faced Frame",
    colors: ["Chrome Faced"],
    type: "customs",
    default_color: "Chrome Faced",
    discount: [
      { quantity: 1000, price: 0.49 },
      { quantity: 2500, price: 0.45 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "cpp_frame",
    name: "CPP Frames",
    fullname: "Chrome Plated Plastic Frame",
    colors: ["Chrome Plated"],
    type: "customs",
    default_color: "Chrome Plated",
    discount: [
      { quantity: 1000, price: 0.49 },
      { quantity: 2500, price: 0.45 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "plastic_frame",
    name: "Black Plastic Frames",
    fullname: "Black Plastic Frame",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 1000, price: 0.49 },
      { quantity: 2500, price: 0.45 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike® Dri-FIT Polo Shirt",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 36.99,
      Medium: 36.99,
      Large: 36.99,
      XLarge: 36.99,
      "2XLarge": 38.99,
      "3XLarge": 39.99,
      "4XLarge": 40.99,
      LT: 40.99,
      XLT: 42.99,
      "2XLT": 43.99,
      "3XLT": 44.99,
      "4XLT": 45.99,
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 37.99,
      Medium: 37.99,
      Large: 37.99,
      XLarge: 37.99,
      "2XLarge": 38.99,
      "3XLarge": 39.99,
      "4XLarge": 40.99,
      "5XLarge": 41.99,
      "6XLarge": 42.99,
    },
  },
  {
    code: "PC61",
    name: "Port & Company Tee",
    fullname: "Port & Company Essential Tee",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 8.99,
      Medium: 8.99,
      Large: 8.99,
      XLarge: 8.99,
      "2XLarge": 10.99,
      "3XLarge": 11.99,
      "4XLarge": 12.99,
      "5XLarge": 13.99,
      "6XLarge": 14.99,
    },
  },
];
