import { CatalogItem } from "../lib/interfaces";
export const HennessyCatalog: CatalogItem[] = [
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    discount: [
      { quantity: 500, price: 59.99 },      
    ],
    sizes: {
      default: 0.00,
    },
  }, 
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 500, price: 59.99 },      
    ],
    sizes: {
      500: 0.0,      
    },
  },
  {
    code: "SDNRG",
    name: "Service Numbers",
    fullname: "Service Dispatch Numbers (1000/bx)",
    colors: ["0000", "1000", "2000", "3000", "4000", "5000", "6000", "7000", "8000", "9000"],
    type: "service",
    default_color: "0000",
    discount: [
      { quantity: 1000, price: 84.99 },      
    ],
    sizes: {
      1000: 0.0,      
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Key Tag Versa #200 (250/bx)",
    colors: ["Blue", "Gray", "Green", "Lilac", "Lime Green", "Orange", "Red", "Tan", "White", "Yellow"],
    type: "sales",
    default_color: "White",
    discount: [
      { quantity: 1, price: 31.95 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {    
    code: "3198SB",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers Black/Silver (12/pk)",
    colors: ["YR 2016","YR 2017","YR 2018","YR 2019","YR 2020","YR 2021","YR 2022","YR 2023","YR 2024","YR 2025","YR 2026"],
    type: "sales",
    default_color: "YR 2016",
    discount: [
      { quantity: 1, price: 10.99 },      
    ],
    sizes: {
      1: 0.0,    
    },
  },
  {
    code: "GP790",
    name: "Sticker",
    fullname: "Sticker - Vehicle Not for Sale (100/pk)",
    colors: ["Yellow"],
    type: "sales",
    default_color: "Yellow",
    discount: [
      { quantity: 1, price: 26.14 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "BGVinyl",
    name: "Vinyl Sheet",
    fullname: "8.5 x 11 Blank Vinyl Sheet #9300 (100/pk)",
    colors: ["White"],
    type: "sales",
    default_color: "White",
    discount: [
      { quantity: 1, price: 135.00 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: ["Black", "Battleship Grey", "Rich Red", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 36.99,
      "3XLarge": 38.99,
      "4XLarge": 40.99,
      "5XLarge": 42.99,
      "6XLarge": 44.99,
    },
  },
  {
    code: "J331",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® All-Conditions Jacket",
    colors: ["Black", "Direct Blue", "True Navy"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 58.29,
      Medium: 58.29,
      Large: 58.29,
      XLarge: 58.29,
      "2XLarge": 60.29,
      "3XLarge": 62.29,
      "4XLarge": 64.29,
    },
  },
  {
    code: "J333",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Torrent Waterproof Jacket",
    colors: ["Black", "Engine Red", "Magnet", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 49.99,
      Medium: 49.99,
      Large: 49.99,
      XLarge: 49.99,
      "2XLarge": 51.99,
      "3XLarge": 53.99,
      "4XLarge": 55.99,
    },
  },
  {
    code: "NF0A7V4F",
    name: "The North Face® Jacket",
    fullname: "The North Face® Down Hybrid Jacket",
    colors: ["Black", "Medium Grey Hthr"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 189.00,
      Medium: 189.00,
      Large: 189.00,
      XLarge: 189.00,
      "2XLarge": 191.00,
      "3XLarge": 193.00,
    },
  },
  {
    code: "ST740",
    name: "Sport-Tek® UV Polo",
    fullname: "Sport-Tek® UV Micropique Polo",
    colors: ["Black", "Deep Red", "Graphite", "True Royal"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 19.99,
      Medium: 19.99,
      Large: 19.99,
      XLarge: 19.99,
      "2XLarge": 21.99,
      "3XLarge": 23.99,
      "4XLarge": 25.99,
    },
  },
  {
    code: "LOG101",
    name: "OGIO® - Jewel Polo",
    fullname: "OGIO® - Jewel Polo",
    colors: [
      "Blacktop",
      "Blue Mist",
      "Bright White",
      "Diesel Grey",
      "Electric Blue",
      "Gridiron Green",
      "Navy",
      "Pink Crush",
      "Rogue Grey",
      "Signal Red",
      "Spar Blue",
    ],
    type: "womens",
    default_color: "Blacktop",
    sizes: {
      Small: 29.99,
      Medium: 29.99,
      Large: 29.99,
      XLarge: 29.99,
      "2XLarge": 31.99,
      "3XLarge": 33.99,
      "4XLarge": 35.99,
    },
  },
  {
    code: "OG101",
    name: "OGIO® - Caliber2.0 Polo",
    fullname: "OGIO® - Caliber2.0 Polo",
    colors: ["Blacktop", "Diesel Grey", "Electric Blue", "Signal Red"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 29.99,
      Medium: 29.99,
      Large: 29.99,
      XLarge: 29.99,
      "2XLarge": 31.99,
      "3XLarge": 33.99,
      "4XLarge": 35.99,
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike Dri-FIT Micro Pique 2.0 Polo",
    colors: ["Anthracite", "Black", "Game Royal", "University Red"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 34.99,
      Medium: 34.99,
      Large: 34.99,
      XLarge: 34.99,
      "2XLarge": 36.99,
      "3XLarge": 38.99,
      "4XLarge": 40.99,
      LT: 40.99,
      XLT: 42.99,
      "2XLT": 44.99,
      "3XLT": 46.99,
      "4XLT": 48.99,
    },
  },
  {
    code: "TM1MAA370",
    name: "TravisMathew Solid Polo",
    fullname: "TravisMathew Cabana Solid Polo",
    colors: ["Black", "Classic Blue", "Crimson", "Stormy Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 74.99,
      Medium: 74.99,
      Large: 74.99,
      XLarge: 74.99,
      "2XLarge": 76.99,
      "3XLarge": 78.99,
    },
  },
  {
    code: "S608",
    name: "Port Authority® Shirt",
    fullname: "Port Authority® Long Sleeve Easy Care Shirt",
    colors: ["Black", "Red", "Royal", "Steel Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 28.99,
      Medium: 28.99,
      Large: 28.99,
      XLarge: 28.99,
      "2XLarge": 30.99,
      "3XLarge": 32.99,
      "4XLarge": 34.99,
      "5XLarge": 36.99,
      "6XLarge": 38.99,
    },
  },
  {
    code: "OG1002",
    name: "OGIO® Woven Shirt",
    fullname: "OGIO® Commuter Woven Shirt",
    colors: ["Blacktop", "Gear Grey Hthr", "Metal Blue Hthr", "White"],
    type: "mens",
    default_color: "Blacktop",
    sizes: {
      Small: 42.99,
      Medium: 42.99,
      Large: 42.99,
      XLarge: 42.99,
      "2XLarge": 44.99,
      "3XLarge": 46.99,
      "4XLarge": 48.99,
    },
  },
  {
    code: "BB18002",
    name: "Brooks Brothers® Shirt",
    fullname: "Brooks Brothers® Wrinkle-Free Nailhead Shirt",
    colors: ["Cobalt Blue", "Deep Black", "Navy Blazer", "White"],
    type: "mens",
    default_color: "Deep Black",
    sizes: {
      Small: 63.99,
      Medium: 63.99,
      Large: 63.99,
      XLarge: 63.99,
      "2XLarge": 65.99,
      "3XLarge": 67.99,
      "4XLarge": 69.99,
    },
  },
  {
    code: "K584",
    name: "Port Authority® 1/4-Zip",
    fullname: "Port Authority® Silk Touch™ 1/4-Zip",
    colors: ["Black", "Red", "Royal", "Steel Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 23.99,
      Medium: 23.99,
      Large: 23.99,
      XLarge: 23.99,
      "2XLarge": 25.99,
      "3XLarge": 27.99,
      "4XLarge": 29.99,
    },
  },
  {
    code: "NKBV6044",
    name: "Nike 1/2-Zip Cover-Up",
    fullname: "Nike Dry 1/2-Zip Cover-Up",
    colors: ["Black", "Black Heather", "Gym Blue"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 62.50,
      Medium: 62.50,
      Large: 62.50,
      XLarge: 62.50,
      "2XLarge": 64.50,
      "3XLarge": 66.50,
      "4XLarge": 68.50,
    },
  },
  {
    code: "TM1MY397",
    name: "TravisMathew 1/4-Zip",
    fullname: "TravisMathew Coto Performance 1/4-Zip",
    colors: [
      "Black",
      "Brilliant Blue Hthr",
      "Quiet Shade Grey Hthr",
      "Vintage Indigo",
    ],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 74.99,
      Medium: 74.99,
      Large: 74.99,
      XLarge: 74.99,
      "2XLarge": 76.99,
      "3XLarge": 78.99,
    },
  },
  {
    code: "5470",
    name: "A/P Voucher Jacket",
    fullname: "9 in. x 12 in. A/P Voucher Jacket (DSA-540)",
    colors: ["Blue", "Buff", "Green", "Lavender", "Pink", "White"],
    type: "office",
    default_color: "Buff",
    discount: [
      { quantity: 100, price: 0.0 },
      { quantity: 500, price: 0.0 },
    ],
    sizes: {
      100: 0.0,
      500: 0.0,
    },
  },
  {
    code: "HENLDU-34MLF-366502A",
    name: "Zinc Metal Frames",
    fullname: "Zinc Metal Frame w/black imprint",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENLAT-34MLF-379167A",
    name: "Zinc Metal Frames",
    fullname: "Zinc Metal Frame w/glossy black imprint",
    colors: ["Metal"],
    type: "customs",
    default_color: "Metal",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENLAL-34CF-459349A",
    name: "Chrome Faced Frames",
    fullname: "Chrome Faced Black Plastic Frame",
    colors: ["Chrome Faced"],
    type: "customs",
    default_color: "Chrome Faced",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENLAL-33G24-373653A",
    name: "Poly Coated Plates",
    fullname: "Poly Coated Cardboard w/black imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENLAT-33G24-367503A",
    name: "Poly Coated Plates",
    fullname: "Poly Coated Cardboard w/black imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENLDU-33G24-373661B",
    name: "Poly Coated Plates",
    fullname: "Poly Coated Cardboard w/black/metallic imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENCAT-33P-497838B",
    name: "Plastic Plates",
    fullname: "White Plastic w/black/yellow imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "HENCAT-33P-497628B",
    name: "Plastic Plates",
    fullname: "White Plastic w/black/yellow imprint",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 1000, price: 0.0 },
      { quantity: 2500, price: 0.0 },
    ],
    sizes: {
      1000: 0.0,
      2500: 0.0,
    },
  },
  {
    code: "G1640",
    name: "Logo Key Chain",
    fullname: "Brushed Zinc/Leather/Big Logo Key Chain",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    sizes: {
      Default: 0.0,
    },
  },
  {
    code: "HENLAT-GPLLKR-456506L",
    name: "Leather Loop Keychain",
    fullname: "Leather Loop Metal Keychain",
    colors: ["Black Leather"],
    type: "accessory",
    default_color: "Black Leather",
    sizes: {
      Default: 0.0,
    },
  },
];