import { CatalogItem } from "../lib/interfaces";
export const NavarreCatalog: CatalogItem[] = [
    {
    code: "NAVCLA-33MRE-495605A",
    name: "Aluminum Embossed Plate",
    fullname: "Aluminum Plate w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 500, price: 2.87 },
      { quantity: 1000, price: 2.60 },
      { quantity: 2500, price: 2.36 },
      { quantity: 5000, price: 2.24 },
      { quantity: 10000, price: 2.02 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVCLA-33MRE-492106A",
    name: "Aluminum Embossed Plate",
    fullname: "Aluminum Plate w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 500, price: 2.87 },
      { quantity: 1000, price: 2.60 },
      { quantity: 2500, price: 2.36 },
      { quantity: 5000, price: 2.24 },
      { quantity: 10000, price: 2.02 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVCLA-33MRE-444122A",
    name: "Aluminum Embossed Plate",
    fullname: "Aluminum Plate w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 500, price: 2.87 },
      { quantity: 1000, price: 2.60 },
      { quantity: 2500, price: 2.36 },
      { quantity: 5000, price: 2.24 },
      { quantity: 10000, price: 2.02 },
    ],
    sizes: {
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVCLA-34CF-484294A",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Chrome-Faced Frame",
    colors: ["Chrome Faced"],
    type: "customs",
    default_color: "Chrome Faced",
    discount: [
      { quantity: 1000, price: 1.50 },
      { quantity: 2500, price: 1.30 },
      { quantity: 5000, price: 1.25 },
      { quantity: 10000, price: 1.14 },
    ],
    sizes: {      
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVCLA-34PE-450838A",
    name: "Black Plastic Frame",
    fullname: "Black Plastic Frame w/white imprint",
    colors: ["Black"],
    type: "customs",
    default_color: "Black",
    discount: [
      { quantity: 1000, price: .95 },
      { quantity: 2500, price: .90 },
      { quantity: 5000, price: .80 },
      { quantity: 10000, price:.65 },      
    ],
    sizes: {      
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVARRE-COLLISION",
    name: "Full Color Sticker",
    fullname: "2 x 2 Navarre Collision Full Color Sticker",
    colors: ["Full Color"],
    type: "customs",
    default_color: "Full Color",
    discount: [
      { quantity: 1000, price: 1.50 },
      { quantity: 2500, price: .51 },
      { quantity: 5000, price: .49 },      
    ],
    sizes: {      
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVCLA-31SD-504429A",
    name: "CARS Decal",
    fullname: "CARS Decal - 4.5 x 1.11",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 2500, price: 1.13 },      
      { quantity: 5000, price: 1.00 },      
    ],
    sizes: {      
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "NAVCLA-31SD-504428A",
    name: "TRUCKS Decal",
    fullname: "TRUCKS Decal - 6 x 1.48",
    colors: ["White"],
    type: "customs",
    default_color: "White",
    discount: [
      { quantity: 2500, price: 1.34 },      
      { quantity: 5000, price: 1.15 },      
    ],
    sizes: {      
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
      10000: 0.0,
    },
  },
  {
    code: "59204navarre",
    name: "Laser Engraved Keychain",
    fullname: "Black Avner Curve Keychain w/laser engraved imprint",
    colors: ["Metal"],
    type: "accessory",
    default_color: "Metal",
    discount: [
      { quantity: 1000, price: 1.95 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "908",
    name: "Tri-Band Pen",
    fullname: "Tri-Band Pen w/white imprint",
    colors: ["Black"],
    type: "accessory",
    default_color: "Black",
    discount: [
      { quantity: 500, price: 1.05 },      
      { quantity: 1000, price: 1.91 },
      { quantity: 2500, price: .79 }, 
      { quantity: 5000, price: .69 },       
    ],
    sizes: {      
      500: 0.0,
      1000: 0.0,
      2500: 0.0,
      5000: 0.0,
    },
  },
  {
    code: "600088V",
    name: "Seat Covers",
    fullname: "No-Slip Plastic Seat Covers (500/roll)",
    colors: ["Plastic"],
    type: "service",
    default_color: "Plastic",
    discount: [
      { quantity: 500, price: 65.00 },      
    ],
    sizes: {
      1: 0.00,
    },
  }, 
  {
    code: "3088",
    name: "Floor Mats",
    fullname: "Floor Mats/Coated Paper (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 500, price: 60.00 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "3044",
    name: "Spring Rings",
    fullname: "Metal Spring Rings (250/pk)",
    colors: ["Metal"],
    type: "service",
    default_color: "Metal",
    discount: [
      { quantity: 250, price: 13.95 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "SDNRG",
    name: "Service Numbers",
    fullname: "Service Dispatch Numbers (1000/bx)",
    colors: [
      "0000",
      "1000",
      "2000",
      "3000",
      "4000",
      "5000",
      "6000",
      "7000",
      "8000",
      "9000",
    ],
    type: "service",
    default_color: "1000",
    discount: [{ quantity: 1, price: 65.00 }],
    sizes: {
      1: 0.0,
    },
  },
  {
    code: "VT400",
    name: "Stock Stickers",
    fullname: "Kleer-Back Stock Stickers Versa #400 (100/pk)",
    colors: ["Blue", "Green", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Blue",
    discount: [
      { quantity: 1, price: 16.95 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "GP200",
    name: "Key Tags",
    fullname: "Key Tag Versa #200 (250/box)",
    colors: ["Blue", "Gray", "Green", "Lilac", "Lime Green", "Orange", "Red", "Tan", "White", "Yellow"],
    type: "sales",
    default_color: "Blue",
    discount: [
      { quantity: 1, price: 35.95 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "226",
    name: "Combo Key Tags",
    fullname: "Combo Key Tags - Numbered (125/box)",
    colors: ["Beige", "Blue", "Green", "Grey", "Lilac", "Orange", "Red", "White", "Yellow"],
    type: "sales",
    default_color: "Beige",
    discount: [
      { quantity: 1, price: 65.00 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "3198BY",
    name: "Oval Year Stickers",
    fullname: "Oval Year Stickers (Black/Yellow)  (12/pk)",
    colors: ["BY_08","BY_09","BY_10","BY_11","BY_12","BY_13","BY_14","BY_15","BY_16","BY_17","BY_18",
      "BY_19","BY_20","BY_21","BY_22","BY_23","BY_24","BY_25","BY_26"],
    type: "sales",
    default_color: "BY 08",
    discount: [
      { quantity: 1, price: 10.99 },      
    ],
    sizes: {
      1: 10.99,    
    },
  },
  {
    code: "NDESTOCK",
    name: "Night Drop Envelopes",
    fullname: "Night Drop Envelopes (500/bx)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 500, price: 99.99 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "7290",
    name: "Inspection Form - 3 Part",
    fullname: "Multi-Point Inspection Form - 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 250, price: 34.14 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "7291",
    name: "Inspection Form - 2 Part",
    fullname: "Multi-Point Inspection Form - 2 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 250, price: 34.14 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "7292",
    name: "Inspection Form - GM",
    fullname: "Multi-Point Inspection Form (GM) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 250, price: 34.14 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "7293",
    name: "Inspection Frm- CHRYSLER",
    fullname: "Multi-Point Inspection Form (Chrysler) 3 Part (250/pk)",
    colors: ["White"],
    type: "service",
    default_color: "White",
    discount: [
      { quantity: 250, price: 34.14 },      
    ],
    sizes: {
      1: 0.00,      
    },
  },
  {
    code: "GP546",
    name: "Deal Jackets",
    fullname: "Deal Jackets (500/box)",
    colors: ["Blue", "Buff", "Fuchsia", "Green", "Grey", "Lavender", "Pink", "Salmon", "White", "Yellow"],
    type: "sales",
    default_color: "Blue",
    discount: [
      { quantity: 1, price: 115.00 },      
    ],
    sizes: {
      1: 0.0,      
    },
  },
  {
    code: "ST740",
    name: "Sport-Tek Micropique Polo",
    fullname: "Sport-Tek® UV Micropique Polo",
    colors: ["Black", "Graphite", "Grey Concrete"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 26.99,
      Medium: 26.99,
      Large: 26.99,
      XLarge: 26.99,
      "2XLarge": 28.99,
      "3XLarge": 31.99,
      "4XLarge": 33.99,
    },
  },
  {
    code: "NKDC1963",
    name: "Nike® Dri-FIT Polo Shirt",
    fullname: "Nike® Dri-FIT Polo",
    colors: ["Anthracite", "Black", "Cool Grey"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 45.99,
      Medium: 45.99,
      Large: 45.99,
      XLarge: 45.99,
      "2XLarge": 47.99,
      "3XLarge": 50.99,
      "4XLarge": 52.99,
      LT: 51.99,
      XLT: 51.99,
      "2XLT": 53.99,
      "3XLT": 56.99,
      "4XLT": 58.99,
    },
  },
  {    
    code: "J317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Core Soft Shell Jacket",
    colors: [ "Battleship Grey", "Black", "Black Charcoal Heather", "Deep Smoke", "Pearl Grey Heather"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 48.99,
      "3XLarge": 51.99,
      "4XLarge": 53.99,
      "5XLarge": 55.99,
      "6XLarge": 57.99,
    },
  },
  {
    code: "L317",
    name: "Port Authority® Jacket",
    fullname: "Port Authority® Women's Core Soft Shell Jacket",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather", "Deep Smoke", "Pearl Grey Heather"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 46.99,
      Medium: 46.99,
      Large: 46.99,
      XLarge: 46.99,
      "2XLarge": 48.99,
      "3XLarge": 51.99,
      "4XLarge": 53.99,      
    },
  },
  {
    code: "J325",
    name: "Port Authority Vest",
    fullname: "Port Authority® Core Soft Shell Vest",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 37.99,
      Medium: 37.99,
      Large: 37.99,
      XLarge: 37.99,
      "2XLarge": 38.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,
    },
  },
  {
    code: "L325",
    name: "Port Authority Vest",
    fullname: "Port Authority® Women's Core Soft Shell Vest",
    colors: ["Battleship Grey", "Black", "Black Charcoal Heather"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 37.99,
      Medium: 37.99,
      Large: 37.99,
      XLarge: 37.99,
      "2XLarge": 38.99,
      "3XLarge": 41.99,
      "4XLarge": 42.99,
    },
  },
  {
    code: "J331",
    name: "Port Authority Jacket",
    fullname: "Port Authority® All-Conditions Jacket",
    colors: ["Black"],
    type: "mens",
    default_color: "Black",
    sizes: {
      Small: 68.99,
      Medium: 68.99,
      Large: 68.99,
      XLarge: 68.99,
      "2XLarge": 70.99,
      "3XLarge": 73.99,
      "4XLarge": 75.99,
    },
  },
  {
    code: "L331",
    name: "Port Authority Jacket",
    fullname: "Port Authority® Women's All-Conditions Jacket",
    colors: ["Black"],
    type: "womens",
    default_color: "Black",
    sizes: {
      Small: 68.99,
      Medium: 68.99,
      Large: 68.99,
      XLarge: 68.99,
      "2XLarge": 70.99,
      "3XLarge": 73.99,
      "4XLarge": 75.99,
    },
  },
  {
    code: "CP90",
    name: "Port Authority Knit Cap",
    fullname: "Port & Company® - Knit Cap",
    colors: ["Athletic Oxford", "Black", "Charcoal Heather"],
    type: "mens",
    default_color: "Black",
    sizes: {
      OSFA: 10.49,
     },
  },   
  {
    code: "C112",
    name: "Port Authority Trucker Cap",
    fullname: "Port Authority® Snapback Trucker Cap",
    colors: ["Black", "Gusty Grey", "Grey Steel"],
    type: "mens",
    default_color: "Black",
    sizes: {
      OSFA: 13.25,
     },
  },   
    ];
    